### ISSUE TITLE
Traffic tile stuck in cache?

### ISSUE THREAD

**Issue by willwhite** [mapbox/mapbox-gl-native#10015]
This is related, but different from https://github.com/mapbox/mapbox-gl-native/issues/9103. I appear to have an old traffic tile with stale data stuck in a for multiple hours.

**Platform:** iOS
**Mapbox SDK version:**

### Steps to trigger behavior

 1. Zooming in and out will occasionally reveal vertical tearing between zoom levels
2. Most of the time this fixes itself automatically as caches clear and sync up. Occasionally, I find a "stuck" tile.

## Screenshots + timeline

Exploring the traffic map at 9/16/2017 17:37 ET and traffic looks bad on I-395, but zooming in a bit reveals some tearing at what looks like a tile boundary and I-395 looks clear (green). Seven minutes later, at 17:44 a few segments in neighboring tiles have changed, but the tears are still visible.

Later, at 20:47 ET, traffic has cleared on I-395 so there is not obvious tearing there. But there are less prominent spots of tearing along what looks like a tile boundary and other cases of stale traffic data.

This morning, 9/17/2017, at 10:41 ET, we still see the same pattern of traffic.

Between each set of screenshots, I fully shut down the app and restarted it. Before taking the last set of screenshots, I restarted my phone.

![untitled](https://user-images.githubusercontent.com/93564/30522260-224e62a8-9b9b-11e7-8aa8-7f34c1012f8f.png)

To ensure that the server was not the source of the stuck tile, I checked the traffic map using [this tool](https://www.mapbox.com/get-directions) and recorded the animation below at 17:44 ET on 9/16/2017. All tiles appear to be rendering correctly with no obvious tearing.

![staletraffic](https://user-images.githubusercontent.com/93564/30522319-385fc5c2-9b9c-11e7-8a47-c8386399f2d4.gif)

I will continue to check to see if the stuck tile is eventually cleared. Is there any debug information that I can provide? Is there a way to examine the cache on my device?

**Comment by willwhite** [comment]
I did some debugging with @1ec5 today. He had me try opening this style in the Mapbox Studio Preview app - the style looked ok, so it's looking more like I have an old tile stuck in an app-specific cache.

As of 19:34 today the tile is still stuck:

![untitled 2](https://user-images.githubusercontent.com/93564/30525966-c5ed2c8e-9bdf-11e7-8a62-a87acff30d4b.png)

**Comment by mb12** [comment]
@willwhite Do you see this issue even if you re-start the application? The file/sqlite cache supports expiring tiles based on http headers, the same is not available in in-memory cache. So if a tile lands in memory cache, it won't be evicted based on expiry headers.

**Comment by friedbunny** [comment]
I wonder if the [tile timestamp debug mode](https://www.mapbox.com/ios-sdk/api/3.6.3/Enums/MGLMapDebugMaskOptions.html#/c:@E@MGLMapDebugMaskOptions@MGLMapDebugTimestampsMask) would be useful here.

**Comment by willwhite** [comment]
@mb12 yes between each set of screenshots I restarted the app.

**Comment by willwhite** [comment]
This is from today at 11:13 ET after an app upgrade:

![image](https://user-images.githubusercontent.com/93564/30775769-4a320852-a068-11e7-98d0-b0ff6368110b.png)

This only thing I haven't tried yet is a full app reinstall. Should I give this a try?

**Comment by willwhite** [comment]
I used the Studio Preview app to isolate what I think is the problem tile:

![image](https://user-images.githubusercontent.com/93564/30775943-78608656-a06b-11e7-862c-7ac0c2fd66df.png)

This tile look like this from the static tile API:

![](https://api.mapbox.com/styles/v1/willwhite/cj1o35lem002s2sqrhlz4xh8y/tiles/14/4687/6268?access_token=pk.eyJ1Ijoid2lsbHdoaXRlIiwiYSI6ImNpamV3dTdhbTAwMTB0Zm01MGY1OGRtaDIifQ.NkgyaKN3zpCZ8jRZ0Zjfjg#14.37/38.8779/-76.9814)

I'm assuming that the last-modified date displayed the debug screen correspond to the mapbox-streets tile because I'm currently seeing a last-modified of `Sat, 23 Sep 2017 18:25:10 GMT` for this tile.

```
curl -I "https://b.tiles.mapbox.com/v4/mapbox.mapbox-traffic-v1/14/4687/6268.vector.pbf?access_token=pk.eyJ1IjoiZGFucGF0IiwiYSI6ImI0WThCVWMifQ.BP_j7Kiv5SNL-p-kTfXNxgWills-MacBook:~ willwhite$ curl -I "https://b.tiles.mapbox.com/v4/mapbox.mapbox-traffic-v1/14/4687/6268.vector.pbf?access_token=pk.eyJ1IjoiZGFucGF0IiwiYSI6ImI0WThCVWMifQ.BP_j7Kiv5SNL-p-kTfXNxg"
HTTP/1.1 200 OK
Content-Type: application/x-protobuf
Content-Length: 14930
Connection: keep-alive
Date: Sat, 23 Sep 2017 18:29:41 GMT
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET
Timing-Allow-Origin: *
X-Rate-Limit-Limit: 100000
X-Rate-Limit-Interval: 60
X-Rate-Limit-Reset: 1506191441
Content-Encoding: gzip
Last-Modified: Sat, 23 Sep 2017 18:25:10 GMT
ETag: "f0c3e2b549d8b77d2483a143e0cc0990"
Expires: Sat, 23 Sep 2017 18:31:47 GMT
X-Cache: Miss from cloudfront
Via: 1.1 978c00aff85cbe1b9a35711178037d78.cloudfront.net (CloudFront)
X-Amz-Cf-Id: Uj2zpQhPPf_hEGJDCDyLcujfaWJqzslUU6XGgQMa1_DLSyyUr7qbaA==
```

**Comment by kkaefer** [comment]
I've investigated this further. The particular tile 14/4687/6268 had an expiration timestamp of 3,007,871,190, which is March 25, 2065. This number looks suspiciously close to twice timestamp of the `modified` column (~1,506,692,782), with a difference of only 888 seconds. I was able to track this down to this line, where we add `delta`: https://github.com/mapbox/mapbox-gl-native/blob/4bb25e8bc16e433c1cd1527cc7c622af0546d0a9/platform/default/online_file_source.cpp#L297

In some situations, `delta` is a full timestamp, namely when `*prior` is 0 here: https://github.com/mapbox/mapbox-gl-native/blob/4bb25e8bc16e433c1cd1527cc7c622af0546d0a9/platform/default/online_file_source.cpp#L285

We explicitly set it to 0 when a preceding optional cache request fails, and proceed to make an actual HTTP request here: https://github.com/mapbox/mapbox-gl-native/blob/4bb25e8bc16e433c1cd1527cc7c622af0546d0a9/src/mbgl/tile/tile_loader_impl.hpp#L65

However, the whole `interpolateExpiration` function body only gets executed when the condition at the top fails, in particular when the expiration timestamp returned by the server is *less than or equal* the current time. This very rarely happens with our servers, but it could sometimes happen, e.g. when the expiration time of the tile the server is returning is only a few seconds into the future, and either the clock on the device is out of sync, or the response takes a few seconds to reach the device (e.g. a high latency network). This issue exists with all tiles, but is particularly apparent with traffic tiles, that—due to the nature of its contents—have a very short expiration timeout, making almost-but-not-quite expired tiles more frequent.

A fix for this could be as simple as checking whether the `prior` field is 0, and treating it as an empty/invalid value. A more long term solution would be to refactor the way we handle all of the `prior*` fields, and remove the need to arbitrarily set one `prior*` optional to a non-empty value to get past this check, which avoids checking the offline cache again: https://github.com/mapbox/mapbox-gl-native/blob/4bb25e8bc16e433c1cd1527cc7c622af0546d0a9/platform/default/default_file_source.cpp#L128-L131

An even longer term solution would be to remove the need to do distinct optional/required requests altogether; optional-only requests are only used in a small number of situations anyway.

**Comment by 1ec5** [comment]
> A fix for this could be as simple as checking whether the prior field is 0, and treating it as an empty/invalid value.

Looks like this fix was implemented in #10124 and backported to the release-agua branch (for Android SDK v4.2.0 and iOS SDK v3.7.0) in #10186.

**Comment by lilykaiser** [comment]
Can this be closed?

**Comment by 1ec5** [comment]
https://github.com/mapbox/mapbox-gl-native/issues/10015#issuecomment-334286498 identifies a couple more robust fixes. @kkaefer, do you think we still need to implement them, given the more tightly scoped fix we’ve already landed?

**Comment by kkaefer** [comment]
We've implemented the "more long term solution" mentioned above.
