### ISSUE TITLE
Rebuild gestures from the ground up

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#10016]
Since the initial release of the Android Maps SDK we have been using the [almeros](https://github.com/Almeros/android-gesture-detectors) gesture library as base for our gesture interactions. While we customized / worked around a couple of issues found in the library. There are some fundamental design decisions we can't workaround (eg. allowing invocation of multiple 2 finger gesture detectors at same time). This issue tracks the requirements around rebuilding it from the ground up. 

Touch handlers exposed by android support library*:
 - onScale
 - onFling
 - onScroll
 - onSingleTapConfirmed / onSingleTapUp
 - onLongPress
 - onDoubleTap / onDoubleTapEvent

Missing touch handlers
 - onRotate
 - onShove (changing tilt)

(*) some of these are currently implemented with Almeros

Missing functionality on Almeros
 - having a velocity to calculate an animation instead of setting incoming values directly.

**Comment by dallasgutauckis** [comment]
I want to add some commentary on an issue I'd like to see improved/resolved. [SeatGeek](https://play.google.com/store/apps/details?id=com.seatgeek.android) uses Mapbox to display event seating charts with prices and deals on the map. The most important gesture functionality is tapping, panning, and zooming (in and out). We've noticed recent versions (5.1.4: https://github.com/mapbox/mapbox-gl-native/issues/10102#issuecomment-334741779) have a considerably "broken" experience (esp. when compared to Google Maps, for instance) with zooming due to the distance required between two fingers to zoom (both in and out). 5.2.0 claims to have made some improvements, but it's arguably jankier at zooming than 5.1.* versions, especially with the new inertial zooming functionality.

I ran an in-person test with people using 5.1.4 of Mapbox in our Android app and observed 37% percent of users unable to zoom the map effectively due to the 2-finger distance concern.

I'll be happy to provide additional input as this issue gets worked on, and it's possible someone from our team can also work on code for this in the not-too-distant future.
