### ISSUE TITLE
incorrect MGLPolyline when passing International Date Line

### ISSUE THREAD

**Issue by mic88101** [mapbox/mapbox-gl-native#10127]
The MGLPolyline will not be displayed correctly once two points at different sides of the International Date Line.

Platform: iOS
Mapbox SDK version: found in 3.70 alpha, 3.6.4 and 3.6.3

**Code**

```
// example of a line passing the International Date Line
let coordAsia = CLLocationCoordinate2D(latitude: 27.0, longitude: 179.0)
let coordUS = CLLocationCoordinate2D(latitude: 34.0, longitude: -179.0)
let line = MGLPolyline(coordinates: [coordUS, coordAsia], count: 2)
self.add(line)
```

**Expected behavior**
The line in the example should cross the International Date Line from Asia then reach US, which is the shortest way between two points.

**Actual behavior**
The line start from Asia and then go West, reach US after passing Europe.

**Comment by jfirebaugh** [comment]
This is expected behavior; Mapbox GL does not try to guess whether the shortest path or the longest path is desired. Instead it supports an explicit mechanism to indicate the intent: if you want a line crossing the antimeridian, then use a longitude coordinate greater than 180 (or less than -180) for one of the two points.
