### ISSUE TITLE
Problem with map on two fragments

### ISSUE THREAD

**Issue by ufocom** [mapbox/mapbox-gl-native#10227]
Hi,
I have two fragments, FragmentA and FragmentB. On both of them i have added in my layout:
` <com.mapbox.mapboxsdk.maps.MapView
                android:id="@+id/mapView"
                android:visibility="gone"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                mapbox:mapbox_cameraTargetLat="34.01591350351023"
                mapbox:mapbox_cameraTargetLng="-118.4945560781314"
                mapbox:mapbox_cameraZoom="14.5"
                mapbox:mapbox_styleUrl="mapbox://styles/mapbox/streets-v10" />`
On both this fragment map has visibility gone. FragmentB is opened from FragmentA.

What is a problem step by stem:
1. FragmentA - show map
2. FragmentA - hide map
3. From fragmentA open fragmentB(fragmentTransaction.add(R.id.content, newFragment,
                "FRAGMENT" + (getSupportFragmentManager().getBackStackEntryCount() + 1));)
4. FragmentB - show map - and there is problem because on foreground I have map from fragmentA and map for FragmentB is on background.

**Comment by tobrun** [comment]
@ufocom this is because the way surfaces work on Android. There are a couple of workarounds though I would suggest using 1 map per activity. Workarounds include using TextureView as render surface (this behaves differently than the (GL)SurfaceView) or use `zMediaOverlay` in MapboxMapOptions to bring a surface to the front. You can read more about this surfaces in the [SurfaceView](https://developer.android.com/reference/android/view/SurfaceView.html) documentation. I'm calling this issue not actionable for us. Let us know if you have any more questions.
