### ISSUE TITLE
Crash when only first launch after installed an app.

### ISSUE THREAD

**Issue by noramimiyuma** [mapbox/mapbox-gl-native#10264]
**Platform:**
iPhone7 iOS 11.0.3

**Mapbox SDK version:**
ios-v3.7.0-beta.2

### Steps to trigger behavior
 1. In advance, If the application has already been installed, uninstall it.
 2. Build and Run the app.
 3. Load the viewController what MGLMapView is used.
 4. Crash while loading the viewContoller.
 5. However, it will operate normally on the second and following launches.

<img width="1160" alt="2017-10-24 11 31 42" src="https://user-images.githubusercontent.com/15150828/31922554-97331a64-b8b0-11e7-9297-cf782a92f0cb.png">

**Comment by noramimiyuma** [comment]
More details below. 

The local databases create on first launch the app.
At that time, the following information and error are output.

```
[ERROR] {}[Database]: no such table: cfurl_cache_response (Code 1)
[INFO] {com.mapbox.mbgl.DefaultFileSour}[Database]: cannot open file at line 38280 of [0e5ffd9123] (Code 14)
[INFO] {com.mapbox.mbgl.DefaultFileSour}[Database]: [0e5ffd9123]:38280: (3) open(/Users/***/****/****/.mapbox/cache.db) -  (Code 14)
```

In addition, it outputs information on the Google Analytics library database. (Google Analytics also coexists with this project)

```
[INFO] {GAIThread}[Database]: statement aborts at 12: [SELECT name FROM sqlite_master WHERE type='table' AND name=?] database schema has changed (Code 17)
```

Furthermore, at the second launch

```
[INFO] {}[Database]: recovered 82 frames from WAL file /Users/***/***/***/Cache.db-wal (Code 283)
[INFO] {GAIThread}[Database]: recovered 12 frames from WAL file /Users/***/***/***/***/Library/googleanalytics-v2.sql-wal (Code 283)
[INFO] {GAIThread}[Database]: recovered 29 frames from WAL file /Users/***/***/***/***/Library/googleanalytics-v3.sql-wal (Code 283)
```

**Comment by boundsj** [comment]
@noramimiyuma I think these look like normal exceptions that happen on the first run related to the underlying database that is used by our Maps SDK's core implementation. 

Is this really a "crash" or do you have an all exceptions breakpoint set so that you are stopping in the debugger? I'm not able to reproduce an actual crash. Also, thanks for helping us test our beta releases! Please make sure you are on the latest one that is now https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.7.0-beta.2
