### ISSUE TITLE
remove delay argument from notifyMapChange

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#1026]
It shouldn't be the responsibility of the view implementation to set up a timer to resend the notification after a delay -- notifications should just be dispatched at the right time.

**Comment by incanus** [comment]
This is not a delay; it relates to the animation timeouts used. For example, if Cocoa tells the map to move on a `300ms` animation, the `Map`/`Transform` are authoritative on whether that animation completed or not, and should send the completion notification at the end of the delay.

**Comment by incanus** [comment]
For context on the need for these, see callbacks like `-[MKMapViewDelegate mapView:regionDidChangeAnimated:]`. 

https://developer.apple.com/library/ios/documentation/MapKit/Reference/MKMapViewDelegate_Protocol/index.html#//apple_ref/occ/intfm/MKMapViewDelegate/mapView:regionDidChangeAnimated:

**Comment by jfirebaugh** [comment]
> the `Map` / `Transform` are authoritative on whether that animation completed or not, and should send the completion notification at the end of the delay

They should be -- that's what I'm suggesting in this issue. But it doesn't look to me like that's the current behavior.

See, e.g.

https://github.com/mapbox/mapbox-gl-native/blob/b4dbba93f868b4d44d0f858a9c54924b910ef62d/src/mbgl/map/transform.cpp#L286-L289

and 

https://github.com/mapbox/mapbox-gl-native/blob/b4dbba93f868b4d44d0f858a9c54924b910ef62d/platform/ios/MGLMapView.mm#L1629-L1637

**Comment by jfirebaugh** [comment]
Also `MGLMapView` shouldn't need to dispatch `notifyMapChange` manually:

https://github.com/mapbox/mapbox-gl-native/blob/b4dbba93f868b4d44d0f858a9c54924b910ef62d/platform/ios/MGLMapView.mm#L586-L598

**Comment by incanus** [comment]
> Also `MGLMapView` shouldn't need to dispatch `notifyMapChange` manually:

It does this because each platform is responsible for the velocity-based deceleration that feels right on that platform, which means differing durations.

**Comment by jfirebaugh** [comment]
Sure. But the point of this bug is: given an easing operation is started on `Map` with a particular duration, then `Map` should have sole responsibility for dispatching notifications of the progress of that easing operation.

Make sense?

**Comment by incanus** [comment]
Not just the easing duration, but also the timing curve, are done Cocoa-side. This isn't done as an atomic duration on the GL side, but rather a series of sub-durations. 

https://github.com/mapbox/mapbox-gl-native/blob/b4dbba93f868b4d44d0f858a9c54924b910ef62d/platform/ios/MGLMapView.mm#L570-L584

But you only want one notification. 

I'm not saying this is the best/only way, but giving some context for why it is how it is now and why it might be the only way.

**Comment by jfirebaugh** [comment]
> But you only want one notification.

If this is necessary, then the notifications have to be done entirely Cocoa-side, and the `MBGLView::notifyMapChange` implementation should be a no-op.

The current behavior is that each call to `mbglMap->moveBy` generates a `MapChangeRegion[Will/Did]Change[Animated]` notification pair, and then MGLMapView dispatches another `MapChangeRegionDidChangeAnimated` notification of its own.

**Comment by incanus** [comment]
> the MBGLView::notifyMapChange implementation should be a no-op

FWIW, I introduced this whole system in order to start tapping into render lifecycle events to an extent that we've not been able to before, in order to get at things like `-[MKMapViewDelegate mapViewDidFinishRenderingMap:fullyRendered:]` that devs need in order to do detailed view interplay with maps. 

https://developer.apple.com/library/ios/documentation/MapKit/Reference/MKMapViewDelegate_Protocol/index.html#//apple_ref/occ/intfm/MKMapViewDelegate/mapViewDidFinishRenderingMap:fullyRendered:

Perhaps using it for viewport changes as well **is** ill-advised. It's sounding like it.

**Comment by jfirebaugh** [comment]
> But you only want one notification.

From [the docs](https://developer.apple.com/library/ios/documentation/MapKit/Reference/MKMapViewDelegate_Protocol/index.html#//apple_ref/occ/intfm/MKMapViewDelegate/mapView:regionWillChangeAnimated:), it doesn't sound to me like this is true. Both `- mapView:regionWillChangeAnimated:` and `- mapView:regionDidChangeAnimated:` state:

> During scrolling, this method may be called many times to report updates to the map position. Therefore, your implementation of this method should be as lightweight as possible to avoid affecting scrolling performance.

**Comment by incanus** [comment]
I meant one notification in the context of one per set of changes — if you make one move, you may get one notification out of MapKit, but for the equivalent change in GL, you might get a `willChangeAnimated:YES` because the system knows that you are kicking off an animation viewport change, then get a series of `didChangeAnimated:` with either `YES` or `NO` depending on how well you are tracking the kickoff notification and how the current one relates to it. 

Additionally, our raster SDK improved upon Apple's implementation to make this more reliable for the user, posting only a single `will` and a single `did` notification (while still offering `mapViewRegionDidChange` for those who needed continuous updates), plus [separated them out](https://github.com/mapbox/mapbox-ios-sdk/blob/release/MapView/Map/RMMapViewDelegate.h#L123-L138) as to whether they were gesture- (examples: finger gestures, compass tap, or tracking mode change) or system-induced (e.g. updating user location tracking or a programmatic change related to change of another UI element). 

We are basically walking a line somewhere between MapKit and up to / ideally including our raster SDK's behavior here.

**Comment by jfirebaugh** [comment]
> while still offering `mapViewRegionDidChange` for those who needed continuous updates

I think you meant `mapViewRegionIsChanging` -- I didn't realize this existed, and now thing make more sense. So the intended series of events:

For an unanimated change:

* `RegionWillChange`
* `RegionDidChange`

For an animated change:

* `RegionWillChangeAnimated`
* `RegionIsChanging` (repeated)
* `RegionDidChangeAnimated`

**Comment by incanus** [comment]
Yeah, exactly — that flow captures it just right. These are things devs want (in addition to rendering start/finish and user interaction indication, which are out of scope here maybe) in order to sync up other UI elements.
