### ISSUE TITLE
Add option to restrict camera to bounding box

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox-gl-native#10302]
Currently, the Android Maps SDK has two options for restricting map panning: disable it completely, or don't allow the camera to move a single centerpoint out of view. 

It would be helpful to be able to restrict the camera to a bounding box as well.

**Comment by himumsaiddad** [comment]
This is currently supported on iOS and it is a very useful feature for implementing custom map overlays that cover a particular area and number of zoom levels.

**Comment by tobrun** [comment]
@himumsaiddad have you see the functionality [here](https://github.com/mapbox/mapbox-gl-native/pull/8622)? this should cover the general use case of limiting your end user. Besides using `setLatLngBoundsForCameraTarget`, you can also use `MapboxMap#setMinZoomPreference` and `MapboxMap#setMaxZoomPreference`.

**Comment by tobrun** [comment]
Since we expose an similar core function already, see https://github.com/mapbox/mapbox-gl-native/issues/10302#issuecomment-340537954. I feel we should implement this as a plugin instead as we can build this on the existing public api. Tracking this downstream in the plugins repo [here](https://github.com/mapbox/mapbox-plugins-android/issues/692).
