### ISSUE TITLE
[core] Allow reference to another layer in style converter

### ISSUE THREAD

**Issue by ChristopherUNIS** [mapbox/mapbox-gl-native#10401]
Allow the use of "ref" layer style property to clone another layer style from Qt.

**Comment by brunoabinader** [comment]
Can you please provide more details? As in e.g. we don't currently have `ref`as a layer style property in the [layer style specification](https://www.mapbox.com/mapbox-gl-js/style-spec/#layers).

**Comment by ChristopherUNIS** [comment]
This property allow to"inherit" another layer properties

Actually it exists but I don't why it is not shown on the website, see the spec here : https://github.com/mapbox/mapbox-gl-style-spec/blob/7efdb9ebc10efd4a54237e0e43900f21d2ac9a7a/reference/v8.json#L349

Also the style parser implements it : https://github.com/mapbox/mapbox-gl-native/blob/9aac976104f4c6453cf9e79e03a002565720f213/src/mbgl/style/parser.cpp#L233

**Comment by ChristopherUNIS** [comment]
For instance it used all over the place in some default styles :

https://github.com/mapbox/mapbox-gl-styles/blob/master/styles/bright-v8.json

**Comment by brunoabinader** [comment]
@ChristopherUNIS thanks for flagging this out - Qt, together with other platforms, uses a generic runtime styling conversion mechanism, so this particular issue is not limited to Qt platform.

The underlying problem here is that we ignore the `ref` value when [parsing the runtime-style generated layer](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/style/conversion/layer.cpp#L103-L202), but not when [parsing a style JSON file/URL](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/style/parser.cpp#L233-L262).

**Comment by brunoabinader** [comment]
Turns out `ref` is deprecated and supported only for backward compatibility in full styles (also reason why it doesn't show up in the documentation).
