### ISSUE TITLE
Fix collision box calculation

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#10462]
It looks like we're calculating collision boxes that are too small for some labels:

![mapbox gl streets 2017-11-14 11-36-30](https://user-images.githubusercontent.com/52399/32775620-3cca3f04-c930-11e7-97f9-016d32fd11da.png)

(zoom ~1.7)

This happens on both master and on https://github.com/mapbox/mapbox-gl-native/pull/10436

/cc @ChrisLoer @ansis

**Comment by kkaefer** [comment]
Looks like this is an artifact from collision boxes not changing size after the initial zoom level (overzoomed tile):

![32 37 42 north 58 55 7 east 3 775273046389124 2017-11-14 11-53-36](https://user-images.githubusercontent.com/52399/32776358-95bfd770-c932-11e7-976c-3cc477446637.png)

**Comment by jfirebaugh** [comment]
I believe this may be the same issue as a render test failure I've been debuggins as part of porting native's "possibly evaluated" property types to JS. The problem is that `SymbolLayout::addFeature` expects to be able to evaluate `text-size` and `icon-size` at `zoom + 1`:

https://github.com/mapbox/mapbox-gl-native/blob/3bef7593a64a51e86dd5a2ed9fd36b4a143350b0/src/mbgl/layout/symbol_layout.cpp#L268-L269

However, `layout` here is `SymbolLayoutProperties::PossiblyEvaluated`. `PossiblyEvaluated` is an optimization to avoid re-evaluating constants and camera functions for every feature -- what it means is "evaluated if the original value was a constant or camera function, unevaluated if the original value was a source or composite function". In the former case, `evaluate` just returns the value previously evaluated for `zoom`, and the `zoom + 1` input is ignored:

https://github.com/mapbox/mapbox-gl-native/blob/3bef7593a64a51e86dd5a2ed9fd36b4a143350b0/src/mbgl/style/properties.hpp#L154-L156

**Comment by jfirebaugh** [comment]
I think the fix I'm going to make in JS is to remove the `zoom` parameter from `PossiblyEvaluated`, and instead make it a member variable that gets set when the `PossiblyEvaluated` is created as a result of (possibly) evaluating properties at a certain zoom level. This will make it clear that you can't supply a different zoom level at the final evaluation step. `SymbolLayout` will then need to create individual `PossiblyEvaluatedPropertyValue`s for `text-size` and `icon-size` at `zoom + 1`, and use those for final evaluation in `addFeature`.

**Comment by jfirebaugh** [comment]
Ok, it looks like the fix will be a bit more complicated than that, even. If I'm reading things right, the symbol layout process needs `text-size` evaluated at up to five (!) different zoom levels, and `icon-size` at three:

* `text-size` at the zoom level of the bucket. Used to calculate the box for icon-text-fit (incorrectly: https://github.com/mapbox/mapbox-gl-js/issues/5656)
* `text-size` and `icon-size` at the zoom level of the bucket, plus one. Used to calculate collision boxes.
* `text-size` at zoom level 18. Used for something line-symbol-placement-related?
* For composite `*-size` expressions: `*-size` at the zoom levels of the two stops that "cover" the zoom level of the bucket. This goes into a vertex buffer and is used by the shader to interpolate the size at render time.

**Comment by ChrisLoer** [comment]
When we fix this, we should recheck the render tests currently ignored against #9732, #10409, and #10412 -- it could be the explanation for some or all of the changes we see.
