### ISSUE TITLE
Feature querying ignores antimeridian (was: MGLAnnotationView flickers if annotations are around the antimeridian)

### ISSUE THREAD

**Issue by captainbarbosa** [mapbox/mapbox-gl-native#10479]
**Platform:** iOS
**Mapbox SDK version:** 3.6.4, 3.7.0-rc.1

When placing `MGLAnnotationView`s on a map that closely straddle both sides of the antimeridian, the annotations flicker when zooming/panning. 
- The issue is not seen if `MGLAnnotationView`s are replaced with `MGLAnnotationImage`.
- The issue is not seen if  the `MGLAnnotationView`s reside on one side of the antimeridian.

### Steps to trigger behavior

 1. Create annotations that straddle the antimeridian on both sides
<details>
<summary>Coordinates used for annotations:</summary>

```swift
let coordinates = [CLLocationCoordinate2D(latitude: 28, longitude: -177),
          CLLocationCoordinate2D(latitude: 30.0, longitude: -178.0),
          CLLocationCoordinate2D(latitude: 35.0, longitude: 180.0),
          CLLocationCoordinate2D(latitude: 40.0, longitude: 175.0),
          CLLocationCoordinate2D(latitude: 45.0, longitude: 170.0),
          CLLocationCoordinate2D(latitude: 46.0, longitude: 170.0),
          CLLocationCoordinate2D(latitude: 51, longitude: 175),
          CLLocationCoordinate2D(latitude: 52, longitude: 174)]
```
</details>

 2. Zoom/pan map

 3. Observe flickering

### Expected behavior

`MGLAnnotationView` should not flicker when zooming and panning on the map.

### Actual behavior

`MGLAnnotationView` flickers when zooming and panning on the map.

![giphy 7](https://user-images.githubusercontent.com/10850812/32908836-9e4e4236-cab9-11e7-88d8-a54ad64db626.gif)

**Comment by ericdeveloper** [comment]
I tested this in `3.7` using a circle layer and while the individual circles didn't flicker entire tiles appeared to flicker at the antimeridian.  Trying the same with just the base map displays the same behavior.  
![dec-19-2017 13-43-25](https://user-images.githubusercontent.com/1154419/34180191-a8009b26-e4c2-11e7-852c-59d40f55db14.gif)

**Comment by 1ec5** [comment]
> entire tiles appeared to flicker at the antimeridian

@ericdeveloper, I would imagine that’s a separate issue, since it occurs even in the absence of annotations.

**Comment by 1ec5** [comment]
I believe the root cause of the original issue above is that, in mbgl, the assumption is that a bbox straddling the antimeridian would have one side beyond ±180° longitude. But `mbgl::Render::queryRenderedFeatures` independently converts each screen coordinate in the query’s bounding polygon to a geographic coordinate:

https://github.com/mapbox/mapbox-gl-native/blob/9ed3aeaee10e4c4e44bfe3967db5347576e0633e/src/mbgl/renderer/renderer.cpp#L45-L54
https://github.com/mapbox/mapbox-gl-native/blob/9ed3aeaee10e4c4e44bfe3967db5347576e0633e/src/mbgl/renderer/tile_pyramid.cpp#L217-L229

The reason this only affects annotation views is that non-view-backed annotations (MGLAnnotationImage) and symbol layers don’t rely on feature querying to determine whether to show a given marker. But if you were to use feature querying on a symbol layer, for example to implement interactivity, you’d run into the same problem of symbols becoming non-interactive near the antimeridian.

/ref #4664 #9731 mapbox/mapbox-gl-js#2321
