### ISSUE TITLE
Black renderend around map while scrolling on Android 4.4.x

### ISSUE THREAD

**Issue by Diederikjh** [mapbox/mapbox-gl-native#10565]
**Platform:**
Android 4.4.2 on device Samsung SM-T231 and
Android 4.4.4 on device Samsung SM-T561

**Mapbox SDK version:**
Example is on 5.1.5 with minimal Android getting started application (can't get 5.2.0 running on the device. Crashes on startup with `java.lang.VerifyError: com/mapbox/mapboxsdk/maps/widgets/MyLocationView`)

Link to [github project](https://github.com/Diederikjh/Mapboxplay) with sample code.

### Steps to trigger behavior

 1. Add map to a scrollable view.
 2. Scroll view.

### Expected behavior
Scrolling of the view doesn't render black areas around the map. (Like it does for all our other test devices.)

### Actual behavior
Black renderings below & above the map, depending on the direction of scroll.

[Screen capture](https://www.youtube.com/watch?v=tBkU7FuNawE&feature=youtu.be) of this happening.

**Comment by tobrun** [comment]
for the VerifyError, see https://github.com/mapbox/mapbox-gl-native/issues/10527

for the black rendering, this is expected behavior when using a (GL)SurfaceView as rendering surface. To work around this you can use a TextureView instead (this can either be done through xml `mapbox_renderTextureMode=true` or with `MapboxMapOptions#setTextureMode(true)`)

That said, I wouldn't advice you to put a MapView in a scrollable container. For this kind of UX, using a 
 bitmap of a map will result in a better UX. You can generate map images with the `MapSnapshotter` API. Let's us know if you have any more issues or questions. Going to close this issue as workaround has been given (+ VerifyError ticket was linked).
