### ISSUE TITLE
Question :: Does mapbox android sdk support clustering??????

### ISSUE THREAD

**Issue by mf-mindcrewtech** [mapbox/mapbox-gl-native#10578]
Can anyone please let me know, is there any way to achieve clustering with mapBox sdk, as I need to plot different markers (approx 1000+ )and need to show as clusters.

Thanks, Any help really appreciate.

**Comment by kkaefer** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!

**Comment by nikiizvorski** [comment]
Currently there is no good way to support multiple objects and not even close to a 1000 on the same device will got OutOfMemory straight. You should use a single SymbolLayer and apply what you need on it. Most markers are depricated from the old apis don't put your app logic on them.

**Comment by langsmith** [comment]
@mf-mindcrewtech , we've got a marker cluster plugin for Android. The documentation isn't quite published yet, which is why you hadn't known about it.

Here's the upcoming README about it:
[https://github.com/mapbox/mapbox-plugins-android/blob/e31b6bbb51a806f48a75ada970d2039405349a55/plugin-cluster/README.md](https://github.com/mapbox/mapbox-plugins-android/blob/e31b6bbb51a806f48a75ada970d2039405349a55/plugin-cluster/README.md)

Upcoming Android demo app marker cluster plugin example: [https://github.com/mapbox/mapbox-android-demo/blob/f05feea9599aee09df69589cf9c840dd356e62df/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/plugins/MarkerClustersPluginActivity.java](https://github.com/mapbox/mapbox-android-demo/blob/f05feea9599aee09df69589cf9c840dd356e62df/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/plugins/MarkerClustersPluginActivity.java)

[Current marker cluster plugin code](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-cluster)

Thanks for using Mapbox!
