### ISSUE TITLE
Link of class LocationSource failed

### ISSUE THREAD

**Issue by olsisaqe** [mapbox/mapbox-gl-native#10660]
**Platform:**
Android 4.4.2
Samsung GT-I9301I
**Mapbox SDK version:**
5.2.0

### Steps to trigger behavior
It gives a runtime error for MapView inflation
It works perfectly for Mapbox 5.1.4. 
Worth to mention that my app has multidexing enabled. 

### Expected behavior
Not having runtime error for class linking

### Actual behavior
crashes on inflation of the MapView:
```12-08 10:49:49.276 13877-13877/com.moovel.demo W/dalvikvm: Link of class 'Lcom/mapbox/mapboxsdk/location/LocationSource;' failed
12-08 10:49:49.276 13877-13877/com.moovel.demo W/dalvikvm: VFY: unable to find class referenced in signature (Lcom/mapbox/mapboxsdk/location/LocationSource;)
12-08 10:49:49.276 13877-13877/com.moovel.demo W/dalvikvm: VFY: storing type 'Ljava/lang/Object;' into field type 'Lcom/mapbox/services/android/telemetry/location/LocationEngine;' (Lcom/mapbox/mapboxsdk/maps/widgets/MyLocationView;.locationEngine)
12-08 10:49:49.276 13877-13877/com.moovel.demo W/dalvikvm: VFY:  rejecting opcode 0x5b at 0x0000
12-08 10:49:49.276 13877-13877/com.moovel.demo W/dalvikvm: VFY:  rejected Lcom/mapbox/mapboxsdk/maps/widgets/MyLocationView;.init (Lcom/mapbox/mapboxsdk/location/LocationSource;)V
12-08 10:49:49.276 13877-13877/com.moovel.demo W/dalvikvm: Verifier rejected class Lcom/mapbox/mapboxsdk/maps/widgets/MyLocationView;
12-08 10:49:49.276 13877-13877/com.moovel.demo W/dalvikvm: Class init failed in Constructor.constructNative (Lcom/mapbox/mapboxsdk/maps/widgets/MyLocationView;)
12-08 10:49:49.276 13877-13877/com.moovel.demo W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x417b5da0) ```

**Comment by tobrun** [comment]
Thank you for the report, fixed with #10579, available in the 5.2.1 release.

**Comment by olsisaqe** [comment]
With the release 5.2.1 we don't crash but the error in the logs is still there and also the `MapView` doesnt determine the current location (since no source was attached I think). Here the log: 

```12-08 14:13:17.007 8146-8146/com.moovel.demo I/FirebaseInitProvider: FirebaseApp initialization successful
12-08 14:13:17.067 8146-8146/com.moovel.demo I/dalvikvm: Failed resolving Lcom/mapbox/mapboxsdk/location/LocationSource; interface 2260 'Lcom/mapzen/android/lost/api/LostApiClient$ConnectionCallbacks;'
12-08 14:13:17.067 8146-8146/com.moovel.demo W/dalvikvm: Link of class 'Lcom/mapbox/mapboxsdk/location/LocationSource;' failed
12-08 14:13:17.067 8146-8146/com.moovel.demo W/dalvikvm: Unable to resolve superclass of Lcom/mapbox/mapboxsdk/EmptyLocationSource; (4243)
12-08 14:13:17.067 8146-8146/com.moovel.demo W/dalvikvm: Link of class 'Lcom/mapbox/mapboxsdk/EmptyLocationSource;' failed
12-08 14:13:17.067 8146-8146/com.moovel.demo E/dalvikvm: Could not find class 'com.mapbox.mapboxsdk.EmptyLocationSource', referenced from method com.mapbox.mapboxsdk.Mapbox.getLocationSource
12-08 14:13:17.067 8146-8146/com.moovel.demo W/dalvikvm: VFY: unable to resolve new-instance 1982 (Lcom/mapbox/mapboxsdk/EmptyLocationSource;) in Lcom/mapbox/mapboxsdk/Mapbox;```

**Comment by tobrun** [comment]
cc @Guardiola31337

**Comment by Guardiola31337** [comment]
Hey @olsisaqe 👋

```java
mapView.getMapAsync(new OnMapReadyCallback() {
      @Override
      public void onMapReady(@NonNull final MapboxMap mapboxMap) {
        mapboxMap.setMyLocationEnabled(true);
      }
});
```

Tested ☝️ in a simple activity of a new project and although it takes more time to get the first fix (because of `AndroidLocationEngine`), the current location view is displayed on the map 👀

![location_pre_19](https://user-images.githubusercontent.com/1668582/33876951-3a09f752-df27-11e7-8b5e-fea31df7198d.png)

_GP-Peak Android 4.0.4_

Per mapbox/mapbox-gl-native#9488 the location provider is optional (we're not including Lost within the SDK anymore) which means that you need to include the `ACCESS_FINE_LOCATION` permission in your `AndroidManifest.xml` file

```xml
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
```

and maybe [Lost](https://github.com/mapzen/lost) or Google Play Services dependencies if the default location engine (`AndroidLocationEngine`) doesn't fit your needs.

For further information on making the location provider optional, you can check #9403 and the implementation details mapbox/mapbox-java#502

In any case, `MyLocationView` and related classes are deprecated, you should use the [location layer plugin](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugins/locationlayer) instead. Documentation for the location layer plugin is available on https://www.mapbox.com/android-docs/plugins/overview/location-layer/.

With regard to the log, it's an unfortunate warning but it's expected. If you run Mapbox Maps SDK on pre 19 Android devices, dalvikvm's verifier will warn about the missing methods. This isn't a problem and you can ignore the warnings.

Feel free to open new tickets if you have any other questions 😉
Closing.
