### ISSUE TITLE
MGLPointAnnotation's coordinate property not updated during associated MGLAnnotationView drag event.

### ISSUE THREAD

**Issue by joninsky** [mapbox/mapbox-gl-native#10779]
**Platform: iOS 11.2* iPhone X*
**Mapbox SDK version: 3.7.1**

### Steps to trigger behavior

 1. Sub class `MGLAnnotationView` and override `setDragState`

```swift
class UEMapHingeView: MGLAnnotationView {

    let greenBall = UIView(frame: CGRect(x: 13, y: 13, width: 26, height: 26))

    override public init(frame: CGRect) {
        super.init(frame: frame)
        self.prepare()
    }
    
    override public init(reuseIdentifier: String?) {
        super.init(reuseIdentifier: reuseIdentifier)
        self.prepare()
    }
    
    override public init(annotation: MGLAnnotation?, reuseIdentifier: String?) {
        super.init(annotation: annotation, reuseIdentifier: reuseIdentifier)
        self.prepare()
    }
    
    required public init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        self.prepare()
    }

    override func setDragState(_ dragState: MGLAnnotationViewDragState, animated: Bool) {
        super.setDragState(dragState, animated: animated)
        switch dragState {
        case .starting:
            if let loc = self.annotation?.coordinate {
                print("Start Drag: \(loc)")
            }
        case .dragging:
             if let loc = self.annotation?.coordinate {
                print("During Drag: \(loc)")
            }
        case .ending, .canceling:
            if let loc = self.annotation?.coordinate {
                print("End Drag: \(loc)")
            }
        case .none:
            return
        }
    }

    func prepare() {
        self.greenBall.layer.cornerRadius = 13
        self.greenBall.backgroundColor = UEColor.lime.one
        self.addSubview(self.greenBall)
        self.isDraggable = true
        self.scalesWithViewingDistance = false
    }
}
```

### Expected behavior

The `.annotation?.coordinate` property accurately reflects the currently dragged location of the `MGLAnnotationView`. Specifically during a `.dragging` event.

### Actual behavior

The location of the `.annotation?.coordinate` property always shows the original location of the `MGLAnnotationView`'s annotation until a `.ending` or `.canceling` event occurs.

**Comment by arthurhammer** [comment]
This is how MapKit's `MKAnnotationView` works too so I'd say this is expected behaviour.

**Comment by joninsky** [comment]
The Google Maps `GMSMarker.position` property accurately reflects the coordinates of a "dragging" marker. 

You just set `GMSMarker.draggable = true` and then print out the `.position` property in the maps delegate call back print out the `.position` property. It changes while dragging.

```swift
public func mapView(_ mapView: GMSMapView, didDrag marker: GMSMarker) {
   print(marker.position)
}
```

[`GMSMarker` reference](https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_marker)

I can think of two reasons that this would be useful. Lets say you let the user position something on a map with coordinates. You let them drag around a marker and show the coordinates while they are moving the marker. Second, lets say you want a poly line with hinges. You want to let the user manipulate the poly line by moving one of the hinges. With the current set up you could not update the underlying poly line.

Finally, @arthurhammer I though Map Box was supposed to be better than Map Kit.

**Comment by 1ec5** [comment]
This annotation view API was designed to match MapKit’s for the most part. This method was originally intended as a hook for customizing the view’s appearance based on the annotation model object, not necessarily for updating application logic.

Since #5561, we don’t seem to have a hook for updating application logic along the lines of Google’s `GMSMapViewDelegate.mapView(_:didDrag:)` method. I think it would be worth reintroducing `MGLMapViewDelegate.mapView(_:didDrag:)` and possibly introducing a new `mapView(_:isDragging:to:)` to go along with it, which would support the use cases above much better than simply updating the annotation model’s coordinates.

In the meantime, if you need to know current in-flight coordinate, you can obtain that information via the view’s screen coordinates, provided you have access to the map view:

```swift
if let mapView = superview as? MGLMapView {
    let inFlightCoordinate = mapView.convert(center, toCoordinateFrom: mapView)
}
```

**Comment by nitaliano** [comment]
@joninsky for what it's worth react-native-maps has an implementation for getting the current position of a marker while dragging it with MapKit https://github.com/react-community/react-native-maps/blob/master/lib/ios/AirMaps/AIRMapManager.m#L624 this is what @1ec5 was mentioning above and you can follow the same pattern.  I've never tried it with Mapbox but I've had success with being able to update the polyline hinges with MapKit, so there doesn't seem to be any reason why it wouldn't work with Mapbox since the APIs are similar.
