### ISSUE TITLE
E/Exiting with error virtual void izat_manager::IzatPassiveLocationListener::onLocationChanged(const izat_manager::IzatLocation*, izat_manager::IzatLocationStatus) line 113 "1"

### ISSUE THREAD

**Issue by edifangyi** [mapbox/mapbox-gl-native#10801]
Platform:
Chinese brand：E人E本
Android 6.0

Mapbox SDK version:
Android

APK:
Google Play Demo

### Steps to trigger behavior

User location  -> All functions

Log:
E/Exiting with error virtual void izat_manager::IzatPassiveLocationListener::onLocationChanged(const izat_manager::IzatLocation*, izat_manager::IzatLocationStatus) line 113 "1"

screenshot：
https://ws1.sinaimg.cn/mw690/648b709cgy1fmub46wwz7j22ao3284qq.jpg

https://ws1.sinaimg.cn/mw690/648b709cgy1fmub5npr8kj22ao328npd.jpg

https://ws1.sinaimg.cn/large/648b709cgy1fmub6q9jb0j22ao3281ky.jpg

**Comment by tobrun** [comment]
@edifangyi it's not clear from above message what your issue is. Capturing from your screenshots and logs it's related to location. With the upcoming release we have deprecated all things location and moved to a separate location layer plugin instead. See [here](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-locationlayer) for more details. Closing this as non-actionable.

**Comment by abhimangalms** [comment]
That same error happened to me also. But could'nt find any solution.

**Comment by AndroidDrone** [comment]
That same error happened to me also. But could not find any solution.

**Comment by tobrun** [comment]
Happy to eyes this more if a minimal reproducible example can be provided. Can you create a new issue for that?
