### ISSUE TITLE
Could not build module 'Mapbox' & Cannot define category for undefined class 'MGLMapView' in MGLMapView+IBAdditions.h

### ISSUE THREAD

**Issue by afxwin** [mapbox/mapbox-gl-native#10824]
**Note: Freshly created project works fine with the production ready Mapbox SDK, but the issue does occur when bringing Mapbox SDK to an existing project. Although it may look like a usage issue, the errors and workaround (at the bottom of the post) seem to suggest it has something to do with the Mapbox source code? I am trying to provide as many details as possible for your diagnoses, however, the issue may be difficult for you to reproduce. Hopefully we can figure out the root cause together. Please let me know what other information should be provided. Thank you.**

**Platform:**
Xcode 9.1 (9B55) on macOS Sierra Version 10.12.6

**Mapbox SDK version:**
3.7.2 SDK & custom dynamic/static builds from the latest ios-v3.7.2 tag

### Steps to trigger behavior

 1. Follow the instructions on https://www.mapbox.com/install/ios/, using "Download" method or https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/INSTALL.md if using custom builds
 2. Add "`@import Mapbox;`" in the AppDelegate.m
 3. Specify the access token in the `application:didFinishLauchingWithouOptions:` method, using `[MGLAccountManager setAccesssToken:]`
 4. Save everything and build

### Expected behavior
Build passes and the application runs.

### Actual behavior
Build fails with the following build errors:
1) Ln7 in the MGLMapView+IBAdditions.h
Cannot define category for undefined class 'MGLMapView'
2) The "`@import Mapbox;`" line in the AppDelegate.m:
Could not build module 'Mapbox'

**Comment by akitchen** [comment]
Hi - thanks for reporting this, and thanks for using Mapbox!. 

It seems that the category header is being imported (or applied) before anything imports `MGLMapView.h`... this is surprising since `Mapbox.h` imports `MGLMapView.h` before `MGLMapView+IBAdditions.h`. Are your results any different if you import Mapbox using `#import <Mapbox/Mapbox.h>` instead of the @ syntax?  FWIW, I was able to change our SDK project's sample app's import of the SDK to `@import Mapbox;` and everything still builds and runs fine for me.

Since you're already building your own SDK, if you change `MGLMapView+IBAdditions.h` to include `#import "MGLMapView.h"` does everything work as expected? I think it should include this line anyways as that is the class it is extending. Feel free to put a pull request together if this works for you, otherwise we'll look into adjusting this in an upcoming release based on your feedback.

Thanks again!

**Comment by afxwin** [comment]
Hi akitchen, thanks for your response.

I was using clang-format to format my code, which turned out to be the root cause. The formatting happens before the compilation, and it changes the import order in the Mapbox.h header file. I have configured the clang-format to not run against the Mapbox SDK code and the build is passing without issues.
