### ISSUE TITLE
[Android] SymbolLayer (LocationLayer) animation stuttering when moving camera

### ISSUE THREAD

**Issue by schachi5000** [mapbox/mapbox-gl-native#10842]
Since the update to android-v5.2.1 we've experienced a lot of stutters when it comes to the LocationLayer icons and simultaneous camera movement. This only seems to happen when the camera is tilted.

Platform: Android
Mapbox SDK version: 5.3

![stutter](https://user-images.githubusercontent.com/25952987/34612167-c76f6582-f228-11e7-818f-028d90b12205.gif)

Expected behavior:
The location icon should be animated smoothly.

Actual behavior:
The location icon stutters when the camera is moved (manually and programmatically) with a tilt.

**Comment by tobrun** [comment]
Thank you for reaching out, this issue though is not an issue with the SDK but with the location layer plugin itself. Please create a ticket downstream instead in https://github.com/mapbox/mapbox-plugins-android. Thank you for reaching out!

**Comment by schachi5000** [comment]
To be honest I don't think that this issue is isolated to the LocationLayerPlugin.
I successfully recreated this behavior with a SymbolLayer and an animated Marker/Icon on it.

**Comment by ChrisLoer** [comment]
@schachi5000 which version were you upgrading from? It occurs to me the behavior you're seeing may have been introduced by https://github.com/mapbox/mapbox-gl-native/pull/9009, which changed how we handled text in pitched maps. The change made it so that text size scaled with the "distance from the camera", which meant that moving around a pitched map requires re-doing symbol placement periodically to avoid collisions. Every time symbol placement happens, all the buffers for the tile have to be re-uploaded to the GPU, and that might account for the stutter you're seeing.

On `master`, we've followed up with further changes that make it so that collision detection no longer requires re-uploading the entire tile, but those changes haven't been rolled into a release yet.

**Comment by schachi5000** [comment]
The previous version was 5.1.3. For verification, I've just tested this version and it does indeed work as intended.

**Comment by tobrun** [comment]
Capturing from internal conversation:
> I think it looks like a performance regression introduced by https://github.com/mapbox/mapbox-gl-native/pull/9009. It’s not something unexpected, just a cost we hoped would be tolerable/worth-it. The issue they’re seeing is made obsolete on `master` by viewport collision detection.

We currently can't provide a workaround for the 5.x releases, so the options for you is either move back to 5.1.3, do other optimizations to make tile loading faster (eg. slimming down the style), or tolerate the stutter for now. I'm tagging this issue with the 6.0.0 milestone as, capturing from above, this issue is made obsolete on master.

**Comment by schachi5000** [comment]
I've feared as muched. A rollback to 5.1.3 is sadly out of the question for us since you've introduced icon anchors to SymbolLayers in 5.2, which are even more crucial for us. 
Do you guys have an ETA for the 6.0.0 milestone? If it's not too far off we may just wait it out.

**Comment by tobrun** [comment]
We are releasing beta.1 this week/next, a final release date hasn't been set as this will depend on the feedback from the beta's.
