### ISSUE TITLE
mapbox gl native does not support chinese character when rendering into png?

### ISSUE THREAD

**Issue by lihuadong1988** [mapbox/mapbox-gl-native#10969]
Platform: linux
Mapbox SDK version:master

Steps to trigger behavior

 1.use mbgl-render to get png.

 Actual behavior
chinese character in png is messy code.

**Comment by ChrisLoer** [comment]
Hi @lihuadong1988 thanks for the report! We expect `mbgl-render` to be able to render Chinese characters. Could you include the arguments you're using as well as a screenshot of the result highlighting the problem?

As an example, if I run:

    mbgl-render -t [my_access_token] -s mapbox://styles/mapbox/streets-v9 -z 11.96 -x 121.42338 -y 31.39636

The result I see is:

![out](https://user-images.githubusercontent.com/375121/35163406-7640ecde-fcfb-11e7-8bd4-612a8c21eea3.png)

Which looks correctly rendered to me.

**Comment by lihuadong1988** [comment]
with the same command，i got result like this:
![image](https://user-images.githubusercontent.com/18736297/35201441-6ce26f34-ff56-11e7-8d9f-cd8ebc79c31e.png)

**Comment by lihuadong1988** [comment]
I do not know why，my server is centos 7.0. @ChrisLoer

**Comment by lihuadong1988** [comment]
i changed my server to Ubuntu, and now Chinese characters looks ringht, but the labels was not render into the dest png. the result is:
![out](https://user-images.githubusercontent.com/18736297/35217561-b21a6be2-ffa6-11e7-8df8-0b667360212f.png)

**Comment by ChrisLoer** [comment]
Hi @lihuadong1988, I can't tell what's wrong with the screenshot above, because I don't know what style you're using to render it and I don't know what you expect to see. It looks to me like Chinese characters are rendering correctly for you, though.

I'm going to close the issue, but please re-open if you can show a rendering problem with Chinese. Unfortunately we can't provide general support for using Mapbox through GitHub issues.
