### ISSUE TITLE
DefaultFileSource.NoCacheRefreshModifiedNotModified test intermittently failing

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#10961]
https://circleci.com/gh/mapbox/mapbox-gl-native/60056 — `master` circa b863871bf245cf78c4ecbbe3ccfbb2b3e0950760.

```
[ RUN      ] DefaultFileSource.NoCacheRefreshModifiedNotModified
../../../test/storage/default_file_source.test.cpp:480: Failure
Expected: (util::now()) < (*res.expires), actual: 8-byte object <63-EF 60-5A 00-00 00-00> vs 8-byte object <63-EF 60-5A 00-00 00-00>
[  FAILED  ] DefaultFileSource.NoCacheRefreshModifiedNotModified (3 ms)
```

/cc @kkaefer

**Comment by kkaefer** [comment]
Looks like the comparison fails because the expiration time is the _same_ as the current time (January 18, 2018 7:02:59 PM, Unix epoch 1516302179). This is likely because we're setting a max age of just one second in our test server: https://github.com/mapbox/mapbox-gl-native/blob/ef5357a870c29a8b016e0b368a1f0a8ff7ef0a11/test/storage/server.js#L70 and the timing works out so that the resource counts as expired by the time it reaches our test. This isn't something that changed recently and probably just a spurious, timing related failure. Please reopen if you start seeing this more frequently.

**Comment by jfirebaugh** [comment]
I know I keep harping on this, but: please don't write timing-dependent tests!

**Comment by friedbunny** [comment]
Saw this [again](https://circleci.com/gh/mapbox/mapbox-gl-native/294881) recently in #14941:

```
../../../test/storage/default_file_source.test.cpp:480: Failure
Expected: (util::now()) < (*res.expires), actual: 8-byte object <92-11 15-5D 00-00 00-00> vs 8-byte object <92-11 15-5D 00-00 00-00>
[  FAILED  ] DefaultFileSource.NoCacheRefreshModifiedNotModified (35 ms)
```

**Comment by friedbunny** [comment]
[Again.](https://circleci.com/gh/mapbox/mapbox-gl-native/338956)
