### ISSUE TITLE
[Crashing] IllegalStateException: setRenderer has already been called for this instance

### ISSUE THREAD

**Issue by mf-mindcrewtech** [mapbox/mapbox-gl-native#10978]
Facing crashing issue when using mapview for multiple fragments inside a view pager with Tab Layout.

NOTE :: I already go through the link [ https://github.com/mapbox/mapbox-gl-native/issues/10711 ] but my FragmentStatePagerAdapter containing 5 fragments. Frag 1 and 3 contain MapView.

**Comment by tobrun** [comment]
@mf-mindcrewtech thank you for reaching out. Was able to reproduce with the release branch, after cherry-picking https://github.com/mapbox/mapbox-gl-native/commit/a500125518cd805a0d539c927627dadad7ee63e5, the crash doesn't show anymore. This issue is going to be fixed with the 5.3.2 release and is aimed to be released this week.

**Comment by tobrun** [comment]
![ezgif com-video-to-gif 32](https://user-images.githubusercontent.com/2151639/35216213-29c98af0-ff67-11e7-85fd-45fa9cda5c27.gif)

**Comment by mf-mindcrewtech** [comment]
@tobrun , okay thanks. Waiting for release

**Comment by mf-mindcrewtech** [comment]
@tobrun , still getting this crashing issue even updating the sdk to 5.3.2

**Comment by LukasPaczos** [comment]
Continuing in https://github.com/mapbox/mapbox-gl-native/issues/11181.
