### ISSUE TITLE
pare down iOS platform gyp reqs

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1099]
We can cut down this list a bit: 

https://github.com/mapbox/mapbox-gl-native/blob/a0060a894d70719a77118106f19fb1a74fc00154/gyp/platform-ios.gypi#L50-L59

Over in the [`podspec`](https://github.com/mapbox/mapbox-gl-native/blob/a0060a894d70719a77118106f19fb1a74fc00154/ios/MapboxGL.podspec#L25-L27) we were able to specify fewer, and keeping these in sync could make maintenance easier and less error-prone.

**Comment by 1ec5** [comment]
Oddly, the framework list in the .gypi file is as short as it can get without causing linker errors. CocoaPods must be linking in UIKit, CoreGraphics, etc., but I’m not sure how.

**Comment by incanus** [comment]
> CocoaPods must be linking in UIKit, CoreGraphics, etc., but I’m not sure how.

This is sort of a longstanding thing I've seen across projects. I've never really had to link CoreGraphics before. Also, it could be part of `@import` vs. `#include`, or related to modules?

**Comment by picciano** [comment]
According to http://stackoverflow.com/questions/24181062/default-frameworks-missing-in-xcode-6-beta

In Xcode 6, the default for new projects is to use the module system (introduced in Xcode 5) to automatically link any frameworks you reference in code via import (Swift) or @import/#import statements (ObjC). Because the project template contains code that imports Foundation and UIKit (and a test case target that imports XCTest), you get those frameworks linked automatically.

**Comment by 1ec5** [comment]
Ah, yes, forgot to update this ticket. We need to enable `CLANG_ENABLE_MODULES` in either platform-ios.gypi or mapboxgl-app.gyp.
