### ISSUE TITLE
android test app crashes on startup

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-native#1100]
I installed the android stuff following the readme.
I ran `make android` and `open -a "Android Studio"`.
In Android Studio I hit the green play button and selected my 4.4.4 device.

It crashes with a bunch of different errors:
https://gist.github.com/ansis/4e43d3c146798191d804
https://gist.github.com/ansis/578f86a81e41e3d8841c
https://gist.github.com/ansis/3df989249dd27fa7555b
https://gist.github.com/ansis/858b705126dd56cb8744

This might be related to https://github.com/mapbox/mapbox-gl-native/issues/738

@ljbade any ideas?

**Comment by ljbade** [comment]
Hmm, I have not seen any startup crashes for a while.

The first one looks like a empty style URL is being set on the map. This might happen the first time the app is run on a device before the UI has fully loaded and selected the Bright style. Probably just need to set the style URL to a default value in the UI XML files.

The second and fourth ones are crashes somewhere in the C++ side so need to be tracked down with GDB. If you get these crashes again can you disable the logcat filter that by default only shows messages from our app and look for the native stack trace which is logged with "DEBUG/"* or "DEBUG\"* at the start of each line.

The third one appears to be a OpenGL error, likely because we are doing something wrong.

**Comment by ansis** [comment]
> Probably just need to set the style URL to a default value in the UI XML files.

@ljbade can you make the change or point me to the right file?

I'll hold off on digging into the other ones until that's fixed, because they might be related. https://github.com/mapbox/mapbox-gl-native/wiki/Android-debugging-with-remote-GDB is well documented, but still a bit intimidating

**Comment by jfirebaugh** [comment]
After 63ea3d4befe7f2a8958cf3496d31d2a71561801b, I was able to build and run in the simulator with no crashes. Lets open fresh tickets for anything that's still reproducible.
