### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by tatsvc** [mapbox/mapbox-gl-native#1108]
How will language support work in the new SDK? Will this be the country's language by default, or can you set it to the language of the OS (this is what Apple Maps does, they have a toggle to always have it in English)? Just something to think about.

cc. @incanus @1ec5 @peterqliu

**Comment by friedbunny** [comment]
As another point of comparison, Google Maps (iOS app and SDK) defaults to device language with no exposed setting or API for switching. Labels in "foreign" places will display both your device language (where available) and the appropriate local name.

![screen shot 2015-03-28 at 11 04 16 am](https://cloud.githubusercontent.com/assets/1198851/6882211/4f1b2ec6-d53a-11e4-88d8-460cbc79f7a2.png)

Meanwhile, Apple will try to draw labels in the device language and (almost always) fallback to local.

![screen shot 2015-03-28 at 11 11 56 am](https://cloud.githubusercontent.com/assets/1198851/6882254/897c87f8-d53b-11e4-832d-7651fee55cb8.png)
 
Google's data is far superior to Apple's, but both have outdated names for things like stadiums. It also appears that Google has done some machine translation of common place names. OSM has very, very few localized (non-English) names in Portland and setting a -native map to strictly Japanese results in no labels at all.

**Comment by incanus** [comment]
Proper support here, including RTL and complex text shaping is a bit out of scope, so moving off of b2 milestone for now.

**Comment by 1ec5** [comment]
To be clear, this ticket is about dynamically showing labels in whatever system language is being used at runtime. Currently that would require a large number of styles or a large number of classes in a single style (although we don't currently expose style classes to iOS SDK clients), to be toggled manually by client code. This is because label text is baked into the Mapbox Streets source, rather than decoupled into a separate source that can be parameterized by locale.

**Comment by jfirebaugh** [comment]
@1ec5 Not sure I understand your comment. Did you look at how the example works? It doesn't use multiple styles or style classes.

**Comment by jfirebaugh** [comment]
Oops, I thought this was a gl-js ticket. For gl-native, the upshot is that once we have a [style API](https://github.com/mapbox/mapbox-gl-native/issues/837) in native, we can do the same as the [gl-js example](https://www.mapbox.com/mapbox-gl-js/example/language-switch/) -- changing the feature property used for the label.

**Comment by 1ec5** [comment]
https://github.com/mapbox/mapbox-gl-native/pull/6819#issuecomment-256210796 would port the GL JS example to iosapp. If we were to truly have parity with MapKit, the SDK would have to automatically switch languages rather than forcing the developer to. However, that would require style-specific logic.

**Comment by 1ec5** [comment]
> If we were to truly have parity with MapKit, the SDK would have to automatically switch languages rather than forcing the developer to. However, that would require style-specific logic.

#7031 outlines a concrete approach to automatically localizing the map that I think would be feasible.
