### ISSUE TITLE
How to add gif image on map using MGLSymbolStyleLayer

### ISSUE THREAD

**Issue by sundeepios** [mapbox/mapbox-gl-native#11096]
Could you please let us know how to add gif image on map using MGLSymbolStyleLayer

**Comment by jmkiley** [comment]
Hello @sundeepios -

Could you clarify whether you would like to add an animated or still gif to your map?

**Comment by jmkiley** [comment]
If you would like to add a GIF as a still image, you can use [`-setImage:forName:`](https://www.mapbox.com/ios-sdk/api/3.7.3/Classes/MGLStyle.html#/c:objc(cs)MGLStyle(im)setImage:forName:) to add the image to the style. Then use that to create a `MGLSymbolStyleLayer`.
```swift
  let image = UIImage(named: "frame_0_delay-0.11s.gif")
  style.setImage(image!, forName: "frame_0")
  
  let point = MGLPointFeature()
  point.coordinate = mapView.centerCoordinate
  let symbolSource = MGLShapeSource(identifier: "symbol-source", shape: point, options: nil)
  style.addSource(symbolSource)

  symbolLayer = MGLSymbolStyleLayer(identifier: "symbol-layer", source: symbolSource)
  symbolLayer.iconImageName = MGLStyleValue(rawValue: "frame_0")
  style.addLayer(symbolLayer)
```

If you would like to show an animated GIF on a map, it may be more performant to use `MGLImageSource`. While we do not have built-in support for animated GIFs [with `MGLImageSource`](https://github.com/mapbox/mapbox-gl-native/issues/10594) or with [`style layers`](https://github.com/mapbox/mapbox-gl-native/issues/10595), you can work around this by splitting up the gif's frames, then updating the source's image on a timer. You can also take this approach with a `MGLSymbolStyleLayer`. Instead of updating the source's image, you would update the layer's `iconImageName` property. Both of these approaches apply to a single animated gif. 
![gif with image source](https://user-images.githubusercontent.com/12474734/35830837-6efe3d9e-0a7c-11e8-87b5-75c3dc22d35f.gif)
![gif with image source](https://user-images.githubusercontent.com/12474734/35830840-7079736e-0a7c-11e8-92ea-7d56b278bfa2.gif)

**Comment by babzilla-web** [comment]
Hello! 3 years passed - did situation with gif animation integration changed? Or we still use this MGLImageSource or iconImageName property ? To split gif on frames and updating them on timer?

**Comment by hussi-emblem** [comment]
situation improved in 2022 ?
