### ISSUE TITLE
Custom marker not visible

### ISSUE THREAD

**Issue by cleemansen** [mapbox/mapbox-gl-native#11129]
**Platform:**

android

**Mapbox SDK version:**

5.4.0 (and also tested w/ 6.0.0-beta1)

### Steps to trigger behavior

 1. clone forked and adjusted _mapbox-android-demo_ repo at https://github.com/cleemansen/mapbox-android-demo
 1. start app in an emulator or device (tested w/ emulator Nexus 5X API 25 and emulator Nexus 5X API 26)
 1. navigate to the sample _Annotations_ > _Draw a custom marker icon_ inside the demo app

### Expected behavior

A custom blue bird map marker should be visible.

### Actual behavior

My custom map marker is not rendered. If you zoom in, sometimes the blue bird marker appears.

- Is something wrong w/ my bird asset? 
- Or is there an issue in mapbox?

**Comment by tobrun** [comment]
@cleemansen could you back this issue up with screenshot / the asset you are trying to render?

**Comment by cleemansen** [comment]
@tobrun for sure:

- the asset (the `xxhdpi` version): 
![ic_map_marker_default_34dp](https://user-images.githubusercontent.com/868171/35875497-c1abb35c-0b6f-11e8-8bf9-ad2e1f628d25.png)

- a screencast of the adjusted demo app:
![bird_marker_cutted](https://user-images.githubusercontent.com/868171/35876204-d5bc1a06-0b71-11e8-97aa-9b34a0928cf4.gif)

**Comment by cleemansen** [comment]
I don't know if it helps:

1. open the adjusted sample (no bird visible)
1. start the android task switcher (right hardware button)
1. select again the demo app
1. the sample renders now the marker

**Comment by tobrun** [comment]
This was an issue with the 5.x series of the SDK and was fixed with https://github.com/mapbox/mapbox-gl-native/pull/10899. 

Retested with 6.0.0 codebase and not seeing this specific issue:
![ezgif com-video-to-gif 39](https://user-images.githubusercontent.com/2151639/35970510-dffe5b0a-0cca-11e8-8b3d-151296ba80e5.gif)

Feel free to retest with the snapshot/beta version. Closing as this issue is resolved with 6.0.0.
