### ISSUE TITLE
[core] Tile prefetching no longer works

### ISSUE THREAD

**Issue by tmpsantos** [mapbox/mapbox-gl-native#11213]
Tile prefetch (prefetching and rendering lower resolution tiles until we get tiles for the current zoom level, avoiding blank spots on the map) is no longer working. I bisect the regression to 10a44050f485a18f8dd6523aca6a7a9f82f7afc7.

This is probably why the `Map.PrefetchTiles` is [failing](https://circleci.com/gh/mapbox/mapbox-gl-native/71720). Sadly seems like the test doesn't always fail, so it would have detected the regression when it was introduced (my bad).

It is easy to reproduce and inspect visually, as one commit before the regression we see that lower resolution tiles are loaded first:

Mapbox GL at 10a44050f485a18f8dd6523aca6a7a9f82f7afc7:
![prefetch_working](https://user-images.githubusercontent.com/996307/36259710-c1cbe95c-1267-11e8-96a7-1a7f4e35db51.png)

Mapbox GL at bfa4cea24c2ab3973f845fda6da6d4a9e8f03e56:
![prefetch_working2](https://user-images.githubusercontent.com/996307/36259712-c466a8c8-1267-11e8-9223-0b9db7d4bb81.png)

/cc @asheemmamoowala @Guardiola31337 @kkaefer

**Comment by ChrisLoer** [comment]
@asheemmamoowala I just saw two CI failures in `Map.PrefetchTiles` off of `master` -- any ideas?

A 'heap-buffer-overflow' on clang4-sanitize-address:

https://circleci.com/gh/mapbox/mapbox-gl-native/76253?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

An unexpected empty tile set on gcc 4.9:

https://circleci.com/gh/mapbox/mapbox-gl-native/76255?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by asheemmamoowala** [comment]
I debugged the `Map.PrefetchTiles` test, and don't see it hitting any of the code introduced in [`10a4405`](https://github.com/mapbox/mapbox-gl-native/commit/10a44050f485a18f8dd6523aca6a7a9f82f7afc7).

I'm seeing a few issues:
1. `Map.PrefetchTiles` sets the map mode to `Static`, but `TilePyramid`'s prefetch-ing is conditional on map mode being `Continuous`.  #10548  added the check in `TilePyramid`. This test should not have passed since that change.

2. The `std::is_permutation` check seems to be passing even when it shouldn't. According to the docs: 
> Returns true if there exists a permutation of the elements in the range [first1, last1) that makes that range equal to the range [first2,last2), where last2 denotes first2 + (last1 - first1) if it was not given.

https://github.com/mapbox/mapbox-gl-native/blob/25cfb5863c9ac3705d2bcf4086c237608264e3ae/test/map/prefetch.test.cpp#L62

In the cases where a parent tile should be prefetched, `expected.size()` > `tiles.size()`. It turns out that the permutation test matches because the expected parent zoom is always the last value in `expected`, and isn't being considered in the permutation check. 

A naive fix for #2 is to move the parent tile zoom value to the beginning of the `expected` vector. With this change, the test passed before #10548 merged, and consistently fails after.

**Comment by asheemmamoowala** [comment]
Moving to -> https://github.com/mapbox/mapbox-gl-native/issues/11326
