### ISSUE TITLE
Some macOS tests on release-boba are failing (mostly color related)

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native#11289]
**Platform:** macOS
**Mapbox SDK version:** `release-boba` at b79a1cc82e21bb8249d871691d6a4d250cd6a97c

The `test` target is failing (either from the macosapp or CI schemes). Log is attached: [Test CI_2018-02-22T17-10-13.txt](https://github.com/mapbox/mapbox-gl-native/files/1749879/Test.CI_2018-02-22T17-10-13.txt)

The bulk of the errors appear to be related to Wide Color support in High Sierra.

Quoting @friedbunny:
>  It being High Sierra-related makes sense, as Circle is still on (Low) Sierra: https://circle-macos-docs.s3.amazonaws.com/image-manifest/build-298/index.html
>
> They seem mostly color-related, but `-[MGLNSStringAdditionsTests testTitleCasedString]` is also failing.

cc @1ec5

**Comment by 1ec5** [comment]
> The bulk of the errors appear to be related to Wide Color support in High Sierra.

Apparently the errors expose a latent issue in the macOS SDK: the SDK itself uses the calibrated RGB color space, but the calibration changed in High Sierra with the introduction of Wide Color support. The intended color space in mbgl is probably sRGB, because that’s the color space [used by CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value).

> They seem mostly color-related, but `-[MGLNSStringAdditionsTests testTitleCasedString]` is also failing.

I originally fixed this issue for both iOS and macOS in 016eacb8fb5749a6f08e3918ccb45e18643eb3c6 for #10224, but 7f1350902e3d566f95d83799e6b40cba48bc2bca in the same PR broke the tests on macOS by assuming the code only runs on iOS.

/cc @frederoni

**Comment by 1ec5** [comment]
Fixed in #11391 on the release-boba branch for macOS map SDK v0.7.0.
