### ISSUE TITLE
iOS - Symbol collision with tilt

### ISSUE THREAD

**Issue by emerciercontexeo** [mapbox/mapbox-gl-native#11300]
**Platform:iOS**
**Mapbox SDK version:3.7.5**

### Steps to trigger behavior

Adding multiple symbol on a symbol layers.

Tilt the map.

Zoom in / out.

### Expected behavior

Collision works well.

### Actual behavior

Collision seems to have trouble on decimal zoom level.

Zoom x : 

![img_0962](https://user-images.githubusercontent.com/8739777/36629109-dbd8e8fe-1951-11e8-9986-372631bf744b.PNG)

Zoom x+1 : 

![img_0963](https://user-images.githubusercontent.com/8739777/36629115-03075ece-1952-11e8-89c2-ef6c90c26c28.PNG)

Zoom x+0.5 : 

![img_0964](https://user-images.githubusercontent.com/8739777/36629144-4867c030-1952-11e8-9ff2-a54c7ead3d43.PNG)

At this point, I don't understand why the symbol disappears but I assume that is not the expected behavior.

Etienne

**Comment by friedbunny** [comment]
@emerciercontexeo There’s been a lot of work done towards improving collision detection in the under-development v4.0.0 release, but I’m unsure to what extent that affects pitched labels. You might try [the latest v4.0.0 pre-release](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v4.0.0-beta.2) and see if this issue persists/changes.

/cc @ChrisLoer @ansis

**Comment by ChrisLoer** [comment]
Hi @emerciercontexeo, just looking at your screenshots, I'm not sure _exactly_ which collision problem you're running into, but it definitely looks like a class of problems we had with our old collision detection algorithm, which should all be fixed in the upcoming release that uses "global viewport collision detection":

- In pitched maps, collision boxes are pitched even for labels that are viewport-aligned, so they fit the labels poorly.
- In overzoomed tiles the collision boxes can become too tall -- it looks like you're experiencing this here, you can see a more extreme example at https://github.com/mapbox/mapbox-gl-js/issues/5095.
- The approximations we use for sizing the boxes are done on a per-tile basis, which means when two symbols are near a tile boundary, you can get wacky results where the two tiles get different collision results (and you end up with a symbol not showing even though it looks like it should).

We were at the limits of what our old architecture could handle, so it's very unlikely we'll be able to patch any of our earlier releases to fix this problem. Luckily, our new approach fundamentally avoids a lot of these problems by doing collision detection across the entire viewport at once instead of trying to do it tile-by-tile and then stitch the results together.

I'm going to close because we don't have a specific action in mind (other than getting the 4.0.0 release out the door), but please feel free to re-open or comment if the new version doesn't work or if I'm missing some important context.

**Comment by emerciercontexeo** [comment]
@ChrisLoer Thanks for the answer. I will try it as soon as possible and keep you in touch.
