### ISSUE TITLE
Mapbox resize not working properly with Fusetools on Android

### ISSUE THREAD

**Issue by Dhvl-Golakiya** [mapbox/mapbox-gl-native#11379]
Hello,
I am using Mapbox with Fusetools. Mapbox resize works properly on iOS but on Android, When I am trying to decrease the height of mapview, it becomes a little bit bigger and then it's height decreases. The same case happens when I increase its height but this time, it becomes a little bit smaller.

I already check these issues:
https://github.com/mapbox/mapbox-gl-native/issues/4187
https://github.com/mapbox/mapbox-gl-native/issues/3622

It seems like the issue is fixed but in this case, the issue still exists.

For the  sample code of reproducing this issue, check the following link:
https://www.dropbox.com/s/12nshvdli38tw2i/MapBoxSample%203.zip?dl=0

If you haven't run Fusetools, follow this steps:
1. Open Project in Fusetools
2. Add your Mapbox token to MapViewSample.java file
3. From MenuBar, Select Preview and Click Preview On Android

let me know if you need any help to run project

**Comment by tobrun** [comment]
@Dhvl-Golakiya 

Thank you for reaching out and providing the sample code. 
The use-case shown in the sample code should be tackled with using TextureView instead of the standard GLSurfaceView.

Before:

![ezgif com-video-to-gif 50](https://user-images.githubusercontent.com/2151639/36972670-47576b12-2070-11e8-9f87-84946d6dcbdf.gif)


After enabling TextureView:

![ezgif com-video-to-gif 49](https://user-images.githubusercontent.com/2151639/36972678-4c779338-2070-11e8-877a-c7fd305ac39d.gif)


Code changes:

```java
        MapboxMapOptions options = new MapboxMapOptions();
        options.textureMode(true);
```
