### ISSUE TITLE
is Disk tile cache actually being used?

### ISSUE THREAD

**Issue by leelx78** [mapbox/mapbox-gl-native#11401]
Hi, I'm on 6.0.0-beta3 and I'm using an offline map.

I notice that *every time* I start the application it always seem to download and redraw the same tiles at runtime. I would expect it to heavily rely on local cache but it doesn't seem that way. The "Data" usage does increase a bit though in the "App Info"

Even zooming in and out the same zone over and over seems to cause a lot of redraws while I would expect it to be butter smooth after the map was drawn once

Even a raster seems to be redrawn each time, particularly at tilt angles

Is this intentional? This is putting a lot of unnecessary strain on CPU in my case. 

I have loads of space on my device that I could use to store drawn tiles..

Thanks!

**Comment by kkaefer** [comment]
The cache should be used for repeated map loads.

* Are you using tiles/styles provided by Mapbox?
* How are you determining that Mapbox GL makes unnecessary requests? What does "data usage increases 'a bit'" mean?
* Can you please describe what you mean by "lots of redraws"? When you interact with the map, GL redraws the entire map by design. What kind of "unnecessary strain" on the CPU are you seeing?

**Comment by leelx78** [comment]
Hi @kkaefer sorry didn't see your reply. 

I'm using my own XYZ raster and vector maps and I'd expect the code to cache the tiles locally on sdcard up to a given point instead of downloading tiles every single time. 

However, I just don't see storage being used after browsing. is this normal? Any pointer on what/where to change the code to make this happen?

Thanks!

**Comment by jfirebaugh** [comment]
What values does your tile server send for the `Cache-Control` and `Expires` HTTP headers?

**Comment by leelx78** [comment]
@jfirebaugh sorry, no idea. I just imagined that the application would take care of that internally, example:

- Map needs a tile
- Look in the cache
- if not int the cache download it and assign a timestamp of some sort
- if the cache exceeds a given size remove the oldest tile (e.g. a sort of circular queue)

Is the raster layer implemented that way?

**Comment by jfirebaugh** [comment]
No, it's not that simple. Caches need to come with an expiration policy, otherwise there would be no way to get updated tiles when the data has changed. The expiration policy for the caches that Mapbox GL uses is controlled by the standard HTTP headers `Cache-Control` and `Expires`. If you're using a non-Mapbox tile server, you'll need to ensure that it sends values for these headers that reflect your desired caching behavior. You can read more about HTTP caching [here](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching).
