### ISSUE TITLE
[iOS] cache.db not created/exist

### ISSUE THREAD

**Issue by wishtrip-dev** [mapbox/mapbox-gl-native#11479]
**Platform:** iOS
**Mapbox SDK version:** 3.7.6

### Steps to trigger behavior

 1. Install Mapbox iOS SDK via Cocoapods 
 2. Add mapView to a main view as described in "Get started" section

### Expected behavior
Mapbox map presented on screen

### Actual behavior
An app crashes with error:
{com.mapbox.mbgl.DefaultFileSour}[Database]: cannot open file at line 40843 of [2b0954060f] (Code 14)
2018-03-19 10:48:14.983507+0200 Staging[67756:1003404] [INFO] {com.mapbox.mbgl.DefaultFileSour}[Database]: [2b0954060f]:40843: (0) open(/Users/wishtrip/Library/Developer/CoreSimulator/Devices/2E9D7B72-13A0-4B4A-B98E-926795099166/data/Containers/Data/Application/EE2BC6A6-C4FB-4217-B110-F7035FB76EF1/Library/Application Support/com.xxxx.xxxxxx/.mapbox/cache.db) - Undefined error: 0 (Code 14)

To prevent the crash I needed to take a cache.db from bundle of working copy and put it manually to correct folder

Any help would be appreciated.
Regards,
WishTrip Dev

**Comment by jmkiley** [comment]
Hi @wishtrip-dev -

Thank you for the report. It looks like you may be hitting an exception breakpoint. Do you still see the message if you disable breakpoints?

Otherwise, I have not been able to reproduce this issue. Do you still see the issue if you run `pod install && pod update` rather than just `pod install`? 

Could you share which version of CocoaPods and Xcode you are using? Also, is this issue occurring in a Swift or Objective-C project?

**Comment by jmkiley** [comment]
It looks like the console output that you are seeing is due to https://github.com/mapbox/mapbox-gl-native/issues/10796. This should not have an impact on performance, and is an exception rather than a crash.

**Comment by wishtrip-dev** [comment]
Hi, @jmkiley.
First, thank you for a fast reply. Disabling All Exceptions breakpoint solved the issue indeed.
Thanks.
