### ISSUE TITLE
removeMarker() not update surface

### ISSUE THREAD

**Issue by luistrejo** [mapbox/mapbox-gl-native#11478]
**Platform: Android**
**Mapbox SDK version: 5.5.0**

### Steps to trigger behavior

 1. Add MarkerOptions to map
 2. Remove the markerOptions

### Expected behavior
The marker disappears.
### Actual behavior
The marker does not disappear immediately if not until the map is moved by the user.

![ezgif-5-9f4d26e40f](https://user-images.githubusercontent.com/7865721/37562104-b223bba2-2a1c-11e8-8ac9-ee41b2579168.gif)

Code:
```
public void showEstaciones(boolean checked) {
        if (checked) {
            markerOptions = new MarkerOptions()
                        .position(lat, lon)
                        .title("Marker")
                        .icon(icon));
            map.addMarker(markerOptions);
        } else {
            map.removeMarker(markerOptions.getMarker());
        }
    }
```

**Comment by tobrun** [comment]
Thank you for reaching out and using our products! Instead of calling `markerOptions.getMarker()` and using markerOptions, you should cache the result from addMarker instead. 

eg.

```java

        final Marker marker = mapboxMap.addMarker(new MarkerOptions().position(new LatLng(45.1855569, 5.7215506)));
        new Handler().postDelayed(new Runnable() {
          @Override
          public void run() {
           mapboxMap.removeMarker(marker);
          }
        }, 2000);
```

Results in:

![ezgif com-video-to-gif 54](https://user-images.githubusercontent.com/2151639/37590997-509bb70a-2b6a-11e8-9c1d-2eef3098a489.gif)
