### ISSUE TITLE
Adding marker to offline map only appears after movement

### ISSUE THREAD

**Issue by dsuresh-ap** [mapbox/mapbox-gl-native#11550]
**Platform: Android**
**Mapbox SDK version:5.0.2 and 5.5.1**

### Steps to trigger behavior

 1. Download map region
 2. Kill app and disconnect wifi
 3. Restart app
 4. Add marker
 5. Remove marker and add another marker

### Expected behavior

Old marker gets removed and new marker gets displayed

### Actual behavior

Old marker gets removed, new marker only gets displayed on the slightest map movement. Annotation manager shows correct number of annotations. (2, 1 for user location, 1 for marker)

Connecting back to internet shows marker.

**Comment by LukasPaczos** [comment]
Thanks for reporting the issue @dsuresh-ap.

I was able to reproduce:
![markers when offline](https://user-images.githubusercontent.com/16925074/38136214-50b51a0e-341d-11e8-87ee-c6953b96ebee.gif)

When the map is in the state that doesn't show markers after a click it's because there always exists a not fully rendered source [here](
https://github.com/mapbox/mapbox-gl-native/blob/release-agua/src/mbgl/renderer/renderer_impl.cpp#L740-L744), which prevents markers invalidation [here](https://github.com/mapbox/mapbox-gl-native/blob/79c9a7ffe7d1b1054884e9667d5a473c812e2691/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java#L80-L83).

On both `release-boba` and `release-agua` a couple of `DID_FINISH_RENDERING_FRAME` events are delivered, but not followed up with a `DID_FINISH_RENDERING_FRAME_FULLY_RENDERED`.

An alternative would be using a `SymbolLayer` or `Marker`s instead of `MarkerView`s.

**Comment by dsuresh-ap** [comment]
@LukasPaczos We intended to switch to SymbolLayers but right now is there any workaround to the issue?

We are adding the Marker using the following code:
`marker = mapboxMap.addMarker(new MapBoxMarkerViewOptions()
                .position(latLng)
                .anchor(0.5f, 0.5f)
                .markerIcon(createMapBoxIcon())
                .title(mapObject.getLabelName()));`

**Comment by LukasPaczos** [comment]
@dsuresh-ap At this point, if you are not performing any `View` specific operations on those markers, the only workaround I can see is using `MarkerOptions` instead of `MarkerViewOptions` and [LocationLayerPlugin](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-locationlayer) for displaying user's location instead of `MyLocationView`.

**Comment by LukasPaczos** [comment]
@dsuresh-ap Noting, that a temporary workaround might also be using
```
mapboxMap.getMarkerViewManager().invalidateViewMarkersInVisibleRegion();
```
after adding a marker.

**Comment by tobrun** [comment]
Workaround for deprecated API given, follow up ticket tackling core side of things in https://github.com/mapbox/mapbox-gl-native/issues/11688.

**Comment by dsuresh-ap** [comment]
@LukasPaczos @tobrun The workaround works provided we postDelayed. Also we noticed the same during rotation.
