### ISSUE TITLE
Achieving equal size of square/pixel on Mapbox anywhere on the world map?

### ISSUE THREAD

**Issue by haxpor** [mapbox/mapbox-gl-native#11621]
**Platform:**
iOS

**Mapbox SDK version:**
3.7.6

The problem I'm facing is similar and closely related to [this](https://github.com/mapbox/mapbox-unity-sdk/issues/413) but that's for Unity SDK.

I want to achieve the same thing. Basically I have pixel grid in which each pixel'd have equal size. Pixel is set to be 10m x 10m. The thing I experienced is that if pixel locates towards the northern or southern part of the world, its size is stretched like the following

![this](https://trello-attachments.s3.amazonaws.com/5a8bfd92b0693f4a55bf9f39/5ac7b4d25937af5239d04098/d78ae6ac0d044f8f612f4c79b744ddcf/photo.jpg)

But when such pixel locates along the equator line, or simply along the middle part of the world. It looks ok like following

![ok](https://trello-attachments.s3.amazonaws.com/5a8bfd92b0693f4a55bf9f39/5ac727fc734cb2f602e83898/bf10226e683dd14de6cdd09ad0961399/photo.jpg)

I've read along on the issue I linked above for Unity SDK. It relates to mercator and the world is not flat thus makes this visual happens. I found out that there's no equal functionalities as presented in Unity for this particular problem on iOS SDK, so I'm not sure which approach I should go on to solve this solution.

How can I achieve equal size of pixel on the gridline on mapbox using Mapbox iOS SDK? Is there already solutions provided in the SDK?

PS.My requirement also needs real distance as shown on the map. I'm not sure it'd affect the solution as presented in the link I linked above.

**Comment by fdermishin-radargeo** [comment]
You're doing something wrong. If 10m x 10m square is displayed in Mercator projection, it will remain square, as both dimensions are stretched equally. However on the first screenshot (also slightly visible on the second one) the grid is stretched unevenly. It would be helpful if you provide details on how you calculate positions of the grid nodes.

The issue you might experience that the pixels are larger the closer they are to the poles. You can compensate this by changing zoom level, e.g. decreasing it when moving toward the poles.

**Comment by fdermishin-radargeo** [comment]
The issue is that you assume that 1 degree of longitude is constant. Actually it varies, and equals 93200.22 m only when latitude is about 33.15°. For example 1 degree of longitude is about 111320 m on equator and 0 m on the poles.

Unfortunately it is impossible to make square grid on a sphere without distortions. However there are some options.

If you need to display pixels so that they look equally, you can base the grid on coordinates in Mercator projection instead of latitude and longitude. The pixels will be square, but they will have different physical size, say 10x10 m on equator and 5x5 m on 60° latitude.

Another option is to keep physical size, but split the surface of the Earth into several regions, and use its own grid for each region. But in this case there will be visible seams between the regions, so that pixels in one region do not align with the pixels of a neighbor region.

**Comment by fdermishin-radargeo** [comment]
I assume that you decided to make tiles that have fixed size in Mercator projection, but different physical size. If you want pixel size to be in the range, say, from 5 m to 20 m, you can limit latitude from -75° to 75° and select tile size so that it equals 20 m on the equator.
You can choose some fixed zoom level to convert between coordinates and tile indices, ignoring zoom level of the camera.

**Comment by haxpor** [comment]
Ok thanks fdermishin-radargeo for helping me out and putting me in the right direction.

My solution is to port sphericalmercator.js into swift, then use it in code. I use a fixed zoom level of level 22 as its visual look is closest to what I need and also before. I went with visually look equal in size, and not pay attention much to physical size thus I did't limit anything.

Anyway from my testing with mercator, tilesize seems not to be in effect no matter what value I set. But only the zoom level that makes the difference.

**FYI**: 
I ported the code [here](https://github.com/abzico/sphericalmercator-swift) along with how to use it to get tile index, or bounding box of longitude/latitude in swift code.
