### ISSUE TITLE
Android P compatibility issues

### ISSUE THREAD

**Issue by cmxyzx** [mapbox/mapbox-gl-native#11625]
**Platform:Android P developer preview 1**
**Mapbox SDK version:6.0.0-beta.6**

### Steps to trigger behavior

 1. init mapview on device running Android P developer preview 1

### Expected behavior
no dark greylist non-sdk api accessing
[Refer to official doc](https://developer.android.com/preview/restrictions-non-sdk-interfaces.html)

### Actual behavior
have dark greylist non-sdk api accessing
```
W/zygote: Accessing hidden field Landroid/view/ScaleGestureDetector;->mMinSpan:I (dark greylist, reflection)
W/zygote: Accessing hidden field Landroid/view/ScaleGestureDetector;->mSpanSlop:I (dark greylist, reflection)
```

**Comment by LukasPaczos** [comment]
Thanks for flagging @cmxyzx! Following up on this in https://github.com/mapbox/mapbox-gestures-android/issues/39.

**Comment by LukasPaczos** [comment]
Noting here that since the release of the Android Pie, the hidden field access violation has been moved to the `light greylist`:
```
Accessing hidden field Landroid/view/View;->mAccessibilityDelegate:Landroid/view/View$AccessibilityDelegate; (light greylist, reflection)
```

I'm closing the ticket, because this will not need our attention until the next major version release of Android, but we will track and monitor that in https://github.com/mapbox/mapbox-gestures-android/issues/39.
