### ISSUE TITLE
stuck on signing mapbox.framework for adobe air native extension

### ISSUE THREAD

**Issue by Xgamefactory** [mapbox/mapbox-gl-native#11698]
Hi,
We are trying to make adobe air native extension for mapbox ios sdk.
Everything are fine excepting error during ipa packaging with mapbox.framework.

we tried to codesign framework on mac with correct identity but with no luck.
(using codesignin on your shell script inside framework)
latest adobe air sdk 29 has no issue signing third party dynamic frameworks but we stucked with mapbox.
We would appreciate if you can point us in correct direction at least.

we have checked all frameworks that packed without problem has not signed.
Is it possible to provide not signed mapbox framework ?
` codesign --display --verbose=4 FRAMEWORK_PATH i`

This tool should return: **code object is not signed at all**

**Comment by friedbunny** [comment]
Binary iOS frameworks need to be somehow signed, otherwise Xcode won’t build them. The expectation is that the end-developer (you, in this case) will re-sign everything with their own credentials as part of the app build process.

This setup is fairly standard and works for typical iOS app implementations (as well as code signing can be said to “work” on Apple platforms, anyway). Unfortunately, we can’t offer support for non-standard integrations, such as Adobe Air.
