### ISSUE TITLE
6.0.1: Return code 1 for dex process

### ISSUE THREAD

**Issue by kjkrum** [mapbox/mapbox-gl-native#11752]
When attempting to install an Android project with Mapbox 6.0.1 on an API 23 device, `:app:transformClassesWithDexForDebug` fails with the error message "Return code 1 for dex process." Googling that error message suggests that Mapbox or one of its transitive dependencies was compiled with Java 1.8 bytecode. I believe this effectively raises the minimum SDK version to 24.  Mapbox 5.5.2 is fine.  (6.0.0 fails with a different error about an unresolved dependency.)

**Comment by kjkrum** [comment]
Related SO answer: https://stackoverflow.com/a/49874621/1953590

**Comment by LukasPaczos** [comment]
Yes, we are using Java 8 language features starting with `v6.x`. If you are using Android Studio 3.1 or above you should be fine, otherwise (or if you encounter issues anyway) you need to add
```
android {
  ...
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
}
```
to your top level `build.gradle` file.
For more information please refer to the [migration guide](https://github.com/mapbox/mapbox-gl-native/wiki/Android-5.x-to-6.x-migration-guide).
