### ISSUE TITLE
[build] node.js downloaded even if WITH_NODEJS=OFF

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-gl-native#11804]
I noticed that even with `cmake -DWITH_NODEJS=OFF` the build still downloads node.js as I see the logs:

```
-- Downloading: https://nodejs.org/download/release/v4.9.1/SHASUMS256.txt
-- NodeJS: Using node, version v4.9.1
-- Downloading: https://nodejs.org/download/release/v4.9.1/node-v4.9.1-headers.tar.gz
```

This is not ideal, especially when nodejs.org is down. I noticed this behavior because nodejs.org was being very slow to respond for me.

**Platform:** OS X/ Linux
**Mapbox SDK version:** master

**Comment by jfirebaugh** [comment]
There are two semi-distinct uses of node in gl-native:

* Building the node bindings for mapbox-gl-native
* Node and npm used as a development dependency for running render tests on various platforms

It looks like `WITH_NODEJS` was originally intended to disable the latter but not the former, which is why node.js is still downloaded even when `WITH_NODEJS` is set.

I am not sure whether it should be extended to include the former or not. @tmpsantos it looks like you added this originally, what do you think?

**Comment by tmpsantos** [comment]
Sorry about the late reply. The idea of `WITH_NODEJS=OFF` was to remove the dependency on `node.js` and `npm` when building the Maps SDK for Qt, which was specially useful when targeting Windows and embedded devices.

**Comment by kkaefer** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/11999
