### ISSUE TITLE
[Android] Google Maps like dynamic badges

### ISSUE THREAD

**Issue by schachi5000** [mapbox/mapbox-gl-native#11826]
Hi there,

I've was trying to imitate badges similar to the ones found in Google Maps.
Sadly with no success. The only thing coming close to this in the Mapbox context might be popups.

Is there a feature or maybe a slick workaround to get something similar?
I'm currently working with the Android SDK v.6.0.0.

Any hint in the right direction would be much appreciated :)

![2018-05-03 11 34 58](https://user-images.githubusercontent.com/25952987/39569615-06dc7c1a-4ec6-11e8-848c-55bd4022bd6d.jpg)

**Comment by tobrun** [comment]
Due to UI requirements + point data, using a [GeoJsonSource](https://www.mapbox.com/mapbox-gl-js/style-spec/#sources-geojson) with a [SymbolLayer](https://www.mapbox.com/mapbox-gl-js/style-spec/#layers-symbol) will get you the best results. For each badge you add a point to the source and create a visual representation with a symbolLayer.

Here is a [small guide to SymbolLayer](https://blog.mapbox.com/a-guide-to-the-android-symbollayer-api-5daac7b66f2c), note that this was written for the 5.x SDK. An updated version of the code can be found [here](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/labs/SymbolLayerMapillaryActivity.java). Let us know if you have any more questions, closing as answered.
