### ISSUE TITLE
Offline maps never load after several maps are downloaded

### ISSUE THREAD

**Issue by fedeojeda95** [mapbox/mapbox-gl-native#11859]
## Offline maps crash 

**Platform:** Android 
**Mapbox SDK version:** 5.5.1

Downloading several maps offline works correctly, whenever a map is downloaded and it's accesed while offline (airplane mode, for example) they are loaded correctly. Nevertheless, after downloading another map, all offline maps stop working, even the ones that were previously working. 

For example, I download for offline access maps A, B, and C. They work correctly offline, loading everything related to them. Afterwards, I download a map D, which won't work offline and now accessing maps A, B and C also won't work.

After further debugging, I found that the method to get the map async (`getMapAsync`) is not being called in the situations that the offline map is not being loaded. When the offline map does indeed work, the method is correctly called:

```Java
        mMapView.getMapAsync(mapboxMap -> {
            // Setup code
        });
```

Further debugging led me to debug the `onMapChanged` function that's implemented in the `MapCallback` class. As it may be seen in the code, the method received an `int` with the change that happened. 

I found that the change `DID_FINISH_LOADING_STYLE` is never actually sent when the maps is not working offline, while if the maps does work online, it is called. 

What is really inconsistent is why if the map was correctly working offline, after downloading another map, it will stop working.

I haven't been able to find a specific reason why this happens or which maps make the rest stop working. I believe it may be related to the size of the maps (if several maps are downloaded but are pretty small, around 10-15mb, I wasn't able to reproduce this)

### Steps to trigger behavior

 1. Download a map for offline access
 2. Go to airplane mode and try accessing it
 3. Repeat 1 and 2 until one of the maps does not load

### Expected behavior

The map loads correctly, showing it on the application. All the previously downloaded maps continue working offline

### Actual behavior

Map never load and a black screen is shown. All the previously downloaded maps that were correctly working before stop working.

Thank you very much in advance!

**Comment by tobrun** [comment]
@fedeojeda95 thank you for the report. This will be related how you are providing the map with your style. You are probably trying to load the style url when OnMapReady executes and that is not correct. OnMapReady will only be executed as result of successfully loading a style. What happens for the online cases is that we will load mapboxstreets (because you didn't provide a style upfront) and execute onMapReady. What happens if you are offline is that we will still load mapboxstreets but since you are offline we can't.. To resolve this you need to provide you style url as early as possible. This can be done with either:

```java
mapView.setStyleUrl("")
//or
mapboxMapOptions.styleUrl("")
```

lmk if these pointers didn't resolve your issue. Closing as answered.
