### ISSUE TITLE
autological-constant-compare in fill_extrusion_bucket.cpp

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11909]
Follow up from the NDK 17 update PR in https://github.com/mapbox/mapbox-gl-native/pull/11458#discussion_r187927487:

![screenshot from 2018-05-15 09-21-29](https://user-images.githubusercontent.com/2151639/40042366-653c02b2-5821-11e8-9ffb-b6812c2479b3.png)

The warning from above has been suppressed for now with https://github.com/mapbox/mapbox-gl-native/commit/56ff8b18baaf1217295ef075d5983338ea2039e4#diff-f07899604a0493652b354b7d538040b1R107 and still [needs to be resolved](https://github.com/mapbox/mapbox-gl-native/pull/11458#discussion_r187917394).

**Comment by lbud** [comment]
Oops, I did not see the comment in the previous ticket. The function of that check is to allow a pattern to reset rather than overflowing its attribute type in the event that an extrusion is so big that its perimeter (`dist`) is longer than 2^16. This would be a rare case (a complex polygon contained entirely inside one tile) but could happen, so it's likely nobody has noticed yet that it has been removed, but I'll resolve this today.
