### ISSUE TITLE
No zoom to max level (25) is possible when using the location plugin

### ISSUE THREAD

**Issue by mrfaa** [mapbox/mapbox-gl-native#11958]
Hi everyone,

does anyone experiences the same behavior?

**Platform: Android**
**Mapbox SDK version: 6.1.2**
**Mapbox location layer plugin: 0.5.2**

### Steps to trigger behavior
When using the new location plugin (https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-locationlayer) no zoom to the max level (25) is possible anymore. This can be seen in the demo app also: https://github.com/mapbox/mapbox-android-demo/blob/a411fa95cd71c1b90a30895060b319310444aebb/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/plugins/LocationPluginActivity.java

### Expected behavior
Max zoom (25) is possible/ensured

### Actual behavior
Max zoom (25) is **not** possible/ensured

**Comment by LukasPaczos** [comment]
Hey @mrfaa, since `v0.5.0` of the `LocationLayerPlugin` this is an expected behavior. To overwrite these settings and enable a wider range of zoom levels use [max/min zoom options](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerOptions.java#L392-L406) which default to [18 and 2 respectively](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerOptions.java#L46-L54). Enabling a bigger max zoom value might result in a choppy animation during location tracking.

**Comment by mrfaa** [comment]
@LukasPaczos thank you very much! Thats it! Maybe a consolidation/harmonization of the max/min zoom setter methods is an option, otherwise it needs to be done in the MapboxMap **and** in the LocationLayerOptions objects.

**Comment by LukasPaczos** [comment]
I'm happy it helped! `LocationLayerPlugin` calls into the same `MapboxMap` methods that set the max/min zoom on the map object itself, so setting a plugin option should be enough. Let us know if it's still an issue.

**Comment by mcfoi** [comment]
Thank you for clarifying this point: it wasn't quite obvious that enabling the Mapbox Android LocationLayerPlugin whould change max zoom value!
