### ISSUE TITLE
Clustering with custom point annotation and annotation view

### ISSUE THREAD

**Issue by Lavmint** [mapbox/mapbox-gl-native#12035]
**Platform: iOS**
**Mapbox SDK version: 4.0.1**

### Steps to trigger behavior

 1. Looking at [this](https://www.mapbox.com/ios-sdk/examples/clustering/) example and make some research of replacing geoJSON url with my own annotations.
 2. Making `StopAnnotation: MGLPointFeature` and `StopAnnotationView: MGLAnnotationView`
 3. Creating source `MGLShapeSource` with features of type `StopAnnotation` via [initialiser](https://www.mapbox.com/ios-sdk/api/4.0.1/Classes/MGLShapeSource.html#/c:objc(cs)MGLShapeSource(im)initWithIdentifier:features:options:)
4. Creating pins, cluster and numbers layers

### Expected behavior
Clustering is working fine. Pins that are not in cluster **shown as** `StopAnnotationView`

### Actual behavior
Clustering is working fine. Pins that are not in cluster **not shown**.

### Comment
Did I miss smth or this is just not possible? Any suggestions?
For now I ended up with:
- hiding annotations at zoomLevel > 16
- displaying cluster source and pins source as circles with different diameters at zoomLevel <=16
This is workaround that causes many troubles in memory usage.
I have several hacks in mind to improve memory usage but they are just hacks.

**Comment by jmkiley** [comment]
Hi @Lavmint -

Thank you for using Mapbox! Clustering for point annotations is being tracked in #5814. For guidance on clustering circle style layers, please see [this example](https://www.mapbox.com/ios-sdk/examples/clustering/).

**Comment by Lavmint** [comment]
@jmkiley, but I've already mentioned this example in Steps.

**Comment by jmkiley** [comment]
It looks like you are trying to use annotation views rather than style layers, the latter of which are used in the example. Clustering for view-backed annotations is being tracked in #5815.  For more information about the different ways to display points on a map, please check out our [adding markers to a map guide](https://www.mapbox.com/ios-sdk/api/4.0.2/adding-markers-to-a-map.html).

If you have any further questions about how to cluster point data with our SDK, please [reach out to our support team](https://www.mapbox.com/contact/). We'd be happy to help!
