### ISSUE TITLE
Moving gesture selected annotations onscreen should be configurable

### ISSUE THREAD

**Issue by jmkiley** [mapbox/mapbox-gl-native#12064]
Currently, if an annotation is selected via a gesture recognizer, the [map pans to fit that annotation on screen](https://github.com/mapbox/mapbox-gl-native/blob/a721b74b87e51d17c5712fe947f56515c77defba/platform/ios/src/MGLMapView.mm#L1616). This behavior should be configurable. 

It looks like we have [considered a delegate method](https://github.com/mapbox/mapbox-gl-native/blob/a721b74b87e51d17c5712fe947f56515c77defba/platform/ios/src/MGLMapView.mm#L4187) for this purpose. 

cc @julianrex

**Comment by jmkiley** [comment]
I'm seeing this behavior with a the [annotation views](https://www.mapbox.com/ios-sdk/examples/annotation-views/) example when the callout is disabled. Added a bug label to this issue.

**Comment by jmkiley** [comment]
This is the documented behavior for [annotation views](https://www.mapbox.com/ios-sdk/api/4.1.0/Classes/MGLAnnotationView.html#/c:objc(cs)MGLAnnotationView(im)setSelected:animated:). Removed the bug label.

I also see this behavior when using the default annotation image in place of an annotation view. The behavior occurs when callouts are not being presents.

**Comment by julianrex** [comment]
Some background context: my intention with adding `-[MGLMapView isBringingAnnotationOnscreenSupportedForAnnotation:animated:]` was to (initially) provide a narrow focus to the pan-onscreen change (supporting `MGLPointAnnotation` only) - but one that would also give us room to extend the behaviour to other annotation types. 

My thought was that a delegate method would be most appropriate here.

**Comment by 1ec5** [comment]
Here’s what I think the expected behavior would be, for parity with both MapKit and Google Maps; please correct me if I’ve missed or mischaracterized a case:

1. Calling `-selectAnnotation:animated:` with `NO` does not pan the map.
2. Calling `-selectAnnotation:animated:` with `YES` does pan the map to fit the annotation and its callout – that’s what the `animated` parameter means.
3. Tapping an enabled point annotation pans to fit the annotation and its callout.
4. Tapping an enabled shape annotation could pan to fit the callout but would not pan to fit the whole annotation. We have some leeway with this case because shape annotations aren’t selectable in either MapKit or Google Maps.
5. Tapping a disabled point or shape annotation doesn’t pan the map, thanks in part to #12352.

Adding a delegate method could get weird in cases (1) and (2): if the developer has explicitly asked the map view to animate (i.e., pan) the map when selecting an annotation, why would we turn around and ask them whether they want to pan the map?

[![sure](https://docs.microsoft.com/en-us/windows/desktop/uxguide/images/mess-confirm-image2.png)](https://docs.microsoft.com/en-us/windows/desktop/uxguide/mess-confirm#design-concepts)

The rationale behind case (3) is that a partially visible callout looks terrible; if there isn’t a callout, moving the annotation fully on-screen may be the only visual acknowledgment of the annotation’s selection. I do wonder whether #12352, which fixed case (5) for shape annotations, eliminated the need for a dedicated delegate method about panning. After all, if the developer wants to make it so that tapping a partially visible annotation does nothing, they probably wouldn’t mind disabling the annotation altogether.

**Comment by julianrex** [comment]
Re:
> Calling `-selectAnnotation:animated:` with `YES` does pan the map to fit the annotation and its callout – that’s what the animated parameter means.

I think it's worth re-evaluating the meaning of the animated parameter here. Currently it's as @1ec5 says - defines whether the map is panned to ensure the annotation and callout are in view. It does not (currently) mean animate the selection transition or callout presentation. If we changed the meaning (to better match other methods with `animated` parameters) then a delegate method (for panning) starts to make sense.

Regardless or not, we may also want to partially undo some of the changes I made in https://github.com/mapbox/mapbox-gl-native/pull/11442

Mapkit's docs for `selectAnnotation:animated:` animated parameter states:
> If YES, the callout view is animated into position.

but it's unclear exactly what "into position" means here. I'd be happy with animated to refer to the animation of the annotation & callout, rather than its movement.

If we do switch to the above AND have a delegate method, then I think we can get the behaviour we're looking for. I'm going to experiment and update #12970. Please check there for an update.

**Comment by 1ec5** [comment]
MapKit interprets `animation` to mean panning the map to ensure the annotation and callout are in view. That’s the behavior we want. We had originally misinterpreted the documentation to mean that the callout gets faded in with animation: #3249.

**Comment by 1ec5** [comment]
> Regardless or not, we may also want to partially undo some of the changes I made in #11442

#11442 did the right thing for GL point annotations but not for view-backed annotations: #13055.
