### ISSUE TITLE
iOS: No longer able to load local Sprite resources

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#1208]
I am setting a custom style in my app, as follows:

    NSString *jsonFile = [[NSBundle mainBundle] pathForResource:@"tallygo-v7" ofType:@"json"];
    NSURL *styleURL = [NSURL URLWithString:[NSString stringWithFormat:@"asset://%@", jsonFile]];
    [self.mapView setStyleURL:styleURL];

However, the sprite sheet (in the app bundle) is no longer loading. This URL was working in previous versions by inserting the URL into the raw JSON at runtime, but is now no longer found:

    asset:///Users/picciano1/Library/Developer/CoreSimulator/Devices/7A8973A8-E8B6-4D23-85BE-25B92FBC0067/data/Containers/Bundle/Application/4ECBD40F-A759-4279-AC15-C5D1C20B4316/TallyGo.app/tallygo

The files are located at the root level of the main bundle. I have tried various paths without success:

    asset://tallygo
    asset:///tallygo
    tallygo

I have even tried hard-coding the absolute path above into the style JSON.

Is there any way to do this now?

**Comment by 1ec5** [comment]
The asset: URL scheme looks inside MapboxGL.bundle due to #1012. To point inside your app’s main bundle, you should be able to pass in a relative or absolute path to it. Does that work for you?

**Comment by picciano** [comment]
I have tried that and it no longer seems to be working. Note that I am referring to the Sprite assets, not the style JSON. The style is loading, however, the Sprite assets are not.

**Comment by 1ec5** [comment]
You’re right, none of this is working correctly right now. As far as the GL backend is concerned, there can only be HTTP(S) URLs backed by `HTTPRequestImpl` and asset: URLs backed by `AssetRequestImpl`. (mapbox: URLs are normalized to HTTP in `mbgl::util::mapbox::normalizeURL()`.) Passing in a file: URL trips an assertion in `HTTPRequestImpl::handleResult()`, but of course we shouldn’t be in there anyways.

Passing in an asset: URL doesn’t work either because `AssetRequestImpl` assumes `mbgl::platform::assetRoot()` to be its root. #1012 changed that root from the app bundle to MapboxGL.bundle, which is where we put various things like the compass image.

**Comment by 1ec5** [comment]
@picciano To answer your specific situation, where did you put your sprite JSON and how did you name it? If the style JSON has `style` set to `asset://tallygo`, `Sprite` expects the sprite JSON to exist at MapboxGL.bundle/tallygo.json or MapboxGL.bundle/tallygo@2x.json, with the sprite sheet in the same place (.png instead of .json).

**Comment by 1ec5** [comment]
(As a temporary workaround, you can also dig yourself out of MapboxGL.bundle with a bunch of `../`’s, but obviously we need a way to specify relative local paths.)

**Comment by picciano** [comment]
I put the style JSON and sprite files at the root level of the main application bundle.
    tallygo-v7.json
    tallygo.json
    tallygo.png
    tallygo@2x.json
    tallygo@2x.png

I just tried `asset://../tallygo` and that worked. Good workaround. Is this captured somewhere else? Or should we leave this issue open until a real fix is in place?

![screen shot 2015-04-07 at 5 11 14 pm](https://cloud.githubusercontent.com/assets/417933/7035741/29b9f13c-dd49-11e4-92ee-3961f48ce0b9.png)

**Comment by 1ec5** [comment]
Let’s leave this issue open.

**Comment by incanus** [comment]
This has a workaround and is not critical for b2.

**Comment by incanus** [comment]
I am seeing style assets at the app bundle root working fine as `asset://foo.json` currently.

**Comment by incanus** [comment]
Ah, we do have differing code paths based on the Mapbox SDK integration method. What I mentioned above only works in the `Mapbox GL.app` test app, but when, say, you use Swift and CocoaPods, Xcode assembles the `Sirius.app` and `Mapbox.framework` build products dynamically and the paths are different.

**Comment by friedbunny** [comment]
The `../` path traversal workaround no longer works. Workaround for the workaround is to use HTTP(S) URLs.

**Comment by picciano** [comment]
This is no longer an issue for us since we can now use client-side images for annotations. Much better than custom sprite sheets!

**Comment by 1ec5** [comment]
> This is no longer an issue for us since we can now use client-side images for annotations.

This is definitely the way to go nowadays if you want custom images.
