### ISSUE TITLE
Pinch in short segment of road

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1209]
Howard at Washburn, around the corner from the Mapbox SF office, is reduced to one lane on iOS but [not on mapbox-gl-js](https://www.mapbox.com/mapbox-gl-styles/#19/37.77459/-122.41369):

![road_narrows](https://cloud.githubusercontent.com/assets/1231218/7008728/16394da6-dc4a-11e4-9c07-b1c620e3a0d9.PNG)

I looked but couldn’t find a sign like this:

![](http://upload.wikimedia.org/wikipedia/commons/3/33/MUTCD_W5-1.svg)

**Comment by incanus** [comment]
![article-2458073-18b7e4f800000578-183_634x460](https://cloud.githubusercontent.com/assets/17722/7008923/7505b120-dc4b-11e4-980b-add753b67334.jpg)

**Comment by mb12** [comment]
You can check if the pinch happens only for Emerald style or other styles as well. If it only happens on Emerald, then its a client rendering issue and not a data issue.

**Comment by 1ec5** [comment]
Good point. Moved to mapbox/mapbox-gl-styles#89.

**Comment by mb12** [comment]
From the screenshot, It looks like pixels within linewidth/2 have been made transparent instead of being kept opaque.  Is there some way to turn off  line anti-aliasing in GL-Native?  This would  isolate if the problem is in line anti-aliasing code.

https://www.mapbox.com/blog/drawing-antialiased-lines/
