### ISSUE TITLE
An error when add new class to Mapbox iOS SDK source code

### ISSUE THREAD

**Issue by coolegg** [mapbox/mapbox-gl-native#12110]
**Platform:** iOS
**Mapbox SDK version:**

### Steps to trigger behavior

 1.Add a new class to the SDK and set it to the public. The dynamic was build successful. 
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/17996856/41211481-38d70592-6d6a-11e8-9883-4e6c5deac57a.png">
But when I used this new class in Demo App, it was wrong.
 2.This is the error
![wechatimg23866](https://user-images.githubusercontent.com/17996856/41211276-c8498878-6d68-11e8-85bf-08fc44ba6d01.jpeg)

 3.How to solve this problem, thank you for your help

### Actual behavior

**Comment by kkaefer** [comment]
Unless you work on adding new features to the SDK _itself_, you should add new classes to your own frameworks or apps instead of modifying the underlying SDK. We are only exposing certain kinds of known symbols (marked with `MGL_EXPORT`) to reduce the framework size; all other symbols will be marked as hidden and removed during linking if they're not accessible.
