### ISSUE TITLE
LatLngBounds of visible region incorrect when map rotated

### ISSUE THREAD

**Issue by kjkrum** [mapbox/mapbox-gl-native#12135]
`MapboxMap.getProjection().getVisibleRegion().latLngBounds` is wildly incorrect when the map is rotated past a certain angle. The angle at which the calculation goes off the rails is the angle of the diagonal of the `MapView`.

To demonstrate this, in my camera idle listener, I get the `LatLngBounds` as above and draw a thick red polyline around their perimeter, removing the old polyline if present. When the map is oriented north-south, half the width of the polyline is visible all around the edge of the map, exactly as you would expect. When it's rotated less than the angle of the diagonal, just a bit of the polyline is visible in the corners, again as you would expect. But as soon as it's rotated past the angle of the diagonal, it's evident that east and west are being set from the wrong corners. In this screenshot, the west edge of the bounds is being set from the bottom right corner, when it should be the bottom left.

![device-2018-06-12-233157](https://user-images.githubusercontent.com/1007080/41334075-04eba834-6e99-11e8-830b-fe39fab2587b.png)

Using 6.1.2. Also tested with 5.5.3.

**Comment by LukasPaczos** [comment]
Thanks for reporting this issue @kjkrum. I'm seeing that https://github.com/mapbox/mapbox-gl-native/pull/11309 introduced this issue while fixing incorrect bounds generated by the builder when crossing IDL. @osana what do you think about bringing back the builder for the visible region bounds generation but fixing it over IDL instead of the solution proposed in https://github.com/mapbox/mapbox-gl-native/pull/11309? I feel like it brings too much complication and another approach to doing the same thing.

**Comment by osana** [comment]
@LukasPaczos @kjkrum  I believe the hard use case is when Map is very zoomed out showing almost the entire world with IDL in the middle and map is rotated. Using includes() as suggested above will not work as it will do the shortest bounds to include those points. 

I think we will have to use LatLngBounds.from() but it is not easy to figure out which value is north, south, east and west.
