### ISSUE TITLE
Do not invoke camera move callbacks for taps

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#12165]
Currently, simple taps that do not include any movement are still invoking camera movement start and idle callbacks. This is to be expected, but not convenient if someone is relying on `OnCameraIdleListener#onCameraIdle` to update clickable symbols.

**Comment by jeffm19** [comment]
Hi @LukasPaczos, do you have a workaround suggestion for those apps that were currently relying on OnCameraIdleListener#onCameraIdle to update clickable symbols? In my current app after the update to 6.2.1, when I tap on the screen, my symbols flicker because of the redraw due to the onCameraIdle call. This did not happen when using 5.5.x.
