### ISSUE TITLE
Switch to ICU for platform::uppercase/lowercase()

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#12174]
We're currently using `nunicode` to perform these operations on systems that don't have a platform-native implementation. Since we're already bundling ICU, we should switch over to ICU and remove nunicode to lower our dependency count.

The only place where we currently use this is in the `upcase`/`downcase` expression functions. Once https://github.com/mapbox/mapbox-gl-native/pull/11869 lands, we could add `uppercase`/`lowercase` to the collator, and expose an optional language when performing the case transformation.

/cc @ChrisLoer

**Comment by ChrisLoer** [comment]
🤔 I agree with the long-term direction here, but the current state of #11869 actually kind of doubles down on nunicode as the fallback when we can't use built-in platform support. I don't know of a hard technical barrier to using ICU universally as our fallback, but nunicode is basically easier:

- We can fold the parts of nunicode we need directly into gl-native, which means the Qt code doesn't get a mason/binary dependency (which is a problem since the Qt build matrix covers a lot of platforms that we're not otherwise building for). Qt is _usually_ built with ICU, but we also have to support the "no ICU" case, so we'd have to either stub out the code for that case or fallback to something else.
- Once we use ICU along with locale information, we have to start making decisions about which locales to bundle (or how to make locale-bundling configurable). Nunicode's use of DUCET kind of side-steps this concern.

**Comment by ChrisLoer** [comment]
cc @nagineni @brunoabinader

**Comment by brunoabinader** [comment]
Both [QLocale::toUpper](https://doc.qt.io/qt-5/qlocale.html#toUpper) and [QLocale::toLower](https://doc.qt.io/qt-5/qlocale.html#toLower) wraps such functionality in the following form:
> If Qt Core is using the ICU libraries, they will be used to perform the transformation according to the rules of the current locale. Otherwise the conversion may be done in a platform-dependent manner, with QString::toUpper() as a generic fallback.

@nagineni we can add this as part of your Qt collator patch :+1:

**Comment by kkaefer** [comment]
This is less important now that we're using Java functions on Android, Cocoa functions on iOS and Qt-provided functions on Qt.
