### ISSUE TITLE
Why Tinder app needs all the architecture lib for mapbox downloaded from the google app store? (42MB)

### ISSUE THREAD

**Issue by fssrepository** [mapbox/mapbox-gl-native#12208]
Is it really needed for an android based app?

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. Unfortunately, you haven't provided enough information for us to be able to help you. When opening an issue, please fill out the provided issue template completely -- we need all this data in order to provide an answer. In particular, for issues such as this we will almost always need you to provide a minimal working example that demonstrates the issue. If you can provide those things, please feel free to open a new issue.

**Comment by fssrepository** [comment]
You haven't made any support on this, as you can download it easily from https://tinder.en.uptodown.com/android. Open it in an android studio, and you can see that the lib folder which contains mapbox file use up almost all the space what the Tinder installer consumes. (there are some images also) The document of yours tells that to reduce the size of installer you can remove some architecture, that's why i have asked why Tinder app needs the whole?
