### ISSUE TITLE
Publishing node modules is broken

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#12206]
Publishing node modules has been broken since #11913 due to incompatibilities between node-pre-gyp and @mapbox/cmake-node-module.

In short: @mapbox/cmake-node-module is generating files named `lib/mbgl-node.abi-48.node`, `lib/mbgl-node.abi-57.node`, etc., but node-pre-gyp expects only one file, built for the currently active version of node, named `lib/mapbox_gl_native.node`.

https://github.com/mapbox/node-pre-gyp/issues/395 proposes allowing the file name expected by node-pre-gyp to be more customizable.

To publish multiple ABI versions from a single host, we may be able to use the `--target` argument to node-pre-gyp, and loop over a list of desired versions. However, this would require us to keep two lists in sync: a list of ABI versions for @mapbox/cmake-node-module to build (actually a list of _excluded_ ABI versions) and a list of node versions (corresponding to the build ABI versions) for node-pre-gyp to publish.

cc @kkaefer @springmeyer

**Comment by kkaefer** [comment]
Restored in https://github.com/mapbox/mapbox-gl-native/pull/12222. We are now using `lib/node-v57/mbgl.node`, which is compatible with the current release of `node-pre-gyp` and conveniently allows us to only publish the binary in question, since `node-pre-gyp` creates a tarball of the entire folder the node module is in.
