### ISSUE TITLE
Chinese labels should be wrapped by character with balanced lines

### ISSUE THREAD

**Issue by barrycug** [mapbox/mapbox-gl-native#1223]
the font is "Unifont Medium” .The english is ok

**Comment by mikemorris** [comment]
Can you please provide more details on what the expected result is versus what is actually rendered?

**Comment by barrycug** [comment]
![issure](https://cloud.githubusercontent.com/assets/1191156/7037006/631010da-ddce-11e4-87b1-2e4ed8877cd9.png)
on the screenshot,you can find the English text have 2 lines,and the chinese text have 1 line.
and  i set the text-max-width =5;
 "text-max-width":5

**Comment by barrycug** [comment]
I know ,the text wrapped line depend on space.But in chinese ,the text have not include the space.

**Comment by friedbunny** [comment]
Japanese has a similar issue, to a lesser degree because names tend to be shorter. The problem is that it would be difficult to determine where to break an un-spaced line — it would likely have to be specific to each language.

Off the top of my head, Japanese could be split on certain characters (like `・` or other punctuation) or when switching character sets, e.g., syllabaries giving way to kanji like in `カタカナ漢字` or alphabet to kanji `ABC公園`, etc.

**Comment by barrycug** [comment]
thank you very mach. I split the text by the size. It is the most simple solution。Mayby I can insert space into the data，this is the correct solution，because it can use the natural language broken。But it is a hard work。

    bool hasspace = false;
    uint32_t space = 32;
    if(!(string.find(space) ==std::string::npos))
    {
        hasspace = true;
    }
    long breakOffset=-1;
    if (!hasspace) {
        if (string.size() > maxWidth/24) {
            breakOffset = string.size()/2+1;
        }
    }
   
    int i=0;
    for (uint32_t chr : string) {
        if (!hasspace &&i==breakOffset) {
            shaping.emplace_back(space, x, y);
            auto metric = metrics.find(space);
            if (metric != metrics.end()) {
                x += metric->second.advance + spacing;
            }
        }
        shaping.emplace_back(chr, x, y);
        auto metric = metrics.find(chr);
        if (metric != metrics.end()) {
            x += metric->second.advance + spacing;
        }
        i++;
    }

**Comment by barrycug** [comment]
the code only support 2 line wrapped.

**Comment by mikemorris** [comment]
Thanks for the detailed explanation @barrycug and @friedbunny! The "proper" way to implement this would probably be to use something like ICU's `BreakIterator` for [boundary analysis](http://userguide.icu-project.org/boundaryanalysis), then calculate the width of glyph clusters [similarly to Mapnik](http://mapnik.org/news/2012/07/22/gsoc2012-status5/) and split on the closest break point. A similar approach for more complex scripts that require shaping is described at http://lists.freedesktop.org/archives/harfbuzz/2014-February/004140.html

**Comment by mikemorris** [comment]
Linking Mapnik line-breaking implementation here for future reference https://github.com/mapnik/mapnik/blob/master/src/text/text_layout.cpp

**Comment by friedbunny** [comment]
That's really interesting reading and looks like the ideal path to pursue, thanks @mikemorris. Do you have any idea how feasible it would be to do this properly/robustly in GL?

**Comment by mikemorris** [comment]
@friedbunny I think it should be pretty straightforward to implement in gl-native because of existing libraries like ICU and HarfBuzz; the challenge will mostly be avoiding performance slowdowns and minimizing bloat. I'd like to tackle this in conjunction with other render-time glyph issues like complex text shaping and RTL/bidirectional script support.

What I expect will be difficult is implementing comparable functionality in mapbox-gl-js, as I'm not sure if it would be feasible to bundle (or request dynamically) contextual line-breaking support or shaping tables, and I don't know any existing JavaScript libraries that have already solved these problems.

**Comment by mikemorris** [comment]
-> https://github.com/mapbox/mapbox-gl/issues/4

**Comment by 1ec5** [comment]
CJK line breaking is orthogonal to complex text shaping. For example, the most cartographically sound way to wrap Chinese text (but not Japanese or Korean) would be character by character, keeping the lines balanced.

Reopening.
