### ISSUE TITLE
MGLSymbolStyleLayer predicate option change

### ISSUE THREAD

**Issue by JamieJeon** [mapbox/mapbox-gl-native#12259]
Platform: iOS
Mapbox SDK version: 4.1.0

### Steps to trigger behavior

 1. I added the MGLSymbolStyleLayer with geojson file and I got the three of features
 2. I added a single tap gesture recognizer to change the predicate of the MGLSymbolStyleLayer
 3. I found a strange thing that is the count of visible features

### Expected behavior

1. I expected that the count of visible features is 2 when the predicate is like this. 
![2018-06-29 11 35 22](https://user-images.githubusercontent.com/20234316/42070280-9b49657e-7b90-11e8-8ea9-b883a0ddf0c7.png)
![poi2](https://user-images.githubusercontent.com/20234316/42072982-d3ab6e36-7b9e-11e8-8117-7a3a8fe8e443.jpeg)

2. I expected that the count of visible features is 3 when the predicate is nil back.
![2018-06-29 11 37 00](https://user-images.githubusercontent.com/20234316/42070319-c3469722-7b90-11e8-9cfb-c5162b313348.png)
![poi3](https://user-images.githubusercontent.com/20234316/42072986-ddcbb01a-7b9e-11e8-8e9a-ed822a557077.jpeg)

### Actual behavior

1. Actual the count of visible features is 3 when the case 1

2. Actual the count of visible features is 2 when the case 2

The visible features aren't refreshed immediately after changing predicate.
If there is a changed feature after changing predicate then I got the collect list of visible features.
Also If I move the map after changing predicate, I got the collect list.
 
Is it a bug???

**Comment by fabian-guerra** [comment]
Hi, @JamieJeon. Thank you for using Mapbox. I am sorry to hear you are having some issues. In order to track the problem could you please share a code snippet or test app?

Also @ChrisLoer flagging this as it seems related to https://github.com/mapbox/mapbox-gl-native/issues/11780

**Comment by ChrisLoer** [comment]
> The visible features aren't refreshed immediately after changing predicate.
If there is a changed feature after changing predicate then I got the collect list of visible features.
Also If I move the map after changing predicate, I got the collect list.

Hi @JamieJeon, if I'm understanding that correctly, it sounds like expected behavior. The `queryRenderedFeatures` API does not synchronously reflect changes to symbol state. The reason is that, for symbols (icons and text), `queryRenderedFeatures` depends on collision detection having been run before it shows results (so for instance, you could add a symbol, but the symbol might not show on screen because of collision detection). Collision detection runs asynchronously (at least every 300ms, sometimes more often), and therefore the results of `queryRenderedFeatures` are similarly asynchronous.

**Comment by JamieJeon** [comment]
@ChrisLoer Thank you for answering this. 
Then, what should i do if i want the result synchronous?? 
Is there the way to refresh the map without moving?

**Comment by ChrisLoer** [comment]
Hi @JamieJeon, there's no way to force collision detection to happen synchronously.

I think you probably want to design around the assumption that this is asynchronous -- that stays closest to how the underlying map works. But if it is really necessary to be able to get the count synchronously, I think you'd have to implement it yourself. Something like "I just added this symbol, and I know the symbol has `icon-allow-overlap: true`, and I know the symbol is positioned within the current viewport, so I'm going to increment my 'visible' counter by one". Sorry, I know that's not an easy answer!
