### ISSUE TITLE
[ios, macos] Write "collator" wrappers for NSExpression

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-native#12269]
Follow-on for #11869: ios/macos now support "collator" expressions, but they're not directly exposed via the SDK. Collator expressions take a dictionary-style object as an argument, e.g.:

["collator", {"case-sensitive": false, "diacritic-sensitive": true, "locale": "en"}]

This is a new pattern so we'll have to figure out the right iOS/macOS way to expose it.

/cc @1ec5 @friedbunny @julianrex

**Comment by ChrisLoer** [comment]
> If collator can be used on its own, independently of a comparison expression, then we need to make sure it can be represented and round-tripped somehow – even if it’s just a struct in the NSPredicate syntax. But I think the modifiers would be the focus of our iOS/macOS support for collators, since it’s much more concise than what we could implement for standalone collators.

I'm not sure of all the terminology here, but currently a `Collator` (the result of evaluating a `CollatorExpression`) can be passed into comparison operators and it can also be passed as an argument to `resolved-locale`. It's not a valid result from an expression (e.g. there's no converter from `Collator` to `mbgl::Value`). cc @anandthakker

**Comment by 1ec5** [comment]
OK, that makes sense. So the most common way to perform a case-insensitive, locale-sensitive comparison in Objective-C or Swift would be:

```swift
NSPredicate(format: "name_fr =[cl] 'quebec'")
```

Note how `l` means “current locale”; there isn’t a way to specify a specific locale using this syntax.

As it is, it’s already possible, if ugly, to create a `collator` expression manually like this:

```swift
NSPredicate(format: "MGL_FUNCTION('==', name_fr, 'quebec', MGL_FUNCTION('collator', %@))",
            ["case-sensitive": false, "diacritic-sensitive": true, "locale": "en"])
```

So far we’ve only defined aftermarket expression functions for the most common operators, but we could define one for creating a collator, with a syntax like this:

```swift
NSPredicate(format: "MGL_FUNCTION('==', name_fr, 'quebec',
                                  collatorCaseInsensitive:diacriticInsensitive:locale:(TRUE, FALSE, 'en'))")
```

But more likely, we’d have operators like `==` convert a dictionary in the third argument to a collator:

```swift
NSPredicate(format: "MGL_FUNCTION('==', name_fr, 'quebec', %@)",
            ["case-sensitive": false, "diacritic-sensitive": true, "locale": "en"])
```

If we encounter a `collator` expression in style JSON, we should be able to convert it to a native comparison in some cases, but if the collator specifies a `locale`, then we’d only be able to use the NSPredicate syntax if the locale happens to match the current locale. Otherwise, we’d have to use the more verbose syntax.

**Comment by 1ec5** [comment]
The `[…]` flags in NSPredicate are represented by [`NSComparisonPredicate.options`](https://developer.apple.com/documentation/foundation/nscomparisonpredicate/1414069-options?language=objc).
