### ISSUE TITLE
getMaxZoom from layer returns "Infinity" for Android iOS

### ISSUE THREAD

**Issue by salihgueler** [mapbox/mapbox-gl-native#12321]
**Platform:** iOS and Android
**Mapbox SDK version:** 6.2.1

### Steps to trigger behavior

 1. Add a layer to custom map from styles with min zoom level `10` and max zoom level `22` (or anything). 
 2. Call the layer with layer id within the iOS or Android code.
 3. getMinZoom value returns `10` value but getMaxZoom returns `Infinity` as value.

Android code to get the min and max zoom values.

```
mapView.getMapAsync { mapboxMap ->
         val layer = mapboxMap.layers.find { it.id == LAYER_ID }
         layer?.let {
             // FIXME: max zoom returns Infinity on iOS and Android, an issue be reported to SDK.
             mapboxMap.setMaxZoomPreference(it.maxZoom.toDouble())
         }
}
```

iOS code to get the min and max zoom values

```
if let historicMap = style.layer(withIdentifier: LAYER_ID) {
    log.verbose("found historic map with min zoom: \(historicMap.minimumZoomLevel) - max zoom: \(historicMap.maximumZoomLevel)")
}
```

**Comment by tobrun** [comment]
Thanks for the report @salihgueler:

Debugging shows that not defining a maxzoom indeed results in Infinity:


```java
    SymbolLayer symbolLayer = mapboxMap.getLayerAs(MARKER_LAYER);
    Timber.e("MaxZoom: %s", symbolLayer.getMaxZoom()); // shows Inifinity
```

This is expected as we define this behaviour explitcly in layer.hpp:

```cpp
    float minZoom = -std::numeric_limits<float>::infinity();
    float maxZoom = std::numeric_limits<float>::infinity();
```

When I define a maxZoom for a layer, it's afterwards correctly retrieved:

```java

    SymbolLayer symbolLayer = mapboxMap.getLayerAs(MARKER_LAYER);
    symbolLayer.setMaxZoom(10);
    Timber.e("MaxZoom: %s", symbolLayer.getMaxZoom()); // shows 10
```

I'm a bit confused what the issue is, are you defining maxZoom/minZoom on the style itself vs on the layer or? Afaik everything is working as designed on our end. Would you be able to provide some additional information? would love to get to the bottom of this.

**Comment by salihgueler** [comment]
Hi @tobrun I have tested it today and it seems like it's working. Before it was returning infinity for iOS and Android. Thanks for the help anyway!
