### ISSUE TITLE
Upload debug builds alongside release builds

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1235]
cf1ecb6976b4f572b3d3eb6fd3f203e2f1ef2714 would make it much easier to debug crashes in apps other than the iOS demo app, but it was reverted in ce32e9f92ba5e9994ea1e8fb4dc09275db193ab2. Currently you either have to put up with the vagaries of debugging optimized builds or go through the rigamarole of building and reinstalling the library manually. Though it’ll increase build times, we should build both configurations.

**Comment by incanus** [comment]
Yep, agree and I will hit this. We'll do tags like currently (`ios-vX.Y.Z`) and for debug, we can do Git hashes. I'll see if I can figure out some way to get the Podspec to interpret the has as part of the zip filename to download like it does with version.

**Comment by incanus** [comment]
@1ec5 How do see best specifying which version to grab? If we roll a `Debug` build for each commit, the `.zip` download URL would differ for each. I guess you'd make a new branch that changes the `MapboxGL.podspec` to point to the hash you wanted? Or else you'd just be using `:path` to a local pod anyway.

**Comment by incanus** [comment]
I think the broader fix here is to still build in `Release`, but not strip debugging symbols, otherwise performance is way worse with using `Debug` just for symbols' sake.

**Comment by incanus** [comment]
Several of posts on the internet: 

- http://jonathanblog2000.blogspot.com/2013/07/xcode-build-settings-for-debug-symbol.html
- http://stackoverflow.com/questions/25512585/debugging-a-static-library-in-xcode

Plus Hockey's above-referenced FAQ:

- http://support.hockeyapp.net/kb/client-integration-ios-mac-os-x/how-to-solve-symbolication-problems

Seem to indicate the following options should be enabled for static libraries, but not apps: 

```
'COPY_PHASE_STRIP': 'NO',
'STRIP_STYLE': 'debugging',
'STRIP_INSTALLED_PRODUCT': 'NO'
```

I've introduced these settings for iOS GL targets in 381b27e1f4734bc7828072e13bc4ae0c0aabe0f3. 

We still strip for both the demo app and downstream apps, but that's ok since the archive process puts the symbols into the `.dSYM` that we use on Hockey. 

Going to roll a one-off app build for some testing of this theory.

**Comment by incanus** [comment]
Done some app build testing here and I think that our problem isn't necessarily that symbols are being stripped in our GL library build, but that use of it via CocoaPods and frameworks (for a Swift app) is what's doing it. 

Running `dwarfdump -u` on the built app binary yields one UUID, which matches `<name>.app.dSYM`, but does not match `MapboxGL.framework.dSYM`.

**Comment by incanus** [comment]
Tracked this down to a specific build which used CocoaPods, which plops dependent libraries' symbols in e.g. `MapboxGL.framework.dSYM` and our symbolication process missed this. 

I think we are ok symbols-wise for builds right now. 

This brings us back to the original ticket, which is to have an easy to way to get a per-hash build via CocoaPods, which means Travis or some other CI running `./scripts/ios/package.sh` on every commit or updating the podspec to build from source. I think the former is not great because of the speed on CI builds already, and the latter had other problems?

**Comment by 1ec5** [comment]
I did successfully get the podspec to build from source, but only by running iOS/package.sh wholesale from within there.

**Comment by incanus** [comment]
Yeah @1ec5 my hunch was we'd do that, the only downside though is the dependencies e.g. from Homebrew, Boost not least of all. We'd have to adapt the podspec to require/work with Homebrew Boost and that's sounding painful.

**Comment by incanus** [comment]
One approach here might be to to make a subspec within the main spec for building from source, for those who care. 

https://guides.cocoapods.org/syntax/podspec.html#default_subspecs

We could exclude the subspec by default, since they are assumed to be dependencies, and require you to explicitly name it in your `Podfile` (something like `pod MapboxGL/Source'). 

I'm not going to grab this just yet, and I don't think it's a beta priority, but we'll probably eventually want it.

**Comment by incanus** [comment]
Pushing this to b2 in favor of https://github.com/mapbox/mapbox-gl-native/issues/1234.

**Comment by incanus** [comment]
This ticket has morphed into building from source for CocoaPods, which is now covered by https://github.com/mapbox/mapbox-gl-native/issues/1437.
