### ISSUE TITLE
Custom styleUrl not working

### ISSUE THREAD

**Issue by adek** [mapbox/mapbox-gl-native#12451]
### Steps to reproduce

 1. We are using the latest mapbox-gl-native library in our Android app.
 2. We've got our own simple style and vector tiles (generated with mapnik-vector-tiles-1.5.0) and it works OK with mapbox GL JS (0.44.0). 
 3. We want to use it in Android app but we can't. We made simple app with activity showing map 

`<com.mapbox.mapboxsdk.maps.MapView
 android:id=“@+id/mapView”
 android:layout_width=“match_parent”
 android:layout_height=“match_parent”
 mapbox:mapbox_cameraTargetLat=“50.671062"
 mapbox:mapbox_cameraTargetLng=“17.926126”
 mapbox:mapbox_styleUrl=“https://myproject.com/mystyle.json”
 mapbox:mapbox_cameraZoom=“6” />`

We are using

`com.mapbox.mapboxsdk:mapbox-android-sdk:6.3.0`

We can't see maps loaded in our app. When I checked mapbox styles - they are working. There is a problem when we want to use our styles. Like I said, on other platform it works great (JS).

We get errors:
`{.com.mapboxtest}[Style]: Failed to load sprite: HTTP status code 404
{GLThread 439}[Style]: Failed to load tile 11/1125/688=>11 for source my-vectors: missing required field: extent
`
So it looks like MapView is working. We are not able to debug - what is generating 404 error. Is there a way to print more info about it. In our tiles of course there is extent field. 

### Configuration

**Android versions:** 7.1, 8.0
**Device models:** Android Emulator, Nexus 6p with Android 7.1
**Mapbox SDK versions:** com.mapbox.mapboxsdk:mapbox-android-sdk:6.3.0

**Comment by jfirebaugh** [comment]
The 404 is coming from the [sprite resource](https://www.mapbox.com/mapbox-gl-js/style-spec/#root-sprite) in the style.

We haven't heard any other reports of the "missing required field: extent" error occurring when the tiles do in fact contain the required [extent](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#41-layers) field. I would suggest double checking that all the layers in your tile do in fact have this field.

**Comment by rouen-sk** [comment]
Hi @jfirebaugh, I am working with @adek  on this, and of course we did checked the tiles for missing extent before we reached out for help. All layers have extent set to 4096. I can attach sample of our tile, so you can try to load it with GL native. 
[689.zip](https://github.com/mapbox/mapbox-gl-native/files/2218252/689.zip)

As for 404 on spritesheet, can you please confirm, that GL native is appending the same extension to the value configured in style - ".json" and ".png"? Because both there exists, and GL JS is using them with no problem.

**Comment by jfirebaugh** [comment]
The "builtup" layer in this tile does not have an extent.

**Comment by jfirebaugh** [comment]
And yes, `@2x.png` may be requested for the sprite on high-resolution screens.

**Comment by rouen-sk** [comment]
@jfirebaugh If I deserialize it (with 2 different libraries: https://github.com/bertt/mapbox-vector-tile-cs; ), I can see the builtup layer has extent 4096. 
![image](https://user-images.githubusercontent.com/7676825/43120636-3bcb04e2-8f1b-11e8-9cd2-2f984e47ffae.png)
![image](https://user-images.githubusercontent.com/7676825/43120929-3039fa06-8f1c-11e8-899d-493e75ef447e.png)
Are you sure the bug is not on your side?
