### ISSUE TITLE
Create object on worker thread

### ISSUE THREAD

**Issue by emerciercontexeo** [mapbox/mapbox-gl-native#12504]
I noticed that in the 6.3.0 (maybe 6.2.0) you added a lot of UIThread condition to mapbox methods.

I understand that interact with the map have to be done on the main thread but I don't understand the limitations added on object creation.

I have a lot of computation to create different sources and layers that can't be done on UI thread to avoid massive freeze on the application.

I used to create all my source and layer in an executor thread then return the result to the main thread to add it to the map.

Today, I can't do it anymore cause using new Source() in background thread throws a CalledFromWorkerThreadException.

I can work around, but I really think that methods and object that does not use the mapbox map should not throw this exception.

Etienne

**Comment by LukasPaczos** [comment]
Thanks for reaching out @emerciercontexeo.

This is being tracked in https://github.com/mapbox/mapbox-gl-native/issues/8484, and we know it's been an issue for a lot of users lately. However, even when creating source objects we are internally setting their data and this types of operations have to be executed on the main thread, otherwise, it can lead to various issues.

At the moment, you can try serializing your `FeatureCollection` with `FeatureCollection#toJson` asynchronously and passing that object when creating `GeoJsonSource`s on the main thread.
