### ISSUE TITLE
iOS and macOS Bindings for DefaultFileSource::mergeOfflineRegions

### ISSUE THREAD

**Issue by asheemmamoowala** [mapbox/mapbox-gl-native#12693]
Implement iOS and macOS bindings for the offline region merge API in #12608.

**Note:** The API requires that the input database path parameter be in a writable location. It may be required to copy the file to a temp folder before calling the API, and delete it before returning results.

**Comment by 1ec5** [comment]
`DefaultFileSource::mergeOfflineRegions()` would be likely be exposed as a method on MGLOfflineStorage that takes a file URL and completion handler.

**Comment by 1ec5** [comment]
> The API requires that the input database path parameter be in a writable location. It may be required to copy the file to a temp folder before calling the API, and delete it before returning results.

Is this because the sideloaded database may need to be upgraded to the latest database schema, or is there some other reason to require write access? I think it would be better for mbgl to accept a path regardless of write access, then either upgrade the database if there is write access or throw an error if it’s read-only. Otherwise, the SDK is forced to unconditionally copy the database, which would be extremely wasteful.

**Comment by asheemmamoowala** [comment]
>Is this because the sideloaded database may need to be upgraded to the latest database schema

This is exactly right. At present there is no migration necessary, so the writability is not required. This will be required in the next release that makes a database schema change. 

> I think it would be better for mbgl to accept a path regardless of write access

This is how it works now. If a database doesn't need to be migrated, then even a db path with read only access works with the `mergeOfflineRegions` API. (at least I found this to be true on a quick test with macOS)w
