### ISSUE TITLE
Passing invalid strings for expressions should fail more gracefully

### ISSUE THREAD

**Issue by captainbarbosa** [mapbox/mapbox-gl-native#12703]
### Steps to reproduce

 1. Set `lineJoin` to an invalid expression, such as 

```swift
let array = [MGLLineJoin.bevel, MGLLineJoin.round, MGLLineJoin.miter]
layer.lineJoin = NSExpression(format: "MGL_MATCH(tag, 'second', %@, 'first', %@, %@)", argumentArray: array)
```

The `mbgl_jsonExpressionObject` looks like this:
```json
(
    match,
        (
        get,
        tag
    ),
    second,
    "__C.MGLLineJoin",
    first,
    "__C.MGLLineJoin",
    "__C.MGLLineJoin"
)
```

 2. Observe a `EXC_BAD_ACCESS` crash.

### Expected behavior
This code should definitely still crash, but we should consider failing more gracefully when NSExpressions contain an invalid string format such as this.

### Actual behavior
Observe a `EXC_BAD_ACCESS` crash lacking helpful information for the developer attempting to debug this expression.

### Configuration

**Mapbox SDK versions:** 4.3.0
**iOS/macOS versions:** 11.4.1
**Device/simulator models:** iPhone X
**Xcode version:** 9.4.1

cc @mapbox/gl-core

**Comment by 1ec5** [comment]
> ```"__C.MGLLineJoin"```

This is quite unexpected; it should be `"join"`, `"round"`, and `"miter"`, as appropriate. `MGLLineJoin` is an enumeration, which automatically gets boxed in an NSValue. The conversion to NSExpression should recognize an NSValue containing a type like MGLLineJoin and convert it to the corresponding string value.

https://github.com/mapbox/mapbox-gl-native/blob/7fc872b797679ae033a32246206efb06c98a0fd5/platform/darwin/src/NSExpression%2BMGLAdditions.mm#L952-L964

We use a macro to associate `MGLLineJoin`’s values with strings. This macro provides a handy `toString()` method.

https://github.com/mapbox/mapbox-gl-native/blob/7fc872b797679ae033a32246206efb06c98a0fd5/platform/darwin/src/MGLLineStyleLayer.mm#L22-L26
https://github.com/mapbox/mapbox-gl-native/blob/7fc872b797679ae033a32246206efb06c98a0fd5/include/mbgl/util/enum.hpp#L23-L28

Here’s an example of using that method, but this is in code that converts from style functions rather than expressions.

https://github.com/mapbox/mapbox-gl-native/blob/7fc872b797679ae033a32246206efb06c98a0fd5/platform/darwin/src/MGLStyleValue_Private.h#L215-L229

**Comment by 1ec5** [comment]
> Observe a `EXC_BAD_ACCESS` crash lacking helpful information for the developer attempting to debug this expression.

This is also unexpected. What’s supposed to happen is that `mbgl::style::conversion::convert()` returns no `value` and populates `valueError`:

https://github.com/mapbox/mapbox-gl-native/blob/7fc872b797679ae033a32246206efb06c98a0fd5/platform/darwin/src/MGLStyleValue_Private.h#L77-L79

Then the SDK turns around and raises an NSException that goes uncaught:

https://github.com/mapbox/mapbox-gl-native/blob/7fc872b797679ae033a32246206efb06c98a0fd5/platform/darwin/src/MGLStyleValue_Private.h#L80-L82

mbgl should be robust enough to avoid crashing outright on an unexpected string value where an enum string is expected.

**Comment by lilykaiser** [comment]
@1ec5 do any of the unexpected behaviors you mention need tracking in a new ticket?
