### ISSUE TITLE
Bring tile queryPadding behavior back into conformance with GL JS

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-native#12701]
GL JS made a change to how it calculates queryPadding in https://github.com/mapbox/mapbox-gl-js/pull/6909.

I'm not sure if the change is relevant to gl-native, but it changes the behavior of the "multiple-layers" query tests.

cc @ryanhamley

**Comment by ryanhamley** [comment]
https://github.com/mapbox/mapbox-gl-js/issues/6896 is the original ticket that mapbox/mapbox-gl-js#6909 fixed. In GL JS, `queryPadding` was being calculated based on the first layer in a bucket because the code was hardcoded to always take the first element from `bucket.layerIds`. I changed it to be calculated for each layer and added a few different query tests to verify the new behavior.
