### ISSUE TITLE
two static renders in a row from same map w/ diff ratio breaks

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-native#1273]
First render, with ratio of 2:
![500x200 2x](https://cloud.githubusercontent.com/assets/108094/7159151/82e80bf8-e380-11e4-9711-6d4a45837f3f.png)

Second render, ratio is 1:
![500x200](https://cloud.githubusercontent.com/assets/108094/7159158/8ea54a50-e380-11e4-97a3-091120ff0389.png)

Third render, ratio still 1:
![500x200-1](https://cloud.githubusercontent.com/assets/108094/7159161/9445a34c-e380-11e4-9273-563211ea4000.png)

Looks like the ratio gets set after render is complete.

**Comment by mikemorris** [comment]
This happens when running api-gl caching map object caching, requesting a @2x static image, then a @1x static image, going from @1x to @2x has similar problems. Refreshing to request the changed dimensions a second time (@1x, @2x, @2x) shows the correct image, because the view has been resized to the same dimensions as the prospective render by then.

```
current: 2
prospective: 1
painter->render
DEBUG [Android] Map::resize
DEBUG [Android] Transform::resize
DEBUG [Android] Transform::resize post lock
DEBUG [Android] Transform ::resize exit true
DEBUG [Android] Map::resize exit
view.swap
current: 1
prospective: 1
```

Backtrace:
- [Map::resize#L406-L413](https://github.com/mapbox/mapbox-gl-native/blob/static-render/src/mbgl/map/map.cpp#L406-L413)
- [View::resize#L17](https://github.com/mapbox/mapbox-gl-native/blob/static-render/src/mbgl/map/view.cpp#L17)
- [HeadlessView::discard#L208](https://github.com/mapbox/mapbox-gl-native/blob/static-render/platform/default/headless_view.cpp#L208)
- [Map::render#L746](https://github.com/mapbox/mapbox-gl-native/blob/static-render/src/mbgl/map/map.cpp#L746)

**Comment by kkaefer** [comment]
Is this still happening?

**Comment by mikemorris** [comment]
This should be resolved by https://github.com/mapbox/mapbox-gl-native/pull/1799
