### ISSUE TITLE
OnCameraIdle() not working

### ISSUE THREAD

**Issue by matinashtiani** [mapbox/mapbox-gl-native#12741]
Hi, onCameraIdle() method does not called when I'm moving map in android app. why none of onCameraIdle(), OnCameraMove and OnCameraChanged() dont invoke?

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. Unfortunately, you haven't provided enough information for us to be able to help you. When opening an issue, please fill out the provided issue template completely -- we need all this data in order to provide an answer. In particular, for issues such as this we will almost always need you to provide a minimal working example that demonstrates the issue. If you can provide those things, please feel free to open a new issue.
