### ISSUE TITLE
Clustered item visualized as symbol when dissolving 

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#12798]
When zooming it, a cluster dissolves into symbols. When that happens you can see the cluster item itself being visualized before rendering the actual symbols. We didn't have this UX with 5.x, so I'm hunching that symbol placement is responsible for this.

![ezgif com-gif-maker 2](https://user-images.githubusercontent.com/2151639/44986329-a8a8a000-af83-11e8-9de6-32ec42ffbf09.gif)

**Comment by ChrisLoer** [comment]
> symbol placement is responsible for this.

Yeah, probably! But I don't think I understand the issue. Just looking at `GeoJsonClusteringActivity.java`, it seems like that icon _is_ supposed to be drawn at lower zoom levels, it's just covered up by the circles when there's clustering going on. So as you cross to the higher zoom where clustering isn't happening, it's just fading out as part of symbol cross fading. Wouldn't the solution just be to set a zoom limit on the "unclustered" layer?

**Comment by tobrun** [comment]
> Wouldn't the solution just be to set a zoom limit on the "unclustered" layer?

Not sure if this is possible as there isn't an arbitrary value that would work for each cluster. Eg. one cluster dissolves at zoom 6 but another at zoom 14. I'm not seeing this kind of configuration on the [gl-js](https://github.com/mapbox/mapbox-gl-js/blob/8121e9db044533d7e44e0afc8c58e71b6d8ec260/debug/cluster.html) code either.

@julianrex are you seeing this behaviour on iOS?

cc @mourner for visibility

**Comment by tobrun** [comment]
Thinking a bit more about this. It's solely the fading in/out of symbols that is responsible for this behaviour. Would it be possible to expose a configuration to enable/disable this fading? Would it make sense adding this as part of the style specification?

**Comment by ChrisLoer** [comment]
> Eg. one cluster dissolves at zoom 6 but another at zoom 14

Ah. I wasn't thinking about how the clustering zoom could change from feature to feature... 🤔 Hmm, minzoom can't be data-driven... not sure what the right workaround would be.

@brunoabinader started moving towards a global fade duration control at #13035 (similar to what we have on GL JS), but it wouldn't be per-layer. We discussed adding per-layer fade duration controls during the implementation of global collision detection, but decided against it mainly because of concerns about style spec complexity (it would also add a fair bit of complexity to the collision/fading code, although it probably wouldn't be terrible). cc @ansis

**Comment by julianrex** [comment]
> @julianrex are you seeing this behaviour on iOS?

Checking...
