### ISSUE TITLE
IconFactory doesn't follow the correct Locale

### ISSUE THREAD

**Issue by mhr9o2o** [mapbox/mapbox-gl-native#12903]
### Steps to reproduce

 1. We change the application Locale programmatically for example from "fr" to "en"
 2. All the assets will be changed respectively but the markers on the map
 3. I create the icons using: IconFactory.getInstance(context)fromResource(int resId);

### Expected behavior
It should create an Icon according to the current and correct locale of the application not the locale of the device.

### Actual behavior
I guess IconFactory follows the locale of the device not the locale of the app.

### Configuration

**Android versions: probably all of them, but as far as we have seen: 7, 8, 9** 
**Device models: All the phones we had checked including Samsung Galaxy S8, Nokia 7 Plus, etc** 
**Mapbox SDK versions: 6.4.0**

**Comment by tobrun** [comment]
@mhr9o2o 
thank you for reaching out and using our products. Changing Locale at runtime for your app is conceived as a bad practice as you should rely on on the system language instead for the best user experience. More information about this in https://developer.android.com/guide/topics/resources/localization. 

In our SDK we follow these guidelines and solely rely on the follow to load localized resources:

```
ContextCompat.getDrawable(context, resourceId);
```

We do not use any configurations to enforce the system language as this is default behavior. If you would still like to create a custom localization feature in your app, please use the other methods exposed in IconFactory instead as `IconFactory#fromBitmap` or `IconFactory#fromFile` or `IconFactory#fromAsset`...

Thanks again for reaching out but this issue is not actionable for us.

**Comment by tobrun** [comment]
FWIW the reason why the icons don't change at runtime is that we copy the bitmap when provided, so if you change your locale and load an image to the map. That added image should match your locale. Changing locale after will not change the image immidiatelly. You will need to load bitmap again and add it to the map.

**Comment by mhr9o2o** [comment]
Thanks dear @tobrun . Actually now I'm creating a bitmap from my drawable resource and then pass the bitmap to the IconFactroy and everything works well.
