### ISSUE TITLE
Mapbox in a recycler view, related to issue #6041

### ISSUE THREAD

**Issue by PieterVenter77** [mapbox/mapbox-gl-native#12957]
### Steps to reproduce

 1. Create a recycler view
 2. Add a view holder containing a mapbox instance
 3. Scroll up and down so that one mapbox instance goes out of view, or simply wait for the app to load

The issue seems related to mapbox being made null or being destroyed, although I am not entirely sure as the logs only really reference /lib/x86/libmapbox-gl.so 

### Expected behavior
All map views load or don't crash. Would also appreciate any references to mapbox being used in a recycler view if any examples exist as though could also help 

### Actual behavior
Map views crash, I can supply logs, however I don't want the logs to be made public as it is work I am doing for a client, so would prefer if I could send these to someone directly.

### Configuration

**Android versions:** 22, 23
**Device models:** Pixel 2
**Mapbox SDK versions:** 6.2.0 - 6.5.0

**Comment by LukasPaczos** [comment]
Hey @PieterVenter77, thanks for using Mapbox!

Putting a map inside of the recycler view is tricky because the rendering surface needs to be stopped and destroyed when the view is destroyed and then recreated. Please keep that in mind and try calling respective map's lifecycle methods, in order, following `View`'s "lifecycle" instead of `Activity`/`Fragment` ones.

That said, this isn't a supported use-case as you should always restrain from putting a scrollable object inside of a scrollable container. For this use-case APIs like `MapboxMap#snapshot` (takes a picture of a displayed map that can be reused later) or `MapSnapshotter` (generates map's picture out of style and bounding box, even if the map is not displayed) are better suited. Closing as not actionable.

**Comment by PieterVenter77** [comment]
thanks for your time, yeah this has definitely been giving me a lot of issues and has been a bit of a nightmare, the problem I have is that for this particular use case we would need to show markers with real-time data coming in as well, so the alternative is going to be having to load an image every single time a marker changes, which also isn't really viable, unless there's a different option ? 

PS. The maps work really nicely in the dialog fragment I am using them in, just for this particular use case of having them in the recycler it's a bit of a nightmare

**Comment by LukasPaczos** [comment]
In this scenario, another option would be placing the marker on on the map _after_ generating the picture. Take a look at [`MapSnapshotterMarkerActivity.java`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/snapshot/MapSnapshotterMarkerActivity.java) example.

**Comment by PieterVenter77** [comment]
Thanks, sounds like a decent alternative because i don't really need interaction for this, i just need to show markers and I handle movement and navigation with a fragment already, thanks a lot for your time, can close my issue 👍
