### ISSUE TITLE
Fatal signal 6 (SIGABRT) at 0x0000089 "terminating with uncaught exception of type jni::PendingJavaException

### ISSUE THREAD

**Issue by Xgamefactory** [mapbox/mapbox-gl-native#13063]
can you someone please explain what does this crash error means ?
```
10-09 13:03:44.620 2200-2200/com.**************.nativemapnavtestapp A/libc: /Volumes/Android/
buildbot/src/android/ndk-release-r17/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: 
abort_message: assertion "terminating with uncaught exception of type jni::PendingJavaException" failed
10-09 13:03:44.620 2200-2200/com.*************.nativemapnavtestapp A/libc: 
Fatal signal 6 (SIGABRT) at 0x00000898 (code=-6), thread 2200 (vemapnavtestapp)

```

**Comment by LukasPaczos** [comment]
Hey, @Xgamefactory, this is a native exception. If you're building from source, you can symbolicate the stack-trace using [this guide](https://github.com/mapbox/mapbox-gl-native/wiki/Getting-line-numbers-from-an-Android-crash-with-ndk-stack). If that doesn't work for you, would you be able to provide a reproducible example?

**Comment by Xgamefactory** [comment]
thanks @LukasPaczos  we have been struggled with building from source for a long time
you can see our issues all had been closed with no willing to help. i understand it just your support policy but unfortunately it doest not help to use your with such kind of support for a serious project. 
plus even with your stable releases there are many issues crashes instead of fixing it mapbox prefer to work on new "cool" features. map and navigation is just a part of our project we have decided to go with more stable heremaps sdk. 
Thanks for your kindly reply. We wish success to mapbox family.

**Comment by chloekraw** [comment]
Hey @Xgamefactory, we understand it can be frustrating to run into crashes, which is why we encourage all of our customers to use our [SDKs](https://www.mapbox.com/mobile/). We have [Maps](https://www.mapbox.com/android-docs/maps/overview/) and [Navigation](https://www.mapbox.com/android-docs/navigation/overview/) SDKs for Android and iOS which meet the needs of the vast majority of our customers. Could I ask why you are building from source, and what you are trying to build? 

We are more than willing to help through our support channel at https://www.mapbox.com/help/, as long as you use our SDKs and provide us with all of the information necessary to reproduce a crash or other unexpected behavior. Fixing crashes caused by our stable releases are our highest priority; when they arise, our team has been extremely responsive and dedicated to resolving them and publishing patch releases. Have you tried to contact us through our support channel instead of GitHub?

For serious projects, we also have options for [paid support](https://www.mapbox.com/support-services/#start) to help you get the most out of Mapbox.

Thank you for trying out our products and we wish you the best of luck with your projects.

**Comment by Xgamefactory** [comment]
Thanks again. but the crash issues happend on your sdk not build from source.

>  Could I ask why you are building from source
you can see in our issues why we are trying to build from source. we have explained it many times.

**Comment by Tsabary** [comment]
I am facing the same PendingJavaException crash, are there any solutions? My app is completely unusable with this crash and I can't seem to find any info about it.
