### ISSUE TITLE
Fatal signal 6 (SIGABRT) weak global reference table overflow (max=51200)

### ISSUE THREAD

**Issue by anthony-skr** [mapbox/mapbox-gl-native#13107]
### Steps to reproduce
I just started to manipulate the sdk, in a very basic way, just playing with location layer.
Then I got a native crash, just like that, when app was idling, in foreground, screen on.

### Crash
I'm not used to native crash, but got a long trace, hope it will help you :
https://gist.github.com/anthony-skr/8c61e41c10e243d6e3eda8d373ce5723

### Configuration

**Android versions:** 7.1.2 (LineageOS)
**Device models:** Samsung Galaxy S7 (herolte)
**Mapbox SDK versions:** android-sdk 6.6.0-beta.1

**Comment by anthony-skr** [comment]
Hey, I'm not able to reproduce it on demand, it happens randomly.
If I find any clue I'll let you know

**Comment by kjellhaaland** [comment]
Hi @LukasPaczos 

I experience the same issue as described by @anthony-skr, and the error causes the app to crash. 
It seems to occur when the LocationComponent follows the device position and updates the location indicator. I have tried several Mapbox versions, including android-v7.0.0-alpha.3

I have made a sample application [here](https://github.com/kjellhaaland/mapbox-jni-error/tree/master/sampleApplication)

**Steps to reproduce:**
Start the app and take a drive (or simulate driving) so that the map follows the user location.
After a few minutes, the error occurs. Eventually the app crashes!

Raw error log [here](https://gist.github.com/kjellhaaland/70595af41234fbd009009c44da65c956)

My device: Lenovo Tablet TB-X704L
Android version: 7.1.1

Hope this issue can be solved fast!

**Comment by anthony-skr** [comment]
For information I do not experience those crashs anymore (without having upgraded mapbox).

The @kjellhaaland's analysis is closed to a refactoring I did around LocationEngine instances. I think before I was using 2 instances and I finally ended with :

```
var mapbox: MapboxMap
...
mapbox.locationComponent.activateLocationComponent(context, engine)
```

Before I was using (old?) LocationLayerPlugin and it's possible I have mess-up with location engines.

Sorry for not providing sample project or more clues, it was so random that I missed the commit when they did stop!

**Comment by spiekermax** [comment]
This bug still exists.

**Comment by omerbn** [comment]
Hey, 
The bug is consistent and it happening after 1-2 minutes.
here's the gist:
https://gist.github.com/omerbn/f78be5b1f4d137f22a47eb486b947285

**Comment by AliKhoshraftar** [comment]
We have same issue on 7.4.0 and all previous ones.

**Comment by razvantmzz** [comment]
any update on this? i have the same issues on 9.6.1.
