### ISSUE TITLE
I compiled mapbox-gl-native on android, which was very difficult and not successful

### ISSUE THREAD

**Issue by leedejun** [mapbox/mapbox-gl-native#13145]
### Steps to reproduce

 1.
 2.
 3.

### Configuration

**Android versions:** 
**Device models:** 
**Mapbox SDK versions:**

**Comment by brunoabinader** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. Unfortunately, you haven't provided enough information for us to be able to help you. When opening an issue, please fill out the provided issue template completely -- we need all this data in order to provide an answer. In particular, for issues such as this we will almost always need you to provide a minimal working example that demonstrates the issue. If you can provide those things, please feel free to open a new issue.
