### ISSUE TITLE
Suggestion: Utilize LifecycleOwner

### ISSUE THREAD

**Issue by percula** [mapbox/mapbox-gl-native#13160]
As an alternative to overriding all the lifecycle methods, Mapbox should utilize the new Android architecture components' [LifecycleOwner](https://developer.android.com/reference/android/arch/lifecycle/LifecycleOwner).

**Comment by tobrun** [comment]
@percula thank you for reaching out and requesting this feature. We have been investigating this in #9039, we are currently on the fence on this topic due to saving state (more info on this in https://github.com/mapbox/mapbox-gl-native/pull/11933). Since we already have a ticket covering this. I'm closing this as a duplicate.
