### ISSUE TITLE
CameraUpdateFactory.scrollBy() issues when map has vertical padding

### ISSUE THREAD

**Issue by ericsvg** [mapbox/mapbox-gl-native#13187]
The app I'm working on has a bottom sheet and in some cases, I need to move the camera as the sheet is expanding so that it doesn't cover some points of interest on the map. Unfortunately moving the camera by small increments doesn't work when a vertical padding is set as the camera moves way more than expected.

### Steps to reproduce

 1. Set non-zero top or bottom padding on the map
 2. Call `map.easeCamera(CameraUpdateFactory.scrollBy(0.0, yPixel))` with a small yPixel value (even zero). Could also use `moveCamera()` or other alternatives

### Expected behavior
Camera moves by the given yPixel value.

### Actual behavior
Camera seems to be moving by the amount of vertical padding in addition to the given yPixel value. The issue doesn't seem to exist with a left/right padding but I haven't thoroughly tested this case.

### Configuration
**Mapbox SDK versions: 6.6.2**

**Comment by tobrun** [comment]
@Jukurrpa 
A quick test confirms:

Start position: `37.176546, -3.599007` with `scrollBy 400,0`

- Without padding:
   - `LatLng [latitude=37.17654988862586, longitude=-3.5961458681115346, altitude=0.0]`

 - With padding (eg. `mapboxMap.setPadding(250, 250, 0, 0)`)
    - `LatLng [latitude=37.177264070224126, longitude=-3.5970400465178045, altitude=0.0]`

**Comment by Jukurrpa** [comment]
Hi, thank you for fixing this. I think I'm running into a similar issue when using `CameraUpdateFactory.newLatLngBounds()`.

Side note first, I don't know if there's been a change in behavior since the v5.x.x but according to your comment in #9217, the map's padding is supposed to be taken in consideration, but it's not the case anymore.

But even when building the camera update by passing the map's padding, the final camera position isn't quite exact as it is shifted south a little. Basically I need to double the map's top padding to get something closer to the expected result.

**Comment by tobrun** [comment]
@Jukurrpa this went unnoticed for a long time and I feel this issue existed since we introduced map padding. The issue stems from the `CameraUpdateFactory` methods always hooking into moveTo, easeTo or animateTo. These methods will shift the target of the camera based on the padding. While that is desired in most cases as newLatLngZoom variants. It doesn't match expected behaviour for scrollBy and newLatLngBounds. I haven't settled on a clean solution yet, thank you for following up!

**Comment by Jukurrpa** [comment]
Glad I could help. Do you have an ETA for when it'll be fixed? Just to know whether to wait for a fix or use workarounds in the meantime.
