### ISSUE TITLE
Possibility to disable caching to DB (due to crashes after versions downgrade)

### ISSUE THREAD

**Issue by atetc** [mapbox/mapbox-gl-native#13273]
Hi!

I didn't find any feature toggle or parameter to disable map caching on Android
You could consider this as specific case (SDK version downgrading), but it's real case.
Is it possible to avoid caching tiles and other items to local SQLite DB?

### Steps to reproduce

 1. Launch online with 6.6.5 version
 2. Check app cache folder and see MapBox offline DB file
3. Upgrade to the next app version (but for some reasons SDK was downgraded to 5.x)
4. Launch app after upgrading and crash on launch.

### Expected behavior

SDK is not writing to local DB (not initializing DB file would be also good) and render only fresh loaded data, then no crashes after version downgrade.

### Actual behavior

SDK always save downloaded tiles and items data to local DB (in cache directory)

### Configuration

**Android versions:** Any
**Device models:** Any
**Mapbox SDK versions:** 6.6.5

P.S. We could implement cache cleanup after upgrading, but running with non-cache mode would be good option in that case.

**Comment by asheemmamoowala** [comment]
@atetc Why are you trying to disable the map cache? Is it to avoid a crash when downgrading the SDK ? 
In #12224, the database loading code was hardened to not clean out databases with an older schema version, which may happen when downgrading. Of course, since this is a new change, it won't be available in an older version of the SDK.
