### ISSUE TITLE
Merging offline DB created with different styles throws an error.

### ISSUE THREAD

**Issue by fabian-guerra** [mapbox/mapbox-gl-native#13282]
When an offline region created with style A is merged into an app that uses style B it throws the following error:

```
[DEBUG] {}[Database](1): BUG IN CLIENT OF libsqlite3.dylib: database integrity compromised by API violation: vnode unlinked while in use:
```

/cc @asheemmamoowala

**Comment by asheemmamoowala** [comment]
@fabian-guerra I used a locally created test DB (bounds around London in streets style). with the iOS demo app and was not able to reproduce this issue. 

Code is @ https://github.com/mapbox/mapbox-gl-native/tree/investigate-13282
Steps I Used:
- Launch app in iOS Simulator (i used iPhone 8 image)
- Change to raster style
- Select Style building extrusions - which is hijacked to merge the test database.

Note: I changed the pack metadata decoding because it was created with `mbgl-offline` and does not contain an NSKeyedArchiver-based blob.

**Comment by fabian-guerra** [comment]
@asheemmamoowala perhaps this is the problem:
> Note: I changed the pack metadata decoding because it was created with mbgl-offline and does not contain an NSKeyedArchiver-based blob.

I made a DB using `mbgl-offline` and I'm seeing this issue.

**Comment by asheemmamoowala** [comment]
So it turns out I didn't push my changes to the investigate branch ref'ed above. In any case, without the changes, I didn't get a crash in the sql code on macOS. the crash was in the macOS `[OfflinePackNameValueTransformer transformedValue:(NSData *)context]`.

That should be an easy fix, but needs confirmation that it does get rid of the crash.
