### ISSUE TITLE
[android] Consolidate abstract components files under modules folder

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#13432]
As part of the work to introduce abstract components https://github.com/mapbox/mapbox-gl-native/pull/12468 we moved some new files to the `modules` packages but, in order to adhere to SEMVER, some files couldn't be moved (see, for example, https://github.com/mapbox/mapbox-gl-native/pull/12468#discussion_r205396633).

As we work on the next release, which will be bringing SEMVER major changes, we should finalize that work and have all files for all components under `modules`. This list includes the new logger (i.e. `/log/*`), http client (`/http/*`), and telemetry (already fully moved?). @mapbox/maps-android: anything else we should move to `modules` this time around?

**Comment by tobrun** [comment]
@zugaldia thank you for ticketing this out, been looking into this and these are my findings so far:
 - Timber is still being pulled in by gestures library, ticket in https://github.com/mapbox/mapbox-gestures-android/issues/50
 - Noticed that turf is brining mapbox-sdk-core while it should only bring geojson
 - Log class doesn't need to be moved to the `module` package because it's actually not modular*. It's a runtime configuration that can replace the platform default logger with another (eg. in the testapp we hook into timber for logging). 

`*` = logging is not part of the Module Provider and it's not required for users to exclude any file for creating another log config.

With follow issues ticketed and no concrete follow up needed here I'm not seeing a need to keep this ticket open. Closing, fee free to reopen if there is a need for it.

**Comment by zugaldia** [comment]
Thanks @tobrun for the quick eyes and for digging up those additional issues.

Don't we still need to move all `http/*` files to `modules/http`?

**Comment by tobrun** [comment]
The files in http are either the definition or the hook for the sdk. These are required for all builds, they are also used if you would choose to swap out okhttp for another http client.

**Comment by zugaldia** [comment]
Thank you @tobrun for clarifying - additionally, the leftover work that sparked this ticket https://github.com/mapbox/mapbox-gl-native/pull/12468#discussion_r205396633 was done as part of https://github.com/mapbox/mapbox-gl-native/pull/13244.
