### ISSUE TITLE
Moving camera is broken when map it tilted

### ISSUE THREAD

**Issue by invised** [mapbox/mapbox-gl-native#13449]
### Steps to reproduce

 1. Set map tilt:
  ```
      mapboxMap.cameraPosition = CameraPosition.Builder()
                .tilt(MapboxConstants.MAXIMUM_TILT)
                .build()
```
 2. Move camera to new bounds:
```
    val boundsUpdate = CameraUpdateFactory.newLatLngBounds(latLngBounds)
    mapboxMap.animateCamera(boundsUpdate)
```
or
```
    val cameraPosition = mapboxMap.getCameraForLatLngBounds(bounds, mapboxMap.cameraPosition.bearing, MapboxConstants.MAXIMUM_TILT)
    mapboxMap.animateCamera(CameraUpdateFactory.newCameraPosition(cameraPosition))
```

### Expected behavior
Camera should be centered around the specified bounds

### Actual behavior
Camera moves in a random fashion. It seems like only the first time it is centered properly, all the subsequent moves are broken (especially zoom)  

### Configuration

**Android versions:** 8.1, 9.0
**Device models:** Android emulator, Nexus 6P, Huawei MediaPad M5...
**Mapbox SDK versions:** 7.0.0-alpha.2, 6.6.7, 6.3.0

This bug is also reproducible in the Mapbox Demo app from Play Store.

**Comment by LukasPaczos** [comment]
Thanks for reaching out @invised! This issue is directly connected to https://github.com/mapbox/mapbox-gl-native/issues/2259 and is going to be resolved at the same time, therefore, closing as a duplicate. Unfortunately, there is no clear workaround at this point, but we will report in https://github.com/mapbox/mapbox-gl-native/issues/2259 as soon as we know more.
