### ISSUE TITLE
Crash when filtering MGLFillStyleLayer with an NSPredicate

### ISSUE THREAD

**Issue by riastrad** [mapbox/mapbox-gl-native#13527]
When applying a predicate with an `IN <array>` statement that has 10-digit long NSNumbers in the array, a crash occurs if the array has 4 or more items in it. Oddly enough, if you trim the values of the numbers in the array down to 4-digits then the crash no longer occurs. 

### Steps to reproduce

 1. Create an `MGLFillStyleLayer`
 2. Apply a predicate to the layer with an array of NSNumbers. For example:
 ```
  layer.predicate = NSPredicate(format: "CAST($featureIdentifier, 'NSNumber') IN %@", [3002970001, 3004140052, 3002950027, 3002970033])
  ```
 3. Add that layer to your mapView's MGLStyle

### Expected behavior

Predicate should filter features in the layer by ID.

### Actual behavior

The app crashes with the following error:
```
'NSInvalidArgumentException', reason: 'Invalid filter value: [2]: Branch labels must be unique.'
```

### Configuration

**Mapbox SDK versions:** 4.6.0
**iOS/macOS versions:** iOS 12.1
**Device/simulator models:** iPhone XR
**Xcode version:** 10.1

cc: @mapbox/maps-ios

**Comment by 1ec5** [comment]
My first guess would be a precision problem in the code that converts NSExpression to JSON. The `NSExpression.mgl_jsonExpressionObject` property is useful for debugging these translation issues.

**Comment by riastrad** [comment]
Running `mgl_jsonExpressionObject` generates the following output: 
```
(
    match,
        (
        id
    ),
        (
        3002970001,
        3004140052,
        3002950027,
        3002970033
    ),
    1,
    0
)
``` 

I'm not seeing anything inherently wrong with this output, but my eye's are also not that fresh at this point.

**Comment by 1ec5** [comment]
These numbers are being converted to floats instead of doubles, despite the comment:

https://github.com/mapbox/mapbox-gl-native/blob/2d527c2af7224d03429b8b2ccb7c1712e8ffe12b/platform/darwin/src/MGLConversion.h#L120-L122 https://github.com/mapbox/mapbox-gl-native/blob/2d527c2af7224d03429b8b2ccb7c1712e8ffe12b/platform/darwin/src/MGLConversion.h#L85-L101

These numbers don’t fit in floating-point precision, so we’d want `toDouble()` to be called here.
