### ISSUE TITLE
Moxy compilation failed; see the compiler error output for details (java.lang.ClassCastException: com.sun.tools.javac.code.Type$ClassType cannot be cast to com.sun.tools.javac.code.Type$WildcardType)

### ISSUE THREAD

**Issue by gunferzs** [mapbox/mapbox-gl-native#13659]
### Steps to reproduce

 1. Add to gradle dependency of Mapbox
 2. Rebuild Project

I use Moxy 1.5.3, kotlin 1.2.15 and when I want run my project, I get next error:
```
e: error: Moxy compilation failed; see the compiler error output for details (java.lang.ClassCastException: com.sun.tools.javac.code.Type$ClassType cannot be cast to com.sun.tools.javac.code.Type$WildcardType)
:app:kaptDebugKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:kaptDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 37s
```

I don't understand what's wrong.

**Comment by tobrun** [comment]
@gunferzs there is nothing in that stacktrace pointing towards the Mapbox Maps SDK for Android being the root cause of this error. I'm finding a similar related stacktrace in the Moxy project [here](https://github.com/Arello-Mobile/Moxy/issues/137). 

Happy to look more into this if there are clear indications that Mapbox is responsible for this issue.

**Comment by gunferzs** [comment]
I see that issue. But my problem isn't Moxy, because if I don't include Mapbox in gradle, application assemble. But if I add Mapbox in gradle, application don't assemble.
