### ISSUE TITLE
Mapbox hangs after it reaches tile count limit after the first time

### ISSUE THREAD

**Issue by ekigamba** [mapbox/mapbox-gl-native#13669]
Mapbox still hangs after tile count limit is exceeded. I had the issue before with mapbox 6.5.0 and now still with 6.7.2 which should have had this issue fixed as per [this issue](https://github.com/mapbox/mapbox-gl-native/issues/12833)

### Steps to reproduce

 1. Compile this https://github.com/onaio/kujaku/ app implementing Mapbox MapView
 2. Checkout to branch `issue/220-update-mapbox-to-6.7.2` which has the mapbox SDK bump to `6.7.2` and run the `sample` module
 2. Open the app and enter a map name in the first field which is named **Offline Map Download** field
 3. Click on **START OFFLINE DOWNLOAD** which will start download a pretty huge offline region with the name you entered. A notification should appear showing the download progress. At around 2.34%, the download stops and a tile count limit exceeded error notification is shown. If you try to open the navigation menu and open an activity that uses the `MapView` such as **Low Level Add Point**, the application hangs and takes too long to open the activity.

I also tried setting the offline region to `OfflineRegion.STATE_INACTIVE` after the tile count limit was exceeded but this produces worse results because the sample application stops responding immediately and even the tile count limit error notification is not displayed.

### Expected behavior
I should be able to navigate to other maps either with the same error but smoothly. This should not make the whole application not respond.

### Configuration

**Android versions:** Android 7.0, 5.1.1
**Device models:** Samsung Galaxy Tab S2(SM-T713), Oppo A37fw
**Mapbox SDK versions:** 6.7.2

**Comment by ekigamba** [comment]
This can also be replicated on the Mapbox Android demo as in this branch https://github.com/onaio/mapbox-android-demo/tree/issue/13669-offline-download-limit-issue

1. If you go to the **Offline** section from the navigation menu
2. Click on the first card labelled ***A simple offline map**
3. The huge map should start downloading and at some point the logs will show the **Mapbox tile count limit exceeded error message**. At this point try and navigate to any other map activity in the sample app, you will notice the app stops responding

**Comment by LukasPaczos** [comment]
Hey @ekigamba, thanks for reporting the issue and providing examples! I was able to reproduce the issue, we'll try to figure out what's going wrong here.

**Comment by ivovandongen** [comment]
@LukasPaczos This is kind of a tricky one.
<img width="1134" alt="deadlock" src="https://user-images.githubusercontent.com/64527/52264627-cf0ba680-293a-11e9-9a5a-0c43f7326952.png">

Don't know if this picture makes it more or less clear. But the problem here is
that we have two locks in play, one in the RunLoop (which is recursive) and one
the JVM. The problem arises when there are at least 2 http threads (A and B)
returning (either success or failure) and the first hits the offline tile count
limit.

Thread A:
- onResponse adds a task to execute it's callback on the DefaultFileSource (DFS) thread
    through the [ASync on HttpRequest](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/src/http_file_source.cpp#L159).
- The callback executing on the DFS thread [locks the Runloop](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/src/run_loop.cpp#L175)
- The callback Triggers a deactivation of the offline download, [clearing the
outstanding requests](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/default/src/mbgl/storage/offline_download.cpp#L361) and destroying all the outstanding requests subsequently.
- The destructor calls back into the JVM to actually cancel the request and
    set the native pointer to 0 to avoid any further callbacks firing. To do so
    it needs to [lock](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/NativeHttpRequest.java#L40).
    This works for the original thread triggering the clean as it already returned
    from Async.send(). But thread B is still waiting, whilst holding the JVM lock (read on).


Thread B (meanwhile):
- Locks the lock on the JVM in [onResponse](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/NativeHttpRequest.java#L47)
- onResponse tries to add a task to execute it's callback on the DefaultFileSource (DFS) thread
    through the [ASync on HttpRequest](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/src/http_file_source.cpp#L159). But is blocked on the lock in [RunLoop::addRunnable()](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/src/run_loop.cpp#L144)


To avoid this situation, there is a couple of things we could do:
- Only lock in cancel if not already locked. Solves this situation, but leaves the chance that
the destructor on the native peer finishes whilst another thread is executing onResponse -> Not sure
what will happen, but accessing memory it shouldn't is quite likely.
- Defer the cleanup until the next runloop iteration. This removes any immediate deadlocks, but leaves the chance it will block on requests yet to come in.
- Re-arrange ownership so that on cleanup the Java peer takes ownership of the c++ peer and the
  destructor on the c++ peer is run only when the Java object is GC'd. This probably needs some
  refactoring on the FileSource interface so we can return shared pointers there.
