### ISSUE TITLE
Add telemetry performance event

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#13789]
This issue tracks integration of https://github.com/mapbox/mapbox-events-android/pull/318 in the maps sdk. @chloekraw @zugaldia, which performance events should we track?

**Comment by zugaldia** [comment]
> which performance events should we track?

I'd like to start with two: tile loading latency and tile downloading failure. However, I'd like to keep the implementation flexible enough to support any performance event we decide to add in the future.

In terms of implementation, we'd like to take advantage of the `MapboxTelemetry.push()` API. To do that we'd need to do the following things:
1. Expose this API in `TelemetryImpl` and `TelemetryDefinition` for events of type `Type.NO_OP` where `event.name` == `performance.trace`.
1. Implement a generic `PerformanceEvent` that extends [`Event`](https://github.com/mapbox/mapbox-events-android/blob/master/libtelemetry/src/main/java/com/mapbox/android/telemetry/Event.java) (note that we do not need to implement the logic for `Parcelable` because that is being deprecated).
1. Test the event data is coming in by collecting both metrics mentioned above in the test app or demo app.

@osana @langsmith Do you have the bandwidth to team up on this one?

cc: @andrlee in case you want to provide any additional guidance.

**Comment by osana** [comment]
Here is a first take on adding generic PerformanceEvent to mapbox-events-android 
https://github.com/mapbox/mapbox-events-android/pull/332

**Comment by langsmith** [comment]
@osana and I chatted this morning about this. As she linked above, creating a `PerformanceEvent` in the telem sdk is the first step. Then we'll tackle the `TelemetryImpl`/ `TelemetryDefinition` implementation and then finish up with testing.

**Comment by langsmith** [comment]
Building gl-native in my Android Studio is an absolute dumpster fire right now, so it's been impossible for me to look through the Maps SDK to work on things myself. Working on fixing things....

**Comment by andrlee** [comment]
folks, it looks like there's a confusion about plans around perf event. we've made changes on our end to enable event creation outside of telem sdk and the guideline going forward would be to keep events outside of sdk. this will drastically accelerate our development cycles. does that make sense? could you please sync with @zugaldia regarding implementation details of the event?

**Comment by langsmith** [comment]
Ok, will do @andrlee

**Comment by tobrun** [comment]
This landed in https://github.com/mapbox/mapbox-gl-native/pull/13795
