### ISSUE TITLE
No support of FeatureCollection/GeometryCollection in Qt platform

### ISSUE THREAD

**Issue by xylosper** [mapbox/mapbox-gl-native#13831]
**Platform: Qt**
**Mapbox SDK version: master**

As far as I can see, other platforms support FeatureCollection/GeometryCollection for data of geojson.
However, in Qt platform, only one QMapbox::Feature can be assigned to data of geojson source.
This makes you add sources/layers as many as features.
Currently, the only way to add multiple features in a source is using JSON string which is much inefficient.
Also, Qt platform lacks GeometryCollection geometry support, although I don't think this is not as critical as FeatureCollection.

**Comment by tmpsantos** [comment]
@xylosper this is intentional. The Qt C++ API is designed with https://doc.qt.io/qt-5/location-plugin-mapboxgl.html in mind. When using QML, it feels very natural to simply set a JSON when you need a data source, and in most of the use cases, the JSON string is small. We might revisit this in the future, but right now we have no plans to add this new API.

Example: https://github.com/tmpsantos/qmapboxglapp/blob/master/qmapboxglapp.qml#L117

**Comment by xylosper** [comment]
Support of FeatureCollection causes API change, so it would be difficult, yes. I agree.

What about just adding support of QList<QMapbox::Feature> / QVector<QMapbox::Feature> for gejson source data?
Since the parameter is given by QVariant anyway, the API won't be changed and it is practically same as supporting FeatureCollection.

**Comment by tmpsantos** [comment]
@xylosper sounds good to me. If you implement it, please add an usage example on the test app.

**Comment by xylosper** [comment]
@tmpsantos Please check to PR #13846
