### ISSUE TITLE
Using AnimatedVectorDrawable for LocationComponentOptions drawables

### ISSUE THREAD

**Issue by ulusoyca** [mapbox/mapbox-gl-native#13855]
I would like to use `AnimatedVectorDrawable` for `LocationComponentOptions#foregroundDrawable()` and animate the drawable in some certain cases. However, API expects Integer Resource id for the drawable and returns the id back when accessed through [LocationComponentOptions](https://docs.mapbox.com/android/api/map-sdk/7.0.0/index.html). 
How can I access the drawable itself to call [start](https://developer.android.com/reference/android/graphics/drawable/AnimatedVectorDrawable.html#start()) in order to start the animation? Is it supported?

**Comment by LukasPaczos** [comment]
Hey @ulusoyca, thanks for reaching out! Unfortunately, the `LocationComponentOptions#foregroundDrawable()` override that takes the resource id as an argument is only a convenience method - every resource is converted to a raw bitmap and passed to the map. And because the map can only digest raw bitmaps, animated drawables are not supported. Closing as answered.
