### ISSUE TITLE
[ios] Scalebar position and size is incorrect

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native#13873]
#13556 introduced new ornament placement, which unfortunately has affected the position and size of the `MGLScaleBar`.

https://github.com/mapbox/mapbox-gl-native/pull/13870 proposes reverting the PR until this can be fixed, but this ticket should be used to document the specific issues.

Zooming in/out changes the position and width of the scale bar, as does rotating the device. 

![scalebar](https://user-images.githubusercontent.com/3765757/52250737-3e47b300-28c7-11e9-8bbe-1cf468ecd9d1.gif)

Looking in the view debugger you can see width and height constraints, but none for the position (it looks like size is handled by the "intrinsic content size" - so perhaps this is changing?). Looking in the debugger where the constraints are installed - you do see them listed in the parent view.

<img width="1183" alt="screen shot 2019-02-04 at 9 54 27 pm" src="https://user-images.githubusercontent.com/3765757/52250804-86ff6c00-28c7-11e9-8b32-a4981c2e68f8.png">

/cc @chloekraw @chriswu42

**Comment by lloydsheng** [comment]
@julianrex Thanks for investigating the issue. I found it was caused by this commit https://github.com/mapbox/mapbox-gl-native/pull/13556/commits/2f2886c5972703b02f9d34bca0d1fdd197afef49#diff-20502b6bc02986a4398d0da84b2d4b94L915 . I removed width and height constraints by mistake. The issue affacts _iOS 11+_ but I just tested _iOS9_.
I'll fix the issue on branch `lloyd-ui-position` and have a full manual test like this https://github.com/mapbox/mapbox-gl-native/pull/13556#issuecomment-449291418 before create a PR.

/cc @fabian-guerra @chriswu42

**Comment by julianrex** [comment]
Thanks for looking at this so quickly @lloydsheng! We'll plan to review and merge so that it hits the next beta!
