### ISSUE TITLE
[ios, macos] remove references to [MGLOfflineStorage sharedOfflineStorage] from internal methods.

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native#13877]
**iOS/macOS versions:** 4.7.0

We should consider removing the explicit dependency on `[MGLOfflineStorage sharedOfflineStorage]` from `MGLOfflinePack`, `MGLMapSnapshotter` and `MGLRendererConfiguration`.

This would pave the way to support multiple offline storage objects which would be especially useful during (parallel) testing.

**Comment by 1ec5** [comment]
These classes refer to the shared object via the class method to avoid maintaining a backreference to the file source. Most of the actual offline pack functionality lives in MGLOfflineStorage rather than MGLOfflinePack. This architecture is somewhat dictated by `mbgl::OfflineManager`, which isn’t quite as object-oriented as what we expose publicly on iOS and macOS. All three classes depend on the file source, which exists in mbgl as a singleton.
