### ISSUE TITLE
port drawing fill-extrusions directly into the main framebuffer

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-native#13984]
Fill-extrusions are currently drawing into a offscreen texture before being copied into the main framebuffer.

In https://github.com/mapbox/mapbox-gl-js/pull/7821 -js switched to drawing fill-extrusions directly into the main framebuffer instead of drawing to an offscreen texture first. This was done for reasons that don’t apply to -native (antialiasing for custom layers) but it also improves performance by avoiding a full screen copy.

**Most of these changes need to be ported to -native.**

For a high level description of the changes see https://github.com/mapbox/mapbox-gl-js/pull/7821

The main changes that need to be ported are:
- drawing buildings directly into the main framebuffer
- drawing semi-transparent buildings with two passes (depth only for the first pass, shading in the second pass)
- only using the opaque pass for fills that are below all buildings
- (maybe) optimizing stencil buffer usage

Let me know when someone picks this up! I can help explain things further

**Comment by kkaefer** [comment]
Porting this blocks GL JS module updates in GL native due to shader changes.

**Comment by tristen** [comment]
Just flagging: I opened a ticket that this issue addresses in  https://github.com/mapbox/mapbox-gl-js/issues/8124. It's fixed in `0.54.0-beta.1` of Mapbox GL JS. On mobile, a `fill-extrusion` layer ignores the ordering of a `fill` layer ordered above it.

<details>
<summary>Preview</summary>

![IMG_1585](https://user-images.githubusercontent.com/61150/55648379-277de980-57ae-11e9-8c7d-623e596a992d.PNG)

</details>

Other geometries (like the white line string) is fine.

**Comment by kkaefer** [comment]
This was merged in #14526
