### ISSUE TITLE
Frequent GeoJSONSource updates force GC every couple seconds

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#14048]
With looking into global reference overflow issue from #14010, I have been profiling different components in the SDK and noticing that using LocationComponent results in gc'ing every couple seconds with the SimpleLocationActivity while not interacting:

![image](https://user-images.githubusercontent.com/2151639/53879386-9da3fa80-400e-11e9-80d6-822e00dbacc8.png)

![image](https://user-images.githubusercontent.com/2151639/53879324-751c0080-400e-11e9-958d-f53478bf37d4.png)

**Comment by tobrun** [comment]
Setting `locationComponent.setRenderMode(RenderMode.NORMAL)` doesn't show the GC'ing:

![image](https://user-images.githubusercontent.com/2151639/53879594-3d618880-400f-11e9-97ec-349f5a160e83.png)

We need to optimize `RenderMode.COMPASS`

**Comment by tobrun** [comment]
`LocationComponentCompassEngine#updateRotation` seems to be source. 
Tracking down which part concretely.

**Comment by tobrun** [comment]
With using:

```
  mapView.setMaximumFps(30);
  locationComponent.setMaxAnimationFps(15);
```

I'm getting better results:

![image](https://user-images.githubusercontent.com/2151639/54355154-a1f89500-4658-11e9-8685-b01ba79b4890.png)

This can be used as intermediate solution until we tackled the root cause of this issue.

**Comment by LukasPaczos** [comment]
I've noticed, that all other objects ignored/commented out, it's the constant detaching and re-attaching of the JVM env to different threads that invokes GC runs. Here's a PR that tries to minimize that for the `GeoJSONSource`'s async features conversion - https://github.com/mapbox/mapbox-gl-native/pull/14375. I can see a great decrease in the GC runs, however, a lot of them are still coming from other places, like the `MapRenderer`.

Because when animating (for example `LocationComponent` or the `AnimatedSymbolLayerActivity`) we are generating new tiles and rendering really quickly, and becuase the `MapRenderer` uses a shared thread pool, the renderer is the main source of the attach/detach calls. Should we make a fixed thread pool of non-rotating threads for the renderer as well?

All above is based on my experimental discovery that attaching and detaching threads is the root cause, I'm not sure if there's anything deeper in our JNI wrapper that might help decrease GC runs instead.

/cc @ivovandongen

**Comment by LukasPaczos** [comment]
Capturing from @ivovandongen in https://github.com/mapbox/mapbox-gl-native/pull/14375:
> Attaching a thread to the JVM indeed forces a sync with the GC (which may or may not require the GC to run).

Following that lead, I noticed that shared thread pool's threads are not manually attached to the JVM (in contrast to the run loop's implementation). This means that they always fall into `JNI_EDETACHED` branch: https://github.com/mapbox/mapbox-gl-native/blob/f3341dd589c6330c0cfd6e8e381398d08493b48a/platform/android/src/attach_env.cpp#L14-L15
while calling `android::AttachEnv()` and are detached as soon as the variable goes out of the scope because of the `true` flag passed to the `JNIEnvDeleter`.

To get rid of the unnecessary GC runs we need to introduce an Android's shared thread pool implementation that manually attaches/detaches the threads to JVM when they are created/destroyed and rely on `android::AttachEnv()` only for getting the `env` reference.
