### ISSUE TITLE
onLocationComponentClick should be consuming

### ISSUE THREAD

**Issue by out-mschlenker** [mapbox/mapbox-gl-native#14046]
### Steps to reproduce

Using the LocationLayer and `onLocationComponentClick`, clicks on the location marker are not consumed and trigger a 'normal' map click - which e.g. triggers the fullscreen.

### Expected behavior

There should be an option within `onLocationComponentClick` e.g. the usual return value : Boolean to specify if the click should be annotated as consumed or not.

### Actual behavior

There is no option to mark the click as consumed. It will be always forwarded to the map itself.

### Configuration

**Android versions:** SDK 28
**Device models:** All
**Mapbox SDK versions:** 7.2.0

**Comment by LukasPaczos** [comment]
Hey @out-mschlenker, thanks fo reaching out! If you look into the code, the `LocationComponent` [is consuming the clicks](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponent.java#L1383). However, in order for those clicks to actually be consumed, you need to add your own map click listener _after_ the component has been activated, because only then the component is registering its internal listener, and [per documentation](https://docs.mapbox.com/android/api/map-sdk/7.2.0/com/mapbox/mapboxsdk/maps/MapboxMap.OnMapClickListener.html#onMapClick-com.mapbox.mapboxsdk.geometry.LatLng-):
> True if this click should be consumed and not passed further to other listeners registered afterwards, false otherwise.

For example, when the location puck is clicked:
```
mapboxMap.addOnMapClickListener(new MapboxMap.OnMapClickListener() {
  @Override
  public boolean onMapClick(@NonNull LatLng point) {
    // This is going to be invoked
    return false;
  }
});

LocationComponent locationComponent = mapboxMap.getLocationComponent();
locationComponent.activateLocationComponent(this, style);

mapboxMap.addOnMapClickListener(new MapboxMap.OnMapClickListener() {
  @Override
  public boolean onMapClick(@NonNull LatLng point) {
    // This is NOT going to be invoked
    return false;
  }
});
```

Closing, as this is working as expected.
