### ISSUE TITLE
[android] Use HTTPS to accept cleartext communication

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-gl-native#14055]
Android API level 28 and higher doesn't accept cleartext communication. This caused issues with with loading info in the Mapbox demo app:

https://github.com/mapbox/mapbox-android-demo/issues/955

In https://github.com/mapbox/mapbox-android-demo/pull/980, I added `android:usesCleartextTraffic="true"` to the app's manifest. 

However, as @lukasz said elsewhere, "we should update the sources to use HTTPS". This will prevent us from having to instruct developers to add `android:usesCleartextTraffic="true"` to their manifest or take other actions.

 
Other links about this:

- https://android-developers.googleblog.com/2016/04/protecting-against-unintentional.html
- https://stackoverflow.com/questions/37866619/cleartext-http-traffic-to-myserver-com-not-permitted-on-android-n-preview
- https://medium.com/@son.rommer/fix-cleartext-traffic-error-in-android-9-pie-2f4e9e2235e6

### Steps to reproduce

 1. Remove `android:usesCleartextTraffic="true"` from the [Mapbox Android demo app](https://github.com/mapbox/mapbox-android-demo)'s manifest.
 2. If you've already got the Mapbox Android demo app installed on your device, uninstall it. Then build and run the demo app on a device that is running Android Pie (API 28).
 3. Try running `StyleCirclesCategoricallyActivity`, `ChoroplethZoomChangeActivity`, or `SpaceStationLocationActivity`

### Expected behavior

Data is successfully loaded into the example. The `StyleCirclesCategoricallyActivity` and `ChoroplethZoomChangeActivity` examples use a `VectorSource`. 

### Actual behavior

The data resources aren't loaded.

### Configuration

**Android versions:** API 28 and above

**Device models:**  

**Mapbox SDK versions:**  7.2.0

**Comment by LukasPaczos** [comment]
This is not an issue with the Maps SDK, but the sources used in the referenced Activities, for example, `StyleCirclesCategoricallyActivity` uses a source (http://api.mapbox.com/v4/examples.8fgz4egr.json?access_token={your_token}), that references underlying data with plain-text:
```
... "tiles":["http://a.tiles.mapbox.com/v4/examples.8fgz4egr/{z}/{x}/{y} ...
```

This should be resolved on the Mapbox Studio level. I'm going to guess, that sources generated right now do use safe connection, but because the referenced source is old, it was not always the case in the past.

Steps to fix the issue in the demo app should be to verify that newly created sources via Mapbox Studio use safe connection and re-generate the source from the example, if that's not, it should be flagged to the Studio team I think.

**Comment by langsmith** [comment]
I'll flag this to the Studio team. Thanks @LukasPaczos
