### ISSUE TITLE
Coverity [64796] Unintended sign extension

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-gl-native#1407]
![screen shot 2015-05-03 at 11 43 23 pm](https://cloud.githubusercontent.com/assets/20300/7449571/3795c326-f1ee-11e4-96ed-8a08af682060.png)

**Comment by kkaefer** [comment]
The issue coverity unearthed is the following:

`count` is unsigned and gets implicitly converted to a signed variable for the `++` operator, which is then shifted. This may cause the most significant bit (=sign) to become 1. `leaf.tile.clip.reference` is of type `std::bitset<>` which only accepts `unsigned long long` values in its constructor. That means [sign extension](http://en.wikipedia.org/wiki/Sign_extension) takes place. When the leftmost bit is `1`, all of the extended bits also become `1`, potentially causing a different value to be assigned than intended.

Practically, this doesn't happen/matter in our case since our bitset is only 8 bits long and will truncate the extended bits anyway.
