### ISSUE TITLE
[Android]Add a hook for automatically mapping Chinese style

### ISSUE THREAD

**Issue by Chaoba** [mapbox/mapbox-gl-native#14153]
In the past, we could mapping styles automatically to China style in China plugin, but since 7.0.0 we have changed the api for style, so it is impossible to do it in China plugin now. Douyin and Moji are using 6.8.1, if they update to 7.x.x in future, they will need to set style by themselves, it will be nice if we could still handle it in China plugin.

My thought is that we add a class `StyleConverter` and api in `Style.Builder` just like `CoordinateShifterManager.coordinateShifter`, so we could intercepter and map styles like this
```
public Builder fromUrl(@NonNull String url) {
      if(styleConverter != null){
          this.styleUrl  = styleConverter.convert(url);
      } else {
         this.styleUrl = url;
     }
      return this;
    }
```

What do you think @tobrun @LukasPaczos @langsmith

**Comment by tobrun** [comment]
@Chaoba what would `styleConverter.convert(url);` alter to the provided url? We already expose a BaseApiUrl to change from a global endpoint to a Chinese one.

**Comment by Chaoba** [comment]
@tobrun Its purpose is convert Styles to China styles, for example
`Style.MAPBOX_STREETS` ->`ChinaStyle.MAPBOX_STREETS_CHINESE`
In China, current we could only use 3 styles, `MAPBOX_STREETS_CHINESE`, `MAPBOX_LIGHT_CHINESE`, `MAPBOX_DARK_CHINESE`.

**Comment by tobrun** [comment]
I don't believe we need a runtime static configuration for this. Would the following be sufficient?

Inside MapboxMap#settStyle():

```java
 if (!TextUtils.isEmpty(builder.getUrl())) {
      String url = builder.getUrl();
      String apiBaseUrl = nativeMapView.getApiBaseUrl();   
      if(apiBaseUrl.equals("china-endpoint")){
        if(url.equals(Style.MAPBOX_STREETS)){
          url = "china-streets";
        }else if(url.equals(Style.LIGHT)){
          url = "china-light"
        }else ....

        }
      }
      nativeMapView.setStyleUrl(url);
}
```

**Comment by LukasPaczos** [comment]
An upside of the runtime static configuration is that in order to change the mapping you only need a China plugin update, whereas keeping the map hardcoded in the `mapbox-gl-native` repo would require a Maps SDK release.

That said, I still feel like this is unnecessary and a little bit confusing. @Chaoba since Chinese users can't utilize any other constant URLs stored in the `Style` class, wouldn't it be better to communicate that only `ChinaStyle` constants can be used with the plugin instead of converting some (`MAPBOX_STREETS`, `LIGHT`, `DARK`) and ignoring the rest? Adding this requirement could be a part of the migration guide instructions for the China plugin.

**Comment by Chaoba** [comment]
@tobrun These Chinese styles are defined and maintained in china plugin, we wouldn't not want to let map sdk has dependency on china plugin, right? So, we'd better just add an api and let china plugin handle these mapping logic.

@LukasPaczos I understand what you mean. But you know in the past we could handle this logic in china plugin, maybe some customers are using this feature and if they update to the latest one suddenly it not works. Since 7.x.x has too much changes, IMHO it would be better if we could let customers do less change during update.

**Comment by LukasPaczos** [comment]
On the other hand, since the style initialization is changed in the `7.x` anyway with the introduction of the `Style.java`, I think now would be the perfect opportunity to introduce the new style constant requirement and document it in the `6.x -> 7.x` migration guide specific to the plugin.

I see what you're trying to say, fewer changes are always better, but in this case, customers will need to modify the discussed codebase regardless and this change could be a part of the package. Unless we have a plan of supporting all core styles by the plugin in the near future.

**Comment by tobrun** [comment]
Thinking about it, we already have a hook for transforming resource urls, see https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/storage/FileSource.java#L42-L59. You need to check for type style https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/storage/Resource.java#L30 and transform that url accordingly. Closing as not actionable for the maps sdk.

**Comment by Chaoba** [comment]
@tobrun Thanks, it could works! 👍
