### ISSUE TITLE
[ios] Exclude CJK resources from offline download by default.

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native#14176]
See https://github.com/mapbox/mapbox-plugins-android/issues/812 for Android equivalent.

Currently, CJK is included in offline regions (by default). See https://github.com/mapbox/mapbox-gl-native/pull/13607/files#diff-867d7f7add578b86f5456961d2bf8381R30

(The sample `iosapp` overrides this default based on the `MGLIdeographicFontFamilyName` value from the application's plist: https://github.com/mapbox/mapbox-gl-native/pull/13607/files#diff-bb284266f7a6a26739305814068fb1bfR107)

/cc @tobrun for coordination.
/cc @tmpsantos 

### Configuration
**Mapbox SDK versions:** 4.10

**Comment by friedbunny** [comment]
Tagging this as a semver-major change — offline packs have always included every glyph, so changing this behavior will break users in outside the western world.

**Comment by tobrun** [comment]
Note that the linked android issue in OP is for the offline plugin so no changes were made to the Android SDK just yet though would like to do the same.

**Comment by zugaldia** [comment]
Capturing chat with the team, because we can make this change without changes to the public API, without breaking the rendering (local glyphs rendering is supported), it brings consistency with the changes already made to Snapshotter https://github.com/mapbox/mapbox-gl-native/pull/13427, and because it reduces the size of the offline download (making the experience better), we're good to move forward with this change and removing the SEMVER major label :+1:.

**Comment by zugaldia** [comment]
Blocked by https://github.com/mapbox/mapbox-gl-native/issues/14271.
