### ISSUE TITLE
Investigate Usage Of iOS Significant Location Change (SLC) API

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#1422]
iOS offers the [Significant Location Change (SLC) API](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/LocationAwarenessPG/CoreLocation/CoreLocation.html#//apple_ref/doc/uid/TP40009497-CH2-SW8) as part of Core Location as a "power-saving alternative to the standard location service."  According to the documentation "The service uses Wi-Fi to determine the user’s location and report changes in that location, allowing the system to manage power usage much more aggressively than it could otherwise."

Investigate further (and implement) as a way to help keep battery usage minimal.

@mapbox/mobile @mapbox/mobiledata

**Comment by incanus** [comment]
https://github.com/mapbox/mapbox-gl-native/issues/1224

**Comment by bleege** [comment]
Ha!  I knew I'd wanted to look at this topic.  :-)

**Comment by boundsj** [comment]
According to the Apple [Energy Efficiency Guide for iOS Apps](https://developer.apple.com/library/ios/documentation/Performance/Conceptual/EnergyGuide-iOS/LocationBestPractices.html#//apple_ref/doc/uid/TP40015243-CH24-SW1):

> Register for Significant-Change Location Updates Only as a Last Resort

> If GPS-level accuracy isn’t critical for your app, you don’t need continuous tracking, and region or visit monitoring isn’t more appropriate for your app, you can use the significant-change location service instead of the standard one.

Given that tidbit and what we've learned from experiments with region monitoring (geofencing) recently, I've decided to close this issue since I don't think that SLC is correct for our case. Of course we can reopen if this turns out to not be true.

fyi @bleege 

cc @1ec5, @friedbunny

**Comment by bleege** [comment]
:+1:
