### ISSUE TITLE
ResourcesCachePathChangeCallback is sporadically not returning

### ISSUE THREAD

**Issue by arnekaiser** [mapbox/mapbox-gl-native#14297]
Sometimes the `ResourcesCachePathChangeCallback` is not returning. After some debugging I found out, that the `FileUtils.OnCheckFileWritePermissionListener` is gone (null) in the `FileUtils.CheckFileWritePermissionTask`. Looks like a strange JNI behavior. 

The problem occurs more often when the resources cache path should be changed directly after the initialization of Mapbox and also on older devices.

### Steps to reproduce

 1. Initialize Mapbox
 2. Set custom resource cache path

### Expected behavior

The cache path should be set every time.

### Actual behavior

Sometimes the cache path isn't set and the callback doesn't return.

### Configuration

**Android versions:** all
**Device models:** all
**Mapbox SDK versions:** 7.3.0

**Comment by tobrun** [comment]
@arnekaiser tracked this down to the callback being GC'ed in some edge cases as it was wrapped internally by a weak reference. Solution for now is to avoid using an anonymous inner class but instead keeping a reference scoped to the outer class instead (this will prevent GC'ing it).

That said, we should revisit how we implement callbacks to avoid behaviors as shown in OP. Some notes on this in https://github.com/mapbox/mapbox-gl-native/pull/14515#issuecomment-487474996.

**Comment by Guardiola31337** [comment]
The problem here is that the GC is non-deterministic and how we're storing `WeakReference`s in `FileUtils` tasks https://github.com/mapbox/mapbox-gl-native/blob/d25ae1c96cc2b4cfeb7906f0857c8e4c451bf69f/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/FileUtils.java#L20 https://github.com/mapbox/mapbox-gl-native/blob/d25ae1c96cc2b4cfeb7906f0857c8e4c451bf69f/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/FileUtils.java#L77 but not retaining them in the public APIs from `OfflineManager` e.g. https://github.com/mapbox/mapbox-gl-native/blob/0fcab654a13bde881ba20ca4cd7ac3a6ae47677c/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java#L226-L254 i.e. there's no way to retain the callback from the client side because callbacks are implemented as inner classes, storing the content and not the reference.

In order to solve this we could:
- Refactor all these callbacks into retained properties (as you mentioned) + add docs so clients are aware of that - forcing the caller to retain callbacks it's not a common practice so IMO this is not ideal
- Remove the `WeakReference`s and reset the callbacks when `onCancelled` and `onPostExecute` so they're properly GC'ed

Both seem that could be implemented without adding any breaking changes and could be included in a patch release.

 👀 https://www.pacoworks.com/2016/07/26/dissecting-callbacks-a-murder-mystery/

**Comment by tobrun** [comment]
your suggestions are valid @Guardiola31337 but they don't take in account that `FileSource#setResourcesCachePath` is static so you don't have a hook into instance properties. Feel free to take it for a spin but haven't found a way to not leak it. We might be able to manage this statically but have been trying to put that off.

**Comment by Guardiola31337** [comment]
We took this for a spin in https://github.com/mapbox/mapbox-gl-native/pull/14589

When you have a chance @tobrun let us know what you think
