### ISSUE TITLE
[core] Format expression parsing error for NSNumber and NSArray attributes.

### ISSUE THREAD

**Issue by fabian-guerra** [mapbox/mapbox-gl-native#14348]
When our iOS SDK is built with a `release configuration` and you set a format expressions that contain an NSArray or NSNumber as parameters to `MGLSymboStyleLayer.text` crashes with error:

`EXC_BAD_ACCESS (code=EXC_I386_GPFLT)`

**Platform:** iOS
**Mapbox SDK version:** release-liquid-beta.1/2

### Steps to trigger behavior

 1. Edit the iosapp schema and set build configuration to Release and turn on Zombie objects in the Diagnostics tab.
 2. Create a format expression with scale and font names.
 3. Set the expression to `MGLSymboStyleLayer.text`
 3. Crash.

The crash happens inside the method: `convert<MBGLValue>` in this line
https://github.com/mapbox/mapbox-gl-native/blob/fab134ba361900b11a7f51adc00621ece912b2df/platform/darwin/src/MGLStyleValue_Private.h#L92

This behavior is only seen when the attributes are either an NSArray or an NSNumber.
e.g.
```
NSArray *jsonExpression = @[ @"format", @"foo", @{ @"text-color": @[@"rgb", @255, @0, @0] } ];
```

But works for NSString.
e.g.
```
NSArray *jsonExpression = @[ @"format", @"foo", @{ @"text-color": @"blue" } ];
```

I made this test pr to reproduce the crash, tap on `Style Symbol Color` example.
https://github.com/mapbox/mapbox-gl-native/pull/14347

cc @alexshalamov @tmpsantos  @chloekraw @julianrex

**Comment by julianrex** [comment]
[A-ha moment below](#aha), the following is left for archeology:

---- 
Admittedly getting a bit lost in the C++ code, but I'm thinking this is due to:

https://github.com/mapbox/mapbox-gl-native/blob/1a5b933983d5b30b7a2947bbdf152122c38e11c1/include/mbgl/style/conversion_impl.hpp#L100-L104

in conjunction with 

https://github.com/mapbox/mapbox-gl-native/blob/1a5b933983d5b30b7a2947bbdf152122c38e11c1/platform/darwin/src/MGLConversion.h#L10-L14

causing `value`'s `release` to be called twice, whereas `retain` is just called the once (during the creation of the temporary.

I tested this by changing `Holder::Holder(...)` to 

```
    Holder(const id v) : value(v)
    {
        CFBridgingRetain(v);
    }
```

i.e. over-retaining the object, to compensate for the over-release. 

----

<a id="aha"/>💡 A-ha!

I think this is due to the compiler's autogenerated copy constructor, and when it gets called from 

https://github.com/mapbox/mapbox-gl-native/blob/1a5b933983d5b30b7a2947bbdf152122c38e11c1/include/mbgl/style/conversion_impl.hpp#L237-L241

If you add a manually created copy-constructor, it seems to be ok, and we have paired `retain`s and `release`s. Running through the Zombies tool in Instruments showed no zombies.

@fabian-guerra can you test adding:

```
Holder(const Holder& other) : value(other.value) {}
```

**Comment by alexshalamov** [comment]
@fabian-guerra @julianrex I cannot reproduce the issue with this fix https://github.com/mapbox/mapbox-gl-native/pull/14352, could you double check that it works for you? Thanks.
