### ISSUE TITLE
symbol-placement=line-center disappears when zooming out

### ISSUE THREAD

**Issue by JRWilding** [mapbox/mapbox-gl-native#14341]
### Steps to reproduce

 1. Configure GeoJsonSource with a Feature with a short LineString as geometry
 2. Configure a SymbolLayer to display an icon for the source with `symbol-placement=line-center`
 3. Zoom the camera out

### Expected behavior
The icon remains visible

### Actual behavior
The icon disappears, presumably at the point where the line's geometry is optimised away.

### Configuration

**Android versions:** 
Android 8
**Device models:** 
Pixel XL
**Mapbox SDK versions:** 
7.3.0

**Comment by tobrun** [comment]
@JRWilding thank you for reaching out and reporting your issue. I believe this is expected behavior. This feature, afaik, is something that is used for street names and once the geometry isn't part of the shown tile, it's shouldn't be visible anymore. You can workaround this by adding point geojson that won't get optimized away.

![ezgif com-video-to-gif (55)](https://user-images.githubusercontent.com/2151639/55627784-4f218180-57af-11e9-9d5d-9b947e0b660a.gif)

Feel free to follow up but closing this for now as works as designed.

**Comment by HansBrende** [comment]
@tobrun the same thing is happening to me for the symbol text (no icon, just text), but the text disappears much earlier, while the line string is still visible. This seems like a bug... I need the label to stay visible even if the line segment is slightly shorter than the text.
