### ISSUE TITLE
[ios] Cleaning a target in Xcode deletes the mbgl.xcodeproj project file & config.xcconfig file

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native#14374]
Moved from closed PR https://github.com/mapbox/mapbox-gl-native/pull/13718 for tracking purposes since this is still valid:

Cleaning a target in Xcode deletes the `mbgl.xcodeproj` project file and `config.xcconfig` file, meaning that the developer needs to `make iproj` before being able to build.

I believe this is because `SYMROOT` is set to `build/ios` (along with build locations set via the user's `WorkspaceSettings.xcsettings`).

Following on from [this comment](https://github.com/mapbox/mapbox-gl-native/pull/13718#issuecomment-453522193), the solution may be to set
`PROJECT_TEMP_DIR` and `CONFIGURATION_BUILD_DIR` to a subdirectory using `xcconfig` files (some targets don't use them currently). We may also be able to remove the [hack of copying the workspace settings file](https://github.com/mapbox/mapbox-gl-native/issues/4738#issuecomment-211516320) - which would be nice, though I suspect this needs to stay.

**Comment by 1ec5** [comment]
> Cleaning a target in Xcode deletes the mbgl.xcodeproj project file and config.xcconfig file, meaning that the developer needs to make iproj before being able to build.

This is happening as of Xcode 10.0, which changed the behavior of the clean action to delete the build products directory instead of individually deleting each of the build products.

At a glance, I’m not sure it’ll be as simple as updating a couple build settings. The CMake-generated mbgl.xcodeproj sits in a gray area between build product and source. Natively, Xcode does have a concept of intermediate build products, but it’s a bit awkward to make an entire Xcode project into one.
