### ISSUE TITLE
(MapBox Android) Settings for mapbox camera gestures

### ISSUE THREAD

**Issue by Mordag** [mapbox/mapbox-gl-native#14436]
I have noticed that the rotation gesture is often accidentally triggered while zooming. Is it possible to access certain gesture settings to reduce their sensitivity? I found no options in the mapbox uiSettings class.

### Configuration
**Mapbox SDK versions:** 7.3.0

**Comment by gaby830** [comment]
Help how does this work

**Comment by pengdev** [comment]
#15136

**Comment by LukasPaczos** [comment]
Good call @pengdev!

@Mordag We've reworked gestures thresholds in `v8.3.0` (#15136). Especially impacting this issue is:
> Disables the rotation gesture detector if a scale gesture has been recognized first to prevent unwanted rotation. This behavior is adjustable through the UiSettings.

Would you be able to give it a shot and see if all the options are available to achieve the UX you're looking for?

I'm going to close the issue for now, but please let us know if we should reopen.
