### ISSUE TITLE
CJK local glyph generation overrides custom text-font

### ISSUE THREAD

**Issue by honjo2** [mapbox/mapbox-gl-native#14470]
Updated to mapbox-ios-sdk-4.10.0.
Then text-font has been disabled.
```json
"text-font": [
  "my-japanese-fontstack"
],
```
In this way PingFang is applied.

https://github.com/mapbox/mapbox-gl-native/pull/13988

**Comment by fabian-guerra** [comment]
Hi, @honjo2. Thank you for using Mapbox. I am sorry to hear you are having some issues. Could you please provide us with a code snippet or test app we could use to track down the issue?

Also, starting `4.10.0` we introduced [`MGLAttributedExpression`](https://docs.mapbox.com/ios/api/maps/4.10.0/Classes/MGLAttributedExpression.html) that let's you set the text, font and scale size to `MGLSymbolStyleLayer.text` could you please try to set the font array using"

```
MGLSymbolStyleLayer.text = [NSExpression mgl_expressionForAttributedExpressions:@[[NSExpression expressionForConstantValue:attributedExpression]]];
```

**Comment by honjo2** [comment]
### My web site using Mapbox GL JS
https://mapion.github.io/mapion-vector/#15/35.62277/139.75021

### Style URL
https://vt01.mapion.co.jp/gl-server/style/lab.json?access_token=mt-pk.eyJ1IjoibWFwaW9uIiwiYSI6InJ5ZXFiOWJyZ3J2MjV3ZDcyNXY3Z3dmYzYifQ.XoOA7fe-5nUi8ALSyCl277

### Using mapbox-ios-sdk-4.9.0 (no problem)
![mapbox-ios-sdk-4 9 0](https://user-images.githubusercontent.com/437640/56537881-96c04f80-659c-11e9-96d3-34728c0d4488.png)

### Using mapbox-ios-sdk-4.10.0 (There is a problem)
![mapbox-ios-sdk-4 10 0](https://user-images.githubusercontent.com/437640/56537922-adff3d00-659c-11e9-9351-3c0fb33a6ea3.png)

### Problem
Why, only KANJI will be PingFang.
Japanese HIRAGANA and KATAKANA is OK.
Alphabet and Number too.

**Comment by fabian-guerra** [comment]
Hi, @honjo2. Thank you for your reply.

In my previous message asked you to try a workaround using `MGLAttributedExpression` object, do you think you could give it a try?

Is it possible you could share the style url and the account name  where is uploaded? If you are not comfortable sharing the info here, you can send an email to customer support here https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231 and reference this ticket.

**Comment by honjo2** [comment]
```
MGLSymbolStyleLayer.text = [NSExpression mgl_expressionForAttributedExpressions:@[[NSExpression expressionForConstantValue:attributedExpression]]];
```

in Swift, please

**Comment by fabian-guerra** [comment]
Hi, @honjo2. This link has an example on how to create an attributed expression in Swift: https://docs.mapbox.com/ios/api/maps/4.10.0/Classes/MGLAttributedExpression.html

If you meant how to use it with the text then:
After retrieving your symbol style layer from your style:
```
symbolStyleLayer.text = NSExpression.init(forAttributedExpressions: [NSExpression(forConstantValue: attributedExpression)])
```

Could you please share with Mapbox support your account name, and style url so we can track down the issue:
https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231

In the ticket please reference this link.

**Comment by 1ec5** [comment]
#13988 switched to local font rendering for all Han codepoints, including hanji in Japanese, and defaulted to a Simplified Chinese font. When local font rendering is enabled, the `textFontNames` property is ignored, because that property is only compatible with server-side fonts uploaded to Mapbox Studio.

Previously, local font rendering would only be enabled when the `MGLIdeographicFontFamilyName` property was set in Info.plist. You can avoid local font rendering by specifying the name of a Japanese font you expect to be installed on the system. Unfortunately, there isn’t a way to turn off ideographic font rendering on iOS anymore. We should special-case a value like `-` or null to turn off local font rendering.

#7862 tracks using local font rendering for all codepoints in all languages. mapbox/mapbox-gl-js#3999 and mapbox/mapbox-gl-js#6197 discuss the need to account for language, not just script, in text processing.

**Comment by friedbunny** [comment]
Thanks, @1ec5. @fabian-guerra and I also did some testing:

- Reverting https://github.com/mapbox/mapbox-gl-native/pull/13988 “fixes” the issue.
- Specifying a default CJK font will override the font for _any_ Chinese characters.
  - This was also true before https://github.com/mapbox/mapbox-gl-native/pull/13988 — if you set the `MGLIdeographicFontFamilyName` plist key, it would then always use that font for any Chinese characters.
  - We couldn’t find a workaround — setting `MGLIdeographicFontFamilyName` to an empty string didn’t work, for example.
- [`PingFang TC`](https://github.com/mapbox/mapbox-gl-native/blob/bc7ae969c40ea0d7de39ccf0451da94f61534d55/platform/ios/app/Info.plist#L27-L28) is not a valid font family name on iOS — it should be `PingFang` or, better, `Helvetica`.

A few points:
- I think our local glyph generation being limited to “ideographic” characters is a mistake and leads to a poor experience for Japanese and Korean (the `JK` in `CJK`). We need to better support our non-Chinese customers/users.
- Local glyph generation happening when a style specifies a custom font is incorrect behavior.
- If we’re going to enable local glyph generation by default for CJK, it should be the default for all character sets — https://github.com/mapbox/mapbox-gl-native/issues/7862.

**Comment by 1ec5** [comment]
> I think our local glyph generation being limited to “ideographic” characters is a mistake and leads to a poor experience for Japanese and Korean (the JK in CJK). We need to better support our non-Chinese customers/users and they should not be required to flip a setting to get proper text rendering.

Font substitution of Han characters causes more than aesthetic issues: due to [Han unification](https://en.wikipedia.org/wiki/Han_unification), a number of characters have distinct glyph forms depending on the language (and to a lesser extent the region):

> For native speakers, variants can be unintelligible or be unacceptable in educated contexts. English speakers may understand a handwritten note saying "4P5 kg" as "495 kg", but writing the nine backwards (so it looks like a "P") can be jarring and would be considered incorrect in any school. Likewise, to users of one CJK language reading a document with "foreign" glyphs: variants of 骨 can appear as mirror images, 者 can be missing a stroke/have an extraneous stroke, and 令 may be unreadable or be confused with 今 depending on which variant of 令 (e.g. 令) is used.

For the purposes of modern map display, hard-coding a Chinese font like PingFang primarily affects Japanese. (Han characters no longer appear in modern place names in Korean or Vietnamese.) There may also be a handful of edge cases in Chinese where a national variant of a character isn’t used where it should be.

There are two ways to disambiguate the characters, and both of them would require significant effort on the server side:

* The most common way is to use the right language-specific font for a given language and country. Unfortunately, Mapbox Streets source tiles contain no explicit language information for the `name` field, and there’s no machine-readable way for GL to know that the `name_ja` and `name_zh` fields contain Japanese and Chinese text, respectively (ref mapbox/tilejson-spec#14).
* [Ideographic variation sequences](https://en.wikipedia.org/wiki/Variant_form_%28Unicode%29) could be inserted into the text in the vector tiles to force one variation or another. Unfortunately, both the fontstack API and GL currently assume a one-to-one relationship between characters and codepoints and between codepoints and glyphs. One of the approaches to #7862 would involve converting system-rendered glyphs into SDFs, in which case this one-to-one relationship would still be a problem. But if we rely on the system for text layout as well as text rendering, then these ideographic variations sequences could be the solution. Note that, depending on the system locale, operating systems often default to Simplified Chinese fonts in the absence of any language data.

**Comment by m-stephen** [comment]
From my understanding, our first step is to set a default font for all character sets. It will fix these issues at least:
1. All characters are rendered by same font.
2. Still enable local glyph generation by default for CJK.

And next step, as @1ec5 mentioned above, might be let sever join this game to improve this.

**Comment by friedbunny** [comment]
- From `ios-v5.2.0-alpha.3` onward, specifying `MGLIdeographicFontFamilyName = NO` in your plist will allow the use of remote fonts for CJK glyphs.
- Hiragana and katakana are also now locally generated by default, since https://github.com/mapbox/mapbox-gl-native/pull/15009.
