### ISSUE TITLE
Memory leak in Android SDK

### ISSUE THREAD

**Issue by philemonmerlet** [mapbox/mapbox-gl-native#14522]
We are experiencing memory leak on the Mapbox SDK (we are using version 7.2). The leak is visible in the Mapbox demo app.

### Steps to reproduce
- Launch the Mapbox Demo app available on Play Store (tested on the 7.3.2 release demo)
- Open the first sample "A simple map view"
- Press back and reopen as many times as needed

### Expected behavior
Memory consumption remains stable or increase a little between two sample launches 

### Actual behavior
Memory consumption increases a lot (we stopped at 200mb of native memory consumption)

<img width="1768" alt="Capture d’écran 2019-04-26 à 15 22 15" src="https://user-images.githubusercontent.com/16834537/56811044-1e75ba80-6838-11e9-9b97-12e5effd40b5.png">

**Mapbox SDK versions:** 
7.3.2

**Comment by tobrun** [comment]
Thank you for the report @philemonmerlet, will have to do some more testing with a release binary but I'm seeing a slightly different result with building the test app locally in debug.

Run 1
![image](https://user-images.githubusercontent.com/2151639/56814000-76afbb00-683e-11e9-9e14-28eef1741ee3.png)

Run 2
![image](https://user-images.githubusercontent.com/2151639/56814543-b62ad700-683f-11e9-85ac-c570a48ef0e3.png)

Before running a map native memory was 25mb and after open/close SimpleMapActivity, it eventually settled back down to 27.2mb

**Comment by WilliamMouline** [comment]
I am experiencing the exact same issue. I have created a very basic sample project where I only added mapbox sdk as dependency. I just followed the tutorial : [https://docs.mapbox.com/help/tutorials/first-steps-android-sdk/](url).

First I added a custom style using one of my mapbox url (containing extrusions for a 3D Building) and every time my activity is paused and resumed, my memory increases drastically : 
![Capture d’écran 2019-04-29 à 11 11 32](https://user-images.githubusercontent.com/7459545/56887056-c4ac0500-6a70-11e9-91d0-734da9379ba7.png)

I also tried using the MAPBOX_STREETS style and the issue is still present even if it's more subtle:
![Capture d’écran 2019-04-29 à 11 47 37](https://user-images.githubusercontent.com/7459545/56888651-c677c780-6a74-11e9-91f0-9cd22cf4dae4.png)

Those examples come from a Pixel XL but I have the same results on different phones (Samsung S7, S9, LG G4..)

**Comment by tobrun** [comment]
Looked more into this in context of https://github.com/mapbox/mapbox-gl-native/issues/14564 and this was specific bug with 7.2.0. Latest on master is cleaning up nicely:

![Screenshot from 2019-05-09 13-36-36](https://user-images.githubusercontent.com/2151639/57451056-6c3ee980-7260-11e9-8ce3-4cfd4eb40cb4.png)
![Screenshot from 2019-05-09 13-36-49](https://user-images.githubusercontent.com/2151639/57451060-6f39da00-7260-11e9-83b3-5a02bdf691ed.png)
