### ISSUE TITLE
 Error: 404 Not Found: @mapbox/cmake-node-module@^1.2.0

### ISSUE THREAD

**Issue by StefanoBiasu** [mapbox/mapbox-gl-native#14533]
I can't get through the compilation on local machine of the mapbox-gl-native.

I just downloaded theproject, installed all the required tools, and run:

`make iframework BUILDTYPE=Release`

### Steps to reproduce

 1. downloaded the project
 2. installed all required tools/frameworks ( brew install node cmake ccache, jazzy and xcpretty)
 3. run: `make iframework BUILDTYPE=Release`

### Expected behavior

 produces a library

### Actual behavior

>   npm ERR! 404 Not Found: @mapbox/cmake-node-module@^1.2.0

### Configuration

**Mapbox SDK versions:** latest source available (last release  ios-v4.11.0-beta.1)
**iOS/macOS versions:** ios-v4.11.0-beta.1
**Device/simulator models:** 
**Xcode version:** 10.1

**Comment by friedbunny** [comment]
Given that the `@mapbox/cmake-node-module` package is publicly available [on npm](https://www.npmjs.com/package/@mapbox/cmake-node-module) and in [this repo](https://github.com/mapbox/cmake-node-module), and neither appear to have any recently changes or releases, I’d suspect this 404 is due to temporary network conditions. Would you mind trying again, @StefanoBiasu?

**Comment by StefanoBiasu** [comment]
First of all, thanks for answering @friedbunny .
I tried many times, nothing changed. Actually the problem was the configuration of npm inside .npmrc configuration file. I simply renamed it temporarily and tried to install cmake-node-module, and it worked. 
Now 
`make iframework BUILDTYPE=Release`
command seems to compile. 
In any case, the bug can be considered closed/rejected.
