### ISSUE TITLE
Rename map identifiers to tileset identifiers

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#14551]
Map IDs are being renamed to tileset IDs across the board. We refer to map IDs in a couple places in the iOS/macOS map SDK’s header documentation:

https://github.com/mapbox/mapbox-gl-native/blob/9bd59bf041b0d0ca400f586fdbfed53d06258613/platform/darwin/src/MGLRasterTileSource.h#L74 https://github.com/mapbox/mapbox-gl-native/blob/9bd59bf041b0d0ca400f586fdbfed53d06258613/platform/darwin/src/MGLRasterTileSource.h#L100

There are also several occurrences of “a Mapbox URL indicating the style’s map ID”, which is inaccurate following #1561. These occurrences should be replaced by “a Mapbox URL identifying the style”:

https://github.com/mapbox/mapbox-gl-native/blob/d3bb518976a8d99c36c627e5be907065497dfa58/platform/darwin/src/MGLOfflineRegion.h#L18 https://github.com/mapbox/mapbox-gl-native/blob/f3341dd589c6330c0cfd6e8e381398d08493b48a/platform/macos/src/MGLMapView%2BIBAdditions.h#L25 https://github.com/mapbox/mapbox-gl-native/blob/5d891b4b2a7ce4f71bfb5b31a08aafa64db0a003/platform/darwin/src/MGLShapeOfflineRegion.h#L62-L63 https://github.com/mapbox/mapbox-gl-native/blob/5d891b4b2a7ce4f71bfb5b31a08aafa64db0a003/platform/darwin/src/MGLTilePyramidOfflineRegion.h#L64-L65 https://github.com/mapbox/mapbox-gl-native/blob/67e5761e722318e96b86e4615fdd071c1805bae8/platform/darwin/src/MGLMapSnapshotter.h#L18 https://github.com/mapbox/mapbox-gl-native/blob/7017ac512e96415d6a6c18512e320197a10ca83f/platform/macos/src/MGLMapView.h#L87 https://github.com/mapbox/mapbox-gl-native/blob/7017ac512e96415d6a6c18512e320197a10ca83f/platform/macos/src/MGLMapView.h#L134 https://github.com/mapbox/mapbox-gl-native/blob/9bd59bf041b0d0ca400f586fdbfed53d06258613/platform/ios/src/MGLMapView.h#L202 https://github.com/mapbox/mapbox-gl-native/blob/9bd59bf041b0d0ca400f586fdbfed53d06258613/platform/ios/src/MGLMapView.h#L262

/cc @mapbox/maps-ios @brsbl

**Comment by tobrun** [comment]
> /cc: @tobrun for Android.

I believe nothing needs to be picked up from Android as we don't use the terms `map ID`

**Comment by HeyStenson** [comment]
@1ec5 In looking at this, it seems that in several cases we're using the term `style's map ID` to refer to a [style ID](https://docs.mapbox.com/help/glossary/style-id/) (rather than a map ID/tileset ID). 

I believe that in your [OP](https://github.com/mapbox/mapbox-gl-native/issues/14551#issue-438990511), that's the case in the following files:
- mapbox-gl-native/platform/darwin/src/MGLOfflineRegion.h
- mapbox-gl-native/platform/macos/src/MGLMapView+IBAdditions.h
- mapbox-gl-native/platform/darwin/src/MGLShapeOfflineRegion.h
- mapbox-gl-native/platform/darwin/src/MGLTilePyramidOfflineRegion.h
- mapbox-gl-native/platform/darwin/src/MGLMapSnapshotter.h
- mapbox-gl-native/platform/macos/src/MGLMapView.h
- mapbox-gl-native/platform/macos/src/MGLMapView.h
- mapbox-gl-native/platform/ios/src/MGLMapView.h
- mapbox-gl-native/platform/ios/src/MGLMapView.h

If that's correct, only the following need to have language changed from `map ID` to `tileset ID`:
- mapbox-gl-native/platform/darwin/src/MGLRasterTileSource.h
- mapbox-gl-native/platform/darwin/src/MGLRasterTileSource.h

and we should consider changing the rest of the instances you found to `style ID` instead. Does that sound right to you?

**Comment by julianrex** [comment]
Sounds good to me.

**Comment by julianrex** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/15116
