### ISSUE TITLE
Symbols not being rendered in empty style

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#14751]
#### release-java

![image](https://user-images.githubusercontent.com/2151639/58271130-9bd71100-7d8b-11e9-8928-75c0ad3333d8.png)

#### master

![image](https://user-images.githubusercontent.com/2151639/58271447-58c96d80-7d8c-11e9-8e16-77e3ce6473ef.png)

Issue can be reproduced with the Simple Map Activity using the following commit: https://github.com/mapbox/mapbox-gl-native/commit/48abc962476d648641c5daedeeaa399070649977

cc @tmpsantos @pozdnyakov @alexshalamov

**Comment by pozdnyakov** [comment]
The issue was introduced with https://github.com/mapbox/mapbox-gl-native/commit/103f86c4bca08c34c592edd481f078b7bf77cb3f
 cc @LukasPaczos

**Comment by LukasPaczos** [comment]
I took this for a spin:
- calling `Style::Impl::loadJSON` with an empty style fails
- calling `Style::Impl::loadURL` with an empty style asset works

Both methods deliver an identical string to `Style::Impl::parse`. This can be reproduced by commenting/uncommenting [this line](https://github.com/mapbox/mapbox-gl-native/commit/db3b98028ace8efa9eb23c5582eb5a26ee68a9d9#diff-0fe12110cfb64442ea5da61bf8316fc0R48) in https://github.com/mapbox/mapbox-gl-native/commit/db3b98028ace8efa9eb23c5582eb5a26ee68a9d9.

Is this an underlying core issue, or is there a reason for this behavior @pozdnyakov? We can change the implementation to use the asset (and the file source request) instead of parsing the style right away, but I'd like to understand why.

**Comment by tmpsantos** [comment]
Accordingly to the style spec, this is the minimum valid style:

```
{
  "version": 8,
  "sources": {}, 
  "layers": []
}
```

**Comment by LukasPaczos** [comment]
This is what an example from https://github.com/mapbox/mapbox-gl-native/issues/14751#issuecomment-497764127 uses, which leads me to believe that `Style::Impl::loadJSON` is not kicking off the right gears internally.
