### ISSUE TITLE
[android]Location transition is not smooth in TRACKING mode.

### ISSUE THREAD

**Issue by mdakram** [mapbox/mapbox-gl-native#14781]
Trying demo application for location component, In TRACKING mode location marker transition is not smooth.

I made some changes in demo app, set initial zoom to 18

### Steps to reproduce

 1.Open demo application, open show a user's location.
 2.Simulate location using lockito
3. location marker transition is not smooth

### Expected behavior
Location marker should move smoothly 

### Actual behavior

Location marker transition is jerky.
[Video](https://www.dropbox.com/s/tmgx3wjuw0vskad/device-2019-05-28-140406.mp4?dl=0)

![mapbox](https://user-images.githubusercontent.com/1751271/58464246-fdfc9100-8152-11e9-827b-5c9b12b4e48b.gif)

### Configuration

**Android versions:** Android 9(Pie)
**Device models:** MI A2
**Mapbox SDK versions:** 8.0.0

**Comment by LukasPaczos** [comment]
Hey @mdakram, thanks for reaching out. What you're seeing is expected behavior - on low zoom levels and significant location changes, the animation is not going to be perfectly smooth because it's based on the Android Animators output and we cannot make the updates any more frequent. Either way, making them more frequent with a different mechanism would significantly impact battery life.

As mentioned in the `LocationComponent`'s javadoc:
> For location puck animation purposes, like navigation, we recommend limiting the maximum zoom level of the map for the best user experience.

I'd recommend decreasing the maximum zoom level if you're expecting users to be extremely zoomed in during a fast-paced movement.

**Comment by mdakram** [comment]
Hi @LukasPaczos Thank you for clarify, i was using earlier version i.e. 6.7.0, it was very smooth.

**Comment by LukasPaczos** [comment]
We've since switched from the `View` based puck to a GL rendered one. That's the sources of differences.

**Comment by mdakram** [comment]
Hi @LukasPaczos can't we have it as configuration/settings, like we have for Surface/texture view. Developer can select View based or GL rendered one?

**Comment by LukasPaczos** [comment]
Unfortunately not @mdakram. The view-based code has been outdated and the synchronization between the GL rendered map and a platform view is not possible for us to support.
