### ISSUE TITLE
Rotation flick animation / drift rotation is too difficult to trigger

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#1487]
Its very difficult to trigger rotation drift animation in the current implementation. Its almost always detected as zoom. There is some discussion on this in https://github.com/mapbox/mapbox-gl-native/issues/1338 as well.

**Comment by 1ec5** [comment]
The rotation and pinch gesture recognizers are firing simultaneously, but drift rotation only kicks in if the rotation velocity is [above 3 rad/s in either direction](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/MGLMapView.mm#L939). This check is necessary to prevent non-flick rotation from causing drift, but we should try decreasing the constant a bit.

**Comment by 1ec5** [comment]
The other thing to consider is that it’s very rare for an iPhone user to perform a perfectly circular rotation gesture. Even when you intend to just rotate with your fingers, they almost always form an ellipse, which triggers the pinch gesture recognizer, because your hand is off to one side of the device.

**Comment by mb12** [comment]
Thanks for the code pointers. 3 rad/sec  is almost half a turn (172 degrees per sec).
I changed it to 0.78 (45 deg per sec) in my repo and rotation drift looks much better.

**Comment by mb12** [comment]
Some other changes may also be needed for this. At times the map drifts in the direction opposite to what one would expect it to.
- Do a clockwise rotation flick.
- Before the first flick finishes, do another clockwise rotation flick.  ==> At this point the drift direction suddenly changes.

**Comment by 1ec5** [comment]
Note that even though 3 rad/sec may sound quite high, a flick only lasts for a small fraction of a second.

**Comment by mb12** [comment]
For a rotation with 3 cm radius,  3 rads/sec translates to finger speed of 0.324 kph (0.2 mph).

**Comment by 1ec5** [comment]
> At this point the drift direction suddenly changes.

That sounds a lot like a lingering angle normalization bug that would be fixed by #1453. 0.78 seems to exacerbate the issue where a rotation is interpreted as an inward pinch – or maybe two-finger tap?

> 0.324 kph (0.2 mph)

Or 541.2 furlongs per fortnight. :wink: Actually, I just did some logging and found it quite easy to flick-rotate at ±4–5 rad/s without trying that hard, so maybe this constant isn’t the problem after all.

**Comment by friedbunny** [comment]
Stale.
