### ISSUE TITLE
Rectangular park draws to the south of any annotation on Emerald

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1489]
In Emerald, every annotation has a rectangular park just to the south that does not go away after panning or even changing to a different style.

![pinpark](https://cloud.githubusercontent.com/assets/1231218/7552221/86d07490-f65d-11e4-867c-5f6a0df2dc80.PNG)

/cc @tatsvc

**Comment by incanus** [comment]
The sprite sizing is wrong: 

![](https://raw.githubusercontent.com/mapbox/mapbox-gl-styles/mb-pages/sprites/emerald%402x.png)

The pin icons should have double-space below them because of how the image center is placed at the point. 

Note the empty space below the pins in Streets: 

![](https://raw.githubusercontent.com/mapbox/mapbox-gl-styles/mb-pages/sprites/mapbox-streets%402x.png)

/cc @peterqliu

**Comment by tatsvc** [comment]
extra context:

![image](https://cloud.githubusercontent.com/assets/2894119/7548001/6599ffbc-f5c7-11e4-88f0-b63ddfe6f29b.png)

**Comment by 1ec5** [comment]
@peterqliu fixed this issue upstream in a3a36603d67109cc7494af4601f8cd2fe3825891, but the submodule will need to be updated for that change to take effect.

**Comment by 1ec5** [comment]
The saga continues in #1492.
