### ISSUE TITLE
Add multiple SymbolManagers not possible

### ISSUE THREAD

**Issue by nijs9** [mapbox/mapbox-gl-native#15015]
### Steps to reproduce

 1. Add a SymbolManager
 2. Configure setIconRotationAlignment(Property.ICON_ROTATION_ALIGNMENT_MAP)
3. Add different symbols to SymbolManager

This works fine, but I want one specific symbol to not align to map when rotating. I should add a second SymbolManager to put in this symbol, and not setting ICON_ROTATION_ALIGNMENT_MAP. Adding a second SymbolManager generates an exception.

### Configuration

**Android versions:*8,9* 
**Device models:*Galaxy S8* 
**Mapbox SDK versions:*7.1.1*

**Comment by tobrun** [comment]
The [icon rotation alignment property](https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-icon-rotation-alignment) doesn't have Date Driven Styling support (yet). This is the feature that would allow us to define this property on the Symbol instead of the SymbolManager. 

>  I should add a second SymbolManager to put in this symbol, and not setting ICON_ROTATION_ALIGNMENT_MAP. Adding a second SymbolManager generates an exception.

Which exception are you hitting? Which version of the annotation plugin are you using? We enabled having multiple managers with https://github.com/mapbox/mapbox-plugins-android/pull/941.

**Comment by nijs9** [comment]
I saw that, but in the latest version of the annotation plugin, you can't set a z-index anymore...

**Comment by tobrun** [comment]
z-index was a hacky way to workaround not being able to handle z-index through style-spec. Now with [symbol-z-order](https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-symbol-z-order) we have proper support. 

You can use [this](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-annotation/src/main/java/com/mapbox/mapboxsdk/plugins/annotation/Symbol.java#L176) method instead.

**Comment by tobrun** [comment]
going to close this as you should be unblocked with above

**Comment by nijs9** [comment]
Thanks!
