### ISSUE TITLE
Add support for NSError and NSException reporting

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native#15011]
Add support for reporting internal `NSError`s and `NSException`s generated by the iOS SDK. 

This is now possible since `-[MMEEventsManager reportError:]` and `-[MMEEventsManager reportException:]` were added in https://github.com/mapbox/mapbox-gl-native/pull/14868 by @alfwatt.

For example, this will allow us to report if https://github.com/mapbox/mapbox-gl-native/issues/14232 (the iOS 12.2 hang) occurs in iOS 13+.

**Comment by m-stephen** [comment]
Sorry for updating this ticket late.
I'm trying to make a function like this for instead of using `[NSException raise: format:]` directly in our SDK:
```
void MGLRaiseException(NSString *name, NSString *reason, NSDictionary *userInfo) {
    NSException *exception = [NSException exceptionWithName:name reason:reason userInfo:userInfo];
    [[MMEEventsManager sharedManager] reportException:exception];
    [exception raise];
}
```

However, after I re-check the `-[MMEEventsManager reportException:]`, this function is not 
 a realtime reporting(they are pushed into an event queue and some triggers can flush to server) but most of exception in our SDK in realtime raised. 
So there is a problem that, if we use this function to report these events, the exception should not be raised, otherwise we may lost most of events since these events are not wrote in disk. But I think it's necessary to throw exception let developers know what&where the bug is. 

So shall we make a real-time reporting or write these event into disk? @alfwatt @julianrex

**Comment by alfwatt** [comment]
@m-stephen we don't have a way to flag an event as 'real time' or 'send immediately' right no, and I don't think we should start throwing exceptions unless there's a real programmer error. Better to use `NSError` objects and `reportError:`

**Comment by julianrex** [comment]
@alfwatt will this be solved when we have deferred telemetry? It sounds like, even if we do, we'll need a way to flush the in-memory events to disk, before raising the exception.
