### ISSUE TITLE
How to profile tiles rendering

### ISSUE THREAD

**Issue by maxtracking** [mapbox/mapbox-gl-native#15035]
### Steps to reproduce
This is not an issue but rather a question that might benefit wider community.

We are using tiles served from our own server and create all layers and data sources in the code using Expressions. This is performant enough on regular phones or tablets but not on the real hardware we need to run it on as it's sort of low-end.

It would be very helpful to be able to profile rendering process somehow to see which layer contributes most to the rendering time. It is possible of course to go one by one through the layers but it's not indicative enough and very time consuming.

### Configuration

**Android versions:** 
8.0.0
**Device models:** 

**Mapbox SDK versions:** 
8.1.0

**Comment by lukaswelte** [comment]
I had the same problem and I then wrote myself a script which did exactly what you describe. Iterate through the layers and render it 100 times and keep track of the timings. 
With that I then had an overview about the performance of individual layers as well as groups (layers starting with the same id prefix) and sourceLayers (e.g. every layer which uses the `road` layer from the vector tile).

I would also be interested if there is better, more sophisticated options out there.
Otherwise I can tell you that with that setup you can fairly quickly identify the problematic layers (tip: look at sourceLayers first, then groups of layers and then individual layers).
