### ISSUE TITLE
appledocs release notes

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1503]
We need a relatively visible place for release notes. A release note will be required for #1491 in the event that it doesn’t make it into beta 1, but they’re handy in general as a way of mitigating things we punt on. We should package the release notes with appledocs-generated documentation.

/cc @incanus @katydecorah

**Comment by incanus** [comment]
I think a solid approach here will be: 

* [ ] Creating a `CHANGELOG.md` in this repo, kicking off with our b1 release. Our [other mobile projects](https://github.com/mapbox/mbxmapkit/blob/master/CHANGELOG.md) have a good precedent for this. 

* [ ] Linking directly to the GitHub-hosted changelog from https://www.mapbox.com/mapbox-gl-ios/ as we do for other mobile tools. 

* [ ] Dressing up an iOS-specific `README.md` (probably in `platform/ios`) that we use for `appledoc --index-desc`. 

* [ ] Add a step to our docs process (both packaging in `make ipackage` as well as user-manual in `./ios/docs/install_docs.sh`) which concatenates the `CHANGELOG.md` or otherwise links it into the front page of the appledoc-generated HTML docs.

**Comment by incanus** [comment]
https://github.com/mapbox/mapbox-gl-native/pull/1508 takes care of everything above except for the changes to `/mapbox-gl-ios`, which will happen after it lands in `master` and we have a solid place to link to.
