### ISSUE TITLE
Wrong name is displayed when a building has both 'name' and 'building:name' tags

### ISSUE THREAD

**Issue by camelCaseSucks** [mapbox/mapbox-gl-native#15033]
**Platform:** Android & studio.mapbox.com
**Mapbox SDK version:** 7.3.0 (Android)

### Expected behavior

If a building has both 'name' and 'building:name' tags, the 'name' should be displayed on the map.

### Actual behavior

The building:name tag is displayed instead. If I add an onMapClickListener that prints all the tags on the Feature object from "poi-label" layer, it shows that the Feature has the tags "name = {osm name value}" and "name_en = {osm building:name value}". The map is displaying the Feature's name_en which was set incorrectly from the building:name tag.

example: https://www.openstreetmap.org/way/247570076

edit: It appears this doesn't always happen.
example: https://www.openstreetmap.org/way/31742332

**Comment by tobrun** [comment]
Confirming that I'm seeing `Bishop's house` instead of `Al-Amir` 

![image](https://user-images.githubusercontent.com/2151639/60424193-177c7700-9bf0-11e9-8c6c-b3ea425b9398.png)

https://www.openstreetmap.org/way/247570076:

![image](https://user-images.githubusercontent.com/2151639/60424332-5ad6e580-9bf0-11e9-911e-488646a06009.png)

**Comment by 1ec5** [comment]
`building:name` is a [relatively rare tag](https://taginfo.openstreetmap.org/keys/building%3Aname) that has never been approved or documented. No editor has built-in support for it as a field, and neither the openstreetmap-carto project nor the Mapbox Streets source recognize the tag. If the building and its current tenant have differing names, either the less important name should be tagged as `alt_name` or the tenant should be mapped as a separate POI within the building way.

“Bishop’s House” is what the Mapbox Streets source calls this feature in the `{name}` and `{name_en}` fields, so the map SDK is behaving correctly. The Mapbox Streets source calls the feature “Bishop’s House” because of [this Wikidata entity](https://www.wikidata.org/wiki/Q4917420) that is linked to the way in question. The Streets source prefers the Wikidata entity’s label over the corresponding `name_*` tag in OSM. This behavior can be beneficial when it comes to map internationalization: the OSM community generally [disfavors transliterations](https://wiki.openstreetmap.org/wiki/Names#Avoid_transliteration) and translations that aren’t verifiable on the ground, whereas end users may expect such translations on the map.

That said, the Wikidata label ends up overriding even the `name` tag, which may contain a more up-to-date name in the local language. This is unfortunate, and we’re tracking the issue internally, but I’m unable to share a timeline as to when the issue will be fixed. In the meantime, you could fix the issue by editing the Wikidata entity’s label in English. The next time the Streets source pulls a fresh Wikidata dump, the correction will be reflected on the map.
