### ISSUE TITLE
Tracking seems to be broken in 8.1.0

### ISSUE THREAD

**Issue by emerciercontexeo** [mapbox/mapbox-gl-native#15107]
I used LocationComponent#setCameraMode on Android 8.0.0 and everything worked as expected.

I update to 8.1.0 and the setCameraMode looks broken.

When I log the onCameraTrackingChange, I see that the camera tracking mode is dismissed immediately after being set without interaction with the map.

### Steps to reproduce

 1. Set the camera tracking mode to Follow

### Expected behavior

The camera should follow the user and the camera tracking mode should remain in follow mode 

### Actual behavior

The camera does not move and the tracking mode is immediately dismissed.

### Configuration

**Android versions: 8** 
**Device models: Nexus 5X** 
**Mapbox SDK versions: 8.1.0**

**Comment by LukasPaczos** [comment]
Hey @emerciercontexeo, `8.1.0` introduced https://github.com/mapbox/mapbox-gl-native/pull/14745 - any traditional animation invoked after the tracking has been set is going to dismiss it. Before that change, the location's tracking animations and traditionally invoked animations could battle each other as they are not compatible.

You can inspect your code for places that invoke `MapboxMap` animations after the tracking has been set. Placing a breakpoint in `OnCameraTrackingChangedListener#onCameraTrackingDismissed` should help you debug those invocations.

Could you verify above and let us know if that was the root cause? If not, a reproducible example would be great. Thank you!
