### ISSUE TITLE
[ios] [docs] Clearly document which zoom levels hide the scalebar

### ISSUE THREAD

**Issue by chloekraw** [mapbox/mapbox-gl-native#15261]
Current documentation states that the scalebar is "not shown at all zoom levels" and a test indicates it's not shown at zoom level 0, but both in-line SDK documentation and the API reference fail to mention which zoom levels actually show the scalebar. Is it only hidden at zoom level 0 or other zoom levels as well? What's the logic we use in the renderer?

"Not shown at all zoom levels":
https://github.com/mapbox/mapbox-gl-native/blob/5f6f20e667d36fd2f2475756c55d17bade8ee3e2/platform/ios/src/MGLMapView.h#L292

"Not shown at zoom level 0":
https://github.com/mapbox/mapbox-gl-native/blob/60ceac5efc3d77199f773f08400fe1d53d5a1b90/platform/ios/test/MGLMapViewScaleBarTests.m#L38

**Comment by jmkiley** [comment]
The visibility isn't really determined by a specific zoom level. The scale bar becomes visible once the maximum distance on the map view is less than either 400 miles or 800 km, depending on measurement unit. The zoom level where this occurs depends on the latitude at the map view's center coordinate, as well as the device screen width. I'll document that behavior since it is unclear.

https://github.com/mapbox/mapbox-gl-native/blob/60ceac5efc3d77199f773f08400fe1d53d5a1b90/platform/ios/src/MGLScaleBar.mm#L271-L276

**Comment by chloekraw** [comment]
thanks @jmkiley! @mapbox/maps-android @Chaoba any idea if the same algorithm applies to the android scalebar?

**Comment by Chaoba** [comment]
@chloekraw We don't have any logic to hide scalebar by zoom level or distance on Android. Since the max distance  is 400 miles or 800 km, I think @jmkiley's idea make sense. I will add this logic to android plugin.

**Comment by chloekraw** [comment]
Thanks @chaoba! Before starting implementation work, let’s wait for one piece of feedback. I’ll give you the details on slack.
