### ISSUE TITLE
[Qt] Terrain tiles and elevation slicing

### ISSUE THREAD

**Issue by j-mar** [mapbox/mapbox-gl-native#15316]
I am trying to implement a "terrain slicing" feature with your Qt SDK. This would be similar to the inundation maps described in the following blog post: https://blog.mapbox.com/global-elevation-data-6689f1d0ba65

Mapbox Terrain v2 has contours which is exactly what I need, but the contours are only available at zoom levels 9 or higher. Do you guys have a data source that makes this data accessible around zoom level 4 or 5?

The alternative is to use the RGB tiles you provide and decode pixel values to elevation. I know that I can implement this outside of the Qt SDK, but that would mean requesting the tiles a second time and implementing our own renderers. It'd be great if we could utilize the functionality provided by the SDK for requesting and caching tiles. Does the SDK provide a way for accessing the already requested tiles? 

If not, another idea would be to modify the SDK. Since your shaders have already implemented elevation decoding, I could potentially add new paint properties to the hillshade renderer that would allow for specifying an elevation and a color. If I were to add these in, what would the potential risks be? Would it be possible to officially integrate these into the Mapbox SDK for long-term support?

**Comment by tmpsantos** [comment]
@j-mar I would have to check with the data team but it is very likely that the vector contour lines we have are derived from the terrain RGB tiles or both are derived from the same source.

You could maybe access the requested tiles from the cache (just a simple sqlite database), the problem is on the ambient cache, tiles can get evicted at any time. Perhaps the best way to make a "flood layer" would be process the data offline and upload it to our servers as a vector layer, so no extra code in the client would be required.

As for having a new layer type for this purpose, the best way to make a layer official is to get it first on the https://docs.mapbox.com/mapbox-gl-js/style-spec/ (you are very welcome to contribute!), these are the layers we commit to support long term.

Finally, all layers today are modular and can be disabled/enabled.
https://github.com/mapbox/mapbox-gl-native/blob/master/platform/default/src/mbgl/layermanager/layer_manager.cpp#L34

I don't think it would be very problematic to maintain a layer in parallel. We are working on making it easier to do so, because we would also like to experiment with new map layers without making them official or only making the official after we see some adoption.
