### ISSUE TITLE
[android] Setting padding moves camera

### ISSUE THREAD

**Issue by 2Rec** [mapbox/mapbox-gl-native#15412]
In previous Mapbox versions setting padding doesn't couse camera movement.

### Steps to reproduce

 1. map.setPadding(0,0,1000,0)
 2.
 3.

### Expected behavior
No camera movement

### Actual behavior
Camera flips by padding value

### Configuration

**Android versions:** 8.2.1
**Device models:** HTC U11
**Mapbox SDK versions:** 8.2.1

**Comment by astojilj** [comment]
Is the problem that camera padding is now animated movement?

Otherwise, please check issues https://github.com/mapbox/mapbox-gl-native/issues/15269 and https://github.com/mapbox/mapbox-gl-native/issues/15199 as this is related.

As mentioned in https://github.com/mapbox/mapbox-gl-native/issues/15199. padding pushes center of content area to area defined by padding. 1000 is too large IMHO - as explained in https://github.com/mapbox/mapbox-gl-native/issues/15411#issuecomment-522604198.

**Comment by 2Rec** [comment]
Let's assume it's correct padding. It's move center as desired to approximatly 78% of screen height. Problem is that it's scrolling map camera with the same value. Previous versions 6.x 7.x didn't work like that.

**Comment by astojilj** [comment]
> Let's assume it's correct padding. It's move center as desired to approximatly 78% of screen height. Problem is that it's scrolling map camera with the same value. Previous versions 6.x 7.x didn't work like that.

Could you please take screenshot or video of the wrong behavior - with a note about expected and actual behavior? It sounds contradictory that moving center is desired but map scrolling is not. Thanks.

**Comment by 2Rec** [comment]
![Screenshot_20190820-105439](https://user-images.githubusercontent.com/11509620/63333155-3918f580-c339-11e9-8c37-6f974a93810e.png)
![Screenshot_20190820-105443](https://user-images.githubusercontent.com/11509620/63333164-3d451300-c339-11e9-89c3-b5365abc4992.png)

1. before padding change
2. after padding change
There's no need to automatically move camera like in previous versions or at least give a choice

**Comment by astojilj** [comment]
@2Rec 

Thanks for sharing the screenshots. If you set padding (0,0,1000,0) and set camera to user location, it should be like on image 1. 

Let's compare it to screenshot of our Android example: https://github.com/mapbox/mapbox-gl-native/pull/14664#issuecomment-495216629

Center point set [using this code](https://github.com/mapbox/mapbox-gl-native/blob/cbcd0875e375b06cbd163af105e8f1e0226f2df0/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/MapPaddingActivity.java#L102) is moved to the center of padded area.

If that is not what you see, let's try to debug the issue.
- what code you use to set the user location?
- are you offsetting camera center position in your code to get it to bottom? 
- could you debug if there is other code resetting padding to 0?

 Second screenshot looks like as if padding is set to 0 or if there is code that is calculating center that is offset from user location and setting camera to it.

Please share the code snippets for setting camera and location and it should help us identify the issue.

**Comment by 2Rec** [comment]
ok, true first image is padding (0,0, value, 0), second is after clearing (0,0,0,0)
still if u have padding (0,0,0,0) and set to (0,0,value,0) it's the same behaviour

- i can't share a code for user location and it's no need
- no offset set and no other moveCamera etc. functions called

It's possible to make workaround by moving Camera to have it in the same place (before and after padding change) (but for what?)

**Comment by LukasPaczos** [comment]
Hey @2Rec! In previous versions of the SDK, going from padding `(0, 0, value, 0)` to `(0, 0, 0, 0)` would not adjust the camera offset until the next camera animation was invoked. Now, the camera immediately reflects the applied padding. If you do not wish to move the camera position back to the center of the screen, you shouldn't reset the padding to `(0, 0, 0, 0)`. This change was introduced to fix https://github.com/mapbox/mapbox-gl-native/issues/14985.

That said, I can see a scenario where this brings additional challenges, for example:
- We're navigating with top padding applied `(0, 0, value, 0)`, the user clicks a POI and camera should travel to the POI that's centered on the screen. With the current behavior, the camera would jump when padding `(0, 0, 0, 0)` is applied to achieve that.

Is this scenario similar to what you're struggling with?

I think to resolve this issue we should:
1. Revert https://github.com/mapbox/mapbox-gl-native/pull/14989, introduce a boolean flag that updates the viewport if required (like https://github.com/mapbox/mapbox-gl-native/issues/14985) and release a patch:
```
void NativeMapView::setContentPadding(JNIEnv&, float top, float left, float bottom, float right, bool update) {
    insets = {top, left, bottom, right};
    if (update) {
        // invalidate the camera position to consider the new padding
        map->jumpTo(map->getCameraOptions(insets));
    }
}
``` 
or just invalidate the camera internally and suggest that in examples when setting the padding.

2. Expose `padding` field in the `CameraPosition` which would unblock above scenario because we could call `mapboxMap.animateCamera(CameraUpdateFactory.newLatLngPadding(latLng, 0, 0, 0, 0))` to achieve a smooth padding transition.

3. Possibly deprecate `MapboxMap#setPadding` in favor of applying the padding with camera movement only to limit entry points and make the API easier to use. For example, `CameraUpdateFactory.newPadding(0, value, 0, 0)`. I believe this is also the case on iOS @julianrex, that we can only apply the padding using the camera options?

**Comment by 2Rec** [comment]
@LukasPaczos 
Exactly, first point i like most, 2 and 3 are nice additional features.
Pozdro :)
