### ISSUE TITLE
icon color not changing

### ISSUE THREAD

**Issue by davidfitz314** [mapbox/mapbox-gl-native#15476]
I'm trying to load an image into the map using the 
".withImage(
					MapViewModel.ICON_ID, BitmapFactory.decodeResource(
					getApplication<Application>().resources, R.drawable.red_marker, 
                                        bitmapOptions //ensuring bitmap is mutable
				)" 

and that works, but when I try to modify the image icons color in the layer with "
.withLayer(
					SymbolLayer(MapViewModel.LAYER_ID, MapViewModel.SOURCE_ID)
						.withProperties(
							PropertyFactory.iconImage("{$FEATURE_ICON_LABEL}"),
							PropertyFactory.iconAllowOverlap(true),
							PropertyFactory.iconOffset(arrayOf(0f, -9f)),
							PropertyFactory.iconColor(Color.BLUE)
						)
				)"

regardless of what color I put in, the icon color never changes. the icon is white and with the color change I expected it to turn blue.

**Android versions:** 
Using Kotlin language
Android compile version is at 28
 
**Device models:** 
Multiple emulator types and 1 real world device samsung galaxy
**Mapbox SDK versions:** 
implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:8.2.0'
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0'

**Comment by LukasPaczos** [comment]
Hey @davidfitz314, in order to make the mutators work on icons, you need to specify that the image you're supplying is an `SDF`, as [per documentation](https://docs.mapbox.com/android/api/map-sdk/8.2.1/com/mapbox/mapboxsdk/style/layers/PropertyFactory.html#iconColor-com.mapbox.mapboxsdk.style.expressions.Expression-).

To mark an image as an SDF, you need to pass a boolean flag in the [`Style.Builder#withImage` method](https://docs.mapbox.com/android/api/map-sdk/8.2.1/com/mapbox/mapboxsdk/maps/Style.Builder.html#withImage-java.lang.String-android.graphics.Bitmap-boolean-), like:
```
.withImage(
MapViewModel.ICON_ID,
BitmapFactory.decodeResource(
  getApplication().resources, R.drawable.red_marker,
  bitmapOptions //ensuring bitmap is mutable),
true /* pass the SDF flag */
)
```

Let us know if that wasn't enough to resolve your issue, thanks!

**Comment by rickycpadilla** [comment]
For anyone stumbling upon this in the future:
https://docs.mapbox.com/help/troubleshooting/using-recolorable-images-in-mapbox-maps/
