### ISSUE TITLE
Slow or unresponsive map when panning/dragging it

### ISSUE THREAD

**Issue by maxtracking** [mapbox/mapbox-gl-native#15502]
### Steps to reproduce

 1. Create map view in simple application
 2. Set self-hosted styles, either from server or locally hosted
 3. Set zoom level to eg 12 or 14 with enough data displayed on the screen (ie all sorts of objects from the tiles)
4. Try to pan the map using single finger

### Expected behaviour
Map pans following the finger quickly.

### Actual behaviour
There are cases when map is irresponsive (does not move/pan), there are cases when it pans but with noticeable lag.
It could be that tiles data is heavy or we hit CPU/GPU limits, but I would like to get to the bottom of the problem, be it MapBox itself or our code, so ideally I'd need a way to investigate or debug what happens with rendering or camera or whatever else it could be. 
Any ideas are appreciated.

### Configuration.

**Android versions:** 
8.0
**Device models:** 
Quad Cortex A9 1GHz (this is some sort of navigation device), 1280*800 
**Mapbox SDK versions:** 
8.2.0, 8.3.0-beta.1, every version starting from 7.x

**Comment by maxtracking** [comment]
Some of the tiles get quite big - in the area of 2-3MB but mostly it's less than that, I'd say between 500KB to 1MB. 

Could you please elaborate what do you mean by filtering?

**Comment by springmeyer** [comment]
> Some of the tiles get quite big - in the area of 2-3MB but mostly it's less than that, I'd say between 500KB to 1MB.

For acceptable performance I recommend 500 KB as a max size per tile (gzip compressed). Ideally you should aim for the range of 100-200 KB (gzip compressed). If you are loading tiles in the range of 2-3 MB then that is highly likely the culprit because parsing them is taking a lot of time and potentially triangulation of the geometries is taking a lot of time (though you'd need to profile to confirm).

> Could you please elaborate what do you mean by filtering?

By filtering I mean removing data that is unneeded for your map, per zoom. Additionally you can save space by aggregating features and simplifying geometries. Any robust vector tile authoring tool should have functionality to do these things. What tool are you using to create the vector tiles?

**Comment by maxtracking** [comment]
Tiles are produced as part of the elaborate process that churns data from many sources and then creates PBF files following s57 format. PBF files I see on the unit are ranged from 4K to ~800K so definitely something to look into.

**Comment by springmeyer** [comment]
Thanks for the details @maxtracking - it sounds like you have some clear next actions then. Look to your data and optimize it. Good luck! You might enjoy this read from @ibesora 's journey in data optimization: https://medium.com/@ibesora/a-data-driven-journey-through-vector-tile-optimization-4a1dbd4f3a27
