### ISSUE TITLE
complete instructions for Android on OSX

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#1570]
The current README is good as far as it goes for getting up and running with Android on OS X, but it leaves you hanging after the "launch Android Studio" step -- I just spent an hour trying to get the test app running in the simulator to take a look #1468 and wasn't successful.

It looks like we need to document:

* Setting up a virtual device that's compatible with what we build -- seems like the default x86 AVD does not work.
* How to launch the AVD and test application.

Ideally, this would be done by someone who knows the ins and outs of Android Studio starting from a clean install and writing down every step along the way.

**Comment by ljbade** [comment]
Hmm I can have a go at this when I try building Android from scratch on OSX to see if I get your crash.

I haven't been using the simulator much myself because it is slower to iterate on than real device. and I recall a few OpenGL bugs in the simulator that I created tickets in Google's bug tracker but never heard back on.

x86 AVD will work if you build the x86 binaries, but by default the `make android` only generates ARM (needed for developing on real devices).

Should we also document how to run on a real device?

I guess the tricky thing here is, how much do we assume Android developers know about Android Studio, I imagine most full timer Androiders would know how to set up the simulator.

For example, do we document all the xcode simulator setup?

Do we document these ourselves or point at the Google documentation?

**Comment by jfirebaugh** [comment]
> x86 AVD will work if you build the x86 binaries

Yeah, the ARM simulator was _super_ slow, like 10 minutes just to boot up. If x86 is faster lets make that easier to get started with. What does AVD stand for? Can we make x86 binaries the default for `make android`?

> Should we also document how to run on a real device?

Yes, this would definitely be helpful.

> I guess the tricky thing here is, how much do we assume Android developers know about Android Studio

Here's a good goal: document enough to get any new team member running the tests and test app on the simulator in 30 minutes or less, regardless of their level of experience. That should be basics plus any necessary pointers to external resources.

**Comment by ljbade** [comment]
We can make x86 binaries the default, but if everyone will be testing on devices then they need to build ARM. Perhaps we can default to both?

**Comment by ljbade** [comment]
Created PR: https://github.com/mapbox/mapbox-gl-native/pull/1587
