### ISSUE TITLE
GPS trail ahead of current position icon

### ISSUE THREAD

**Issue by oantacamelia** [mapbox/mapbox-gl-native#15730]
The current position icon is behind the trail rendering.

 <img width="211" alt="Screen Shot 2019-09-30 at 12 34 47" src="https://user-images.githubusercontent.com/36509829/65868138-6a490480-e380-11e9-9be2-aff6a0214fb5.png">

I used the following setting for  user's location icon:
- locationComponent.cameraMode = CameraMode.TRACKING_GPS
- locationComponent.renderMode = RenderMode.COMPASS

Also, I used LocationEngineCallback for location updates in order to render the trail line. 

The expected behaviour would be to display the user's location icon at the end of the trail.

Configuration
Android versions: 9.0
Device models: Samsung SM-G973F (S10)
Mapbox SDK versions: 8.3.0

**Comment by LukasPaczos** [comment]
Hey @oantacamelia. Location puck is smoothly animated over the course of the location update and since we do not offer any algorithms to predict the next location updates in the Maps SDK, the location is always going to be a little bit behind the real user position.

The animation duration between two location updates is calculated using:
https://github.com/mapbox/mapbox-gl-native/blob/d446b3382b7de03d9031445e37c1ebf183092ea2/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationAnimatorCoordinator.java#L106-L107

The `durationMultiplier` is customizable using [`LocationComponentOptions.Builder#trackingAnimationDurationMultiplier`](https://docs.mapbox.com/android/api/map-sdk/8.4.0/com/mapbox/mapboxsdk/location/LocationComponentOptions.Builder.html#trackingAnimationDurationMultiplier-float-) which you can use to speed up the animation and make it more direct or align it with your line updates.
