### ISSUE TITLE
Stop using obsolete? Map functions on Android

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#1575]
These functions been replaced by custom implementation in iOS:
- `setZoom`
- `setLatLng`
- `resetNorth`

(will add other as I find them)

Discussion on what to do in C++ side with these functions in https://github.com/mapbox/mapbox-gl-native/issues/1574

**Comment by jfirebaugh** [comment]
@ljbade What do you mean by "replaced by custom implementation"?

These functions are by no means obsolete. As with #1576, if iOS is no longer using them it may just be a question of which is more convenient.

**Comment by ljbade** [comment]
@jfirebaugh Basically iOS used to use setZoom to change the zoom level, but now uses setLatLngZoom along with getZoom.

I am wondering since setZoom etc have not been used for a while in iOS (even in the test cases) that they have been broken but nobody noticed.

**Comment by jfirebaugh** [comment]
Closing here since I think this is causing confusion. Just because iOS doesn't use a particular method doesn't necessarily mean it's "obsolete" or "duplicate". Eventually we'll probably go through and rationalize the map view methods in the style of https://github.com/mapbox/mapbox-gl-js/pull/1215, but that's not actionable right now.
