### ISSUE TITLE
Mapbox MMELocationManager causes threadlock with iOS 13/Xcode 11

### ISSUE THREAD

**Issue by joeboyscout04** [mapbox/mapbox-gl-native#15801]
We are seeing an issue where our application would freeze on startup when running on iOS 13 building with Xcode 11.1.  When setting a breakpoint in the application, the process running is `MMELocationManager didUpdateLocation`.  While the lockup is occuring, I see many (hundreds) of logs to the console similar to `Discarding message for event 29 because of too many unprocessed messages`.

<img width="1674" alt="Screen Shot 2019-10-11 at 14 49 35" src="https://user-images.githubusercontent.com/1489809/66652847-f687e100-ec36-11e9-90b9-8dd75db5534d.png">

### Steps to reproduce
We have only seen this issue recently and so far the only way to reproduce is to:

 1.  Start the application running in debug mode.
 2. Threadlock occurs just after app startup. 

### Expected behavior
I would expect the application to run normally. 

### Actual behavior
The application locks up on startup and the UI becomes unresponsive for many seconds. 

### Configuration

**5.4.0** But also seen on previous version of `4.10.0`
**iOS 13.0** 
**iPhone XS**
**Xcode 11.1**

**Comment by alfwatt** [comment]
Does your application initialize the Mapbox framework from a background thread or queue?

https://stackoverflow.com/questions/41478284/discarding-message-for-event-0-because-of-too-many-unprocessed-messages-in-xcode?noredirect=1

**Comment by joeboyscout04** [comment]
I'm not sure I understand...we don't initialize the Mapbox framework itself in our code as far as I can see.  It's just, bam, it's running. We just `import Mapbox` where we need it to create a `MGLMapView`, which we do from the main thread, but this error seems to occur before any map views are created (most of the time close to startup of the app).

**Comment by alfwatt** [comment]
@joeboyscout04 better link: https://stackoverflow.com/questions/7857323/ios5-what-does-discarding-message-for-event-0-because-of-too-many-unprocessed-m/8108274#8108274

Those messages are the result of initializing a `CLLocationManager` on a background thread with no run loop, as you can see from your trace the instance we use for telemetry is setup on the main thread, and you can see the main thread sitting in `mach_message_trap` most likely waiting for a lock to clear.

Try setting a breakpoint on `-[CLLocationManager init]` to see if there is a location manager being created on a background thread which may be holding a lock which the main thread is waiting for.

**Comment by joeboyscout04** [comment]
Thanks for the good explanation.  We found some suspicious code using CLLocationManager and removed it.  So far I haven’t had the same issue, but it’s hard to reproduce reliably. 

I think we can close this, and reopen if the issue reoccurs.
