### ISSUE TITLE
events=true on non-mapbox URLs?

### ISSUE THREAD

**Issue by halset** [mapbox/mapbox-gl-native#1592]
I am using my own tile source and wonder why all of the requests has events=true added to the URL. It is not a problem, just strange. Looks like this is from #1185

**Comment by bleege** [comment]
Good question @halset!  This has to do with an internal Mapbox system for keeping track of the number of tiles that are served [based on Mapbox plan type](https://github.com/mapbox/mapbox-gl-native/blob/58c9e2687de5befc69cb50321d303d7fa704cbfa/platform/darwin/http_request_nsurl.mm#L157-L164).  If you're running your own tile source and want to disable this setting  `MGLMapboxMetricsEnabled` to NO / false in `Settings.bundle`.  For more info please [see this guide](https://www.mapbox.com/mapbox-gl-ios/#metrics_opt_out).

**Comment by friedbunny** [comment]
@bleege Would it make sense to check the tile source for `mapbox://` and disable adding `events=true` to the URL automatically if not applicable?

Or, if Metrics aren't going to be required for non-Mapbox sources, perhaps they can be automatically disabled entirely.

**Comment by bleege** [comment]
@halset @friedbunny I spoke too soon.  The more we thought about this, the more we realized that this isn't the right approach.  We should have better support for non Mapbox tiles in the SDK.  We're going to do this in 2 ways due to timing.  The first will be to add a check for non `mapbox.com` urls into the iOS GL SDK for Beta 2 so that support will get out much sooner.  The second is that we'll eventually move this support down into the Core GL layer itself so that it'll truly be cross platform for all our native GL SDKs.  I'll ticket these both out in a moment.

Finally, I want to clarify the `MGLMapboxMetricsEnabled` setting.  This is strictly for Metrics Opt Out and is part of the [Mapbox Terms of Service](https://www.mapbox.com/tos/).

Sorry for the confusion on all this!

**Comment by bleege** [comment]
I just ticketed out the issues I described above.  We'll do the iOS GL version in #1596 immediately while the Core GL version will come later down the road in #1597.

Thanks for bringing this to our attention!

**Comment by halset** [comment]
Thank you for taking this minor issue so serious!

**Comment by bleege** [comment]
Absolutely!  We want to make sure we're not forcing non Mapbox Tile sources to use stuff that isn't of use / need for this.  Thanks again for asking about this.  Please keep questions like this coming!

BTW, #1596 is already done so when Beta 2 is out the door this problem will disappear!  :-)
