### ISSUE TITLE
[Android] - Offline region download [HTTP] Request with response = 422: Unknown

### ISSUE THREAD

**Issue by nstele** [mapbox/mapbox-gl-native#16486]
I've recently changed the Tile URL that I use and looks like this:

**"tiles": [
        "https://api.mapbox.com/styles/v1/mapbox/streets-v11/tiles/512/{z}/{x}/{y}?access_token=TOKEN_VALUE"]**

When I try to attemp to download a region I got this:

**D/Mbgl-HttpRequest: [HTTP] Request with response = 422: Unknown**

Before this change I was able to download the same region without any problem. Also I've changed the tile set size to 256 and get the same result. 

**Platform: Android and iOS**
**Mapbox SDK version: 8.2.0 for Android and latest version for iOS**

### Steps to trigger behavior

 1. Change the tile set URL for Mapbox satellite and Mapbox Open Street to latest versions
 2. Try to download an offline region
 3. Get HTTP response 422

### Expected behavior
Download the offline region (previouly working with old tile set)

### Actual behavior
The download fails and return HTTP 422

**Comment by nstele** [comment]
@tobrun this is urgent since the tiles set will be deprecated on 6/1

**Comment by tobrun** [comment]
@nstele it seems you have a custom style definition? If you want to download an offline region with one of our predefined styles you can use `Style.MAPBOX_STREETS` instead (you aren't required to setup any tilesize etc.).

**Comment by nstele** [comment]
@tobrun  Now I'm able to load the style (custom style) but something happen before it turns black the map 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/4140972/83260760-b5761a00-a190-11ea-904d-41989dcf870d.gif)

**Comment by nstele** [comment]
@tobrun I'm using a custom style, the only change I've made since I use this custom style is the way to define the sources for this layer:

Before:

 ```
"mb_satellite_streets": {
      "type": "raster",
      "url": "mapbox://mapbox.streets-satellite",
      "tileSize": 256
    },
```

Now:

```
"sources": {
    "mb_satellite_streets": {
      "type": "raster",
      "tiles": [
        "https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v11/tiles/{z}/{x}/{y}?access_token=MY_TOKEN"
      ],
      "tileSize": 512
    },
```

When I work with the map I can display the layers without problems, but when I try to download this style I get **`D/Mbgl-HttpRequest: [HTTP] Request with response = 422: Unknown
`**

**Comment by shabnomnom** [comment]
@nstele just want to summarize you are seeing `422` error because the SDK is appending the  `offline=true` to the end of your URL and that was not happening with the classic style?

 I also noticed on your [last test ](https://github.com/mapbox/mapbox-gl-native/issues/16486#issuecomment-636397472) the correct URL is  : `mapbox://styles/mapbox/satellite-streets-v11` rather than  `mapbox://styles/mapbox/satellite-v11`. Are you still getting an error with the correct URL?

**Comment by nstele** [comment]
@shabnomnom 

1. Raster classic style we are currently using in production:
```
"sources": {
     "mb_satellite_streets": {
     "type": "raster",
     **"url": "mapbox://mapbox.streets-satellite",**
     "tileSize": 256
   }
}
```
      Results: works ok, I can display the maps with all styles and also download maps. Those are the styles that you are going to deprecated. 

2.  First approach was change the url for 

 ```
 "sources": {
    "mb_satellite_streets": {
      "type": "raster",
      **"url": "mapbox://styles/mapbox/satellite-v11",**
      "tileSize": 512
    },   
```  

Results: I can't display Satellites Style in map, (map shows a black background) despite other layers can be displayed without any problems

3. Last approach was use this URL and format for sources:

```
"sources": {
    "mb_satellite_streets": {
      "type": "raster",
      "tiles": [
        "https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v11/tiles/{z}/{x}/{y}?access_token=MY_TOKEN"
      ],
      "tileSize": 512
    },
```

Results: I can display the style for satellite without problems but when I try to download the map I get **422**

Let me know if you needs more info about it

**Comment by nstele** [comment]
@shabnomnom @shivani-patel23 @chloekraw any news about this?

**Comment by shabnomnom** [comment]
@nstele I see that you are mentioning that you want to download a custom style, but in your first approach, you are referring to the mapbox satellite layer like so: `mapbox://styles/mapbox/satellite-v11`. 

1. Is this layer only a place holder for your custom layer? 

2. if you just want to load [Mapbox satellite layer](https://docs.mapbox.com/api/maps/#styles), you can use the following URL: 
URL:`mapbox://styles/mapbox/satellite-v9` or continue using [mapbox.satellites](https://docs.mapbox.com/help/glossary/raster-tiles-api/) with the /v4/ endpoint since that raster tileset is not deprecating. 

3. In order to confirm if this issue is only happening with our raster layer, would you also check if you are getting the same error when loading vector style such as: 
`mapbox.com/styles/v1/mapbox/streets-v11/tiles/1/1/0?` ?

**Comment by nstele** [comment]
@shabnomnom the custom style is composed by other layers, but as base layer we use satellites, open street, etc raster layers.

So if you combine our layers with Satellites or Open Streets new sources, we get the result described above.

**Comment by shabnomnom** [comment]
@nstele the Static Tile API team was able to resolve the `422` error caused by `offline=true` parameter, so you should be unblocked here.

 However, a better implimentation is using Vector Tiles API and Raster Tiles API instead of the Static TIle API. If you have not done this already, use the Vector Tiles API for your vector layers and the Raster Tiles API for your raster layers. Especially because the requests from Vector Tiles API and Raster Tiles API are included in the cost of their MAUs/SDK usage. Please reach out to the Mapbox support if you have any implimentation/pricing specific questions.
