### ISSUE TITLE
POI disappears unnecessarily when zooming in or rotating

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1690]
The “Restaurant Tsugaru” POI in the first screenshot disappears as soon as you zoom in to the next level, even though there doesn’t appear to be anything that would collide with it that wasn’t in the previous zoom level:

![out](https://cloud.githubusercontent.com/assets/1231218/7988544/e65e22c8-0a98-11e5-8f68-5f9fb92d70fd.PNG)

![in](https://cloud.githubusercontent.com/assets/1231218/7988559/f4daece6-0a98-11e5-8356-1ca808adf130.PNG)

When rotating, I see this POI possibly avoiding collisions with a nearby one (“Shinmori Optometry”), but at certain angles, neither POI shows up, probably because of each other:

![food](https://cloud.githubusercontent.com/assets/1231218/7988693/99baa04e-0a99-11e5-9f56-e9a8199f4474.PNG)

![nothing](https://cloud.githubusercontent.com/assets/1231218/7988708/a5b14362-0a99-11e5-9695-c46fb01898a2.PNG)

![sight](https://cloud.githubusercontent.com/assets/1231218/7988712/acb98bc4-0a99-11e5-9ec8-8e0990662a0e.PNG)

[In mapbox-gl-js](https://www.mapbox.com/mapbox-gl-styles/#17.69/37.34897/-121.89358/-16.9), the same POIs also blink in and out when zooming and rotating, though the thresholds are slightly different.

**Comment by friedbunny** [comment]
Not the best gif, but Tsugaru Restaurant disappears at max zoom and the surrounding collision boxes become red.

![ezgif com-gif-maker](https://cloud.githubusercontent.com/assets/1198851/8491398/c9bb0e64-2105-11e5-8573-32a64cf1b130.gif)

**Comment by friedbunny** [comment]
Still happens.

**Comment by ansis** [comment]
This is expected right now

The label that disappears is blocked by other labels that will show up later in the zoom level (when you zoom in a bit more). It's implemented this way to reduce labels popping in and out all the time while zooming.

I agree that it would be better if the label didn't disappear but I'm going to treat this as an enhancement, not a bug.

I don't see us doing a major revision of the labelling algorithm anytime soon but I'm keeping track of all the algorithm suggestions in a separate master ticket. They all impact each other so I think it makes sense to close the individual issues and keep the ideas in one spot: https://github.com/mapbox/mapbox-gl/issues/14

**Comment by mb12** [comment]
@ansis Is this a regression due to overscaling changes? Previously when placement was done for multiple zoom levels, it used to enforce the invariant that if a symbol appeared it would continue to show for current zoom level and next (or until forever when placement was done for source maxzoom). It would be a nice invariant to have for symbol placement.

**Comment by ansis** [comment]
> @ansis Is this a regression due to overscaling changes? Previously when placement was done for multiple zoom levels, it used to enforce the invariant that if a symbol appeared it would continue to show for current zoom level and next (or until forever when placement was done for source maxzoom). It would be a nice invariant to have for symbol placement.

Yes and no. Before we started reparsing tiles at every zoom level it would use the same parsed data at every zoom level above the maximum zoom level. After the source's maximum zoom level labels would never disappear when zooming in. The could disappear at lower zoom levels though. Switching to reparsed tiles had many benefits including better performance and denser labels. I don't think we'll switch back

**Comment by mb12** [comment]
@ansis Is the following an accurate description(or not) of the expected behavior for cases where only the zoomlevel is changing (rotation and tilt remains same)?

1.)  If the zoom starts at a level < maxzoom, symbols can disappear when data from a new tile gets loaded? 
2.) If zoom starts at maxzoom, symbol will not disappear (if rotation and tilt remains same).

**Comment by ansis** [comment]
@mb12 
1) yes
2) often, but not always. For example:

there are labels `A` and `B` and the maxzoom is 14. `A` is placed before B and is blocked by some other label. `A` can only be shown at `z16.3`. If the tile placement is calculated at `z14` or `z15` then `A` will not show up anywhere within that tile's zoom level so it will be ignored completely. If the tile is placed at `z16` then `A` is not ignored and it might block `B`. It's possible that `B` is visible for `z14-15.99`, neither is visible for `z16-16.3`, and `A` is visible for `z16.3+`.

It's a tradeoff between consistency and density.

**Comment by mb12** [comment]
@ansis  Thank you very much for the detailed explanation.

**Comment by Jakobud** [comment]
Seems like there should be an option to force individual markers to always render no matter if they are overlapping other markers or labels or whatever. Sometimes you want to show all markers no matter what. Does it look crowded? Yeah probably. But let the user decide what they want instead of forcing this on them.
