### ISSUE TITLE
Annotations API In Android

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#1716]
Implement marker annotations in Android similar to how it was implemented in iOS in ecb8e2800d0fbc4e4f843b0d13efc28038ede3ef.

**Comment by hallahan** [comment]
I forked the repo and am working on a branch that attempts to add a point annotation to the map via a call to the native [Map::addPointAnnotation](https://github.com/hallahan/mapbox-gl-native/blob/master/src/mbgl/map/map.cpp#L240).

https://github.com/hallahan/mapbox-gl-native/commit/ef31fc5aed4e07b3d9e98b25180b8f809d51a5cf

The JNI part of things is straightforward, and I have verified that `addPointAnnotation` in the C++ Map is indeed being called. However, my single point annotation is not successfully rendering on the map.

I'm studying how annotations work in the core library in this [MapboxGL Native Annotations Walkthrough](https://gist.github.com/hallahan/eb2de11bdd4619a11eec). @incanus, one conceptual question I have deals with that final conversion to the vector space of a tile for a given point:

```cpp
const Coordinate coordinate(extent * (pp.x * z2 - x), extent * (pp.y * z2 - y));
```

__We just computed `x`, which is a 32 bit unsigned int. We then do `pp.x * z2 - x` which just subtracts the truncated int from the complete double. How does that then relate to determine the correct coordinate in the vector space of the given tile?__

I was able to follow the code through setting up the annotation vector tiles as well as telling the map what to update. 

__Where do I look to learn about how that actual sprite is rendered on the map?__ My guess is that the actual problem here is that somehow the sprite itself is not being rendered in Android. I don't think the problem at hand is involved with the cutting of the annotation vector tiles.

**Comment by hallahan** [comment]
Note, stepping through all of the function calls mentioned in the [point annotation walkthrough](https://gist.github.com/hallahan/eb2de11bdd4619a11eec) seem to execute fine when poking around my android device in `gdb`. My thought is that the annotation is actually added to the map just fine. Maybe the marker sprite is just not being rendered?

**Comment by hallahan** [comment]
I am currently working on the annotation proof of concept of adding a single marker to the map via the Android MapView. I have my own fork/branch of MapboxGL where I have simply added a basic [`addAnnotation(LatLng latLng)`](https://github.com/hallahan/mapbox-gl-native/blob/ef31fc5aed4e07b3d9e98b25180b8f809d51a5cf/android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/NativeMapView.java#L200) as well as a simple [MenuItem](https://github.com/hallahan/mapbox-gl-native/commit/ef31fc5aed4e07b3d9e98b25180b8f809d51a5cf#diff-95983679f3cfbcc48f1e84ce52ec443bR216) to toggle on and off a marker. 

![screenshot_2015-07-13-10-46-09](https://cloud.githubusercontent.com/assets/556367/8656989/de0787a6-294f-11e5-9741-b05fcb6f5d1f.png)

We then [call the native `addPointAnnotation`](https://github.com/hallahan/mapbox-gl-native/blob/ef31fc5aed4e07b3d9e98b25180b8f809d51a5cf/android/cpp/jni.cpp#L439) via a JNI call.

Extending the Java API seems straightforward, however, there is a problem with actually rendering this marker on the map. Calling `addPointAnnotation` on the native map view appears to be behaving normally. Stepping through (in gdb) all of the calls of [`auto result = data->annotationManager.addPointAnnotations(points, properties, getMaxZoom());`](https://github.com/mapbox/mapbox-gl-native/blob/ac2ad993a594e309362787e0697ff1727b799e8e/src/mbgl/map/map.cpp#L302) appears to be behaving normally when comparing to what happens in the XCode debugger on iOS.

My suspicion is that there is a problem loading that `default_marker` glyph that we have in iOS for markers. It looks like this marker comes from somewhere other than the standard glyps in MapboxGL, specifically for annotations. Could someone help point out:

__Where do glyphs get loaded, in specific, `default_marker`, and how is that loaded in the texture buffer for GL to render?__

<img width="36" alt="screenshot 2015-07-13 11 08 58" src="https://cloud.githubusercontent.com/assets/556367/8657018/ff316212-294f-11e5-9021-2ec68b6e44df.png">


I will continue to trace through what happens in the `MapContext::updateAnnotationTiles` call on the map thread, however, I was hoping to get a bit of a tour of the architecture and code with this specific part of the rendering pipeline. In particular, how do marker annotations integrate?

cc @kkaefer @tmpsantos

**Comment by tmpsantos** [comment]
> We then call the native addPointAnnotation via a JNI call.

`nativeMapView->getMap().addPointAnnotation(mbgl::LatLng(latitude, longitude), std::string(""));`

Try using `std::string("default_marker")`.

**Comment by hallahan** [comment]
Thank you @tmpsantos. We now have our first marker annotation on MapboxGL!

![marker-poc](https://cloud.githubusercontent.com/assets/556367/8658033/45efa0dc-2956-11e5-8464-732f44e8fe01.png)

**Comment by hallahan** [comment]
![screenshot_2015-07-16-10-23-19](https://cloud.githubusercontent.com/assets/556367/8730350/06dc5d76-2ba5-11e5-8b5b-75b8b51d64a8.png)

**Comment by bleege** [comment]
This is really looking great @hallahan!  :+1:

**Comment by hallahan** [comment]
Lines, Polygons, and..., you can specify what sprite you want as your marker.

![2015-07-17 15 24 56](https://cloud.githubusercontent.com/assets/556367/8750720/ff6b1da2-2c5d-11e5-8272-1ed571ac0d6d.png)

**Comment by incanus** [comment]
Is this complete or do we still need to build out parity @bleege?

**Comment by bleege** [comment]
Overall, I think we're in good shape here as @hallahan did a great job laying the foundation.  There are still a few a [TODOs](https://github.com/mapbox/mapbox-gl-native/blob/8e5bbb062cd75bdaac4b0bb76b608e9165eb649b/android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/annotations/Annotation.java#L55-L63) and [higher level features](https://github.com/mapbox/mapbox-gl-native/blob/8e5bbb062cd75bdaac4b0bb76b608e9165eb649b/android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/annotations/CircleOptions.java#L10) like [geodesic polylines](https://github.com/mapbox/mapbox-gl-native/issues/1726) that are still to be built out.

**Comment by bleege** [comment]
Bumping to `0.2.0` to finish the [remaining features mentioned above](https://github.com/mapbox/mapbox-gl-native/issues/1716#issuecomment-126556240).

Popups are being handled in #894

**Comment by ljbade** [comment]
Done!

**Comment by bleege** [comment]
> Done!

@ljbade Could you comment a bit on why you believe this is "Done"?  What changed since the 31-Aug-2015 comment?  I see that #1726 has been ticketed out separately, but it's unclear what else was finished.  Thanks!

**Comment by ljbade** [comment]
@bleege Well we implemented all features of iOS SDK annotations since https://github.com/mapbox/mapbox-gl-native/issues/2744 and https://github.com/mapbox/mapbox-gl-native/issues/2726

Finally I have removed all annotation properties that are not supported in Core GL.

So the original aim of this ticket to reach parity with iOS has been achieved.
