### ISSUE TITLE
update changelog for 0.4.0

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1756]
It's always easy to do an `initial release`! Now we have to update [this guy](https://github.com/mapbox/mapbox-gl-native/blob/master/CHANGELOG.md) and I could use some help. 

Let's work at https://gist.github.com/incanus/051c2bfc5057ae414e6a until we're happy, then plop it into the live one. 

Or just paste ideas/remembrances here. 

@mapbox/gl

**Comment by 1ec5** [comment]
* MGLMapView no longer manages Mapbox access tokens directly; an access token cannot be passed in when initializing the map view. Instead, set `MGLMapboxAccessToken` to your access token in your app’s Info.plist file, or call `+[MGLAccountManager setAccessToken:]` before initializing the map view. If you were setting the access token inside an Interface Builder inspectable, also remove it from the User Defined Runtime Attributes section of the Identity inspector. (#1553)
* `-[MGLAccountManager setMapboxMetricsEnabledSettingShownInApp:]` has been removed. If you implement a Mapbox Metrics switch inside your app, instead of inside a Settings bundle, set `MGLMapboxMetricsEnabledSettingShownInApp` to `YES` in the Info.plist file. (#1553)
* MGLMapView supports Interface Builder designables. When you add an MGLMapView to a storyboard, it displays instructions for getting set up directly on the storyboard canvas. (#1573)
* Headers have been audited for nullability, improving type safety in both Objective-C and Swift 1.2 when compiling with Xcode 6.3 or above. (#1578)
* Headers now make use of lightweight generics, eliminating many unnecessary casts when working with annotations in Swift 2.0 in Xcode 7. (#1711)
* `-[MGLMapView mapID]` has been renamed `-styleID`. (#1561)
* The default title for the user location annotation is now “You Are Here”. You can customize the title by setting `mapView.userAnnotation.title`. (#1559)
* Internal use of the Reachability library has been cleaned up so that your app can include its own copy of Reachability. (#1718)

**Comment by jfirebaugh** [comment]
I believe that all my changes were internal-only and probably not interesting for a changelog beyond a general "improve overall performance and stability" item.

**Comment by 1ec5** [comment]
* [Improved placement and density of labels](https://www.mapbox.com/blog/better-label-placement-mapbox-mobile/). (#1666)
* Added a shortcut to the Mapbox Metrics switch to the action sheet that is attached to the ℹ️ button. (#1611)
* Fixed an issue in which certain features, such as roundabouts, were not rendered completely. (#1725)
* Fixed an issue in which the map would sometimes spin 180° while rotating the map. (#1453)

**Comment by 1ec5** [comment]
@incanus, rather than arranging the changes chronologically, I think they should be in roughly the order I proposed above. We don’t want to bury the lede on #1553, which is a breaking change.
