### ISSUE TITLE
Handle Gestures

### ISSUE THREAD

**Issue by crazyBoat** [mapbox/mapbox-gl-native#1758]
Hello, how I can handle gestures from mapview?

**Comment by 1ec5** [comment]
Which platform are you using the map view on?

**Comment by crazyBoat** [comment]
iOS

**Comment by 1ec5** [comment]
MGLMapView handles standard gestures (swipe to pan, pinch to zoom, rotate with two fingers, etc.) by default. If you need to handle additional gestures, UIKit provides a set of gesture recognizer classes like [UILongPressGestureRecognizer](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UILongPressGestureRecognizer_Class/) that help you handle gestures with minimal extra code.

Does this answer your question?

**Comment by crazyBoat** [comment]
what is the best way to avoid conflicts between mapbox gestures and my personal implementation with gesture recogniser?

**Comment by 1ec5** [comment]
If you’re looking to _replace_ one of the built-in gestures, you can disable that gesture by setting [`rotateEnabled`](https://www.mapbox.com/mapbox-gl-ios/api/Classes/MGLMapView.html#//api/name/rotateEnabled), [`scrollEnabled`](https://www.mapbox.com/mapbox-gl-ios/api/Classes/MGLMapView.html#//api/name/scrollEnabled), or [`zoomEnabled`](https://www.mapbox.com/mapbox-gl-ios/api/Classes/MGLMapView.html#//api/name/zoomEnabled) to false. Otherwise, what kind of conflict are you trying to work around?

**Comment by tomtaylor** [comment]
@crazyBoat you can implement the `gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:` method in the `UIGestureRecognizerDelegate` protocol to allow your gesture recognizer to pass through to the `MGLMapView` ones without interfering.

**Comment by andrewcar** [comment]
Even after implementing gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer: set to true, the pan gesture is not passing through to the map view.

**Comment by 1ec5** [comment]
The suggestion in https://github.com/mapbox/mapbox-gl-native/issues/1758#issuecomment-114250985 was to use this method to intercept the gestures you don't want MGLMapView handling. Unconditionally returning true will always allow both gesture recognizers to fire simultaneously, which is probably not your intent.

**Comment by 1ec5** [comment]
Related: #2278.
