### ISSUE TITLE
Properties to enable/disable attribution/logo bug

### ISSUE THREAD

**Issue by tomtaylor** [mapbox/mapbox-gl-native#1770]
I'd really like to be able to disable the attribution button (I'm handling it separately in the app), and the Mapbox logo (it conflicts with a UI element). This was possible in `RMMapView` - it'd be great to get those back in. Thanks!

**Comment by friedbunny** [comment]
Thanks for the request, Tom! We should definitely include these settings.

The `RMMapView` settings were:
- [`.hideAttribution`](https://www.mapbox.com/mapbox-ios-sdk/api/Classes/RMMapView.html#//api/name/hideAttribution)
- [`.showLogoBug`](https://www.mapbox.com/mapbox-ios-sdk/api/Classes/RMMapView.html#//api/name/showLogoBug)

I don't like the naming inconsistency — can we settle on either `hide` or `show`?

/cc @incanus @1ec5

**Comment by incanus** [comment]
The naming logic backstory is: 

- The dev should be aware that they are _hiding_ attribution, which we want to make sure they understand in terms of our data licensing agreements. 
- The logo bug defaults to shown. 

We could change `.showLogoBug` to `.hideLogoBug` pretty easily, though.

**Comment by picciano** [comment]
Might as well throw in `.hideCompass` too.

**Comment by incanus** [comment]
Good call, though iOS 9 adds `.showsCompass`.

**Comment by 1ec5** [comment]
> The dev should be aware that they are _hiding_ attribution

By default, the logo bug would be “not hidden”. We should avoid obfuscating the API with that double negative, just like it would be a usability crime to put a “Do not …” switch in Settings.

If we want to make hiding attribution a deliberate action, we could expose that capability through a method rather than a property: `[mapView hideAttribution]`. Or make setting `.showLogoBug` trigger a compiler warning that can be suppressed with a Clang pragma. :wink:

(Also, Cocoa naming convention calls for property names to be descriptive, not imperative. So `.showsCompass`, not `.showCompass`.)

**Comment by picciano** [comment]
Or...

```
mapView.compassView.hidden = NO;
mapView.logoView.hidden = YES;
mapView.attributionButton.hidden = YES;
```

Just make these views properties and there is an added benefit of being able to replace the design of these elements.

**Comment by 1ec5** [comment]
That’s a good point, @picciano. We aren’t doing anything fantastically clever with these views anyways.

**Comment by incanus** [comment]
I've added these in #1815 (pending tests), which will make it into the next release. They are `readonly` for now since this hits the use case of hiding/showing but there are constraints involved with actually replacing the views, so we should test around that more before allowing replacement.
