### ISSUE TITLE
Storyboard view hierarchy can lead to squashed subviews

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#1779]
Setting your storyboard up with the map view at the base level of the hierarchy like this:

![screen shot 2015-06-23 at 11 09 24 am](https://cloud.githubusercontent.com/assets/1198851/8313763/ad5d277a-1999-11e5-9f41-5fcad8006578.png)

Leads to the attribution button and logo bug being squashed after the initial load — i.e., load the MBGL view controller, switch to a different view controller, come back to MBGL and this happens:

![ios simulator screen shot jun 23 2015 11 10 27 am](https://cloud.githubusercontent.com/assets/1198851/8313760/ab145bf0-1999-11e5-9fdc-1392742e9bf3.png)

Work around is to place the map view within another view, remembering to reset to suggested constraints:

![screen shot 2015-06-23 at 11 19 34 am](https://cloud.githubusercontent.com/assets/1198851/8313813/f3912a52-1999-11e5-960e-412cd51697fe.png)

/cc @1ec5

**Comment by 1ec5** [comment]
The logo (and attribution button) both have intrinsic width and height constraints that are [removed](https://github.com/mapbox/mapbox-gl-native/blob/29fd554c326da14badf9531aa5d5eaf7ed7c4c50/platform/ios/MGLMapView.mm#L465) whenever the MGLMapView moves to a new superview, as is the case when returning to the tab view containing the MGLMapView. The compass is unaffected because it has a container view whose constraints are removed.
