### ISSUE TITLE
Support comp-op blend modes

### ISSUE THREAD

**Issue by edenh** [mapbox/mapbox-gl-native#191]
Blend modes are used extensively in the outdoors style for hillshades, contours, landcover, buildings, etc.

https://github.com/mapbox/llmr/pull/380

**Comment by georgbachmann** [comment]
As I'd also love to see blend modes for my own hill-shading layer...
Can somebody give me a quick update? It's still not possible, right? Is it because of performance I guess? Will we see blend modes in the future? Are there any updates about is?
Would be cool if somebody could bring me up to date :)
