### ISSUE TITLE
Location Services prompt disappears too soon

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1930]
A fresh install of iosapp on iOS 9 displays a Location Services prompt for “Always” permissions, but this prompt disappears after a second without any user intervention. Then if you hit the user location tracking button, a “When in Use” prompt appears, so iosapp has no access to background location updates. If at some point you revoke iosapp’s “When in Use” permission, pressing the user location tracking button does nothing.

Unclear how this affects #1909.

/cc @incanus @friedbunny

**Comment by 1ec5** [comment]
Also reproduces on iOS 8.4.

**Comment by friedbunny** [comment]
#1909 either appears to be unaffected or fixes this problem. Pushing the location button in the demo app brings up the permission dialog as expected using both `WhenInUse` and `Always`.

**Comment by friedbunny** [comment]
>  If at some point you revoke iosapp’s “When in Use” permission, pressing the user location tracking button does nothing.

This is something we've left up to developers to handle in the [`didFailToLocateUserWithError:`](https://github.com/friedbunny/treble/blob/40f9f11b3a96a7150b6676ff2358d7c9f7efe387/treble/TRBLMapboxMapView.m#L156-L194) delegate method, for now. Should probably move in-house.

**Comment by friedbunny** [comment]
This may have been fixed by #1909, but I'm going to confirm that before closing this.

**Comment by friedbunny** [comment]
Nope, not fixed.

**Comment by friedbunny** [comment]
The problem here is that the demo app is trying to [`restoreState:`](https://github.com/mapbox/mapbox-gl-native/blob/77893249fc8ea5e5f0a529d3f33a06a72b799972/ios/app/MBXViewController.mm#L105) on the first run, which is clobbering the [`.showsUserLocation = YES`](https://github.com/mapbox/mapbox-gl-native/blob/77893249fc8ea5e5f0a529d3f33a06a72b799972/ios/app/MBXViewController.mm#L52) permissions dialog.

It's generally good practice to delay asking for permissions or only do so when the user really needs/wants those permissions. As the permissions dialog blocks our map from loading, I'm going to set `.showsUserLocation = YES` some point later, after the map has loaded.

**Comment by friedbunny** [comment]
`mapViewDidFinishLoadingMap:` would be a good place to do this, except it's not hooked up — #2263.

**Comment by incanus** [comment]
I'm not generally into timers, but in the interest of simplicity, maybe just set `showsUserLocation = YES` a second after `viewDidAppear:`?
