### ISSUE TITLE
allow iOS per-frame callback

### ISSUE THREAD

**Issue by tomtaylor** [mapbox/mapbox-gl-native#1981]
I'd like to implement a fixed scale overlay view (a `CAShapeLayer`) on top of a `MGLMapView`. One that tracks the location of the underlying coordinates and positions itself accordingly. Specifically, I want to draw a line at a fixed screen distance away from and alongside a polyline annotation. 

The region change delegate methods let me do this, but they don't fire frequently enough, so the layer jitters as the map scrolls. Looking through the code I can see `glkView:drawInRect:`, which is used to update the user location annotation view.

Have you considered exposing an API to let me implement something similar myself? I'd consider a `MGLMapView` subclass, but there isn't a convenient hook into that that point in the drawInRect method.

**Comment by incanus** [comment]
Related: https://github.com/mapbox/mapbox-gl-native/issues/1125

This would basically need to happen right about [here](https://github.com/mapbox/mapbox-gl-native/blob/e1291fe094acfc93c4582ac6ae98703cc3dcb80c/platform/ios/MGLMapView.mm#L715) in the process, between drawing the GL frame and updating the `Transform`, which affects pixel/geo conversions thereafter.

**Comment by incanus** [comment]
Also would solve https://github.com/mapbox/mapbox-gl-native/issues/2045.

**Comment by 1ec5** [comment]
A combination of `-mapViewRegionIsChanging:` and `-mapView:regionDidChangeAnimated:` should actually keep your view in sync with the map; if not, that’s a bug. Otherwise, you certainly could subclass MGLMapView and override `-glkView:drawInRect:`, but make sure to call `super`’s implementation in that case. (You’ll probably need to declare that your subclass conforms to GLKViewDelegate, since MGLMapView does so privately.)

**Comment by 1ec5** [comment]
@tomtaylor, [`-[MGLMapViewDelegate mapViewDidFinishRenderingFrame:fullyRendered:]`](https://github.com/mapbox/mapbox-gl-native/blob/0d5d2a923b45c81f3830a60b8e8a45b64827e628/platform/ios/src/MGLMapView.h#L1112-L1116) should fire frequently enough for your use case, far more reliably than `-mapViewRegionIsChanging:` and `-mapView:regionDidChangeAnimated:`. The method isn’t documented because the `fullyRendered` parameter doesn’t work as expected yet. As of #4801, we’re using this callback to update MGLAnnotationViews’ positions on screen as the viewport changes.
