### ISSUE TITLE
Documentation Request: setup Mapbox Framework for development

### ISSUE THREAD

**Issue by quicklywilliam** [mapbox/mapbox-gl-native#2001]
I use Mapbox-gl-native for my project and I'm trying to build from source by embedding the mbgl xcodeproject. Is this a supported configuration? I've gotten it to work but not in a way that works cleanly. Is there some documentation on this somewhere?

**Comment by 1ec5** [comment]
Just the readme, I'm afraid. Basically you run `make iproj` and replace iosapp with your own project inside the resulting workspace. Inside Mapbox, we've tended to rely on prerelease tags that we publish via the podspec in master. When I'm developing and need to see GL inside a realistic application, as opposed to iosapp, I overwrite the pod with the results of `make ipackage`.

Solid documentation for this approach would be more than welcome, although the CocoaPods and binary approaches detailed at http://www.mapbox.com/mapbox-gl-ios/ will probably continue to be favored over embedding the project.

**Comment by jfirebaugh** [comment]
@quicklywilliam Is there a particular reason you are trying to build from source rather than use CocoaPods or a binary release?

**Comment by quicklywilliam** [comment]
Thanks for the responses. We're trying to build from source because we've seen a number of bugs in switching to GL and we'd like to help fix them. We also have been using patches and hacks to work around some bugs while we wait for them to be fixed (or until we figure out how to fix them).

It's possible we will move back to using CocoaPods in the future, particularly once MapBoxGL and our own code base have stabilized.

Best,
William

**Comment by 1ec5** [comment]
See https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/INSTALL.md for instructions on integrating a locally-built Mapbox iOS SDK into your application.

We’ve since revamped our build system, so it isn’t necessary or possible to insert your project into a gyp-generated project or vice-versa any more. The SDK is now built inside an Xcode workspace, to which you can add your own projects. Or you can take ios.xcodeproj and the generated platform.xcodeproj and put them in your own workspace.
