### ISSUE TITLE
Crash installing MGLMapView in different view controllers — -[MGLMapView updateConstraints]

### ISSUE THREAD

**Issue by robipresotto** [mapbox/mapbox-gl-native#2020]
EXC_BAD_ACCESS

[NSLayoutConstraint deactivateConstraints:self.logoViewConstraints];

all the time if you are using singleton for the map view

**Comment by robipresotto** [comment]
version: https://github.com/mapbox/mapbox-gl-native/commit/ec7da43e85

**Comment by 1ec5** [comment]
Probably related to #1793.

**Comment by 1ec5** [comment]
> using singleton for the map view

@robipresotto, can you clarify what you mean by this? Do you mean a singleton in the programming sense, or in the sense of a standalone view in a storyboard or XIB?

**Comment by 1ec5** [comment]
The issue is that `logoViewConstraints` is stale and includes some constraints that no longer apply after the view was removed from the first view controller. The approach we take for the compass container will fix the crash; the trick is simply to make sure that the logo view retains the two constraints it needs to keep its intrinsic size.

**Comment by picciano** [comment]
This is working now. Thanks!
