### ISSUE TITLE
depthMask turned on during translucent phase for Fill Buckets (Feature or bug).

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#2028]
Can some one please clarify why we turn on depthMask during translucent phase for FillBuckets? Wouldn't it overwrite pixels at higher z depth drawn during the opaque phase?

**Comment by ansis** [comment]
The depth buffer is turned on to prevent the antialiasing outline from overlapping the polygon. 

Polygons are antialiased by drawing a 2 fragment wide line. One half of the line overlaps with the polygon. The outline is drawn with a [higher z value](https://github.com/mapbox/mapbox-gl-native/blob/3cc55a9dacf2c0984ca277500b334c3f44fa60c0/src/mbgl/renderer/painter_fill.cpp#L147) so that fragments that overlap the polygon fill are dropped.

The opaque pass happens before the translucent pass so it doesn't block anything there.
