### ISSUE TITLE
eglChooseConfig() returned no configs crash (propagate error to java instead of crashing).

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#2144]
While testing on emulator running ICS(4.0), I hit this crash.

1.) Is it possible to give this error in java instead of crashing?
2.) Is there any guideline on when emulator is expected to have opengl support and when its not? I created an AVD with API level 17 and opengl works. But with API level 14 it does not work on emulator.
3.) Is it possible to propagate all std::runtime_error esp. in native_map_view.cpp to java side instead of crashing? 

```
I/mbgl    ( 1615): {Main}[Android]: nativeGetAccessToken
I/mbgl    ( 1615): {Main}[Android]: nativeInitializeDisplay
D/libEGL  ( 1615): Emulator without GPU support detected. Fallback to software renderer.
D/libEGL  ( 1615): loaded /system/lib/egl/libGLES_android.so
I/mbgl    ( 1615): {Main}[OpenGL]: EGL Vendor: Android
I/mbgl    ( 1615): {Main}[OpenGL]: EGL Version: 1.4 Android META-EGL
I/mbgl    ( 1615): {Main}[OpenGL]: EGL Client APIs: OpenGL ES
I/mbgl    ( 1615): {Main}[OpenGL]: EGL Client Extensions: EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_fence_sync EGL_ANDROID_image_native_buffer EGL_ANDROID_swap_rectangle EGL_NV_system_time 
W/mbgl    ( 1615): {Main}[Android]: In emulator! Enabling hacks :-(
E/mbgl    ( 1615): {Main}[OpenGL]: eglChooseConfig() returned no configs.
F/libc    ( 1615): Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1)
I/DEBUG   (   34): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (   34): Build fingerprint: 'generic/sdk/generic:4.0.2/ICS_MR0/229537:eng/test-keys'
I/DEBUG   (   34): pid: 1615, tid: 1615  >>> com.mapbox.mapboxgl.testapp <<<
I/DEBUG   (   34): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr deadbaad
I/DEBUG   (   34):  r0 deadbaad  r1 00000001  r2 40000000  r3 00000000
I/DEBUG   (   34):  r4 00000000  r5 00000027  r6 001b4ed8  r7 434c4e47
I/DEBUG   (   34):  r8 fffff078  r9 00003038  10 00012820  fp bee660e8
I/DEBUG   (   34):  ip ffffffff  sp bee660b0  lr 4001f121  pc 4001b880  cpsr 60000030
I/DEBUG   (   34):  d0  0000000440800000  d1  3ff0000040800000
I/DEBUG   (   34):  d2  437e8000000000fe  d3  000000003f000000
I/DEBUG   (   34):  d4  000001fd00000000  d5  3fe999999999999a
I/DEBUG   (   34):  d6  3ff0000000000000  d7  3f8000003f800000
I/DEBUG   (   34):  d8  0000000000000000  d9  0000000000000000
I/DEBUG   (   34):  d10 0000000000000000  d11 0000000000000000
I/DEBUG   (   34):  d12 0000000000000000  d13 0000000000000000
I/DEBUG   (   34):  d14 0000000000000000  d15 0000000000000000
I/DEBUG   (   34):  scr 60000012

```

**Comment by ljbade** [comment]
There seem to be many bugs I have encountered when using older API levels with OpenGL in the emulator. These seem to be fixed in later releases.

You will even see a few workarounds in there where I check if we are running in an emulator:
`W/mbgl    ( 1615): {Main}[Android]: In emulator! Enabling hacks :-(`

**Comment by ljbade** [comment]
The main reason for this crash is:
`Emulator without GPU support detected. Fallback to software renderer.`

In which case the emulator literally returns no configs because it can't load the driver.

I have tried to catch C++ errors and pass them to Java before, but this resulted in more problems then it fixed, particularly when trying to debug crashes. https://github.com/mapbox/mapbox-gl-native/issues/562

In any JNI project you have to accept there will be crashes in the native code that do not result in a nice Java exception. There will even be parts of the Java library where the native code might have a runtime error and not be able to return a Java exception.
