### ISSUE TITLE
samples and sampleBuffers in NativeMapView::chooseConfig (Question)

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#2145]
Can someone please comment on the following check in chooseConfig.

```
 configOk &= sampleBuffers == 0;
 configOk &= samples == 0;
```

Should this condition be relaxed  to 'sampleBuffers >= 0" and 'samples >= 0' and give priority to lower samples and buffers when sorting eligible configs? I've verified that the application works correctly even when I forced it to pick samples==1.  Are we always guaranteed to get an EGLConfig with 0 samples and 0 sampleBuffers even though we are not including EGL_SAMPLES or EGL_SAMPLE_BUFFERS in the attribList passed to eglChooseConfig?

**Comment by ljbade** [comment]
Every GPU supports no sample buffers (basically no anti-aliasing). But I will double check the assumption for `EGL_SAMPLES` in `attribList`

**Comment by mb12** [comment]
@tobrun Can you please clarify why you think the condition shouldn't be relaxed as suggested?

**Comment by tobrun** [comment]
@mb12:
I closed this issue as a part of cleanup in the issue tracker. 

The reason why I closed this is that @ljbade didn't take any actions on this and if I understood @ljbade correctly this will not change any behaviour since every GPU supports no sample buffers.

if you feel this would be a good addition feel free to reopen this issue and PR these changes. 

We at Mapbox :heart: PR's.
