### ISSUE TITLE
Opening control center during pan animation causes map to disappear

### ISSUE THREAD

**Issue by bmeine** [mapbox/mapbox-gl-native#2158]
I've only tested this on a physical device with iOS 7.1 using the sample app.

To reproduce:
-Zoom in far enough that you have plenty of panning room (max or close to it)
-Start panning very fast from bottom to top
-During one of the rapid upward swipes, start your finger below the screen so it brings up the control center
-The control center opens and the map is gone...the Mapbox logo and attribution are still there

It seems to only happen if the control center is opened while the panning animation is still running.

**Comment by 1ec5** [comment]
MGLMapView throws up a snapshot of the map [upon receiving](https://github.com/mapbox/mapbox-gl-native/blob/3f99f5e712000f6b3b469c566e57ddd05dcff3e8/platform/ios/MGLMapView.mm#L352) a `UIApplicationWillResignActiveNotification` or `UIApplicationDidEnterBackgroundNotification`, to avoid making OpenGL calls in the background (which causes crashes). The snapshot taken during animation can sometimes be behind or omit some tiles.

We added the `UIApplicationWillResignActiveNotification` because we were still seeing background-drawing crashes. However, that was probably #1460, fixed in #1869, so we should double-check whether snapshotting on `UIApplicationWillResignActiveNotification` is still required.

**Comment by 1ec5** [comment]
(The same behavior occurs with Notification Center or any modal alert.)

**Comment by incanus** [comment]
Another option here would be to `cancelAnimations()` upon receiving the signal?

**Comment by 1ec5** [comment]
#2309 is an attempt at fixing this issue.
