### ISSUE TITLE
MGLUserTrackingModeFollowWithCourse is requesting heading updates needlessly 

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#2180]
Maybe a minor thing, but when the user tracking mode is set to `MGLUserTrackingModeFollowWithCourse`, I don't think we should be requesting heading updates from the location manager.

MGLMapView.mm lines 2317-2334
```
        case MGLUserTrackingModeFollowWithHeading:
        case MGLUserTrackingModeFollowWithCourse:
        {
            self.showsUserLocation = YES;

            if (self.zoomLevel < self.currentMinimumZoom) [self setZoomLevel:self.currentMinimumZoom animated:YES];

            if (self.userLocationAnnotationView)
            {
                [self locationManager:self.locationManager didUpdateLocations:@[self.userLocation.location]];
            }

            [self updateHeadingForDeviceOrientation];

            [self.locationManager startUpdatingHeading];

            break;
        }
```

**Comment by 1ec5** [comment]
Good catch.

**Comment by pushian** [comment]
Why do we want to disable heading update for MGLUserTrackingModeFollowWithCourse? In Google MAP, the heading update is also updated for .FollowWithCourse

**Comment by 1ec5** [comment]
If the user location annotation isn’t using the heading for anything in `MGLUserTrackingModeFollowWithCourse`, then it’s wasteful to track heading updates. If you’re looking to receive location updates in your own code, implement your own CLLocationManager instead of relying on the stock `-[MGLMapViewDelegate mapView:didUpdateLocation:]`. Implementing an additional CLLocationManager with similar settings won’t add any appreciable overhead.
