### ISSUE TITLE
Check size, Number of tiles before download

### ISSUE THREAD

**Issue by akapoor-ari** [mapbox/mapbox-gl-native#2218]
Note: Offline maps / Maps download needs to be supported in Android GL SDK for this issue. This is dependent on https://github.com/mapbox/mapbox-gl-native/issues/584

This is a feature request for Mapbox GL Android SDK to support interfaces to allow user to know the size and number of tiles for an ROI before starting the download. In the Mapbox raster SDK it was observed that number of tiles are returned only after the download starts and there was no way to get the size of the download.

**Comment by jfirebaugh** [comment]
This is not strictly possible as requested: in order to know the number of tiles required, it is necessary to first download the Style JSON and the TileJSON for all tile sources.

However, the APIs exposed in #3715 will calculate the number of required tiles once those resources have been downloaded, and at that point you can deactivate the download.

**Comment by jfirebaugh** [comment]
Estimating the total size is #3890.
