### ISSUE TITLE
Move HTTP caching to Java

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2231]
Either via OkHTTP's built-in [`Cache`](http://square.github.io/okhttp/javadoc/com/squareup/okhttp/Cache.html) or implementing our current SQLite cache using the Android platform [`SQLiteDatabase`](http://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html)

Follows on from #823 so we can implement all of `FileSource` in Java. This allows us to drop the native sqlite dependency.

**Comment by tobrun** [comment]
This landed with #2857, closing

**Comment by jfirebaugh** [comment]
This ticket is basically about a native implementation of `SQLiteCache`, or some other means of removing the native SQLite dependency for Android, so it wasn't fixed with #2857. However, given how offline is shaping up I'm skeptical that we'll ever want to do that, so it's fine with me to leave it closed.
