### ISSUE TITLE
Use @NotNull and @Nullable

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2242]
We should use `@NotNull` and `@Nullable` where applicable on all public Java API to ensure IDE picks up incorrect use.

**Comment by tobrun** [comment]
Completely agree with @NonNull, but while implementing the lollipop constructor I had the feeling that the @Nulllable was doing more harm than good. It was cluttering the code and it would never generate an actual lint warning. Only benefit I'm seeing is for documentation and code completion purposes.

**Comment by ljbade** [comment]
@tobrun Does the Android platform use `@Nullable` or just `@NonNull`?

**Comment by tobrun** [comment]
I'm seeing 40 ```@Nullable``` and 14 ```@NonNull``` occurrences in Activity source code of Lollipop. In the support library they are using them rarely (mostly for bundles or listeners). I would love to see what they have done in ioshed 2015 but they haven't released it yet. 

While thinking this a bit through. I have come to the conclusion that constructor arguments should not be annotated. They are by default non-null due to dependency they have with the created object. If more or less dependencies are possible then the object should be exposing more/less constructors.

For method arguments I find   ```@Nullable ``` great. It defines the argument as optional.
As return type it is also useful because it implies that referenced type is bound to the state of object (it can also be used to indicate not-implemented methods). 

I'm not a big fan of ```@NonNull```for method arguments. Because this indicates that you are not properly handling null values. The following is valid:

  ```java
    public void removeAnnotation(@NonNull Annotation annotation) {
 		long id = annotation.getId();
		mNativeMapView.removeAnnotation(id);
 		mAnnotations.remove(annotation);
	}
  ```


But I rather see this

  ```java
   public void removeAnnotation(Annotation annotation) {
 		if(annotation!=null){
           long id = annotation.getId();
		   mNativeMapView.removeAnnotation(id);
 		   mAnnotations.remove(annotation);
        }
	}
  ```

@bleege @ljbade Would love to hear your input. Will implement the annotations based on that.

Btw This was only about NonNull and Nullable, other Android Annotations should also be implemented. Eg. ```@DoubleRange``` for zoomlevel.

**Comment by bleege** [comment]
> I'm not a big fan of @NonNull for method arguments. Because this indicates that you are not properly handling null values.

Totally agree.  We're using `@NonNull` strictly for IDE feedback that Android Studio provides.  In other words increase the amount of help the IDE can give SDK developers during SDK development.  The thinking is this could be helpful as the SDK grows in size.  _`null` checks still need to be done in the method bodies._  Maybe this is leading to more confusion that it's worth however?

TBH, I'm not a big fan of annotations to begin with because it's super easy for them to get out of control.  They also, as you mentioned, can indicate that certain things are not being properly handled.

**Comment by ljbade** [comment]
I'm implementing theese and the null checks as I work through #2002

**Comment by ljbade** [comment]
Hmm do we need to copy over annotations from overidden view functions.

**Comment by tobrun** [comment]
If we are calling super we should add them. The enforcement of these requirements are still viable. 

FYI:
I must mention that it not always possible to add them, for example see annotations from Visibility. These are retained, so not usable outside of the platform sources.

```java
/** @hide */
    @IntDef({VISIBLE, INVISIBLE, GONE})
    @Retention(RetentionPolicy.SOURCE)
    public @interface Visibility {}
```
