### ISSUE TITLE
Ensure correct version number

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2275]
A few places we should double check we use correct version number in the 0.1.0 release.

In Gradle:
- https://github.com/mapbox/mapbox-gl-native/blob/master/android/java/MapboxGLAndroidSDKTestApp/build.gradle#L52-L53 (might also reset the `versionCode` to 1)
- https://github.com/mapbox/mapbox-gl-native/blob/master/android/java/MapboxGLAndroidSDK/gradle.properties#L2
- `version.hpp` - should be picked up from the git tag
- any other places?

**Comment by ljbade** [comment]
@bleege You going to hit this before final `0.1.0` release?

**Comment by bleege** [comment]
@ljbade Thanks for flagging this, but these numbers will only need to be changed once we're satisfied with the SNAPSHOT release.  If we removed the `SNAPSHOT` now it would causes human confusion as well as computer confusion as the build scripts would try to publish it to the distribution channel of the Sonatype Repository and not the SNAPSHOT channel.

**Comment by bleege** [comment]
Updated https://github.com/mapbox/mapbox-gl-native/blob/master/android/java/MapboxGLAndroidSDK/gradle.properties#L2 as that's what controls the built artifact.

Did not update the TestApp https://github.com/mapbox/mapbox-gl-native/blob/master/android/java/MapboxGLAndroidSDKTestApp/build.gradle#L52-L53 as it's used only for development purposes and isn't involved with releasing at all.

I don't see a `version.hpp` in the source code, but I'll ask about it before considering this done.

**Comment by bleege** [comment]
I asked @kkaefer about `version.hpp` and he told me that it's [actually generated by a script called `build-version.py`](https://github.com/mapbox/mapbox-gl-native/blob/master/scripts/build-version.py).  It also has to do with the Core GL and not the bindings (aka iOS, Android, etc).

The only real issue with it is that this version will still [be pulled from tags](https://github.com/mapbox/mapbox-gl-native/blob/master/gyp/version.gypi#L16), which could be "slightly problematic since we have multiple conflicting tags and it’ll just use the most recent one which currently is node-v2.0.0-pre.7".  That said, as long as tags are known and will continue to exist it's not as big of an issue.

**Comment by ljbade** [comment]
@bleege ah yeah we should do something about how version.hpp works so we can use it for things like user agent

**Comment by kkaefer** [comment]
See #2275

**Comment by ljbade** [comment]
@kkaefer wrong ticket number?

**Comment by ljbade** [comment]
Ah you meant: https://github.com/mapbox/mapbox-gl-native/issues/2430

**Comment by kkaefer** [comment]
Yes, thanks!
