### ISSUE TITLE
iOS test failure: testCompassTap, ((tester.mapView.direction) equal to (0)) failed: ("217.430747715") is not equal to ("0") - tapping compass should reset map direction

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#2347]
https://travis-ci.org/mapbox/mapbox-gl-native/jobs/80715437

If we don't have any leads on fixing this, let's disable the test.

cc @incanus @1ec5 @friedbunny

**Comment by friedbunny** [comment]
Tests that are failing on Travis that _should not be failing_ and never fail locally:

- `testDirectionSet`
- `testCompassTap`
- `testDirectionReset`
- `testCenterSet`

Given that I can't find anything actual wrong with any of these features or the tests themselves, I'm going to see what happens when all of them are disabled on Travis. I suspect that Travis will find something else to fail.

**Comment by friedbunny** [comment]
Yup, `testDelegateRegionDidChange` [started failing](https://travis-ci.org/mapbox/mapbox-gl-native/jobs/81083416) after those four tests were disabled.

**Comment by incanus** [comment]
Fascinating.

**Comment by friedbunny** [comment]
I've got one run to pass after disabling `testDelegateRegionDidChange`, too — will it pass twice in a row?!

**Comment by friedbunny** [comment]
OK, four passes. Going to squash and PR.
