### ISSUE TITLE
Publish a platform specific binary whenever a version tag is pushed

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-native#2365]
I forgot to add `[publish binary]` to a npm version bump commit and had to push https://github.com/mapbox/mapbox-gl-native/commit/b81f7967134d5404950c693caaeebe177b92e1b3 (which I'm not proud of).

Would it make sense to publish a node-pre-gyp binary whenever a tag that starts with "node-" is pushed? This should be a relatively simple addition to https://github.com/mapbox/mapbox-gl-native/blob/master/scripts/node/after_script.sh#L15. We can preserve the existing behavior too.

**Comment by mikemorris** [comment]
I tend to bump version and commit, tag, edit the commit to add `[publish binary]` (so Travis doesn't try to publish twice) then `git push && git push --tags`

**Comment by lucaswoj** [comment]
> Open to this if we can prevent Travis trying to publish twice.

I imagine there is / should be protection from overwriting a published binary.

Alternately, we _could_ remove the existing behavior (adding `[publish binary]` to a commit message). Are there any cases where we'd want to publish a binary without a git tag?

**Comment by lucaswoj** [comment]
Changed the title issue title to reflect an expansion in scope. We should look into this as a cross platform feature.

**Comment by incanus** [comment]
I think part of my hesitation to do this originally was load on Travis. But I like this otherwise.

**Comment by incanus** [comment]
> Are there any cases where we'd want to publish a binary without a git tag?

Not for iOS, and I don't see foresee any for Android, though we don't have things automated over there yet due to some crypto stuff, maybe more /cc @bleege 

Related here, would be awesome to maybe also hit https://github.com/mapbox/mapbox-gl-native/issues/1349 for all of our platforms as well. We pop iOS ones up there (like at https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v2.1.2) and that'd be a nice reference point. Eventually, we could probably skip having these on S3 as well.

**Comment by bleege** [comment]
I would love to have an automated publish system for Android.  That said it's not feasible at this moment due to the current build process setup as well as the need for secure crypto storage for signing and distributing to the Sonatype Central Repository.  This also has to do with likely moving Android off of Travis CI as well as [getting the C++ stuff integrated within Android](https://github.com/mapbox/mapbox-gl-native/issues/1753).

**Comment by mikemorris** [comment]
Implemented for node in https://github.com/mapbox/mapbox-gl-native/pull/2944
