### ISSUE TITLE
iOS user location annotation should not be pulsing until location locked 

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#2439]
When we added the accuracy circle, we seem to have introduced the behavior that you can see both it and the pulsing halo, which is not right. You should only see the pulsing halo when the accuracy circle disappears. 

/cc @friedbunny @1ec5

**Comment by friedbunny** [comment]
[Here's where we show/hide the halo](https://github.com/mapbox/mapbox-gl-native/blob/6d357eb0c87897ef99926a4b2b12d0ae3354e7d8/platform/ios/MGLMapView.mm#L2721-L2722) in `MGLMapView`'s location update code — the accuracy threshold is 10 meters, which may be too large for devices without GPS.

We show both the accuracy circle and the pulsing halo when the accuracy is <10 meters, like Apple does here:

![apple-halo 7 04 19 pm](https://cloud.githubusercontent.com/assets/1198851/10151353/c4d995a6-6614-11e5-8ae0-52891c1344e9.gif)

Going to close because is behaving as intended... for now.
