### ISSUE TITLE
Add setOnInfoWindowClickListener() 

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2448]
Needed for parity with Google Maps, they expose a method setOnInfoWindowClickListener on MapView, Our current implementation uses a method directly on Marker:

```java
  marker.setInfoWindowOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View view, MotionEvent motionEvent) {
                Toast.makeText(getApplicationContext(), "Custom Info Touch Listener!!", Toast.LENGTH_SHORT).show();
                marker.hideInfoWindow();
                return true;
            }
        });
```

**Comment by bleege** [comment]
@tobrun I don't see the method `setOnInfoWindowClickListener()` in the [Google Map MapView API](https://developers.google.com/android/reference/com/google/android/gms/maps/MapView).  I do see it on the [`GoogleMap` class however](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.html#setOnInfoWindowClickListener%28com.google.android.gms.maps.GoogleMap.OnInfoWindowClickListener%29).  Since the Mapbox SDK doesn't currently have a corresponding "MapboxMap" object but instead relies on direct access to `MapView` I don't think we need to implement this now.

Let's close this for now and re-open it in the future if / when the "MapboxMap" concept is built.  As part of that I'm going to move the [first commit I made on a dev branch](https://github.com/mapbox/mapbox-gl-native/commit/b990d31ae3184da903fc5b426ea980f3d85c4cc4) (regarding moving InfoWindow classes to annotations package) to a different ticket.

**Comment by ljbade** [comment]
@bleege The Google MapView/MapFragment are very thin shim classes that expose all their functionality in `GoogleMaps`. I don't see why we would need a `MaboxMap` class first. Perhaps we can just leave this for 2.2.0?

**Comment by bleege** [comment]
@ljbade Technically yes, but if our goal is to mirror the Google Maps API how does this help?

**Comment by ljbade** [comment]
@ljbade well we can add all theese to MapView, then in 3.0.0 or whatever we call it after the refactor, everything that is in MapView currently (at least all the `public` methods), will be moved to `MapboxMap`. And `MapView` will have a single method `getMapAsync()`

**Comment by ljbade** [comment]
Hitting this in https://github.com/mapbox/mapbox-gl-native/issues/2546

**Comment by bleege** [comment]
This is being moved to `android-v2.2.0` per https://github.com/mapbox/mapbox-gl-native/issues/2546#issuecomment-148726940
