### ISSUE TITLE
Passing null in MarkerOptions.sprite results in crash

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2460]
```java
new MarkerOptions()
                .position(new LatLng(lat,lng))
                .title(title)
                .sprite(null)
                .snippet(snippet)
                .getMarker();
```
In case of null, we should provide fallback on "default_marker"

**Comment by ljbade** [comment]
Yeah that makes sense,

**Comment by ljbade** [comment]
Let's implement and document this in #2002

**Comment by ljbade** [comment]
Implemented this in #2440. `null` sprite will load the new red default marker. However it is drawn really huge due to shortcomings in the core API.

In the meantime while waiting for a scaling fix, `"default_marker"` will continue to work nicely as long as styles submodule is not updated. (see #2106)

**Comment by ljbade** [comment]
I changed the `null` behaviour to use `"default_marker"` instead of the large red marker. Will change this back after #2106

**Comment by bleege** [comment]
This was addressed in https://github.com/mapbox/mapbox-gl-native/issues/2535 today.
