### ISSUE TITLE
Not setting a style results in blank Map

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2463]
We are not informing the end developer that setting a style is required.
 - provide a default style?
 - implement logging/exception to inform end developer?

**Comment by tobrun** [comment]
Same case for entering a not valid url

**Comment by ljbade** [comment]
There should be some stuff in the log from the C++ side.

Problem we have is setting style is async, we don't know URL is bad until sometime after we return from `setStyleURL`.

I used to have a basic URL validity check in the Java side that threw an exception, but caused more issues than it fixed.

**Comment by ljbade** [comment]
I'm documenting that `null` will load the default style in #2002 so going to have to implement this for v2.0.0

**Comment by ljbade** [comment]
Also the failed loading onMapChange event should be fired.

**Comment by tobrun** [comment]
@bleege 
is this issue actionable? 
Should we load a default style in those cases?

I noticed this use-case on current master

- open Activity with a map but not calling setStyle
- blank Map
- rotate device
- Mapbox Streets style is loaded

**Comment by bleege** [comment]
Setting a style is part of the [setup process](https://www.mapbox.com/android-sdk/examples/) (along with an Access Token) so seeing a blank map seems like a good "error message".  I'm open to be convinced otherwise though.  ;-)

The reason for the Mapbox Streets in the TestApp after rotation is due to it being set as [the default value in the Activity for state tracking](https://github.com/mapbox/mapbox-gl-native/blob/c10f6489e61a52e3ae36af7cd2c40d120f9181da/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java#L73).  This then [gets set in `onStateSave()`](https://github.com/mapbox/mapbox-gl-native/blob/c10f6489e61a52e3ae36af7cd2c40d120f9181da/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java#L266) and then [loaded in `onCreate()` during rotation](https://github.com/mapbox/mapbox-gl-native/blob/c10f6489e61a52e3ae36af7cd2c40d120f9181da/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java#L197).  This won't happen in the SDK on it's own.
