### ISSUE TITLE
Memory churn when location tracking is enabled

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2577]
Memory usage when app is idle and location tracking is disabled:
![screen shot 2015-10-09 at 12 35 27](https://cloud.githubusercontent.com/assets/2151639/10391881/3f97b10e-6e82-11e5-8e46-b92ebd88e8d6.png)

Memory usage when app is idle and location tracking is enabled:
![screen shot 2015-10-09 at 12 32 52](https://cloud.githubusercontent.com/assets/2151639/10391840/feaefdfa-6e81-11e5-95f7-edf56fdd00cc.png)

**Comment by ljbade** [comment]
Cool I've never used that before. Lets have a look.

**Comment by ljbade** [comment]
The memory usage also creeps us slowly when just gesturing the map.

**Comment by ljbade** [comment]
Hmm after playing around a bit I now even see memory usage increasing while idle?

**Comment by ljbade** [comment]
Using the track allocations button I realised the memory churn when idle was caused by the GPU profiler being enabled.

**Comment by ljbade** [comment]
@tobrun It's the `onSensorChanged` from `CompassView`. We need to rate limit the sensor updates.

**Comment by ljbade** [comment]
Specifically the `new GeomagneticField`. Should reuse that object.

**Comment by ljbade** [comment]
Unfortunately you can't reuse it :-(

**Comment by ljbade** [comment]
Looking at http://developer.android.com/reference/android/hardware/SensorManager.html#registerListener(android.hardware.SensorEventListener,%20android.hardware.Sensor,%20int,%20android.os.Handler)

API 9 and onwards you can specify a rate in microseconds for sensor updates to be delivered instead of `SENSOR_DELAY_UI` which we currently use. Lets set this to 1 second.

Also from API 19 and onwards you can use http://developer.android.com/reference/android/hardware/SensorManager.html#registerListener(android.hardware.SensorEventListener,%20android.hardware.Sensor,%20int,%20int,%20android.os.Handler) to enable event batching to reduce CPU interrupts and battery drain. This might not be needed if we rate limit to 1 second.

**Comment by ljbade** [comment]
@tobrun Let me know what you think of the commit ^

I rate limit to one second both in `registerListener` and the handler, since Android was still sending events faster than once per second.

It reduces the rate of memory consumption, but does not stop it due to the inability to reuse GeomagneticField.

**Comment by ljbade** [comment]
@bleege I set the 2.1.0 milestone as this should be fixed along side user tracking work.

@tobrun @bleege If we end up not implementing compass user tracking mode in 2.1.0 we should comment out the `registerListeners` code. If we do implement compass tracking mode, we should only enable sensor updates when we are actually in a compass tracking mode (not if just location or GPS only mode). Ref https://github.com/mapbox/mapbox-gl-native/issues/2049

**Comment by ljbade** [comment]
Hmm playing with Google Maps, we might need a faster update rate of perhaps 1/60 or 1/30 seconds.

In my commit ^ I set the update rate as a constant so very easy to increase this.

I am also thinking that when we implement the heading arrow on the GPS location dot in no or location only tracking mode, we should add a `setMyLocationHeadingEnabled` option. This would be enabled by default, but when disabled hide the arrow and also disable the sensor updates.

**Comment by tobrun** [comment]
@ljbade 
Awesome finds :+1: and you resolved one of the open todo's for #2049! :tada: 

> I am also thinking that when we implement the heading arrow on the GPS location dot in no or location only tracking mode, we should add a setMyLocationHeadingEnabled option. This would be enabled by default, but when disabled hide the arrow and also disable the sensor updates.

Current setup is not ideal yet. Will focus on making it work before tinkering with the details. I'm focussing on delivering it Monday for Sirius (so @bleege can rol a new SNAPSHOT). Afterwards we can easily change small details for end-developers needs.

**Comment by tobrun** [comment]
@ljbade just an idea, 
maybe we can subclass GeomagneticField in a way to make it reusable?

**Comment by ljbade** [comment]
@tobrun Yeah that might be possible...

**Comment by bleege** [comment]
This is all good to know and something we should stay on top of.  Let's finish the rest of `android-v2.1.0` first as originally planned.  After the user tracking functionality is completed in #2049 we can reassess / review what the performance looks like then.  Based on the knowledge at that time we can determine whether or not we feel confident in shipping user tracking in `android-v2.1.0`.

I'm going to leave this as part of `android-v2.1.0` milestone for now so that we remember to come back to it for review after #2049 and the remaining tasks are complete.

**Comment by ljbade** [comment]
I'm going to make a PR for the release branch that comments out the compass sensor so we avoid memory church and battery use. This is in-case the user location tracking #2049 does not make it into 2.1.0

**Comment by ljbade** [comment]
In the PR I'll also include the fix for the location marker not being in the right place.

**Comment by ljbade** [comment]
@tobrun Quick heads up about the last two comments ^
This is only in case your #2049 doesn't make it in so we at least fix the two existing bugs.

@bleege If #2049 isn't ready in time for v2.1.0, merge this PR into the release branch before your next Sirius SNAPSHOT builds.

**Comment by tobrun** [comment]
@ljbade @bleege 
I did some more cherry picking from that user location branch.
I left bearing out for now.
