### ISSUE TITLE
Remove styleID property; replace with style URL inspectable

### ISSUE THREAD

**Issue by petaren** [mapbox/mapbox-gl-native#2628]
I'm trying to use a custom map in the iOS SDK. I have tried typing out the styleID in interface builder like this:
![interfacebuilder image](https://cloud.githubusercontent.com/assets/3486895/10511502/ecc17b4c-7339-11e5-9dd2-580c497f5048.png)

But that gives me the error message: `[ERROR] {Map}[Setup]: loading style failed: HTTP status code 404`

I have tried setting it in code too with the same error and tried numerous different styles.

**Comment by 1ec5** [comment]
The style ID should be just `moggen/9c5b2248`. Note that the iOS SDK only supports styles created in the new, vector-based Mapbox Studio, not Mapbox Studio Classic.

**Comment by petaren** [comment]
Still doesn't work. Just getting another error:
`[ERROR] {Map}[Setup]: loading style failed: HTTP status code 403`

**Comment by friedbunny** [comment]
Couple things:

1. As @1ec5 said, `moggen.9c5b2248` is a raster map that is not directly compatible with the [GL style spec](https://github.com/mapbox/mapbox-gl-style-spec). If you want to use this map as-is, it can be [loaded as a raster source in a GL style](https://www.mapbox.com/ios-sdk/examples/raster-styles/).
1. Presuming this was a GL style, access tokens must have access to the style you're trying to load — e.g., they should be from the same account.

**Comment by bsudekum** [comment]
@1ec5 wouldn't it makes sense that the method `setStyleUrl` and this input field accept the same values? eg: `mapbox://styles/user/id`

**Comment by incanus** [comment]
`setStyleUrl` = style URL
`styleID` = style ID part of style URL

More correct would probably be to change the IB field to be a style URL.

**Comment by bsudekum** [comment]
> More correct would probably be to change the IB field to be a style URL.

Yes

**Comment by 1ec5** [comment]
> More correct would probably be to change the IB field to be a style URL.

Interface Builder doesn’t support NSURLs as inspectables. That’s why the style ID property exists. We could have a “style URL string” property instead, but I don’t think that really solves any problems. You’d have to know the URL syntax, but the UI wouldn’t have any affordance to help you get it right.

**Comment by jfirebaugh** [comment]
The UI doesn't have any affordance to help you get the ID right either. I think we should make it a URL string, for consistency with the API.

**Comment by petaren** [comment]
Since I don't have access to our projects mapbox account I tried creating my own just to play around with and get working.

I have now registered a new account. In the web UI I have created a new project. In my Xcode project I have switched out the access token to my new accounts token. 
The new projects settings looks like this:
![projsettings](https://www.dropbox.com/s/61t53vy20rw2q7l/Screenshot%202015-10-15%2019.15.31.png?dl=0)
 
I have inputted the Map ID into Interface Builder in Xcode into the StyleId field as follows: `petered/nnaoffm2`
And I'm still getting: `[ERROR] {Map}[Setup]: loading style failed: HTTP status code 403`

**Comment by 1ec5** [comment]
@petaren, that’s the raster editor. As @friedbunny explained, you’ll need to create a GL style instead. The raster editor’s vector-based replacement, [Mapbox Studio](https://www.mapbox.com/mapbox-studio/), is currently in beta.

@jfirebaugh, for an Interface Builder user, the API should ideally be an implementation detail; it isn’t particularly important that the UI matches any programmatic API except where the inspectable technology forces our hand. That said, I’m trying to come up with ways to name the underlying property:

Current:

```objc
@property (nonatomic, nullable) IBInspectable NSString *styleID;
```
<img width="260" alt="styleid" src="https://cloud.githubusercontent.com/assets/1231218/10522169/a06a36c8-7328-11e5-86a5-607085e17d96.png">

We can’t rename the property `styleURL`, because that’s already taken for the NSURL. Cocoa naming conventions would have us call it `styleURLString`, which doesn’t fit:

```objc
@property (nonatomic, nullable) IBInspectable NSString *styleURLString;
```
<img width="260" alt="styleurlstring" src="https://cloud.githubusercontent.com/assets/1231218/10522241/0aee0326-7329-11e5-81da-17ad9426e375.png">

We’d want the inspectable to look like a URL bar. This is the best I’ve come up with so far, and I’m not sure whether to be proud or ashamed of it:

```objc
@property (nonatomic, nullable) IBInspectable NSString *styleURL__;
```
<img width="260" alt="styleurl__" src="https://cloud.githubusercontent.com/assets/1231218/10522410/d42948a4-7329-11e5-8855-928968b5e5fb.png">

Also note that by renaming or replacing this method, we’d be requiring all storyboard users to manually delete the “styleID” property from the User-Defined Runtime Attributes inspector and reenter the style URL. As a backwards-incompatible change, we’ll be bumping the version up to 3.0.0.

**Comment by petaren** [comment]
@1ec5 Ah! That explains it, I thought the web editor was the GL editor and that the Classic one was the raster. Do you guys happen to have any influence over who gets beta invitations to the GL editor or is there any other way for us to create a GL map?

**Comment by 1ec5** [comment]
@petaren, please sign up at https://www.mapbox.com/mapbox-studio/#start-designing.

**Comment by ljbade** [comment]
@jfirebaugh @1ec5 Just making a note that on Android I decided to use only setStyleUrl (and not ID) so in Sirius the custom style dialog just takes the full `mapbox://` URL just like the method.

**Comment by 1ec5** [comment]
#2632 removes the styleID property in favor of the styleURL property and an inspectable that looks like it's called styleURL. The change makes sense because Mapbox Studio consistently displays the full URL, never just the ID. Otherwise I would've preferred more concise input in IB.
