### ISSUE TITLE
~Actor<O> is blocking

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#2644]
When canceling a `WorkTask`, we block until that task has completed its entire invocation. This isn't something we should do. You can make this behavior more visible when adding a `sleep(4)` in a worker task, (e.g. in `TileWorker::parse()`). Panning fast now stalls heavily, as partial work requests are getting canceled.

/cc @jfirebaugh

**Comment by jfirebaugh** [comment]
This is by design. `WorkTask`s typically have references to objects which need to outlive the task, whose owner is in turn owning the task. If the task isn't canceled, then these lifetime invariants will not hold: the objects will be destroyed along with their owner, while the work task will continue running with dangling references.

**Comment by jfirebaugh** [comment]
Worker tasks should be designed to check a flag in inner loops and exit early if the flag indicates the task has been cancelled. Most do; the exception I see is `SymbolBucket`, which has no early exit for the loops in `needsDependencies` and `addFeatures`.

**Comment by tmpsantos** [comment]
> This is by design.

And I like the design here because protects us from bugs that are very difficult to debug that haunted us in the past. On #3636 suggested a special deleter for `TileData` that if turns out to be needed somewhere else we could make it more generic and call it `NonBlockerDeleter` and have a method like `::willBlockOnDestructor()` to postpone the deletion on objects with `WorkRequest`s.

**Comment by kkaefer** [comment]
This is resurfacing: When parsing tiles, we're checking a flag after parsing every feature whether we still need the tile. However, our landuse layer, in particular on zoom level 7, contains some *very* complex features that take > 1 second to parse in their call to clipper + libtess2. These tasks are not interruptible. We should do two things:

1. Make tile parsing cancellation non-blocking. This means that parsing a tile must not access resources shared with the main thread or other threads.
2. Refactor our landuse layer to avoid single polygons that are too complex

/cc @mourner

**Comment by jfirebaugh** [comment]
As of #6337 there's no cancellation of tasks, but destroying the actor can still block. We need #667 in order to remove that.

**Comment by jfirebaugh** [comment]
It should be safe to change this now.
