### ISSUE TITLE
Make URL normalization safe

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-native#2695]
https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/util/mapbox.cpp#L87-L90

All of the normalization methods in this file assume that `pathname` has the right arity before using parts of it constructing URLs. When it doesn't - when it's just a style id or something, or missing some chunk - then concatenating the strings leads to a malloc, as seen in http://stackoverflow.com/questions/33227894/how-do-i-show-a-map-from-a-mapbox-project-with-the-mapbox-ios-sdk

The methods should assert the correct arity before proceeding.

**Comment by ljbade** [comment]
@tmcw Yeah can we support this, I have tried to do it before on Java but was getting too complicated.

Also we need a way to return an error back via JNI instead of normal C++ exception which just crashes the app on Java with no way to provide a useful error message to developers.

Something like a `isStyleUrlValid()` function, or even some sort of `bool` or otherwise return from `setStyleUrl()`. Then we can throw on Java a helpfully named exception like `InvalidStyleUrlException`

Another alternative is to generate a `failedToLoad` event (see https://github.com/mapbox/mapbox-gl-native/issues/630 and https://github.com/mapbox/mapbox-gl-native/issues/2263)

@jfirebaugh what is your preference about sending the URL validation result back to Java?

**Comment by jfirebaugh** [comment]
The first step is to make this not crash: if the result from `getMapboxURLPathname()` has less segments than expected, `return url`.

Later we can add validation and diagnostic messages. These should probably happen at style parse time, with the rest of the validations.

**Comment by 1ec5** [comment]
→ #2804
