### ISSUE TITLE
write iOS metrics tests

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#2822]
Refs https://github.com/mapbox/mapbox-gl-native/commit/1421755434963cd4a35e7a4f757bf400f90528b7 and https://github.com/mapbox/mapbox-gl-native/pull/2769.

**Comment by 1ec5** [comment]
Blocked by #3155.

**Comment by 1ec5** [comment]
The non-UI, XCTest-based unit tests added to OS X in #3406 and to iOS in #4641 offer a way forward for this functionality. We should be able to mock user location and HTTP requests so that MGLMapboxEvents can operate more or less independently of MGLMapView. The tricky part will be managing MGLMapboxEvents’ lifecycle, since it’s a singleton.

**Comment by jfirebaugh** [comment]
Closing; this has been open for a long time without progress and isn't likely to happen.
