### ISSUE TITLE
Catch C++ exceptions before returning to JNI

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#2825]
Per #2804, the Android SDK suffers from a native crash any time there’s an uncaught C++ exception at the mbgl level. An uncaught exception there usually indicates developer error, so the Android SDK needs to present that error in a way that’s actionable without spelunking into mbgl code. The Android bindings cannot rely on an assumption that the C++ code won’t throw exceptions.

platform/android/jni.cpp needs to have C-style exception handling. For example, [`nativeSetStyleURL()`](https://github.com/mapbox/mapbox-gl-native/blob/f3ffb45cf6adbdca375217c645eb455ff47991ec/platform/android/jni.cpp#L563) should be wrapped in a try-catch statement. When an exception is caught, this function should return some kind of error code. For functions that already need to return a value, this would imply some kind of out parameter or a tuple-typed return value.

Though this could be a fair amount of work, it pays off in the form of Android bindings that can actually be debugged.

/cc @ljbade @bleege @jfirebaugh

**Comment by ljbade** [comment]
As discussed in slack a wrinkle with `nativeSetStyleURL` is that the invalid style URL error will be thrown from the map thread, not the UI thread, so adding a catch to `nativeSetStyleURL` will not work.

Instead we can take advantage of how Java checking JNI thrown Java exceptions. If we convert exception to Java exception in the map thread instead of killing the thread. Then when we next call into Java land (`View::invalidate`) the exception will be picked up and crash the app Java side with a useful message.

We also need to log the C++ exception stack trace to logcat first so that in the log we have both the original stack trace, and the new Java one which will point to `invalidate()`

**Comment by ljbade** [comment]
@1ec5 Historic context on my previous attempt at C++ exception handling:
https://github.com/mapbox/mapbox-gl-native/issues/562

**Comment by ljbade** [comment]
@1ec5 Should we also open a iOS ticket for iOS exception handling? Will help in https://github.com/mapbox/mapbox-gl-native/issues/2775#issuecomment-150829090

>  I don't believe iOS has any direct way of knowing if a style has failed to load.

**Comment by 1ec5** [comment]
@ljbade, once #2762 is fixed, iOS will get such notifications for free.

**Comment by bleege** [comment]
> once #2762 is fixed, iOS will get such notifications for free.

The joys of living in an all C++ world.  :smiley:
