### ISSUE TITLE
Try OkHTTP on Android again

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2856]
Time to try https://github.com/mapbox/mapbox-gl-native/pull/2033 again and use OkHTTP instead of curl for Android.

Previous blocker for this was https://github.com/mapbox/mapbox-gl-native/issues/2400 which has not been looked at for a while.

Things that might have fixed that crash:
- updating libuv - https://github.com/mapbox/mapbox-gl-native/pull/2609
- refactor in the core GL HTTP code - https://github.com/mapbox/mapbox-gl-native/pull/2617

OkHTTP will be an enabler for offline support.

/cc @bleege @tobrun

**Comment by ljbade** [comment]
We will need to perform extended testing over a period of time as #2400 was a rare and hard to reproduce reliably.

Perhaps a Sirius build with this change included will provide the confidence needed.

**Comment by ljbade** [comment]
Simply switching `config.mk` to the Android HTTP implementation, reveals bit rot in `http_request_android.cpp` due to refactors.

**Comment by mb12** [comment]
@ljbade The only advantage of this is  reduced .apk size. Its no longer an issue on Android (since apk size limit has been doubled). Why do we want to change this if curl implementation does not have any bugs?

**Comment by ljbade** [comment]
After fixing the compile errors, the OkHTTP stack is working again. So far I have not been able to reproduce #2400 but more testing is needed.

**Comment by bleege** [comment]
> Why do we want to change this if curl implementation does not have any bugs?

@mb12 The big reason is as you mentioned, a reduced `.aar` and `.apk` sizes.  Not having to compile it for `N` ABI really helps keep things svelte.  Another reason is to use more platform specific implementations (in this case Java for Android) as it is more accessible to developers.

**Comment by bleege** [comment]
For future reference, by replacing curl with OkHttp the Mapbox Android Library .aar file goes from ~11 MB to ~7.8 MB.

![curl](https://cloud.githubusercontent.com/assets/989928/11036718/d043b9b4-86bf-11e5-85c9-f55202f26a60.png)
_Mapbox Android SDK 2.2.0 with curl_

![okhttp](https://cloud.githubusercontent.com/assets/989928/11036725/d5cdbb96-86bf-11e5-9c20-0a6c949c37ee.png)
_Mapbox Android SDK 2.3.0-SNAPSHOT with OkHttp replacing curl_

The size of OkHttp and it's dependency Okio combine to be about ~375 KB so that the net result is a **~2.825 MB overall decrease in size by replacing curl with OkHttp**.

![okhttp-library](https://cloud.githubusercontent.com/assets/989928/11036865/7b4c4fa6-86c0-11e5-8a9e-48012b540e1e.png)
_OkHttp Library_

![okio-library](https://cloud.githubusercontent.com/assets/989928/11036874/83cd6b56-86c0-11e5-83a0-dcaa84969819.png)
_Okio Library_
