### ISSUE TITLE
MAPBOX_ACCESS_TOKEN on Linux not working

### ISSUE THREAD

**Issue by bessermt** [mapbox/mapbox-gl-native#2974]
I was trying to build the MapboxGLAndroidSDKTestApp and in the instructions it said to set the environment variable MAPBOX_ACCESS_TOKEN as described in:

https://github.com/mapbox/mapbox-gl-native/blob/master/docs/DEVELOP_ANDROID_LINUX.md

This did not seem to create the file:

android/java/MapboxGLAndroidSDKTestApp/src/main/res/raw/token.txt

as described. Was there something more I should have done? Can someone check this works? I see the build script, but I'm new with gradle and so I'm not sure how to best debug it. I added the res/raw/token.txt file by hand and that seemed to work, but will this cause trouble elsewhere if I'm missing the environment variable?

**Comment by 1ec5** [comment]
The token.txt is probably sufficient, but @bleege would know for sure.

**Comment by tobrun** [comment]
@bessermt: 
thank you for bringing this to our attention, 
the documentation is not up to date.

### token.txt

We recently moved the `token.txt` from:

>android/java/MapboxGLAndroidSDKTestApp/src/main/res/raw/token.txt

to:

>android/java/MapboxGLAndroidSDK/src/main/res/raw/token.txt

Note that this token is used for development purposes. 
If you solely want to integrate the Mapbox SDK into your app consider using:

#### Activity/Fragment:
```java
 mMapView.setAccessToken(String accesToken);
```

#### AndroidManifest
```xml
 <meta-data
     android:name="com.mapbox.AccessToken"
     android:value="" />
```

**Comment by bleege** [comment]
It looks like the work behind this was done in #713 and #2526, but there's no mention as to the reasoning why `token.txt` was moved from the TestApp to the SDK proper.  I'm open to understanding this, but to me it seems like it'd make more sense for `token.txt` to stay in the TestApp as this is where anyone using the SDK in an app would have to configure it.

**Comment by tobrun** [comment]
@bleege 
As indicated in referenced issues this was required to be able to use a MapFragment in the SDK. 
That being said, I'm open to any suggestions improving this, I'm not :100: satisfied with current setup. 

### The problem
I will start with a quote from @ljbade :
> Key thing is that the token is set before onCreate where we will throw an exception if it is not set.

Implementing the information above gives the following problem with MapFragment:

```java
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
    super.onCreateView(inflater, container, savedInstanceState);
    mMap = (MapView) inflater.inflate(R.layout.fragment_main, container, true);
    // Need to set accessToken here, else it will crash and burn!
    mMap.onCreate(savedInstanceState);
    return mMap;
 }
```

### Possible solutions:
There are multiple ways of supplying the token into the code above:

 - using an abstract method

  ```java
  protected abstract String getAccessToken();
  ```

 - using a newInstance method when creating the fragment
  
 ```java
   public MapFragment newInstance(String accessToken){
     MapFragment fragment = new MapFragment();
     Bundle args = new Bundle();
     args.putString("key",accessToken)
     fragment.setArguments(args);
     return fragment;
   }
```
  
### Problem with these solutions:
The solutions above will cover most use-cases but fail to comply with [fragments declared in layout files](http://developer.android.com/training/basics/fragments/creating.html#AddInLayout):

```xml
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="horizontal"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent">

    <fragment android:name="com.mapbox.mapboxsdk.MapFragment"
              android:id="@+id/fragment_map"
              android:layout_weight="match_parent"
              android:layout_width="match_parent" />

</LinearLayout>
```

It is not possible to supply a fragment declared in a layout file with an accesstoken without subclassing it.
In par with this If we want to have parity with Gmaps and land #2042 it is also not possible without this construction.

### Current solution:
#### Going the extra mile for our users
The following question comes to mind:
 > are you required to use an accesstoken or is it optional? 

rephrased this become: 
 > is this a convention or is this a configuration?

I believe for 99% of the cases this will be a `convention` and I would like to apply `convention over configuration` for this. We are able do the heavy lifting for our users and thus lowering the amount of friction they perceive during integration.

### Going the extra mile for ourselves

One requirement for development purposes is the possibility of a gitignored accesstoken (this is documented in #713).

### Introducing ApiAccess

To support requirements above I created 2 conventions by using the [ApiAccess](https://github.com/mapbox/mapbox-gl-native/blob/39911e581c7bc82116c1c70608f246924de33b85/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/utils/ApiAccess.java) class.

End user should use the manifest convention (same as Google Maps):

```xml
 <meta-data
     android:name="com.mapbox.AccessToken"
     android:value="" />
```

Developer should use the token.txt convention (because this can be gitignored):

```
android/java/MapboxGLAndroidSDKTestApp/src/main/res/raw/token.txt
```


@bleege 
Coming back to your remark:
> but to me it seems like it'd make more sense for token.txt to stay in the TestApp as this is where anyone using the SDK in an app would have to configure it.

Yes I completely agree, but end developers should use the convention of AndroidManifest as shown in the source code of the testapp [here](https://github.com/mapbox/mapbox-gl-native/blob/master/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml#L63). The unconventional token.txt is purely for development purposes.

Would love to hear you feedback on this.

**Comment by ljbade** [comment]
@bleege @tobrun the `token.txt

**Comment by ljbade** [comment]
However the real issue in this ticket as described in the first comment, is that we are not auto generating token.txt from the environment variable as was intended.

**Comment by tobrun** [comment]
> However the real issue in this ticket as described in the first comment, is that we are not auto generating token.txt from the environment variable as was intended.

the token.txt is still being generated but in a different location as in the documentation. See https://github.com/mapbox/mapbox-gl-native/commit/30cac4ff0013051ffac8941524b9b88a1a98ffcc

I believe the whole test app setup is confusing. Going to write something up for GL-internal.

**Comment by ljbade** [comment]
@tobrun Ah I see we moved from `android/java/` to `android/` but missed that change. I will make a quick PR for this.

**Comment by tobrun** [comment]
@ljbade ah, yeah, seem to have missed that as well

**Comment by ljbade** [comment]
The script is correct, but your documentation change is wrong @tobrun.

See the code at https://github.com/mapbox/mapbox-gl-native/blob/83cf2197fa544481295d62221d7d7f294d466d6f/scripts/android/run.sh#L16

**Comment by ljbade** [comment]
However I think that script file is only run on Travis...

It needs to be part of `make` or `gradle`.

**Comment by tobrun** [comment]
I'm not fully aware of the history behind it, but the token is currently generated with gradle [here](https://github.com/mapbox/mapbox-gl-native/blob/master/android/MapboxGLAndroidSDKTestApp/build.gradle#L18)

**Comment by ljbade** [comment]
Your right. I do wonder why it is in SDK though (like @bleege is). I remember when I set it up it was in TestApp and I can't remember when it was moved.

**Comment by tobrun** [comment]
@ljbade 
As indicated above:
when I added MapFragment to the SDK, I was not able to:

```java            
context.getResources().openRawResource(R.raw.token)
```

Because that resource was residing in the sample app..
So I had to move it up the hierarchy to use it.

**Comment by tobrun** [comment]
@ljbade 
Feel free to adjust anything about this workflow! 
as indicated before I'm not :100: behind current system.
We just need a `convention` for end developers to use our MapFragment

**Comment by ljbade** [comment]
@tobrun I realise there is a danger of `token.txt` leaking into a SDK `.aar` with our current setup. Particularly as we compile release currently on our own machines.

Are you aware of any other open source libraries that use tokens? I wonder how they manage not checking them in.

**Comment by tobrun** [comment]
> I realise there is a danger of token.txt leaking into a SDK .aar with our current setup.  

Yes completely agree that this is not safe..

Replacing 
```java 
context.getResources().openRawResource(R.raw.token) 
```

with 
```java
context.getResources().getIdentifier("token", "raw", YourActivity.this.getPackageName());
```
would resolve the current issue of having token.txt in the Sample app, 
while still being able to use ApiAccess in the fragment class. 

More info: getIdentifier [java doc](http://developer.android.com/reference/android/content/res/Resources.html#getIdentifier(java.lang.String, java.lang.String, java.lang.String)).

While we are at it, why not replace token.txt with an resource xml file?

**Comment by bleege** [comment]
This is great @tobrun.  Thanks for the insights into things.  It sounds like we're all on the same page about getting `token.txt` back into the TestApp ala #1929 which is cool.

> I will start with a quote from @ljbade :
>> Key thing is that the token is set before onCreate where we will throw an exception if it is not set.

I think this is the issue as this statement isn't 100% accurate.  This is something that is totally under our control and can be re-engineered.  The bigger goal is to have runtime configuration parameters (aka access tokens, etc) not embedded in the SDK itself.

I'll create a new ticket so that we can refactor ApiAccess to support this as well as unhijack this ticket from @bessermt.  :smiley:
