### ISSUE TITLE
[iOS] No identifier for annotation

### ISSUE THREAD

**Issue by Sh1mor1nka** [mapbox/mapbox-gl-native#3036]
1) I have many annotations, i need to present unique callout but in leftCalloutAccessoryView and rightCalloutAccessoryViewForAnnotation i can't identify annotation, only by title or subtitle, but what if i have the same titles or subtitles, it's not very good. Please add some property to store annotation  identifier. 

2) And it's will be very great if i can show custom callout view, not only left or right part but whole view. For example i need to press on callout and present another viewController, but i can't do these now. I can't add button to rightCalloutAccessoryViewForAnnotation but i can't execute button selector.

Thank you.

**Comment by 1ec5** [comment]
> Please add some property to store annotation identifier. 

There’s no such thing as an “annotation identifier”. Instead, your view controller should store a reference to the annotation you want to identify, then check whether the `annotation` parameter is equal to that annotation.

> And it's will be very great if i can show custom callout view, not only left or right part but whole view.

This is being tracked in #2211.

> I can't add button to rightCalloutAccessoryViewForAnnotation but i can't execute button selector.

If the right callout accessory view is a descendant of UIControl, such as a UIButton, your map view delegate can implement `-mapView:annotation:calloutAccessoryControlTapped:`.

**Comment by Sh1mor1nka** [comment]
I have 457 annotations now, each annotation should have their own image, and i can't identify annotation to set correct image to it, or show correct calloutView. Now i identify annotation only by title, it's not very good. Annotation must have identifier! Please :)

And there are no clustering for annotations as i understand, yes?

**Comment by 1ec5** [comment]
> I have 457 annotations now, each annotation should have their own image, and i can't identify annotation to set correct image to it, or show correct calloutView.

In general, if you need to manage a few annotations after adding them to the map view, your view controller should store that annotation in an instance variable.

However, in your case, it sounds like the image would be considered part of the data for an annotation, rather than mere decoration. So instead of adding a series of `MGLPointAnnotation`s or `MGLPolygon`s to the map view:

1. Create a subclass `MGLPointAnnotation` or `MGLPolygon`, or create a class that conforms to the `MGLAnnotation` protocol. In that class, implement an `identifier` property.
1. Add instances of that class to the map view.
1. In methods such as `-mapView:rightCalloutAccessoryViewForAnnotation:`, cast the `annotation` to your custom class and get its `identifier`.

In other words, `MGLPointAnnotation` is a convenience class for the most common case where the title and subtitle represent the essence of an annotation. But if the annotation’s data model should be represented by something else, you should subclass.

> And there are no clustering for annotations as i understand, yes?

Correct. We’re planning to implement it for #320.

> Is there any method called when i tap whole callout, not only right or left view based on UIControl?

`-mapView:tapOnCalloutForAnnotation:` was added in #2596 and will appear in the next release. If you need it sooner, you can install a prerelease:

* If you’re using CocoaPods, point your Podfile to `https://raw.githubusercontent.com/mapbox/mapbox-gl-native/ios-v3.0.0-pre.5/ios/Mapbox-iOS-SDK.podspec`.
* Otherwise, [install one of the top two ZIP files here](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.0.0-pre.5).

I hope this helps!

**Comment by Sh1mor1nka** [comment]
Subclassing is good solution, thank you!

And thank you about ```-mapView:tapOnCalloutForAnnotation:```
