### ISSUE TITLE
move changelog to something easier for platform releases

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#3068]
Having a running changelog in the main `CHANGELOG.md` requires extra work, merging, and cherry-picking around releases since a) you don't want Android in iOS notes and vice-versa on pages like [this](https://www.mapbox.com/ios-sdk/api/2.1.2/) and b) you don't want `master` specific notes there either cluttering up final releases. But we need a way to track them as commits/PRs move along so we don't miss anything. 

After some chat, @1ec5 @friedbunny and I thought it best to put this in the wiki because it's versioned and has less potential for data loss. Doing this in either release milestones or release objects in GitHub runs the risk of loss/overwrite. 

@mapbox/mobile @mapbox/gl

**Comment by jfirebaugh** [comment]
I'm :-1: on keeping the CHANGELOG in any out of band medium like the wiki, release milestones, whatever.

If the difficulty is around platform releases, let's reconsider some of our existing workflow:

* Maybe we should have per-platform CHANGELOG.md's rather than an omnibus
* Maybe we should _not_ update CHANGELOG.md on individual commits and instead compile it at release time.

**Comment by tmcw** [comment]
On the "compile it at release time" point, we've been using `commitzen` over in Studio-land and it's worked well for sorting commits into changelog & non-changelog buckets.

**Comment by incanus** [comment]
We used to have per-platform changelogs! This was exactly my concern. 

> - Maybe we should not update CHANGELOG.md on individual commits and instead compile it at release time.

We used to do this on mobile, but it got unwieldy even in the raster days. Could check out `commitzen`, but isn't that also out of band? 

The wiki could be linked into the master, published one for releases too, at the top ("see here for changes coming in the next version...") while still being versioned in that wiki.

**Comment by incanus** [comment]
If we do go back to platform changelogs, we should still separate out stable from development. So something like this could work: 

- `CHANGELOG_IOS.md`
- `CHANGELOG_ANDROID.md`
- `CHANGELOG_NODE.md`
- `CHANGELOG.md` (for `master`)

Do we need a core (C++ API-specific) changelog as well?

**Comment by jfirebaugh** [comment]
@tmcw Can you link up "commitzen"? Google isn't giving me anything useful.

If we do platform-specific changelogs, let's do: `platform/{ios,android,node}/CHANGELOG.md`, not suffixes.

**Comment by 1ec5** [comment]
> I'm :-1: on keeping the CHANGELOG in any out of band medium like the wiki, release milestones, whatever.

What are the downsides? Is it that the main repo ceases to be self-contained?

> Maybe we should _not_ update CHANGELOG.md on individual commits and instead compile it at release time.

The pain point was the very high likelihood of missing an important change, as well as the difficulty of determining what exactly made it into a particular release. This is where it becomes important to ensure that each merged PR actually says “merged” rather than “closed”.

As a compromise, how about maintaining (platform-specific) changelogs in the repo but drafting prerelease changelogs on the (versioned) wiki.

**Comment by tmcw** [comment]
Commitizen: https://github.com/commitizen/cz-cli - @scothis can give a demo in the SF office

**Comment by mikemorris** [comment]
:-1: on wiki as an out-of-band tool version controlled separately from the main repo. Harder to keep in sync across, for example, multiple platform branches that each add new features. I'd much rather resolve the conflict in git than tracking/reverting pending commits in a wiki.

Commitizen sounds like a possible option for keeping an "authoritative" changelog in commit messages (which I personally need to get better at writing anyway), then using a tool to compile into a changelog at release time.

**Comment by 1ec5** [comment]
For the sake of explicitness, so far the iOS SDK release notes have been hand-compiled because we:

1. Don’t want routine/minor changes to clutter up the notes and bury more important changes
1. Place backwards-incompatible changes up top
1. Emphasize developer/user impact rather than justifying code changes

We also currently list PR numbers in each release note, which effectively forces you to force-push to the feature branch even when ff-merging doesn’t require it. (Or you can guess what the next PR number will be. Still awkward.)

Let’s use something like Commitzen to produce an unabridged, cross-platform changelog, then hand-curate it into per-platform release notes documents just before release. With the Commitzen-based changelog, it should be obvious what made it into the release. And there’s no need to remember to update three or so different files as part of a PR.

**Comment by incanus** [comment]
I'm liking that @1ec5.

**Comment by 1ec5** [comment]
As an interim step, I’ve started copying the relevant section of CHANGELOG.md into GitHub releases when I publish (pre)releases of the iOS SDK. By definition, tagging a (pre)release means that the contents won’t change, so there’s no risk that this information will get out of sync or that we’ll lose track of it. It’s also the only good place to put notes about what’s changed since the previous prerelease – stuff that doesn’t belong in the final release notes, nor in the master changelog.

Another interim change we should make is to split the platform-specific Android and iOS release notes into separate files: #3735. I’m not sure why they were ever combined in the first place. The master CHANGELOG.md should be reserved for a more comprehensive log of changes to the repository as a whole, possibly aided by commitzen, rather than curated release notes.

**Comment by jfirebaugh** [comment]
⇢ #3735, #4432
