### ISSUE TITLE
Unable to load map made with Mapbox Studio

### ISSUE THREAD

**Issue by Dwar3xwar** [mapbox/mapbox-gl-native#3079]
With the release of Mapbox Studio, I decided to make a new map. However when I post the styleId into the IB interface, it shows me a black screen.

The error is as follows: ```[ERROR] {Map}[Setup]: loading style failed: HTTP status code 401```

This is my storyboard:
![screen shot 2015-11-19 at 1 06 48 pm](https://cloud.githubusercontent.com/assets/12078810/11279406/738a7210-8ebe-11e5-8e2b-5b5283e4c454.png)

Any ideas?

**Comment by kkaefer** [comment]
Did you supply an access token?

**Comment by Dwar3xwar** [comment]
Yes, the map works with the default Streets one.

**Comment by 1ec5** [comment]
What version of the iOS SDK do you have installed?

**Comment by Dwar3xwar** [comment]
I'm using v2.1.2 on Xcode beta 7.0

**Comment by 1ec5** [comment]
I can reproduce this issue with your style. We’ve revamped this inspectable in an upcoming release, so that you’d enter a style URL of `mapbox://style/dwar3xwar/cih6hhfaq00bl9sm57we5142m` instead. In the meantime, you can work around this issue by setting the style ID to `style/dwar3xwar/cih6hhfaq00bl9sm57we5142m`. Let us know if you continue to see problems.

**Comment by Mehul-Mobiquity** [comment]
How can we use custom style-set uploaded in Mapbox account in iOS app?

**Comment by kkaefer** [comment]
@Mehul-Mobiquity have a look at https://www.mapbox.com/ios-sdk/examples/custom-style/

**Comment by Mehul-Mobiquity** [comment]
@kkaefer your suggestion shows style but not the tiles associated with it. any help for it?

**Comment by 1ec5** [comment]
This is a very stale ticket; the UI has changed since it was originally posted.

@Mehul-Mobiquity, if you're using an Interface Builder storyboard or XIB, as in the original comment above, select the map view and enter the mapbox://… style URL into the Style URL field in the Attributes inspector. Alternatively, if you're setting up the map view in code, follow that example. You can find out the style URL for any style you author in Mapbox Studio (the newer online version) by clicking Publish then Use.

On the other hand, I wonder if you're actually asking how to use a raster _tileset_ rather than a vector map style. In that case, follow [this example](https://www.mapbox.com/ios-sdk/examples/raster-styles/) instead.

In the future, if you have a support question rather than a bug report or feature request, please contact [Mapbox Support](https://www.mapbox.com/contact/) directly. Thanks!
