### ISSUE TITLE
Improve or customize InfoWindow

### ISSUE THREAD

**Issue by vns-cuong** [mapbox/mapbox-gl-native#3085]
Please tell me if we can display an info window like this in Android with Mapbox.
![unsupportedmapbox2](https://cloud.githubusercontent.com/assets/15936707/11292012/69245360-8f7a-11e5-866e-a8b043810a9f.png)
https://drive.google.com/file/d/0B4_M3f30IWv0Zm5NYm9ON05yTnM/view?usp=sharing

Thanks in advance.

**Comment by tobrun** [comment]
@vns-cuong 

## InfoWindowAdapter
You can use the [InfoWindowAdapter](https://github.com/mapbox/mapbox-gl-native/blob/master/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java#L480) to achieve this effect. This interface will be called when you click on a Marker and allows you to adapt the contents to a View instead of the default InfoWindow.

#### Example
An example of this can be found [here](https://github.com/mapbox/mapbox-gl-native/blob/39911e581c7bc82116c1c70608f246924de33b85/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/InfoWindowAdapterActivity.java#L57).

**Comment by vns-cuong** [comment]
@tobrun Great! Thanks so much :+1:

**Comment by vns-cuong** [comment]
@tobrun Please help me again!
Does iOs support it as well? Please give me some trace for it.

Thank you in advance.

**Comment by tobrun** [comment]
@friedbunny 
How can you achieve this on iOS?

**Comment by friedbunny** [comment]
iOS doesn't support this level of callout customization yet, though #3013 might add it.

For now on iOS, it's only possible to customize the title/subtitle, and the left/right accessory views. See [`-[MGLMapView mapView:leftCalloutAccessoryViewForAnnotation:]`](https://www.mapbox.com/ios-sdk/api/2.1.2/Protocols/MGLMapViewDelegate.html#//api/name/mapView:leftCalloutAccessoryViewForAnnotation:) and [`-[MGLMapView mapView:rightCalloutAccessoryViewForAnnotation:]`](https://www.mapbox.com/ios-sdk/api/2.1.2/Protocols/MGLMapViewDelegate.html#//api/name/mapView:rightCalloutAccessoryViewForAnnotation:).

**Comment by Leminur** [comment]
I don't get it. What is the name of the library that we need to use to create the custom marker window for android ? (InfoWindowAdapter). I can't import the correct library in order to use the function "getInfoWindow", for instance.  It seems like the dependency I imported in does not have classes that can handle the custom marker window. (I am using the 4.2.0 Beta.2 SDK) It can't resolve the method at "setInfoWindowAdapter".

I have searched all over the internet for custom marker library, I have found out that I had to use Google maps's own InfoWindowAdapter, I do not wish to open another issue for that kind of thing. Can you guys help me out? Thanks! @vns-cuong @tobrun @friedbunny

**Comment by tobrun** [comment]
@Leminur you don't need another library for this. It's included in the SDK itself as an inner class within MapboxMap:

```java
 /**
     * Interface definition for a callback to be invoked when an info window will be shown.
     *
     * @see MapboxMap#setInfoWindowAdapter(InfoWindowAdapter)
     */
    public interface InfoWindowAdapter {
        /**
         * Called when an info window will be shown as a result of a marker click.
         *
         * @param marker The marker the user clicked on.
         * @return View to be shown as a info window. If null is returned the default
         * info window will be shown.
         */
        @Nullable
        View getInfoWindow(@NonNull Marker marker);
    }

```

**Comment by ppanero** [comment]
@vns-cuong @tobrun @friedbunny Hey there! I am in a similar problem. I cannot resolve the "setInfoWindowAdapter" is it true as @Leminur stated that Google Map's class has to be imported?  In the doc it appears to be on MapView class but is not resolving. 

Just in case Im using v4.1.1

Thanks for the help in advance.

**Comment by tobrun** [comment]
You should be able to resolve it against mapboxmap,  not mapview. Will need to double check the documentation.

**Comment by ppanero** [comment]
@tobrun Thank you very much :D

**Comment by hso-icd** [comment]
Is it possible to control the positioning of the info window returned by getInfoWindow() in an implementation of InfoWindowAdapter? I tried to call offsetTopAndBottom() on it before returning it, and the info window is positioned at the specified offset relative to the marker when it first appears. But when I start dragging the map, the info window is moved to the default position relative to the marker.

**Comment by nielsfalk** [comment]
@tobrun Is it possible to get something like an info-window for the SymbolLayer?

**Comment by nielsfalk** [comment]
thx @tobrun 
it took me a wile to find out that the trick is to inflate the a BubbleLayout into a bitmap.
hidden in [line (635) ](https://github.com/mapbox/mapbox-android-demo/blob/a3c58d7c454eedb310bed3da16ab3e648ba135ab/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/labs/RecyclerViewSymbolLayerActivity.java#L625-L653)

**Comment by moorthysubu** [comment]
How to implement multiple clicks widgets in the info window view as this example showing up bitmap as the info window basically
