### ISSUE TITLE
[iOS] Compass does not receive touch events if its frame changes

### ISSUE THREAD

**Issue by mappy-mobile** [mapbox/mapbox-gl-native#3099]
If the user of the iOS framework changes the frame of the compass view (e.g. if part of the map is covered by UI elements) , the end user cannot tap on the compass to reset the north position.
The touch zone is still the default compass view position.

expected : update touch zone when changing compass view frame.

**Comment by tobrun** [comment]
@mappy-mobile 
is this issue related to Android or iOS? 
In case of Android, how are you altering the location of the CompassView? 
By using `mMapView.setCompassMargins(int left, int top, int right, int bottom)`?

**Comment by mappy-mobile** [comment]
@tobrun oh sorry I forgot to specify it's related to the iOS lib. I'm adding a label.

**Comment by 1ec5** [comment]
I don’t see anything that explicitly favors the compass tap gesture recognizer over the single tap gesture recognizer. On top of that, the compass tap recognizer should be attached to the compass view, not its container. An argument in favor of #1830 perhaps.

**Comment by incanus** [comment]
We saw problems with this before related to a) constraints updating properly and b) taps on container vs. compass image as @1ec5 states. Also possibly related to clipping settings for the container vie.w

**Comment by 1ec5** [comment]
It’s unlikely to be an issue with the constraints updating, though, because (unless I’m missing something) the compass still appears in the right place.

**Comment by mappy-mobile** [comment]
Yes I'm using explicit values to change the frame of the compass view, my point was only about tap events registered in the wrong bounds.

**Comment by 1ec5** [comment]
OK, that explains it. MGLMapView intercepts tap events on the compass view's invisible container view with a gesture recognizer. I think #1830 is the way to go here; we just need to make the button trigger the action on touch down rather than touch up inside.

**Comment by RomainQuidet** [comment]
Hi,
Romain, from Mappy team, dedicated to mapbox SDK. I wonder why is there a container here for the compass ? It's a bit overkill for the memory. The compass view can itself handle the tap recognizer. And when not visible, the interaction can also be turned off with userInteractionEnabled property of the compass UIImageView. So when users modify the compass frame.

What happened here is that the container is constrained by layout constraints. Our developer moved the compassView itself by modifying its frame. So yes, the container did not move, as the tap recognizer. And the compassView moved away. 

If a view is constrained by layout constraints, modifying its frame is forbidden. One idea might be to add an API entry to set the compassView center position in the SDK.

Romain

**Comment by incanus** [comment]
The reason the compass has a container is due to jitter and performance with constraints directly against it, holding to the right and the top layout guide, while rotating. We hit this problem back in the raster SDK days (as well as this tap issue) and having a container solved this. See https://github.com/mapbox/mapbox-ios-sdk-legacy/pull/315 for backstory.

**Comment by RomainQuidet** [comment]
Hi,
It seems that the bug is not corrected... we set the compassView frame to something else, the touch is not working.
If a view is positioned by layout constraints, modifying its frame is forbidden, and result in unknown behavior.  This is what happen here.
We need have have the possibility to change the compass position (as well as logo position). Adding an external API (ex: setOffset) will allow internal code to update the constraints and update the view. Another solution would be to expose the constraints but it is less user friendly.

I can take care of that in a pull request if you want.

**Comment by AdamBCo** [comment]
Any progress on this issue?

@RomainQuidet were you able to fix this issue?

**Comment by 1ec5** [comment]
This was fixed in #3099, which is in 3.0.0.

**Comment by 1ec5** [comment]
Oh never mind, I missed @RomainQuidet's comment above.

**Comment by RomainQuidet** [comment]
Hi, 
Sorry no I did not work on that as @1ec5 was on it. I can work on it if right now.

**Comment by johndpope** [comment]
incidentally - for people coming here looking how to reposition compass - 
in swift mapview - you can use 
        var rect = self.compassView.frame
        rect.origin.y += self.frame.height - 110
        self.compassView.frame = rect

**Comment by RomainQuidet** [comment]
there's another story for that, it's #3697 with PR #4219

**Comment by hashemp206** [comment]
I still have problem with compassView doesn't intercept touch event by changing its position
