### ISSUE TITLE
Prevent black flash when loading styles

### ISSUE THREAD

**Issue by tomtaylor** [mapbox/mapbox-gl-native#3101]
I've set a background colour on my `MGLMapView`, to the background of the Streets style, so it looks a little less jarring when loading. However, it still flashes black while loading the map for the first time. It'd be great if it could keep the background colour until the style is fully loaded.

**Comment by 1ec5** [comment]
This would be fixed by #3096 I believe.

**Comment by tomtaylor** [comment]
Ah ha, thanks.

**Comment by abpopov** [comment]
I solve this by this code
 mapView.layer.backgroundColor =[[UIColor clearColor] CGColor];

**Comment by friedbunny** [comment]
Fixed by #3096.

**Comment by 1ec5** [comment]
The fix in #3096 only takes effect if you set `MGLMapView.opaque = NO`; otherwise, UIKit considers the behavior to be undefined if the map view fails to draw its entire bounds. So setting `opaque = NO` is the recommended way to deal with the black flash.

**Comment by mxcl** [comment]
`isOpaque` should be `false` by default since that is the behavior of almost all UIKit views since iOS 7 almost four years ago. The black flash alone is why my boss decided that we would use Google Maps instead. :P

**Comment by 1ec5** [comment]
As of the iOS 10 SDK, [`UIView.isOpaque`](https://developer.apple.com/reference/uikit/uiview/1622622-isopaque) is `true` by default, and so is `MKMapView.isOpaque`.

The black flash you’re seeing is more likely the style’s background layer being rendered before the other layers come in, since the other layers likely require fetching vector tiles. (This is the phase in which MapKit would render a graticule: see #119.)

The background color of a style usually matches the color of land, although Mapbox Satellite and Satellite Streets have black as their background color. You can configure the background color by customizing a style in Mapbox Studio or, as of Mapbox iOS SDK v3.4.0, by modifying `mapView.style.layers.last?.backgroundColor` inside `MGLMapViewDelegate.mapView(_:didFinishLoadingStyle:)`.

If you’re seeing a noticeable black flash despite the style’s background color being set to something lighter, I agree that we should revisit this issue and find a better solution.

**Comment by mxcl** [comment]
`UIView`, probably, the majority of UIKit, certainly not. It is easy enough to test, almost all of my apps are clear background views (UILabel, UITableView, UIButton, UI*) and I get no black flashes due to opaqueness being true.

> The black flash you’re seeing is more likely the style’s background layer being rendered before the other layers come in, since the other layers likely require fetching vector tiles. (This is the phase in which MapKit would render a graticule: see #119.)

I set `isOpaque` to false and the black flash stopped…

**Comment by 1ec5** [comment]
I don’t mean to be stubborn; just wondering whether we’re missing something that allows MapKit to default to being opaque but still avoid the black flash. I’ve opened #7256 to track defaulting `isOpaque` to `NO`, as you’ve requested.
