### ISSUE TITLE
Composite sources with custom data

### ISSUE THREAD

**Issue by kristfal** [mapbox/mapbox-gl-native#3141]
Hey,

Short version:

Composite sources for custom data does not seem to be honored by gl-native. Gl-js handles composite sources for custom data (but in a rather unexpected way), see https://github.com/mapbox/mapbox-gl-js/issues/1764 for details.

Long version:

Looking at a few of the Mapbox styles, composite sources (one source layer from multiple data sets) seems to be supported in the client, such as here: https://github.com/mapbox/mapbox-gl-styles/blob/master/styles/outdoors-v7.json and https://github.com/mapbox/mapbox-gl-styles/blob/master/styles/streets-v8.json

```json
"sources": {
    "mapbox": {
      "type": "vector",
      "url": "mapbox://mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v6"
    }
  },
```

with custom sources, this would seem to be the way to go as referenced at https://www.mapbox.com/mapbox-gl-style-spec/:

```json
mapbox-streets": {
  "type": "vector",
  "tiles": [
    "http://a.example.com/tiles/{z}/{x}/{y}.pbf",
    "http://b.example.com/tiles/{z}/{x}/{y}.pbf"
  ],
  "maxzoom": 14
}
```

However the tileJSON spec specifies that each endpoint must return the same data (https://github.com/mapbox/tilejson-spec/tree/master/2.1.0), indicating that it is not possible to merge multiple custom sources into one source layer.

Attempting to use different source data for each tileURL results in the gl-native client only loading tiles from the first source in the array, ignoring the rest of the tile sources. This behavior is different from mapbox-gl-js as reported in https://github.com/mapbox/mapbox-gl-js/issues/1764

We'd expect (wish/hope) composite sources with custom data to work the same way as composite sources with mapbox hosted data, where the client loads all tiles from each tile source and treats them as a composite.

**Comment by kkaefer** [comment]
Composite sources are not a feature that is supported by the client; they're implemented by the server infrastructure. If you want to use custom data alongside Mapbox-supplied data, you'll have to upload the data to the Mapbox.com hosting infrastructure so that the server can combine the tiles on-the-fly. The fact that these tiles consist of more than one tile is completely hidden from the client implementation.

Sources can only describe one tile endpoint. If you supply two URLs that point to different data, Mapbox GL will not necessarily use both of these URLs (hence the requirement in the TileJSON spec). You can supply multiple URLs due to considerations for browsers. In the past, many browsers restricted the number of simultaneous HTTP connection to one server to a very low number (in some cases just 2), which meant that tile loading was slower than it could be. Therefore, in web browsers, we typically round robin these tile URLs so that we can circumvent the hostname limit. For Mapbox GL Native, this isn't necessary because we can control the HTTP requests ourselves. Therefore, we only use the first URL.

If you want to use more than one tile endpoint, you can use multiple [sources](https://www.mapbox.com/mapbox-gl-style-spec/#sources) and reference the appropriate one in the layer.
