### ISSUE TITLE
upgrade gyp

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mapbox-gl-native#3178]
We're already using a newer version of gyp to build the Node.js bindings - let's upgrade the version of gyp we use to build everything else and review [our existing patches](https://github.com/mapbox/mapbox-gl-native/commits/master/deps/gyp).

/cc @1ec5

**Comment by kkaefer** [comment]
Maybe it's time to change our build to CMake? The only reason we're stuck on gyp are so that integration with node bindings is easer (by building it in one build step, rather than first building a library, then adding that library to node). We're working around gyp's deficiencies in https://github.com/mapbox/mapbox-gl-native/blob/master/scripts/node/create_npm_scheme.sh has well to add direct run targets for `npm test` and `npm run test-suite`, due to the lack of Xcode schemes support in gyp.

There are at least two modules for using CMake instead of gyp: [node-cmake](https://www.npmjs.com/package/node-cmake) and [cmake-js](https://www.npmjs.com/package/cmake-js), which both seem well maintained.

**Comment by 1ec5** [comment]
> The only reason we're stuck on gyp are so that integration with node bindings is easer

The node bindings already seem to be using a different copy of gyp. Or at least there’s a separate copy being installed in node_modules, in addition to the much older copy in deps that we’re thinking of upgrading.

**Comment by mikemorris** [comment]
> due to the lack of Xcode schemes support in gyp

Is this something we could possibly upstream into gyp? Is CMake really a more attractive build system?

> The node bindings already seem to be using a different copy of gyp

Yep, this was to land `make xnode` support for Node.js v0.10.x in https://github.com/mapbox/mapbox-gl-native/commit/36a8fb32d5e4fd58d5ea04f45a4cabdbab9ed920. Previously `make node` builds were just using the default `node-gyp` bundled with whichever version of Node.js was active when compiling.

**Comment by kkaefer** [comment]
@mikemorris There's a half-baked branch at https://codereview.chromium.org/385963006/ that adds schemes, but gyp is pretty much unmaintained, as Google is moving away from `gyp` to `gn` or `bazel`.

**Comment by mikemorris** [comment]
@kkaefer Given the current state of gyp/gn/bazel I'm sold on moving to CMake if we can nail [nan](https://github.com/nodejs/nan) support, I could work on patching anything upstream if needed.

**Comment by incanus** [comment]
Possibly useful: https://github.com/mapbox/mapbox-gl-native/issues/18

**Comment by mikemorris** [comment]
Fixed in #3193, let's open a new ticket for discussion around switching build systems to CMake or something else.
