### ISSUE TITLE
convert Android Bitrise build to bitrise.yml

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#3265]
CI build workflows should always be governed by scripts under source control, not externally. We need to move the Android build logic out of the Bitrise "workflow" and into `bitrise.yml`, like the iOS build.

**Comment by incanus** [comment]
iOS work was done in https://github.com/mapbox/mapbox-gl-native/issues/2898.

**Comment by jfirebaugh** [comment]
Done :white_check_mark: for per-commit builds. Still needs to be done for scheduled builds. I can't find any Bitrise UI for editing scheduled builds though.

**Comment by jfirebaugh** [comment]
From Bitrise chat:

> Edit schedule: you have to delete it and add a new one

**Comment by bleege** [comment]
> I can't find any Bitrise UI for editing scheduled builds though.

What part are you looking to edit?  The scheduled build should point to a name of workflow so changing the workflow steps shouldn't impact the schedule.

**Comment by jfirebaugh** [comment]
Ok, all set.

https://github.com/mapbox/mapbox-gl-native/blob/dc4fa1c52e3869396039af00734ef9cc91a116c5/platform/android/bitrise.yml

The GUI workflows just do `bitrise trigger primary` and `bitrise trigger scheduled`, respectively.

**Comment by bleege** [comment]
@jfirebaugh I just verified that 2 SNAPSHOTS were made in the last 12 hours.  The first one (Number 8) was made around 7 PM Central / 5 PM Pacific (see screenshot) which I'm thinking was about the time you made the adjustments to "build and publish" workflow and likely fired off a test run of it which resulted in this.

The second one (Number 9) looks like it completed 2:30 AM Central / 12:30 AM Pacific.  Normally this is an hour off when they usually complete as the original schedule was set for 1 AM Central and the build and publish process takes about 29 minutes (compiling C++ for 4 ABI is the big time investment).  Bitrise is a bit odd though as the UI doesn't have the notion of timezones in it so 1 AM originally got set to US Central because that's where I was when I set this up.  :smiley:  My theory is that with the changes made the timezone got reset to US Pacific (as that's where you are) with an hour offset due to recent changes in Daylight Savings Time (I don't think Europe was on it yet when I originally set the schedule).  Time is hard.

At the end of the day though, this is looking good.  We can have as many SNAPSHOTS as we want and as long as we're still creating new ones sometime in the middle of the North American night Monday through Friday we should be good to go.

![20151216-snapshot-8](https://cloud.githubusercontent.com/assets/989928/11844866/9b8134e8-a3d6-11e5-87c9-ece1dcf2a67f.png)
_SNAPSHOT 8_

![20151216-snapshot-9](https://cloud.githubusercontent.com/assets/989928/11844870/a36e89f8-a3d6-11e5-85cc-a88bcacdbfb7.png)
_SNAPSHOT 9_

**Comment by jfirebaugh** [comment]
Yep, the first one was a test run and the second one was the scheduled build. Thanks for confirming that this is working.

**Comment by bleege** [comment]
Heads up @zugaldia @tobrun that Android Bitrise Configs are now in Git.

**Comment by tobrun** [comment]
@jfirebaugh Thank you for picking this up!
