### ISSUE TITLE
Add Android Bitrise CI integration for per commit workflow

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3273]
Currently when you create a PR, it is only showing Travis and Bitrise-iOS:

<img width="803" alt="screen shot 2015-12-11 at 18 29 43" src="https://cloud.githubusercontent.com/assets/2151639/11759712/403844a8-a036-11e5-8fba-832eb0257a35.png">

We are missing the `per commit` workflow for Android Integration on Bitrise.

cc @incanus

**Comment by jfirebaugh** [comment]
@incanus Any hints on this? Is it in the workflow somewhere? That's the only place where the iOS and Android projects differ as far as I can tell.

**Comment by jfirebaugh** [comment]
Could it be that Bitrise pushes status updates with some sort of static key, and when iOS and Android builds are running simultaneously, the iOS one somehow always wins? This seems far-fetched because we'd expect the Android one to win the race _sometimes_, and I never have seen that, but it's my only hunch right now.

**Comment by jfirebaugh** [comment]
> we'd expect the Android one to win the race sometimes, and I never have seen that

I just did in fact see this. So I think we'll need to hit up Bitrise support about this -- as far as I know we can't fix it on our side short of having a single combined "Mobile" build on Bitrise.

**Comment by tobrun** [comment]
I reached out to Bitrise about this problem. Will comment back if I hear from them.

**Comment by viktorbenei** [comment]
Hi,

I believe the issue is that every status update uses the same ID, in our case (as you can see it on the screenshot too): `continuous-integration/bitrise/push`. Actually we have two IDs, `.../push` and `.../pr` if I remember it correctly, but the point is that one ID shows only one status on GitHub, even if it's called/specified by the service multiple times (for the separate Apps on bitrise.io).

I'm not sure if we can use dynamic IDs, including the App ID for example in the status ID, or if we have to implement an app grouping or platform matrix feature and only call the GitHub API once, with the result of all checks.

You can request this on our UserVoice (https://bitrise.uservoice.com) and we'll have a look too, whether we can include the App ID in this GitHub status API ID.

**Comment by birmacher** [comment]
Hi,

We fixed the issue by updating the Status API context strings in the following way:
`continuous-integration/bitrise/push` will change to `ci/bitrise/{app_slug}/push`
`continuous-integration/bitrise/pr` will change to `ci/bitrise/{app_slug}/pr`

It will solve the problem when running the same commit for multiple apps.
I'll update it here when the fix is live on Bitrise.

**Comment by birmacher** [comment]
Hi @tobrun,

The fix is live on Bitrise. Please let us know if you find any problems with it.

**Comment by friedbunny** [comment]
Thanks for the attentiveness, @birmacher. This is definitely an improvement, but perhaps there a way to more positively identify each individual bitrise build?

![screen shot 2016-01-14 at 10 36 15 am](https://cloud.githubusercontent.com/assets/1198851/12328745/c5c56720-baaa-11e5-9b06-f64fb9c26890.png)

**Comment by viktorbenei** [comment]
What would you like to see @friedbunny ? Just a single entry for bitrise?

**Comment by friedbunny** [comment]
@viktorbenei I really like that each bitrise build is broken out, but the app slug hash is not particularly meaningful — i.e., one must click on the "Details" link to find out that `155ef7da24b38dcd` is the OS X build.

Ideally, `155ef7da24b38dcd` would be replaced with a human-readable identifier, like the title of the build: "GL Native – OS X" in this case.

**Comment by friedbunny** [comment]
(@birmacher @viktorbenei Hope I'm not coming off as complaining, btw — thanks for implementing this feature and being so responsive, we really appreciate it.)

**Comment by tobrun** [comment]
@viktorbenei @birmacher thank you for this, this makes our lives much easier! :rocket:

**Comment by viktorbenei** [comment]
Thank you for your feedback! 😉 We always try to improve our system, getting feedback from power users is always a tremendous help!

Re: the ID: I see your point, I'm just not sure what the best solution would be.. The slug has the advantage that it's a fixed length, URL safe identifier. The issue with using the title would be that it might change any time, leaving a previous check uncompleted, as the GitHub API uses this ID to match status API calls, which means that if the ID changes during the build (you change the title) the status of the build on GitHub will remain in "building".

Another thing is the length and style of the title. Something like `ci/bitrise/A strangeLy FORMatted #title/push` might be a bit misleading, although, of course, you can change the title any time. Alternatively we could normalize the title so way, making it something like `ci/bitrise/a-strangely-formatted-title/push`, but I'm not sure this is expected / would be helpful. What do you think?

There's one more thing to consider using the title, we'll have to check the GitHub API docs for any limitation regarding this ID, whether the API has restrictions regarding the length and allowed characters in this ID.

**Comment by jfirebaugh** [comment]
@viktorbenei @birmacher I want to echo @friedbunny and @tobrun -- being able to see all the builds is _super_ helpful.

As far as further tweaks, how about changing the status "description" (a status API attribute that is shown after the bold slug part in the UI) from 'Bitrise.io - build is {status}' to 'Bitrise.io - "{title}" is {status}'?

**Comment by birmacher** [comment]
Great idea @jfirebaugh. We will update it in the upcoming days! I'll ping you when it's live.

**Comment by tobrun** [comment]
Nothing actionable left of original PR. Closing

**Comment by viktorbenei** [comment]
We now also include the app title in the status API text - we're working on figuring out the best format for it.
