### ISSUE TITLE
event for camera changing

### ISSUE THREAD

**Issue by dagatsoin** [mapbox/mapbox-gl-native#3279]
Is there an event which fires at each camera change (coordinate, pitch, ...) BEFORE the render ?
My goal is to sync the camera of another view with the mapbox camera.

**Comment by dagatsoin** [comment]
Maybe by emplementing `mapViewWillStartRenderingFrame` which is still in todo state?
If so, I bet I have to build a special version of MBGL binary. Could someone explain which scheme I have to use to compile the binary and where is the output path? (newbie in xcode here)

**Comment by 1ec5** [comment]
-[MGLMapViewDelegate mapView:regionWillChangeAnimated:] is called before the camera changes. Let us know if that isn't working as expected.

If you'd like to build the iOS SDK from source, see:

https://github.com/mapbox/mapbox-gl-native/blob/master/INSTALL.md
https://github.com/mapbox/mapbox-gl-native/blob/master/docs/DEVELOP_IOS_OSX.md
https://github.com/mapbox/mapbox-gl-native/blob/master/docs/BUILD_IOS_OSX.md

**Comment by dagatsoin** [comment]
@1ec5 I need something called at each frame. Because I will have to track changes even if camera does not move.
I will try to implement `mapViewWillStartRenderingFrame` but I am a bit confused where to write it. Do you know where ? (I am using the IOS SDK.)

**Comment by 1ec5** [comment]
Ah, we have -mapViewRegionIsChanging:, whoch gets called immediately after every incremental frame in an animated camera change, but nothing before it.

Since you're interested in all redraws, not just those caused by camera changes, -mapViewWillStartRenderingFrame:fullyRendered: is the callback you want. It turns out that this delegate method is implemented, but fullyRendered isn't. See #2775 and #1804 for context.

**Comment by 1ec5** [comment]
(The TODO in this case seems to indicate that the method isn't implemented completely, but it should be good enough for your use case.)

**Comment by dagatsoin** [comment]
perfect :)
