### ISSUE TITLE
"showAnnotations:animated:" bug in small map

### ISSUE THREAD

**Issue by sirljan** [mapbox/mapbox-gl-native#3392]
Hi

I found bug. Method `showAnnotations:animated:` doesn't work properly on smaller map size.
Steps to reproduce:
- When you have mglmapview sized e.g. 128x128, 
- you create polyline annotation 
- execute showAnnotation method
-> mapview scroll to center of annotation but in such zoom scale it is not visible.

Here is prepared code https://bitbucket.org/sirljan/mapboxtrythings
I would expect to see this:
<img width="432" alt="screen shot 2015-12-23 at 01 37 33" src="https://cloud.githubusercontent.com/assets/419850/11969253/4de6bee2-a917-11e5-8a85-0d1bdda654ee.png">
But I see this:
<img width="432" alt="screen shot 2015-12-23 at 01 48 49" src="https://cloud.githubusercontent.com/assets/419850/11969256/576509c4-a917-11e5-8120-14b6f2e39e50.png">

To see it in action unzip this video.
[showAnnotationBug.mov.zip](https://github.com/mapbox/mapbox-gl-native/files/70367/showAnnotationBug.mov.zip)

**Comment by 1ec5** [comment]
Possibly the same bug as #3110.

/cc @friedbunny

**Comment by sirljan** [comment]
Herer is workaround:
```swift
var coordinates = [CLLocationCoordinate2D]()
//appending coordinates
mapView.setVisibleCoordinates(&coordinates, count: UInt(coordinates.count), edgePadding: UIEdgeInsetsMake(inset, inset, inset, inset), animated: false)
```

**Comment by friedbunny** [comment]
Thanks @sirljan, you've been a great help in tracking this down.

This bug is caused by attempting to set edge insets that are greater than the size of the view. In `-[MGLMapView showAnnotations:animated:]` we [hardcode the edge inset to 100 points](https://github.com/mapbox/mapbox-gl-native/blob/7a6076ea9df72f34565d8f316f8c5c19279677b8/platform/ios/src/MGLMapView.mm#L2657) on all sides, which means that views with height or width <=200 points will exhibit this problem.

**Comment by sirljan** [comment]
Glad to hear that.
Wow :) I feel like super hero.
