### ISSUE TITLE
Absolute file URL is treated as mapbox: style URL

### ISSUE THREAD

**Issue by AskinOharis** [mapbox/mapbox-gl-native#3505]
Hi guys,
I try to use custom raster tiles in my project but I always get the following error:
"loading style failed: HTTP status code 401"

My MGLMapView is embed in an .xib file with just the default settings and I set the styleURL within the code (using local styles):
<p><code>NSString *path = [[NSBundle mainBundle] pathForResource:@"alpstein_raster" ofType:@"json"];
styleURL = [NSURL URLWithString:path];
self.mapView.styleURL = styleURL;</code></p>

My alpstein_raster json looks like:
<pre><code>
{
  "version": 8,
  "name": "Alpstein",
  "sources": {
    "Alpstein-Summer": {
      "type": "raster",
      "tiles": [
        "http://xxx/AlpsteinSummer/{z}/{x}/{y}.png",
		"http://xxx/AlpsteinSummer/{z}/{x}/{y}.png",
		"http://xxx/AlpsteinSummer/{z}/{x}/{y}.png",
		"http://xxx/AlpsteinSummer/{z}/{x}/{y}.png"
      ],
      "tileSize": 256
      "maxzoom": 17
    }
  },

  "layers": [{
    "id": "Alpstein",
    "type": "raster",
    "source": "Alpstein-Summer",
    "paint": {
      "raster-fade-duration": 100
    }
  }]
}
</code></pre>

I don´t set an AccessTokes since I don´t use MapBox Tilessources.
Any idea what I am doing wrong?
Tx for help, 
Askin

**Comment by AskinOharis** [comment]
When I upload my JSON file to a webserver it works:
<pre><code>
NSString *urlstr = @"http://www.someurl.com/alpstein_raster.json";
styleURL = [NSURL URLWithString:urlstr];
</code></pre>

**Comment by 1ec5** [comment]
MGLMapView is seeing an absolute file URL and treating it as a mapbox: URL. The workaround is to use a relative URL. Relative URLs are calculated relative to the main bundle:

```objc
[NSURL URLWithString:@"alpstein_raster"]
```

**Comment by RomainQuidet** [comment]
confirmed, it's working on local file with [NSURL URLWithString:@"asset://myfilename.json"]

**Comment by RomainQuidet** [comment]
@1ec5 Don't you think it would be useful to also expose the setStyleJSON api ? Users could need to load dynamically constructed json strings (versus files).

**Comment by AskinOharis** [comment]
tx guys -> [NSURL URLWithString:@"asset://alpstein_raster.json"]; works

**Comment by 1ec5** [comment]
Hm, it shouldn’t be necessary to use the asset: protocol – that’s an implementation detail. A relative URL like `myfilename.json` is expected to work. Reopening because we should get absolute file URLs to work too. It’s just a matter of calculating the common base between an absolute file path and the path to the main bundle.

> Don't you think it would be useful to also expose the setStyleJSON api ?

This API was exposed way back when, until we removed it in #1184 to reduce MGLMapView’s complexity. Moreover, passing a JSON file as a string was unwieldy for manipulating more than the most simple of styles, since you had to serialize back and forth (see mapbox/mapbox-gl-cocoa#31). There are plans to introduce a proper, object-oriented style API (#837), which would address this and other use cases.
