### ISSUE TITLE
Exclude iOS simulator location events from telemetry

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#3621]
/cc @1ec5 @boundsj

**Comment by 1ec5** [comment]
We can `#ifdef` out some entry point for MGLMapboxEvents when compiled for x86. That’ll prevent any iOS Simulator location updates from reaching the telemetry endpoint. There’s still a possibility that Xcode’s Simulated Location feature would cause telemetry data to be sent too. We can address that by detecting the presence of a debugger, but I think that’d be lower priority, since Xcode’s default simulations are single motionless points.
