### ISSUE TITLE
Content insets

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#3627]
Content insets were implemented in mbgl and for iOS and OS X in #3583. MapView should expose some sort of inset or padding property so that the map’s center can be shifted downward to account for e.g. a translucent or floating toolbar at the top.

/cc @tobrun

**Comment by bleege** [comment]
I'm going to review @lgeromegnace's PR in #3687 and then build an example using it in the TestApp so that we can verify it and demonstrate to others how it's used.

**Comment by bleege** [comment]
The API build out from #3687 has now been been reviewed and merged into `master`.  Will build out example next.

**Comment by bleege** [comment]
I set the location to be center on Nashville and then took screenshots of with and without a top offset of 250 pixels.  Not much has changed and this is likely due to density not being factored in to the API.

![device-2016-01-27-135809](https://cloud.githubusercontent.com/assets/989928/12626456/58db1fa2-c4fe-11e5-8c26-8ece21850706.png)
_No Content Offset_

![device-2016-01-27-135905](https://cloud.githubusercontent.com/assets/989928/12626464/63feec38-c4fe-11e5-872b-dfd9eb6fe28a.png)
_Top Content Offset Of 250px_

**Comment by 1ec5** [comment]
@bleege, this is because setting the insets alone does not move the map. [On iOS](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/src/MGLMapView.mm#L846-L869) and OS X, calling `-setContentInset:` causes the map to shift with optional animation.

**Comment by bleege** [comment]
Thanks for the clarification @1ec5.  To help illustrate this better (and the fact that we still have API work todo), I added a Marker to the map.

![device-2016-01-27-145136](https://cloud.githubusercontent.com/assets/989928/12628077/0fe32be2-c507-11e5-8f82-b56857e83bc2.png)
_No Content Offset_

![device-2016-01-27-145226](https://cloud.githubusercontent.com/assets/989928/12628086/1917c984-c507-11e5-9eae-91f0addc8dc7.png)
_Top Content Offset Of 1000px_

**Comment by bleege** [comment]
Looking at the Google Maps API the only place (that I can find) that they expose any type of content insets is in `CameraUpdateFactory`, specifically [with two `newLatLngBounds()` methods](https://developers.google.com/android/reference/com/google/android/gms/maps/CameraUpdateFactory) that take `padding` parameters.  The `padding` is uniformly applied in all directions, which is different from Core GL that gives 4, count 'em 4!, directions to specify.  I'm thinking that the best bet will be implement these methods that allow for only the single value of padding and then overload them by providing methods that can handle all 4.

I'm also wondering about timing for this as the manual `setLatLng()`, `setZoomLevel()`, etc type methods will be removed in `4.0.0` as part of [the MapboxMap ticket](https://github.com/mapbox/mapbox-gl-native/issues/3145).  This will leave only the Camera API as the way to manipulate the map.  It may make more sense to comment out the bindings methods for `setContentPadding()` in `master` for now and implement this all for `4.0.0` rather than ship API methods that aren't fully supported for `3.2.0`.

/cc @zugaldia @tobrun 

![screen shot 2016-01-27 at 4 58 11 pm](https://cloud.githubusercontent.com/assets/989928/12631684/5c883c4c-c518-11e5-80c0-2be0a4e06944.png)
_CameraUpdateFactory.newLatLngBounds() methods_

![screen shot 2016-01-27 at 5 02 43 pm](https://cloud.githubusercontent.com/assets/989928/12631698/6bb0727a-c518-11e5-8fd5-35dc923b97d2.png)
_Definition of `padding`_

**Comment by 1ec5** [comment]
I think this is a good place to diverge from what the Google Maps SDK provides. We started with a uniform padding concept in GL JS, but in mapbox/mapbox-gl-js#1675 we decided to allow each side to be specified independently. Uniform padding isn’t suitable for use cases such as a translucent toolbar or floating search bar at the top.

**Comment by tobrun** [comment]
@bleege after reading your thorough analysis, it seems you have a concrete gameplan! I'm now thinking about landing #3145 without `LatLngBounds` integration. This is one of the API's that is not high on my list to finish before merging. Is this something you want to pick up after?

**Comment by bleege** [comment]
@tobrun Yep, let's punt on #3627 (Content Insets) until `4.0.0`.  I'll add a ticket to comment out the `setContentPadding()` methods to keep them from being used in `3.2.0`.

> This is one of the API's that is not high on my list to finish before merging. Is this something you want to pick up after? 

Nope, the Content Insets don't have to be included in the initial iteration on the MapboxMap work in #3145 .  That said this is likely going to be an important feature for future Navigation work so working on this immediately after MapboxMap lands will be important.  It sounds like you have things well underway with this from your work in #3145 so I'll let you finish #3627 off at that time.

**Comment by tobrun** [comment]
@bleege  :+1:

**Comment by tobrun** [comment]
As mentioned in https://github.com/mapbox/mapbox-gl-native/issues/3761#issuecomment-182251936 it seems that Google Maps SDK is exposing this as `GoogleMap.setPadding(int,int,int,int)`. I'm going to implement this in the same fashion. Will close this in favour of the feature request in #3761.
