### ISSUE TITLE
distanceFromLocatio() method

### ISSUE THREAD

**Issue by minikin** [mapbox/mapbox-gl-native#3699]
I'm sure that many developers will appreciate it if you add ```distanceFromLocation()``` method :

>Measuring the Distance Between Coordinates

>Returns the distance (in meters) from the receiver’s location to the specified location.

>Declaration
>func distanceFromLocation(_ location: CLLocation) -> CLLocationDistance

>Parameters
>location | The other location.

>Return Value
>The distance (in meters) between the two locations.

>Discussion
This method measures the distance between the two locations by tracing a line between them that follows the curvature of the Earth. The resulting arc is a smooth curve and does not take into account specific altitude changes between the two locations.
>

[Core Location Framework Reference > CLLocation Class Reference](https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocation_Class/#//apple_ref/occ/instm/CLLocation/distanceFromLocation:)

**Comment by 1ec5** [comment]
We could easily provide this, but in general, we’ve been focused on providing an alternative to MapKit, rather than a replacement for Core Location. Under the hood, the Mapbox iOS SDK already links to Core Location for things like determining the user’s current location, something a third-party framework would never be able to do on iOS. So just by installing the Mapbox iOS SDK, you can already use `CLLocation.distanceFromLocation(_:)` without any additional work. (If not, there’s no additional overhead in linking to CoreLocation.framework.)

**Comment by minikin** [comment]
@1ec5 Thank you for the clarification.
