### ISSUE TITLE
Use consistent pattern for changelogs

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-native#3735]
The state of changelogs:
* iOS uses /releases https://github.com/mapbox/mapbox-gl-native/releases
* node uses https://github.com/mapbox/mapbox-gl-native/blob/master/platform/node/CHANGELOG.md
* ~~Android does not have a changelog other then checking out the milestone~~ Android: https://github.com/mapbox/mapbox-gl-native/blob/master/CHANGELOG.md

Can we come to a consensus on how/where changelogs are displayed? I'm fan of inside `/platform/{platform}/CHANGELOG.md`

I think changes should be available in both the actual repo and if each team wants, in their docs on mapbox.com. I say this because platforms on line node and linux do not have docs on mapbox.com.

/cc @jfirebaugh @zugaldia @bleege @friedbunny @1ec5

**Comment by bleege** [comment]
Android and iOS share the same change log --> https://github.com/mapbox/mapbox-gl-native/blob/master/CHANGELOG.md

**Comment by bsudekum** [comment]
@bleege I stand corrected

**Comment by 1ec5** [comment]
When rolling new iOS SDK releases, I copy the relevant section of CHANGELOG.md into the GitHub release. By definition, tagging a (pre)release means that the contents won’t change, so there’s no risk that this information will get out of sync or that we’ll lose track of it.

For prereleases, the GitHub release lists just the deltas since the previous prerelease. With so many changes from release to release, it isn’t reasonable to expect a developer to spot what’s new. There may also be fixes for regressions in a previous prerelease that don’t warrant inclusion in the final release’s notes.

I support splitting the changelog out into platform-specific changelogs, as we’ve done with the node bindings. That aligns with the general push to move all platform-specific files into platform/. platform/ios/scripts/package.sh and platform/ios/scripts/document.sh will need to be updated, as will CONTRIBUTING.md.

**Comment by bleege** [comment]
np @bsudekum there's so much stuff in mapbox-gl-native things can be hard to find sometime.

**Comment by friedbunny** [comment]
I'm not a fan of the combined Android + iOS changelog, +1 to splitting into the relevant `platform/` folders.

**Comment by bleege** [comment]
Sounds good to me @friedbunny.  Care to make that happen?

**Comment by friedbunny** [comment]
Let's wait until the dust settles on iOS v3.1.0. 👍

**Comment by 1ec5** [comment]
The Android and iOS changelogs have been split apart in #4466 and are now located at the suggested path. For the iOS SDK, we’ll continue to copy the relevant section of the changelog into GitHub releases and the front page of the [API documentation](https://www.mapbox.com/ios-sdk/api/). (The changelog is also available offline as part of the distribution.) The Android SDK doesn’t use GitHub’s release feature, so I think we’re good here.
