### ISSUE TITLE
Increase glyph atlas capacity

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-native#3781]
@bhousel could you port https://github.com/mapbox/mapbox-gl-js/pull/1923 to -native?

**Comment by bhousel** [comment]
sounds fun!

**Comment by mb12** [comment]
@ansis and @bhousel

1.)  Is there any plan to do similar optimization for SpriteAtlas? Recently the size of SpriteAtlas was statically  increased to 1024x1024. A similar improvement would allow the sprite atlas to be smaller for common use cases.
2.)
Also for GlyphAtals does the improvement also included shrinking the size dynamically?

**Comment by bhousel** [comment]
> Is there any plan to do similar optimization for SpriteAtlas?

Yes this is in my queue also.

> Also for GlyphAtals does the improvement also included shrinking the size dynamically?

The current plan is to refcount the glyphs so that we can replace them when they are not referenced by visible tiles.  I hadn't considered shrinking the atlas texture, but it's a possibility.  Something like that would likely only occur if the map navigates from a place where CJK languages are in use to one where they are not - so I'm not sure how aggressively we want to optimize this.

**Comment by mb12** [comment]
@bhousel  Thanks for the clarification. The ability to shrink the size automatically would be more useful for SpriteAtlas that houses user defined marker icons.

**Comment by 1ec5** [comment]
> I hadn't considered shrinking the atlas texture, but it's a possibility. Something like that would likely only occur if the map navigates from a place where CJK languages are in use to one where they are not - so I'm not sure how aggressively we want to optimize this.

Without cleaning up the textures, we’d exacerbate #1681, right?
