### ISSUE TITLE
Black screen while loading map first time in offline iOS 

### ISSUE THREAD

**Issue by gurumaheshPCS** [mapbox/mapbox-gl-native#3789]
Hi,
For the first time i am loading the app. internet is not available. i am seeing black screen. Once i got internet how to reload the map in iOS.

**Comment by friedbunny** [comment]
Mapbox styles must be downloaded from the network before they can be cached, as must the map data. You can load a local style, but this will only effectively change the first-load background color of your map if there is no internet connection.

True offline support is a feature we're currently working on in #584 and expect to be available sometime in the next few months — but [Mapbox's terms of service](https://www.mapbox.com/help/offline-map-cache/) require that your users be the ones to download the map data, so the first load experience will likely be much the same as it currently is.

**Comment by friedbunny** [comment]
> Once i got internet how to reload the map in iOS.

Apologies, I appear to have missed this part of the question. See https://github.com/mapbox/mapbox-gl-native/issues/3102#issuecomment-177321404 for one suggested way to reload a failed style on iOS.

**Comment by tylrtrmbl** [comment]
Hi @friedbunny. I notice that whenever I load the app in airplane mode, I have the black background described, for the reason you described. However, I'd prefer this looked a little – well – better – for my users who haven't turned on their network yet. I would provide a little card over the screen nudging them to turn on their radios.

I basically want an interim background color other than black while the map loads.

I'm also wondering if this is related to the FOUC @incanus reported yesterday in #5795; though it would have to be a slightly different manifestation, since my black square is the whole map background.

**Comment by friedbunny** [comment]
@tylrtrmbl I don’t have a good answer for you, but you could try a couple things:

- `MGLMapView.opaque = NO` and insert a placeholder view below your map view. This will probably flash your placeholder before showing the actual map content.
- Show the placeholder view and wait to add the map view to the hierarchy until you’re sure it can display content.
