### ISSUE TITLE
Suggestion: add setOnZoomChangedListener()

### ISSUE THREAD

**Issue by mudar** [mapbox/mapbox-gl-native#3798]
My map needs to load many Markers, so I load them into the visible bounds only (with some padding). So zooming out can require map updates to fill the newly visible empty areas.

I currently need to rely on `onMapChanged()`, checking the zoom value with previous one I've stored, and trigger API updates on significant changes.

@tobrun thanks for the very quick answers :-) this is my last suggestion for today

**Comment by tobrun** [comment]
This type of feature is being tracked in #3751, but it is currently not certain that we will eventually implement this in the SDK because the OnCameraChangeListener in #3745 could make this and many other listeners obsolete. Since this issue doesn't specify more requirements details than the initial one. I'm going to close this down. 

Thank again for this valuable feedback!
