### ISSUE TITLE
Annotations not shown when Internet connection is down

### ISSUE THREAD

**Issue by ferrarop** [mapbox/mapbox-gl-native#3817]
In iOS, if I kill the app, disable Internet connection, and reopen the app, the annotations are not shown anymore.
The map is shown (at least the portion that is cached), but the annotations are not.
Everything works fine with Internet connection.

Minimal Working Example:
      
    override func viewDidLoad() {
        super.viewDidLoad()
            
        mapView = MGLMapView(frame: view.bounds)
        mapView.autoresizingMask = [.FlexibleWidth, .FlexibleHeight]
        
        let center = CLLocationCoordinate2D(latitude: 38.894368, longitude: -77.036487)
        mapView.setCenterCoordinate(center, zoomLevel: 15, animated: false)
        
        view.addSubview(mapView)
        
        let annotation = MGLPointAnnotation()
        annotation.coordinate = center
        mapView.addAnnotation(annotation)    
    } 

I also tried with a custom image (stored locally): the function "mapView(mapView: MGLMapView, imageForAnnotation annotation: MGLAnnotation)" is called correctly (if I set self as the mapView delegate), but the annotation is not shown.

**Comment by jfirebaugh** [comment]
`SymbolLayer` needs to pass [its own `SpriteAtlas`](https://github.com/mapbox/mapbox-gl-native/blob/62bbf2627a32a57188e4026aca8dc337e07ded7f/src/mbgl/layer/symbol_layer.hpp#L100) into [`needsDependencies`](https://github.com/mapbox/mapbox-gl-native/blob/62bbf2627a32a57188e4026aca8dc337e07ded7f/src/mbgl/layer/symbol_layer.cpp#L168), so that `needsDependencies` checks the annotation sprite store for loaded state rather than the style sprite store. This requires rejiggering `SpriteStore` and `SpriteAtlas` types a bit. (I continue to think those two should be merged.)

**Comment by jfirebaugh** [comment]
Updated title / tags to reflect that this bug is not iOS specific.

**Comment by ferrarop** [comment]
I've just tried installing version 3.1.0 on iOS, and annotations (with local images) seem to show up fine for me, even if Internet connection is down.
I haven't tested it extensively, I just confirmed they show up in a minimal working example like the one I posted.
