### ISSUE TITLE
Rename 'linux' target to 'glfw'

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#3821]
We've been able to build `linux` target in OS X for a while now. This target uses [GLFW](http://www.glfw.org/index.html) for rendering, and thus I feel having `glfw` target would be less confusing.

/cc @mapbox/gl

**Comment by jfirebaugh** [comment]
I think I'm 👎  on this. "linux" is the platform. The use of GLFW is an implementation detail of the test app for that platform.

**Comment by mikemorris** [comment]
I actually got tripped up by `make linux` when looking into OpenSWR/OSMesa software rendering in https://github.com/mapbox/mapbox-gl-native/issues/4498. IMHO `make glfw` could be useful to differentiate the interactive `linuxapp` build from the various headless Linux builds that do not need GLFW.

**Comment by kkaefer** [comment]
@jfirebaugh there are two different things here, which are confusingly both named "linux": The `platform-linux` backend, and the `linux` debug app, which isn't actually Linux specific anyway. This is only about renaming the debug app.

**Comment by jfirebaugh** [comment]
Yeah -- I think we need to enforce some simplifications and abstractions to control the complexity of our build matrix and build system.

* We should be thinking in terms of platforms -- iOS, Android, Node, Linux -- as much as possible, rather than individual build targets/outputs.
* We should be thinking about abstractions that are common across all the platforms -- [a test suite that can be run with `PLATFORM=<platform> make test`](https://github.com/mapbox/mapbox-gl-native/issues/2701#issuecomment-204616779), a test app that can be run with `PLATFORM=<platform> make test-app`, etc.
* We can't have an individual make target for every combination of platform and build product -- the combinatorial complexity is too great.
* We should limit the scope of what we try to support across platform -- is it really worth it to maintain support for running the linux debug app on OS X, for example?

**Comment by kkaefer** [comment]
> is it really worth it to maintain support for running the linux debug app on OS X

My take would be yes, since the OS X app adds a lot of complexity and weird UI and is more of an end user facing application, rather than a means to debug the renderer. I'm typically using the GLFW app to prototype new features and debug existing issues. There's nothing in GLFW that is Linux-specific; it's just the only app (until Qt lands) that runs on Linux.

**Comment by 1ec5** [comment]
osxapp is intended to be as much an analogue to iosapp as possible, so it depends on the Mapbox OS X SDK just as iosapp depends on the iOS SDK. It isn't so much of an end user application, but its focus is definitely on SDK features like annotations and gesture recognition rather than renderer output.

**Comment by kkaefer** [comment]
Fair enough; I'm :+1: on keeping both GLFW and the OSX app as supported targets on Mac OS.

**Comment by mikemorris** [comment]
Heads up that https://github.com/mapbox/mapbox-gl-native/issues/4498 will introduce an alternate headless rendering pipeline for `make node`, using OSMesa for software rendering rather than GLX for rendering on a hardware GPU.

**Comment by jfirebaugh** [comment]
Okay, we should move `platform/linux/main.cpp` to `bin/glfw.cpp` and build it like `offline`/`render` are built.
