### ISSUE TITLE
Using old method from Mapbox SDK 0.7.4

### ISSUE THREAD

**Issue by Buminta** [mapbox/mapbox-gl-native#3844]
Hi team Mapbox!
I'm very happy when Mapbox-gl-native release.
So i using it at now.
But it's hard work for transfer from old version to now version.
I'm not found from wiki or documents some method for transfer it.
Example:
```
mapView.addListener
// For Scroll, Zoom event, DelayMapListener, ShowMarker, HideMarker, TapMarker, LongTap event,...
```
i'm using all event from them.

or
```
mapView.getBoundingBox()
````
For algorithm hide and show marker from me. 

From https://www.mapbox.com/android-sdk/api/3.2.0/ only show some basic events from mapview.
But I need more than this.

Everybody help me, thanks so much!

**Comment by tobrun** [comment]
@Buminta 
A lot has changed since the `0.7.4` release. We build a new SDK from scratch to use gl vector tiles instead of raster tiles from the `0.7.4` days. This is the primary reason for the big api change you are noticing. 

Related to your questions:
 - Most listener definitions can be found on [MapView](https://www.mapbox.com/android-sdk/api/3.2.0/) itself. Reach out if you have any questions of how to use them or some have not been included.
 - `getBoundigBox` is currently not a getter we support but you can use the workaround:
  - ```java
   int viewportWidth = mMapView.getWidth();
        int viewportHeight = mMapView.getHeight();

        LatLng topLeft = mMapView.fromScreenLocation(new PointF(0, 0));
        LatLng topRight = mMapView.fromScreenLocation(new PointF(viewportWidth, 0));
        LatLng bottomRight = mMapView.fromScreenLocation(new PointF(viewportWidth, viewportHeight));
        LatLng bottomLeft = mMapView.fromScreenLocation(new PointF(0, viewportHeight));
```
    You can then feed these values in a `VisibleCoordinateBounds, which is a synonym for BoundingBox in the `3.2.0` release. For the `4.0.0` we are thinking about exposing a getter in the same way as Google Maps SDK is exposing.

Reach out if you have any other questions.
