### ISSUE TITLE
Resizing of MapView on Android

### ISSUE THREAD

**Issue by hanspeide** [mapbox/mapbox-gl-native#3856]
I'm having a `MapView` that is covering 1/3 of the screen. When the user taps the map I want it to expand to fullscreen. I've attempted to implement this using a parent `LinearLayout` with weights 0.33/0.77, and changing to 1.0/0.0 when the user taps the map. The parent layout resizes correctly, but the map does not resize. Calling `.invalidate()` on the `MapView` has no effect. Am I doing something wrong, or is this not supported?

**Comment by tobrun** [comment]
@hanspeide thank you for reaching out and reporting your problem. This is a known issue that is we are investigating, @bleege created a test activity to tracked this down in #3622. Since there is not a open issue for this bug, we will be using this one.

@bleege I have assigned you since you have background + were already investigating this.

**Comment by hanspeide** [comment]
@tobrun Thanks. The screenshots in #3622 have the same layout problem that I'm seeing.

**Comment by bleege** [comment]
Work will be trackec in #3622.
