### ISSUE TITLE
Unable to select annotation on other side of antimeridian

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#3879]
When the viewport straddles the antimeridian but mostly contains the Western Hemisphere, clicking an annotation located in the Eastern Hemisphere does nothing. Likewise, when the center coordinate is in the Eastern Hemisphere, clicking an annotation in the Western Hemisphere does nothing.

/cc @boundsj

**Comment by jfirebaugh** [comment]
The rtree lookup in `AnnotationManager::getPointAnnotationsInBounds` needs to split bounds that cross the antimeridian into two wrapped bounds that don't cross it.

Also `AnnotationManager::addPointAnnotations` should probably ensure that rtree insertions happen with wrapped coordinates.

Alternatively, it may be possible to use `boost::geometry::cs::geographic` in [our registration](https://github.com/mapbox/mapbox-gl-native/blob/62bbf2627a32a57188e4026aca8dc337e07ded7f/src/mbgl/annotation/point_annotation_impl.hpp#L32-L33), rather than `boost::geometry::cs::cartesian`, and have boost do this for us automatically.

**Comment by 1ec5** [comment]
Fixed in #4285.
