### ISSUE TITLE
[android] Potential memory leak on MapView/MapboxMap

### ISSUE THREAD

**Issue by lgeromegnace** [mapbox/mapbox-gl-native#3972]
Hi guys! 

Great work with the MapboxMap implementation. We have noticed a potential memory leak around the `MapView` and `MapboxMap`:

* in `MapView`
```
    private void initialize(@NonNull Context context, @Nullable AttributeSet attrs) {
        mOnMapChangedListener = new CopyOnWriteArrayList<>();
        mMapboxMap = new MapboxMap(this); // => reference on MapboxMap
        mAnnotations = new ArrayList<>();
        mIcons = new ArrayList<>();
...
```  

* in `MapboxMap`
```
    MapboxMap(@NonNull MapView mapView) {
        mMapView = mapView; // reference on MapView
        mMapView.addOnMapChangedListener(new MapChangeCameraPositionListener());
        mUiSettings = new UiSettings(mapView); // reference on MapView
        mProjection = new Projection(mapView); // reference on MapView
        mSelectedMarkers = new ArrayList<>();
        mInfoWindows = new ArrayList<>();
    }
```

It looks like a cyclic reference that is never broken.

**Comment by mb12** [comment]
@lgeromegnace the cyclic references are fine and handled by mark and sweep garbage collection.  So long as the client application does not hold a reference to the activity containing   MapboxMap, these objects will be collected during garbage collection since these objects ate not unreachable  once the reference to  activity containing them is gone.

**Comment by lgeromegnace** [comment]
@mb12 thanks for the enlightenments! I close the issue.
