### ISSUE TITLE
Z-ordering of MGLAnnotationImages

### ISSUE THREAD

**Issue by johnnewman** [mapbox/mapbox-gl-native#3992]
Not a bug, just a support question.  On Mapbox iOS 3.1.1, is there a way to layer annotations on the map so that certain MGLAnnotationImages appear above or below others?  We have some pins that we'd like to take priority over others.  Thanks!

**Comment by 1ec5** [comment]
Currently that isn't possible with MGLAnnotations. If these markers or shapes are known at design-time, you could specify them in a GeoJSON source and set a style that uses that source. Otherwise, for runtime manipulation of individual features, we're currently blocked on mapbox/mapbox-gl-native#3630.

**Comment by friedbunny** [comment]
There is no way to affect the visual ordering of runtime annotations, at the moment. Per https://github.com/mapbox/mapbox-gl-native/issues/3971#issuecomment-184769454, how and when we implement this class of features depends on the ongoing (and huge) [style API refactor](https://github.com/mapbox/mapbox-gl-native/issues/837).

**Comment by johnnewman** [comment]
Ok, thanks for the help :smile:
