### ISSUE TITLE
How to judge the map is still or stable after flying or scrolling on Android SDK

### ISSUE THREAD

**Issue by Trinea** [mapbox/mapbox-gl-native#4075]
How to judge the map is still or stable after fling or scroll for  Android SDK

**Comment by tobrun** [comment]
@Trinea 
You can use `OnMapChangeListener` to listen MapChange events. You will need to use that listener in conjunction with your gesture listeners. This interaction will slightly improve with `4.0.0` release, due to the introduction of the `OnCameraChangeListener` but you will still have add some code to get the specific use-case you are describing.

**Comment by Trinea** [comment]
Thank you very, I have made it.
