### ISSUE TITLE
iOS Location services indicator always on

### ISSUE THREAD

**Issue by adamtb705** [mapbox/mapbox-gl-native#4086]
I have tried several different ways of initializing Mapbox in my iOS project (Fabric, setAccessToken(), and API key in info.plist), and iOS's location services indicator always turns on as soon as the access token code is run. It stays on while my app is active even when I'm not requesting a location and after I've stopped location updates when leaving my map. However, this does not occur prior to granting requestWhenInUseAuthorization on my main map, but it occurs in each subsequent app launch. 

I'm not really sure if this is an issue or whether it's expected behavior. Appreciate any thoughts you might have.

Thanks

**Comment by friedbunny** [comment]
This sounds like expected behavior — our SDKs gather telemetry data under a variety of circumstances, but especially when the app is running in the foreground. This telemetry data includes anonymized location information, which is why your app continues to indicate that it's using location services (because it is).

Check out [our telemetry overview](https://www.mapbox.com/telemetry/) for more information on how we use this aggregated data (_spoiler: to improve OSM_) and how fiercely we keep it anonymous and private. We're happy to answer questions you might have about any of this here, or you're welcome to get in touch with us [privately](https://www.mapbox.com/contact/).

**Comment by adamtb705** [comment]
Excellent. Thanks for the quick response.

**Comment by adamtb705** [comment]
For completion sake: I opted out of telemetry to test, and it behaves as expected.
