### ISSUE TITLE
Does mapbox android sdk support clustering?

### ISSUE THREAD

**Issue by MiguelFale** [mapbox/mapbox-gl-native#4111]
Hello!

Is there any API for clustering points in the map? If not, do you have an estimate of when it'll be available?

Thanks in advance!

**Comment by tmcw** [comment]
Hi @MiguelFale, we don't support clustering in the Android SDK quite yet. We just finished up implementing clustering for Mapbox GL JS and will port it to Android & iOS as soon as a few other features are shipped, like Offline. The ticket tracking this work is https://github.com/mapbox/mapbox-gl-native/issues/320

**Comment by Suyogyart** [comment]
Is "Annotation" clustering for Mapbox available yet for IOS sdk ??

**Comment by mf-mindcrewtech** [comment]
Is clustering is possible in android? and if yes so how?

**Comment by langsmith** [comment]
@mf-mindcrewtech , we've got a marker cluster plugin for Android. The documentation isn't quite published yet, which is why you hadn't known about it.

Here's the upcoming README about it:
[https://github.com/mapbox/mapbox-plugins-android/blob/e31b6bbb51a806f48a75ada970d2039405349a55/plugin-cluster/README.md](https://github.com/mapbox/mapbox-plugins-android/blob/e31b6bbb51a806f48a75ada970d2039405349a55/plugin-cluster/README.md)

Upcoming Android demo app marker cluster plugin example: [https://github.com/mapbox/mapbox-android-demo/blob/f05feea9599aee09df69589cf9c840dd356e62df/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/plugins/MarkerClustersPluginActivity.java](https://github.com/mapbox/mapbox-android-demo/blob/f05feea9599aee09df69589cf9c840dd356e62df/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/plugins/MarkerClustersPluginActivity.java)

[Current marker cluster plugin code](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-cluster)

Thanks for using Mapbox!

**Comment by novodimaporo** [comment]
Im trying to implement this, but it doesnt have any interface to put custom Icons on it, each marker I have needs a unique image.

**Comment by cooper1408** [comment]
@mf-mindcrewtech we are having hard time implementing clustering / symbol layer with custom icons in react native. can you please share your code or approach of android whatever you have done. on email vijay.sharma@appinventiv.com or share your email so that we can discuss.

**Comment by nitaliano** [comment]
@cooper1408 we have examples of clustering here https://github.com/mapbox/react-native-mapbox-gl/blob/master/example/src/components/EarthQuakes.js that could be a good starting point, or you can use https://github.com/mapbox/supercluster to manage clustering yourself.

you can open up an issue in https://github.com/mapbox/react-native-mapbox-gl or join https://gitter.im/react-native-mapbox-gl/Lobby I would be able to help you out 😄

**Comment by maley63** [comment]
@mf-mindcrewtech 
Would it be possible to share your code for the Android Clustering of different icons please?
I have recently created my first app for iPhone but struggling to implement the Android Clustering for this.
If you would like to email I could explain in more detail thanks.
Or if anyone could help or point in right direction it would be much appreciated.
Thanks,
maley6387@gmail.com

**Comment by mf-mindcrewtech** [comment]
Hi @cooper1408  and @maley63 ,

I will share the demo code by today.

**Comment by mf-mindcrewtech** [comment]
Hi @cooper1408 and @maley63 ,

Here is the code https://github.com/MaroofAhmedSiddique/MapBoxCustomClustering

If you have any questions, please let me know here or on skype : maroofahmedsiddique

**Comment by novodimaporo** [comment]
Hi, how do we cluster marker now? The plugin is removed.

**Comment by langsmith** [comment]
Hi @novodimaporo , please see https://www.mapbox.com/android-docs/maps/overview/clustering/
