### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Pasha0093** [mapbox/mapbox-gl-native#4134]
Hi have a black screen after execute

`CameraPosition.Builder cameraPosition = new CameraPosition.Builder() .target(position.toBoxLatLng()) .bearing(bearing).tilt(90); if(!isZoomed){ cameraPosition.zoom(16); } isZoomed = true; map.animateCamera(CameraUpdateFactory.newCameraPosition(cameraPosition.build()), 25000, null);`

Using com.mapbox.mapboxsdk:mapbox-android-sdk:3.2.0@aar

**Comment by Pasha0093** [comment]
this code work as expected but without animation 
 map.moveCamera(CameraUpdateFactory.newCameraPosition(cameraPosition.build()));

**Comment by tobrun** [comment]
@Pasha0093 thank you for reaching out and reporting your problem. 
This issue is no longer reproducible with the codebase for the `4.0.0` release.
If needed you can already use the `4.0.0-SNAPSHOT` to workaround this issue.
Note that there is a big API change between `3.2.0` and `4.0.0`.
Installation instructions can be found [here](https://www.mapbox.com/android-sdk/#gradle).
