### ISSUE TITLE
AddCircle method for map, support modify radius of circle

### ISSUE THREAD

**Issue by Trinea** [mapbox/mapbox-gl-native#4153]
Like below, we need add circle on the map, so we can change the radius constantly to make a animation.
![](https://github.com/Trinea/trinea-download/blob/master/temp/add-circle.gif?raw=true)

**Comment by Trinea** [comment]
@jjhurlock

**Comment by jjhurlock** [comment]
@Trinea We have a UserLocationView, that implements a similar effect [here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/UserLocationView.java)

Is this helpful to start implementing this feature?

**Comment by tobrun** [comment]
@jjhurlock while the SDK has a similar effect we are currently not exposing this as an API. This is something I have been thinking about in #3276. This will allow end developers to draw Android Views on a certain LatLng and give them the ability to do whatever they like with it.

Note that exposing this as an API has a history to it.. we prefer people using GL based markers because they are more performant and allow scaling. On the other hand these markers are very limited in what we can do with hem, for example having marker animation.

**Comment by Trinea** [comment]
ok, this is not urgent for us.

https://github.com/mapbox/mapbox-gl-native/issues/4090
https://github.com/mapbox/mapbox-gl-native/issues/3985
https://github.com/mapbox/mapbox-gl-native/issues/4159

These are urgent for us, please process first, Thank you

**Comment by zugaldia** [comment]
Just noting that the request here, if I understand correctly, is to (1) receive an event callback while hovering over a previously added marker, in order to trigger some custom behavior (in this case, (2) an animation).

@tobrun is this something unlocked for view markers now that https://github.com/mapbox/mapbox-gl-native/issues/3276 has landed?

**Comment by tobrun** [comment]
Yes, 

A user should be able to track the camera position with an OnCameraChangeListener and check if the LatLng from the camera matches the location of a Marker. If it does, the user should get a reference to the related view with `mapboxMap.getViewMarkerManager().getView(markerView)` and should be able to execute an animation.

**Comment by tobrun** [comment]
I created some sample code on achieving this with ViewMarkers in https://github.com/mapbox/mapbox-gl-native/pull/5346. 
@bleege is running point on integrating this into the location picker example #5282.

**Comment by zugaldia** [comment]
@tobrun Great, this looks fantastic.

As discussed in https://github.com/mapbox/mapbox-gl-native/pull/5346#issuecomment-225913453, @bleege is picking this code up together with the `MyLocationView` usecase to create a new sample activity that demoes this functionality.

@Trinea good news, this will be included in the next Android 4.1 release.

**Comment by zugaldia** [comment]
Related: https://github.com/mapbox/mapbox-gl-native/issues/2167#issuecomment-200302992

**Comment by zugaldia** [comment]
Done in https://github.com/mapbox/mapbox-gl-native/issues/4153.

**Comment by zugaldia** [comment]
@Trinea good news, this is also completed, and it will be available in the next release of the SDK.
