### ISSUE TITLE
Remove GSON From Offline Example TestApp

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#4172]
The [`CustomMetadata`](https://github.com/mapbox/mapbox-gl-native/blob/2b0749e3c6a4e87b6ad4a9978b1be93f1d57fc21/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/offline/CustomMetadata.java) helper class for the [`OfflineActivity`](https://github.com/mapbox/mapbox-gl-native/blob/2b0749e3c6a4e87b6ad4a9978b1be93f1d57fc21/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/OfflineActivity.java) makes use of Google's [Gson](https://github.com/google/gson) library for JSON serialization.  While using the Offline API in the Mapbox Android SDK **does NOT require using any Google libraries NOR Google Play Services** we can be clearer about this by utilizing the stock Android JSON API instead.

Let's solve this by making the `CustomMetadata` class part of the Offline API as this seems to be a core part of downloading a region for offline use.  Let's also use the Android JSON API under the hood to do the JSON serialization / deserialization.

/cc @zugaldia @tobrun

**Comment by zugaldia** [comment]
> While using the Offline API in the Mapbox Android SDK does NOT require using any Google libraries NOR Google Play Services.

To clarify, there are no dependencies in the offline implementation in either Google libraries nor Google Play Services. This is just sample code in the TestApp and developers are free to use other approaches. Note though that we do currently have a [dependency on Gson](https://github.com/mapbox/mapbox-directions-android/blob/master/directions/lib/build.gradle#L34) for the directions and geocoding libraries (which I reused for this sample code).

> Let's solve this by making the CustomMetadata class part of the Offline API as this seems to be a core part of downloading a region for offline use.

I believe this against the [API design](https://github.com/mapbox/mapbox-gl-native/blob/master/include/mbgl/storage/offline.hpp#L54-L61) we have in mind for the metadata object, but @jfirebaugh can correct me otherwise. The Android SDK bindings should leave the interpretation of this metadata up to the application to improve portability.

Having said that, I don't see any problems rewriting the sample code to purely use Android stock APIs.

**Comment by bleege** [comment]
> I believe this against the API design we have in mind for the metadata object, but @jfirebaugh can correct me otherwise. The Android SDK bindings should leave the interpretation of this metadata up to the application to improve portability.

This is great to learn.  Coming to the API as a noob I wasn't sure what was stuff the API would provide for me vs what I need to provided for my app.  Anything we can do to make this more obvious and guide developers will be a big win.

> To clarify, there are no dependencies in the offline implementation in either Google libraries nor Google Play Services. 

Exactly.  Mapbox Android products target and use stock Android (AOSP) API and not OEM nor Google specific implementations.

**Comment by zugaldia** [comment]
> Anything we can do to make this more obvious and guide developers will be a big win.

Agreed. It's [already explained in the javadoc](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java#L27-L32), but we can make it more explicit either in the `getMetadata` method code or once we surface the examples.
