### ISSUE TITLE
Android warning: building without thread priority control

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#4188]
I have observed the following warning when building the `android` target lately:

```
  CXX(target) Release/obj.target/platform-android/platform/default/thread.o
../../platform/default/thread.cpp:23:9: warning: Building without thread priority control [-W#pragma-messages]
#pragma message("Building without thread priority control")
        ^
1 warning generated.
```

Not sure how critical this is but thought of flagging it just in case.

/cc: @bleege @tobrun @jfirebaugh @tmpsantos

**Comment by tmpsantos** [comment]
This is not critical, just a nice to have.

The define needed to get this working (`SCHED_IDLE`) is available since Android NDK API Level 21. I just checked on mason we use API 9 for some platforms and for some others 21.

Build to x86 spits the warning (API 9), for x86-64 doesn't (API 21). I believe ARM for instance is fixed at 9 because of backwards compatibility. x86-64 support started at API 21 so it makes sense to fix the NDK for x86-64 from 21.

![screenshot from 2016-03-03 16-27-29](https://cloud.githubusercontent.com/assets/996307/13506438/e166f592-e15c-11e5-9f64-62d9cb64dca3.png)

**Comment by zugaldia** [comment]
That makes sense, thank you @tmpsantos for the :eyes: !
