### ISSUE TITLE
Enable Proguard For Debug And Release In Android TestApp

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#4201]
Per @tobrun's recommendation we should run the TestApp with Proguard so that the development team can catch Proguard issues sooner than internal testing reveals.  Let's add it to both `Debug` and `Release` build types in the TestApp's build.gradle.

/cc @zugaldia @tobrun

**Comment by tobrun** [comment]
One thing I'm not :100: on is enabling proguard for debug builds, mainly because it will increase build time during development and developer efficiency is something I deeply care about.

 To back this up I did a test:

Without proguard:
<img width="378" alt="screen shot 2016-03-05 at 11 54 26" src="https://cloud.githubusercontent.com/assets/2151639/13548927/73966642-e2c9-11e5-9d1e-61d828453a72.png">

With proguard:
<img width="364" alt="screen shot 2016-03-05 at 11 55 27" src="https://cloud.githubusercontent.com/assets/2151639/13548931/80982db2-e2c9-11e5-994f-8017c9e42e4b.png">

**Comment by zugaldia** [comment]
> One thing I'm not :100: on is enabling proguard for debug builds, mainly because it will increase build time during development and developer efficiency is something I deeply care about.

I'm also fine with enabling proguard only for release builds. Not only it's a time saver, it's also good to have a debug build without proguard so that we could have a proguard-free baseline.

**Comment by bleege** [comment]
I agree that time is important on builds and speeding them up is A Good Thing™.  That said, I worry that if we only enable proguard for Release flavor builds we won't have solved anything as the 3 of us will still likely being using Debug flavor for day to day to development.  Humans.

The only way around this would be if we had some sort of automated Testing system as part of our CI process that built and used the TestApp on devices that are managed by a 3rd party cloud provider.  Hmmm.  :wink:
