### ISSUE TITLE
Javadoc Offline package for 4.0.0

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4295]
We are missing some class javadoc for the `offline` package, method javadoc should be validated.

<img width="1066" alt="screen shot 2016-03-12 at 17 09 31" src="https://cloud.githubusercontent.com/assets/2151639/13725647/5d982a72-e875-11e5-8c43-d1aeb7c812af.png">

**Comment by zugaldia** [comment]
@danswick @cammace I've added the missing javadoc blocks to the callbacks listed above in https://github.com/mapbox/mapbox-gl-native/tree/4295-offline-javadoc. Please review if the docs look good to proceed to merge with the release branch. Otherwise, please feel free to make any changes in that branch.

**Comment by cammace** [comment]
@zugaldia I'll take a look

**Comment by cammace** [comment]
:+1:

**Comment by zugaldia** [comment]
@cammace our `beta.1` docs just went live in https://www.mapbox.com/android-sdk/api/4.0.0-beta.1/ (without these changes though). Could you check other classes/fields to make sure that are well documented too? Thanks!

**Comment by zugaldia** [comment]
Merging the docs as they are, if there's anything else that needs to be documented, let's open a new ticket.
