### ISSUE TITLE
Add Circle (with radius expressed in physical units)

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4312]
A circle on the earth's surface on a specific LatLng as center.
iOS equivalent: https://github.com/mapbox/mapbox-gl-native/issues/2167

**Comment by tmcw** [comment]
Given that there are circles defined from

* Pixel radius
* Meter radius, but always a circle in mercator
* Meter radius, and actually a [spherical cap](https://en.wikipedia.org/wiki/Spherical_cap), so sometimes oblong on mercator

We should have a solid vocabulary that helps differentiate from the beginning.

**Comment by 1ec5** [comment]
> Meter radius, and actually a spherical cap, so sometimes oblong on mercator

#1726 tracks what’s called a geodesic polyline on iOS.

**Comment by tobrun** [comment]
I created this issue for parity with [gmaps](https://developers.google.com/android/reference/com/google/android/gms/maps/model/Circle). There they define this circle as `sperical cap`.

**Comment by zugaldia** [comment]
We're in a good position now to add this API. Meanwhile, we currently have three workarounds:

* Using a polygon: https://github.com/mapbox/mapbox-gl-native/issues/2167#issuecomment-200302992
* Using a MarkerView: https://github.com/mapbox/mapbox-gl-native/pull/5346
* Using the Runtime Style API: [`CircleLayerActivity`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/CircleLayerActivity.java)

**Comment by 1ec5** [comment]
Note the differences between the three approaches: the polygon approach is for a circle whose radius corresponds to a physical ground distance, whereas the `MarkerView` and `CircleLayerActivity` approaches are for circles whose radii correspond to fixed screen distances, regardless of the zoom level or latitude.

**Comment by bilthon** [comment]
Using a polygon feels like a hackish workaround. This feature should really be supported at the native level.

**Comment by tobrun** [comment]
Circles are supported through CircleLayer, we do not expose an annotation API for it atm.

**Comment by bilthon** [comment]
The problem I have with the CircleLayer right now is that the only way I found of creating a circle with dynamic in-app data is using a geoJSON source. But geojson doesn't seem to allow us to specify a circle. https://stackoverflow.com/questions/16942697/geojson-circles-supported-or-not

**Comment by zugaldia** [comment]
> The problem I have with the CircleLayer right now is that the only way I found of creating a circle with dynamic in-app data is using a geoJSON source. But geojson doesn't seem to allow us to specify a circle.

For a `CircleLayer` is enough if you set a point to indicate the center of the circle. For example, you could create a `GeoJsonSource` with:

```
GeoJsonSource geoJsonSource = new GeoJsonSource("circle-source",
    Point.fromCoordinates(Position.fromLngLat(-0.07520, 51.50550)));
mapboxMap.addSource(geoJsonSource);
```

And then use the `CircleLayer` to visualize it:

```
CircleLayer circleLayer = new CircleLayer("circle-layer", "circle-source");
circleLayer.setProperties(
    PropertyFactory.visibility(Property.VISIBLE),
    PropertyFactory.circleRadius(25f),
    PropertyFactory.circleColor(Color.argb(1, 55, 148, 179)));
mapboxMap.addLayer(circleLayer);
```

If you need more control over the circle, another option you might want to look into is the `SymbolLayer`. The [`LocationLayer`](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugins/locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayer.java) plugin is a good example of it.

**Comment by 1ec5** [comment]
@tobrun @zugaldia, please note that there’s a fundamental difference between the kind of circle drawn by CircleLayer (whose radius is expressed in screen units) and the kind of circle that’s tracked in this ticket (whose radius corresponds to a physical distance). Please refer to https://github.com/mapbox/mapbox-gl-native/issues/4312#issuecomment-247448140. This is still a valid feature request, although there’s a tension between implementing this very useful feature while at the same time conforming to the Simple Features specification and GeoJSON.

**Comment by jrgonzalezg** [comment]
Now there seems to be annotation support for circles using `CircleOptions` and `CircleManager`. And the `CircleOptions` seem quite similar to the Google Maps version, but unlike the behavior on Google Maps it seems that the radius here is using screen pixels instead of meters and the circle does not properly scale with zoom. Workarounds like sampling the circumference and using a polygon with `FillManager` work but require quite a bit of boilerplate. Also I don't really understand what's the purpose of `CircleManager` / `CircleOptions` working that way with radius in device pixels and ignoring zoom changes. Will it be possible to fix this to work as Google Maps (if there aren't any valid use cases for the current behavior) or to provide a variant that works like in Google Maps?

**Comment by androideveloper** [comment]
Coming from Google Maps and found the same issue. Any updates on this?

**Comment by p-fischer** [comment]
Hi, it seems the only workaround to achieve a circle with a radius defined in meters is to draw a polygon.
Since the polygon drawing API got less accurate over recent mapbox versions (see my issue #13125) and is officially marked as deprecated in Mapbox Android SDK v7 I want to stress an urgency to provide a new API for this common use case.

**Comment by tobrun** [comment]
First step to implement this feature is supporting http://turfjs.org/docs/#circle in the java port of turf. This is ticketed in https://github.com/mapbox/mapbox-java/issues/1002.

**Comment by elroid** [comment]
This is very much still an issue, and I'm unclear why it appears to be so fundamentally blocked. I'd venture to guess the vast majority of your users will be coming from a similar deployment using Google Maps, and there's no reason to expect that this crucial aspect works differently to the way it does there - especially since just about everything else in the MapBox SDK mirrors it so closely. I'm not even clear what the point of being able to draw a fixed-size circle over a map is. If the state of the map view was irrelevant I could draw something similar to this using a normal Android view and just place it on top of the MapView. 
At the very least, if this problem is not going to be addressed (and after 4 years of discussion, I'm not holding my breath), there should be a clear example somewhere of how to draw a geographically-static-sized circle using the existing SDK. I've spent the last hour trying to establish the approved workaround and I'm so far none the wiser. :-(

**Comment by miladsalimiiii** [comment]
> 

Did you try this ?! for draw circle

**Comment by miladsalimiiii** [comment]
> > The problem I have with the CircleLayer right now is that the only way I found of creating a circle with dynamic in-app data is using a geoJSON source. But geojson doesn't seem to allow us to specify a circle.
> 
> For a `CircleLayer` is enough if you set a point to indicate the center of the circle. For example, you could create a `GeoJsonSource` with:
> 
> ```
> GeoJsonSource geoJsonSource = new GeoJsonSource("circle-source",
>     Point.fromCoordinates(Position.fromLngLat(-0.07520, 51.50550)));
> mapboxMap.addSource(geoJsonSource);
> ```
> 
> And then use the `CircleLayer` to visualize it:
> 
> ```
> CircleLayer circleLayer = new CircleLayer("circle-layer", "circle-source");
> circleLayer.setProperties(
>     PropertyFactory.visibility(Property.VISIBLE),
>     PropertyFactory.circleRadius(25f),
>     PropertyFactory.circleColor(Color.argb(1, 55, 148, 179)));
> mapboxMap.addLayer(circleLayer);
> ```
> 
> If you need more control over the circle, another option you might want to look into is the `SymbolLayer`. The [`LocationLayer`](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugins/locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayer.java) plugin is a good example of it.

Did you try this ?! for draw circle
