### ISSUE TITLE
Add LocationSource

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4331]
[LocationSource](https://developers.google.com/android/reference/com/google/android/gms/maps/LocationSource) is our equivalent of `LocationServices`.

**Comment by bleege** [comment]
Can you describe in more detail what problem this issue would solve?

**Comment by mkv123** [comment]
Currently the user location marker is internally hardcoded to use the device's GPS positioning to define where it is. Imho this is architecurally a bit at odds with separating data and visualization, but also in a very practical sense it makes the position marker very inflexible. 

For example let's say you want a virtual walk through of the route, like a play button to preview your journey. Currently we'd have to re-implement the user position marker for this functionality, instead of simply setting its location. Another case would be for using any 3rd party location source, ranging from IP address to airplane schedules to qr codes.

**Comment by mkv123** [comment]
@tobrun Btw, why the SEMVER-MAJOR tag? If implemented in the same way as in google-play-services, where you provide a default one, but allow overriding it, it wouldn't break API as far as I can tell.

**Comment by tobrun** [comment]
@mkv123 sorry for only getting back to you now. The initial focus of this ticket was to rename `LocationServices` to `LocationSource` (reason behind the `semver`-label). Since posting this some requirements have changed and including a pluggable system for anything location related is on our list of long term improvements to the SDK.

**Comment by tobrun** [comment]
Looking a bit more into this it seems that there are two requirements here:
 - general refactor of LocationServices to be a default LocationSource
 - make pluggable system using the LocationSource interface

**Comment by tobrun** [comment]
Been working on this a bit and need to conclude that this requires a bigger lift as initially thought. Making the system pluggable requires bigger refactors to LocationServices and Telemetry. We ideally pick this up when we introduce a separate telemetry module. I'm going to submit some fixes that I made to telemetry separately.

**Comment by zugaldia** [comment]
We have recently made some progress here:

> general refactor of LocationServices to be a default LocationSource

With https://github.com/mapbox/mapbox-java/issues/269 we now have an abstract `LocationEngine` with sample implementations for Lost and Play Services. We could tweak the former as the default implementation for our `LocationSource`. It conforms to `LocationSource` while expanding its functionality.

> make pluggable system using the LocationSource interface

That's achieved with the newly introduced `LocationEngine` interface.

**Comment by zugaldia** [comment]
Fixed via https://github.com/mapbox/mapbox-gl-native/pull/7892.
