### ISSUE TITLE
Nightly 4.0.0 release builds

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#4351]
The Android nightly build builds the `master` branch. In the run up to the 4.0.0 final release, should we switch this over to the `release-ios-3.2.0-android-4.0.0` branch? Or create a second scheduled nightly build?

cc @zugaldia @bleege

**Comment by zugaldia** [comment]
@jfirebaugh If the goal, apart from building/testing daily, is to potentially get more apps using it, I'd prefer to switch it over to the `release-ios-3.2.0-android-4.0.0` branch temporarily so that the current snapshot set up / instructions just work.

**Comment by bleege** [comment]
I'll echo @zugaldia preference to use `release-ios-3.2.0-android-4.0.0` until `4.0.0` officially releases.  I'll make the change in Bitrise now so that tonight's SNAPSHOT comes from the release branch.

**Comment by bleege** [comment]
I replaced the `scheduled` workflow's Git Clone's step's Branch setting with `release-ios-3.2.0-android-4.0.0` from it's original `$BITRISE_GIT_BRANCH`.  To test this out I was going to schedule an immediate build of this workflow, but the UI for doing so forces a branch to be selected automatically instead of relying on the script.  In other words we'll have to let this run on it's own later tonight and check the log to see if it worked.

<img width="589" alt="screen shot 2016-03-16 at 5 40 09 pm" src="https://cloud.githubusercontent.com/assets/989928/13829744/edf51ae0-eb9e-11e5-9227-230f3627fd2a.png">
_New Setting_

**Comment by jfirebaugh** [comment]
Judging by https://github.com/mapbox/mapbox-gl-native/issues/4330#issuecomment-197769707, nightly builds are working as expected.
