### ISSUE TITLE
iOS, Android are not using the offline database

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#4362]
iOS creates an offline database named ["offline.db"](https://github.com/mapbox/mapbox-gl-native/blob/ff9c3a57b05fa3287a126ffd7c66cddc7e0929dc/platform/darwin/src/MGLOfflineStorage.mm#L25-L25), but then uses the name ["cache.db"](https://github.com/mapbox/mapbox-gl-native/blob/c2cd9335e9c9ff599cd84723eada6a503d1e5c80/platform/ios/src/MGLMapView.mm#L312-L312) for the actual map view. These need to be the same name, if not the same instance of `DefaultFileSource`.

**Comment by jfirebaugh** [comment]
It looks like the path, as well as the name, is different.

**Comment by 1ec5** [comment]
I copied the Android SDK, which is doing the same thing: [mbgl-cache.db](https://github.com/mapbox/mapbox-gl-native/blob/20c3706536ac9e927f80a50e9ec8906dfd0d2baf/platform/android/src/native_map_view.cpp#L79), [mbgl-offline.db](https://github.com/mapbox/mapbox-gl-native/blob/55cacfafd47d81204161e789c4282e0537152591/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java#L17).

**Comment by 1ec5** [comment]
On iOS, per #4371, the unified cache definitely shouldn’t go in the Caches directory, where the ambient cache currently resides. If we put it in the Documents directory, where the offline cache currently resides, a .db file will be listed in iTunes as a shareable document for every Mapbox-powered application, which is a poor user experience. As a compromise, we can put the unified cache in Application Support, but there are two caveats:

1. It isn’t possible for a user to export their offline cache to another device or import it from another device. For example, if a user installs both the iOS and OS X versions of an application, they can currently drag their OS X offline cache into iTunes, and the iOS application should automatically be able to make use of it.
1. If disk space runs low on the iOS device, the unified cache will continue to eat up disk space, potentially due to ambiently cached content, and the only way to reclaim that space would be to delete the application.

**Comment by 1ec5** [comment]
#4372 puts the OS X offline cache in a subfolder of Application Support, but neither caveat in https://github.com/mapbox/mapbox-gl-native/issues/4362#issuecomment-198131488 applies to OS X.

**Comment by 1ec5** [comment]
Per chat, on iOS, we’re going to place the offline cache in Application Support. If there’s an existing offline.db in Documents, we’ll move it; if there’s an existing caches.db in Caches, we’ll delete it.

**Comment by NamtarR** [comment]
In Android after complete download of a region and switching off network connection the map is not using downloaded data - it shows nothing after move or zoom change. Moreover, if I switch network connection and then launch the app it is trying to load style data (and that is the style the region has been downloaded with) from Mapbox servers and it crashes with no exception but

    03-18 10:38:40.768 9236-9304/ru.aspirity.stolbyapp E/mbgl: {Map}[Setup]: loading style failed: Unable to resolve host "api.mapbox.com": No address associated with hostname
    03-18 10:38:40.769 9236-9304/ru.aspirity.stolbyapp A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 9304 (Map Thread)

It seems it is not using offline data at all.

**Comment by 1ec5** [comment]
Fixed in the iOS and OS X SDKs in #4377.

**Comment by zugaldia** [comment]
Android work is in https://github.com/mapbox/mapbox-gl-native/pull/4383.

**Comment by 1ec5** [comment]
Closing in favor of #4377 on iOS and OS X and #4383 on Android. Unifying the `mbgl::DefaultFileSource` on Android is tracked as tail work in #4386.

**Comment by 1ec5** [comment]
@NamtarR, the fix is now in the [v3.2.0-beta.2](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.2.0-beta.2) of the iOS SDK. Please let us know if you continue to see this issue. Thanks!

**Comment by zugaldia** [comment]
Android fixed this in https://github.com/mapbox/mapbox-gl-native/pull/4383 and the fix will be available in the next SNAPSHOT.
