### ISSUE TITLE
Marking MGLOfflinePack init method NS_UNAVAILABLE inhibits unit testing

### ISSUE THREAD

**Issue by postmechanical** [mapbox/mapbox-gl-native#4421]
The use case is testing of a category on `MGLOfflinePack` to add functionality to `MGLOfflinePack` instances that are specific to the app domain. The `NS_UNAVAILABLE` attribute on `MGLOfflinePack` prevents the use of partial mocks. Going through `MGLOfflineStorage`'s `addPackForRegion:withContext:completionHandler:` just to obtain a `MGLOfflinePack` instance to mock is overkill.

**Comment by 1ec5** [comment]
For context, `-init` was marked unavailable because the [actual designated initializer](https://github.com/mapbox/mapbox-gl-native/blob/ios-v3.2.0-beta.2/platform/darwin/src/MGLOfflinePack.mm#L57) is private by necessity. (Its first parameter is a namespaced C++ object, which would be incompatible for any pure Objective-C or Swift projects.)

**Comment by postmechanical** [comment]
@1ec5 How about exposing a purse Obj-C/Swift project initializer like `- (instancetype)initWithRegion:(id <MGLOfflineRegion>)region`?

**Comment by 1ec5** [comment]
That would be great, but unfortunately, I don’t think it’s possible for a C++ type to conform to an Objective-C protocol.

**Comment by 1ec5** [comment]
Fundamentally, this class is just a wrapper around a C++ object (the one that gets passed into this initializer). Maybe we can flip this around: you'd initialize a pack with the region and context, but it would remain invalid until you add it to the shared MGLOfflineStorage (which would set the mbgl::OfflineRegion property behind the scenes).

**Comment by postmechanical** [comment]
@1ec5 Why not have `MGLOfflinePack` extract the C++ object rather than `MGLOfflineStorage`?

https://github.com/mapbox/mapbox-gl-native/blob/1ee7264b0edf6601a8170a30c40af4282679f495/platform/darwin/src/MGLOfflineStorage.mm#L86

**Comment by 1ec5** [comment]
`-addPackForRegion:withContext:completionHandler:` isn’t so much extracting the C++ object as it is creating the C++ object asynchronously. My intended fix for #4287 would couple MGLOfflinePack more closely to MGLOfflinePack, so that MGLOfflinePack will have a `packs` property, but it would be awkward for that property to change just because `-[MGLOfflinePack init]` is called.

I think your proposal would make more sense if MGLOfflinePack appeared to be entirely independent of MGLOfflineStorage from a client perspective. Following that line of reasoning, MGLOfflineStorage wouldn’t maintain a central registry of packs; it’d still be up to your class to strongly reference the pack somewhere. But then there’s no way to implement a “get all packs” API that would return the same objects each time you call it.

**Comment by postmechanical** [comment]
@1ec5 How are you testing `MGLOfflinePack` then?

**Comment by 1ec5** [comment]
Currently, we’re testing only the underlying `mbgl::OfflineRegion` object and the end-to-end functionality provided by MGLOfflineStorage. I opened #4426 to track bringing our existing tests into a public repository and test MGLOfflinePack in isolation.

**Comment by 1ec5** [comment]
#4482 removes the `NS_UNAVAILABLE` attribute. However, note that `-[MGLOfflinePack init]` creates a pack that’s invalid right off the bat, so any call to the built-in methods raises an exception. This is unavoidable in the current architecture because packs are tightly coupled to the MGLOfflineStorage singleton. Hopefully this helps with your use case. The same PR adds tests of MGLOfflineStorage, where most of the SDK-level offline logic lives, as well as some trivial tests of MGLOfflinePack.

**Comment by 1ec5** [comment]
Fixed in #4482, which will be in v3.2.0-beta.3.
