### ISSUE TITLE
[someOfflinePack suspend] doesn't work immediately

### ISSUE THREAD

**Issue by khavn** [mapbox/mapbox-gl-native#4451]
Sorry, my English is not good.
I use Mapbox 3.2.0 beta 2.
I create a offline region and active download it. When I call suspend method for pause download. Offline keep downloading. it will stops after a few seconds.
I think when suspend method is called. Offline pause immediately.
It will be easier to use. Because if user taps stops, but download keep going, user tap again. default_file_source object will create many threads Inactive and Active.

**Comment by 1ec5** [comment]
See https://github.com/mapbox/mapbox-gl-native/issues/4418#issuecomment-199552625 and https://github.com/mapbox/mapbox-gl-native/issues/4229#issuecomment-193577954 for an explanation of this behavior. In practice, an offline pack is more likely to pause immediately if it’s currently downloading tiles that aren’t cached due to normal map usage. But regardless, there’s no guarantee that pausing would take effect immediately, because everything about an offline pack is asynchronous.
