### ISSUE TITLE
[ios] how to stopUpdatingLocation?

### ISSUE THREAD

**Issue by Sh1mor1nka** [mapbox/mapbox-gl-native#4539]
Is there any way to manually stop updating location?

**Comment by boundsj** [comment]
Hi @Sh1mor1nka. I assume you are asking about the [iOS Core Location Manager's `stopUpdatingLocation` method](https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocationManager_Class/#//apple_ref/occ/instm/CLLocationManager/stopUpdatingLocation). The iOS SDK uses that API in a few places (map view and telemetry). Can you please say more about which location manager you are referring to? Also, any details you can provide about your use case for turning off location services would be helpful.

**Comment by boundsj** [comment]
@Sh1mor1nka you can control the behavior you are describing in the map view by setting [`showsUserLocation`](https://www.mapbox.com/ios-sdk/api/3.1.2/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(py)showsUserLocation) [see docs](https://www.mapbox.com/ios-sdk/api/3.1.2/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(py)showsUserLocation) as required for your application.

Regarding the presence or lack thereof of the location arrow in the iOS status bar: We've found that the arrow may take several seconds to disappear after you disengage your app's use of location services. Also, since the status bar arrow (like the network activity indicator) represents all location services activity for all apps on your device including iOS system services that use location, it may not disappear at all because of another app or service -- even if your app is not using the location APIs.

**Comment by Sh1mor1nka** [comment]
@boundsj I tried set `showsUserLocation` to `NO`, but arrow wan't disappear.

> Regarding the presence or lack thereof of the location arrow in the iOS status bar: We've found that the arrow may take several seconds to disappear after you disengage your app's use of location services. 

Correct. After I send app to background with enabled `NSLocationWhenInUseUsageDescription` arrow disappears in ~10 seconds.

> Also, since the status bar arrow (like the network activity indicator) represents all location services activity for all apps on your device including iOS system services that use location, it may not disappear at all because of another app or service -- even if your app is not using the location APIs.

I'm sure that only my app use location at this moment.

In fact `NSLocationWhenInUseUsageDescription` almost what i want so i close issue. Thank you for help!

**Comment by boundsj** [comment]
Thanks @Sh1mor1nka. Please also note: when the app is running in the foreground and shows a map view, the SDK runs [Mapbox Telemetry Services](https://www.mapbox.com/telemetry) which also uses an iOS location manager. Currently, Telemetry will run for the duration of a session that uses a map view. In your case, this may be the reason for the continued presence of the arrow while the app is running.
