### ISSUE TITLE
[Android] Custom user location marker behaviour

### ISSUE THREAD

**Issue by NamtarR** [mapbox/mapbox-gl-native#4552]
I need to implement user location tracking with device and also show user's bearing with device compass sensor (if it is present, of course). Two choices for implementing user location tracking are custom tracking and enabling Mapbox setMyLocationEnabled(true).
While implementing my own custom tracking I got stuck with the problem of rotating user marker icon. It seems that there is no way to do that right. I have tried getting already showing icon and rotating its bitmap, but this leads to OOM in no time.
Mapbox user tracking seems to lack user marker customization features and there is no way to show any custom user icon with heading.
What can I do about it and will there be any changes in Mapbox user location tracking?

**Comment by tobrun** [comment]
@NamtarR thank you for reaching out, we are aware about the issues you are bringing forward here. 
For this I created a master ticker on UserLocationView refactor in #4396. I can't give you an ETA when this is going to land but it's high on my priority list. I would love if you could review the items in #4396 and add remarks on them. 

 - did you see that we expose user location tracking in `mapboxMap.getTrackingSettings()`?

Since we already have another ticket tracking this, I'm going to close.

**Comment by haydenkaizeta** [comment]
@tobrun it seems this was closed but only a way to follow the compass was added. is there a way to provide custom bearing? if you enable bearing currently it seems to me you can only track compass or set to always north.
