### ISSUE TITLE
Convert auxiliary iOS Bitrise workflows to checked in scripts

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#4642]
The ["nightly" and "release" workflows](https://www.bitrise.io/app/7514e4cf3da2cc57/workflow/editor) should live in https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/bitrise.yml. We need change control and history for these processes.

See the [Android platform equivalent](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/bitrise.yml) for an example of how to do this.

**Comment by 1ec5** [comment]
Yes, agreed. The current workflows are prototypes only, and we should commit them once we're happy with and committed to their functionality (hah!).

As part of this, we should stop pinning our steps to specific versions. The checked-in workflows are using very outdated versions of steps because we don't have a good alert mechanism for outdated steps.

**Comment by boundsj** [comment]
I've been looking at bitrise a lot recently. I can take this once https://github.com/mapbox/mapbox-gl-native/pull/4641lands and we have the prototype workflows working reasonably well.

**Comment by friedbunny** [comment]
We effectively did this in #7005 and #10170 — the prototype workflows have been deleted and we only run workflows from `bitrise.yml`.
