### ISSUE TITLE
Eliminate iOS package.sh

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#4645]
The iOS platform `package.sh` script should be expressed as a set of make rules in the Makefile. Or alternatively, as a single make rule parameterized by environment variables and driven by a build matrix. (Too bad Bitrise doesn't have build matrixes.)

**Comment by 1ec5** [comment]
I think we should move the meat of package.sh into the Xcode projects themselves, as build phases. The build you build in Xcode should be more or less the same thing we release. Most of the variants are due to differences in where we copy resources, and the project is better suited to dealing with that.

We can of course provide a make rule with different variables, but it should ideally amount to a single invocation of xcodebuild. That would greatly simplify deployment automation.

**Comment by jfirebaugh** [comment]
Since we're now using package.sh in OS X, I guess we decided not to do this.

**Comment by 1ec5** [comment]
Yeah, unfortunately it isn’t feasible on iOS because a target can only build for one destination at a time. I decided to make the OS X SDK parallel whatever we’re doing on the iOS side, just to keep things consistent.
