### ISSUE TITLE
MGLLocationManager starts monitoring for regions

### ISSUE THREAD

**Issue by Lengo46** [mapbox/mapbox-gl-native#4654]
Hello Mapbox team,

In the new Mapbox version 3.2.0. The MGLLocationManager starts monitoring for regions every second when the user moves. I do **not** use MGLLocationManager, but I monitor all regions for my App.

`func locationManager(manager: CLLocationManager, didStartMonitoringForRegion region: CLRegion) {
        print("Starting monitoring \(region.identifier)")
    }`

My log keeps flooding with MGLLocationManagerRegionIdentifier.fence.center

`Starting monitoring MGLLocationManagerRegionIdentifier.fence.center
Starting monitoring MGLLocationManagerRegionIdentifier.fence.center
Starting monitoring MGLLocationManagerRegionIdentifier.fence.center
Starting monitoring MGLLocationManagerRegionIdentifier.fence.center
Starting monitoring MGLLocationManagerRegionIdentifier.fence.center`

Doesn't this drain the battery?

**Comment by boundsj** [comment]
Thanks @Lengo46. 

[This guard] (https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/src/MGLLocationManager.m#L139) should prevent calls to the location manager's `startMonitoringForRegion` once the `monitoredRegions.count` is > 0. The region radius used in v3.2.0 is 300 meters. So, it surprising that your logs indicate that the region is exited "every second when the user moves" -- calls to `startMonitoringForRegion` should naturally be less. That said, the current implementation should re-establish the region frequently (i.e. several times per minute) if the user is moving down a road at highway speeds.

In any case, I don't think that this is problematic for the battery since MGLLocationManager only keeps one named region so the Cocoa location manager [will just replace the existing one with a new one](https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocationManager_Class/#//apple_ref/occ/instm/CLLocationManager/startMonitoringForRegion:). Also, the purpose of the region monitoring is actually intended to help battery drain -- you can [read about our work in that area blog](https://www.mapbox.com/blog/introducing-hibernation-mode/).

In the meantime, so that we can try to tame those logs, can you please say more about your test setup? Are you seeing this on a device or simulator? What iOS version? Any other specifics of your environment, like poor connectivity, that might prevent the guard I mentioned above from engaging (i.e. anything that would prevent a region from getting established initially?)

**Comment by Lengo46** [comment]
Hi boundsj,

Thanks for your reply. Above error happend on de simulator (iPhone 6s, iOS 9.3.1). In the coming week I will also test it on a real device. Connection was good.

**Comment by boundsj** [comment]
@Lengo46 following up, the existing "guard" will not stop regions from being created - it only aborts creating regions for locations that are less accurate than the threshold. In fact, a region can be created as a device moves at a frequency of as much as one per second. This does not impact the battery and, in fact, the region monitoring helps telemetry very much since it allows it to shut down when a device is not moving. Resetting the region as the user moves is actually the safest way to go since we always have the best chance at having a region established at the device current location when hibernation starts.

Still, since the region monitoring API is a shared resource, it would be nice to be less demanding of it if for no other reason than to reduce the number of calls back to the `didStartMonitoringForRegion` delegate of any arbitrary location manager instance. I'd like to leave this open and update the region creation logic in the future. Thanks for your contribution!

**Comment by boundsj** [comment]
stale

**Comment by lefleets** [comment]
> [This guard](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/src/MGLLocationManager.m#L139) should prevent calls to the location manager's `startMonitoringForRegion`

I'd be curious to see this and learn more. Link is 404. Is it still around or is there updated info?

Thanks!
