### ISSUE TITLE
what is the intended constrain behaviour?

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-native#4655]
https://github.com/mapbox/mapbox-gl-native/blob/35b579fde196ec3dd2a487ab5d528c8662571a43/src/mbgl/map/transform_state.cpp#L297-L299

``` cpp
scale_ = util::max(scale_,
                       static_cast<double>((rotatedNorth() ? height : width) / util::tileSize),
                       static_cast<double>((rotatedNorth() ? width : height) / util::tileSize));
```

looks like it's equivalent to

``` cpp
scale_ = util::max(scale_,
                       static_cast<double>(width / util::tileSize),
                       static_cast<double>(height / util::tileSize));
```

@1ec5 Is this the intended behaviour?

It's constraining based on the width even if the constrain mode is `HeightOnly`.

**Comment by 1ec5** [comment]
Yes, I made this change in #3401, so that the only difference between the two modes is that WidthAndHeight prevents you from seeing both sides of the antimeridian at a time, while HeightOnly allows scrolling seamlessly across it. The current HeightOnly behavior matches other SDKs and avoids the situation where the same coordinate appears twice on screen. If there is a need for tiling the world multiple times, we should add another constraining mode.

**Comment by 1ec5** [comment]
This part of #3401 was motivated by a bug in the OS X SDK, but in principle you would've seen the same thing in the iOS SDK on an iPad:

> Before this change, osxapp effectively constrained the zoom level based on whether the window was shorter or taller than 512 points.

I suppose I could've fixed that issue by turning off all constraints, but we don't show anything beyond certain latitudes.
