### ISSUE TITLE
Location services not working when app is in background

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#4715]
**Platform: iOS**
**Mapbox SDK version: 3.2.0**

### Steps to trigger behavior

 1. Open navigation app and begin a route
 2. Observe that location tracking is working correctly
 3. Put app into background by switching to another app

### Expected behavior

That the navigation app continues to monitor the user's location and provide voice guidance while the app is in background.

### Actual behavior

The location manager stops updating and navigation is no longer provided.

### Notes

It looks like this was introduced in 3.1.2 as part of https://github.com/mapbox/mapbox-gl-native/pull/3641

We recently upgraded from 3.1.0 to 3.2.0, so we only recently noticed this behavior. Is that correct that the intent was to couple the location manager to the wakeGL and sleepGL calls? Navigation apps obviously need to continue to receive location updates when the app is in background. What is the suggested work around for this? Does the client app need to create it own instance of location manager rather that rely on the mapView's instance?

Thanks!

**Comment by 1ec5** [comment]
Yes, the location manager provided by MGLMapView isn't intended to be used in the background, because the user dot isn't needed in the background and not all delegates would need that kind of ubiquity. The solution is to create your own location manager.

Core Location is designed so that you can have multiple location managers in a given application with different characteristics. Although there may be some interplay between them, there shouldn't be an additive effect on battery usage.

**Comment by 1ec5** [comment]
We should document this behavior and other caveats about the location manager passed to the delegate, such as the fact that it's only active while user location tracking is on.

**Comment by picciano** [comment]
Not the answer I was hoping for, but as always, thanks for the quick response!
In case you don't hear it enough, you guys are really building an amazing product here. Best in class.

**Comment by friedbunny** [comment]
Thanks, @picciano. 😃

**Comment by friedbunny** [comment]
> We should document this behavior and other caveats about the location manager passed to the delegate, such as the fact that it's only active while user location tracking is on.

As @1ec5 pointed out in chat, we [have documented](https://www.mapbox.com/ios-sdk/api/3.2.0/Protocols/MGLMapViewDelegate.html#/c:objc(pl)MGLMapViewDelegate(im)mapView:didUpdateUserLocation:) that MGLMapView’s location manager can't be used in the background — it’s just that this actually became impossible with #3641.

**Comment by Porubay** [comment]
Thank you for the detailed response [1ec5](https://github.com/1ec5). I am glad that the battery should not affect the battery in any way. That is, I understand that a single core will act as the only [location](https://www.cleveroad.com/blog/location-based-services-applications-like-waze-development-secrets) manager and will already be taking data from it all other applications?

**Comment by 1ec5** [comment]
The interaction between location managers in different applications isn’t very well documented. However, if I understand correctly, if two location managers are running on the phone at the same time (perhaps in different applications), and one is more aggressive than the other, it is possible for the less aggressive location manager to receive location updates that it wouldn’t otherwise receive.
