### ISSUE TITLE
Annotation with image from sprite

### ISSUE THREAD

**Issue by mozinator** [mapbox/mapbox-gl-native#4750]
At the moment its only possible to add an annotation with an custom image or the default marker image.
It would be useful to be able to pick an existing sprite image.

**Comment by 1ec5** [comment]
Would the sprite image be a sprite that comes with the style, such as a Maki icon? This was originally the only way you could customize an annotation: by implementing `-[MGLMapViewDelegate mapView:symbolForAnnotation:]` to return a string that matched a sprite name in the style. When we introduced MGLAnnotationImage in #941, we removed `-mapView:symbolForAnnotation:`, expecting that developers would gravitate toward the new API anyways: https://github.com/mapbox/mapbox-gl-native/pull/941/files#r34008986. We’re currently working on #837, and I’d expect that eventually (maybe not initially) this will become possible again, in order to have parity with Mapbox GL JS.

**Comment by lilykaiser** [comment]
Closing due to ticket age. If this is still a problem, please re-open

**Comment by 1ec5** [comment]
To reuse one of the style’s images for an annotation, obtain the image using [`-[MGLStyle imageForName:]`](https://www.mapbox.com/ios-sdk/api/3.6.4/Classes/MGLStyle.html#/c:objc%28cs%29MGLStyle%28im%29imageForName:). Alternatively, replace the annotation with an MGLSymbolStyleLayer backed by an MGLShapeSource, and set the style layer’s `iconImage` property to the image’s name.
