### ISSUE TITLE
MGLAccountManager overriding CLLocationManager desiredAccuracy

### ISSUE THREAD

**Issue by jasonwiener** [mapbox/mapbox-gl-native#4758]
Hi.  I installed the MapBox SDK via Fabric. I use a shared CLLocationManager (with desiredAccuracy = kCLLocationAccuracyBestForNavigation, distanceFilter = 5) for granular tracking.  However, when I instantiate the MGLAccountManager in the AppDelegate, it overrides my manager and completely flumoxes the location ops in the build.

**Platform:** iOS 9.2.1
**Mapbox SDK version:** 3.2.0
### Steps to reproduce

I reproduced this by travelling a known 2 mile route (iPhone 6, iOS 9.2.1). First I did the route with MGLAccountManager init'd in the AppDelegate. Then again after disabling it. Only after disabling was I able to get CLLocationManager to act as expected.

**Comment by friedbunny** [comment]
>it overrides my manager and completely flumoxes the location ops in the build

Could you expand a bit on this — what exactly do you expect to happen and what actually happens instead?

The location managers in MGLMapView and MGLMapboxEvents are both set to fairly low accuracy, but neither should have any effect on non-Mapbox location manager(s) in an app.

**Comment by jasonwiener** [comment]
Before I installed the MapBox SDK, I've never had a problem with accuracy. I instantiated it with the prescribed line at the end of `didFinishLaunchingWithOptions` using `Fabric.with([Crashlytics.self, MGLAccountManager.self])`

I started noticing issues with accuracy jumping all over the place during tests. In some cases the location would "jump" as much as 10 miles off and then track back. Once I commented out the MapBox SDK calls in the AppDelegate, the location services returned to normal with proper updates on a 5m delta (as defined using distanceFilter param).

**Comment by 1ec5** [comment]
Does this happen always, or only when your application is in background mode and/or in the background (i.e., obscured by another application)?

**Comment by boundsj** [comment]
Hi @jasonwiener 

It's true iOS Location Services are shared since the SDK's API exposes controls for physical hardware and there is only one set of radios/sensors that make up the location service. However, each instance of CLLocationManager in an application is distinct and has it's own opportunity to control the settings. All of the CLLocationManager instances in your application (including the ones used by the Mapbox SDK) and all the other apps that have CLLocationManager instances that run in the background while your app runs can ask the location service to use a desired accuracy. But, since there is only one set of radios, the instance that asks for the highest desired accuracy will cause the location service to use the most powerful and battery consuming radios (GPS).

The Mapbox SDK's background use of CLLocationManager **only** ever asks for a 3KM desired accuracy. Therefore, it'll never be responsible for triggering GPS. Your application (or any other app in the background) can set the desired accuracy higher but the Mapbox SDK will never cause these other location manager instances to somehow change their desired accuracy. It is also worth noting that it is not uncommon to receive location objects with a horizontalAccuracy of many thousands of meters even when you request "best" desired accuracy.

I suggest that you perform your real world test several more times and also try it with other apps that use location services in the background (i.e. waze, Google or Apple maps with navigation on, etc..) to get a sense for how the system works holistically. Also, if you are not using it already, check out Xcode Instruments `Location Energy Impact` instrument. In the example below, you can see the various **and distinct** CLLocationManager instances getting allocated and released and having their desired accuracy changed **independently** of one another. This tool (see example below) will help you confirm your program is working as intended before you perform your real world tests.

<img width="970" alt="f554171a-f4bc-11e5-948c-1811d7b9939b-1" src="https://cloud.githubusercontent.com/assets/63186/14663910/8f7695f6-067a-11e6-91ad-5ad02aa960f3.png">

**Comment by jasonwiener** [comment]
@1ec5 it was happening in both background and foreground modes. @boundsj thanks. i'll do so & report back
