### ISSUE TITLE
Bitrise isn't building Node.js binaries for OS X

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mapbox-gl-native#4854]
Breaking this out from https://github.com/mapbox/mapbox-gl-native/issues/1349

Linux binaries are triggered and published successfully with [`./platform/node/scripts/after_script.sh ${TRAVIS_JOB_NUMBER} ${TRAVIS_TAG:-}`](https://github.com/mapbox/mapbox-gl-native/blob/64fe75b01109d38977b20c83773e6236e55905a8/.travis.yml#L63), but [`./platform/node/scripts/after_script.sh ${BITRISE_BUILD_NUMBER} ${BITRISE_GIT_TAG:-}`](https://github.com/mapbox/mapbox-gl-native/blob/64fe75b01109d38977b20c83773e6236e55905a8/platform/node/bitrise.yml#L38) fails to publish OS X binaries.

Is `BITRISE_GIT_TAG` formatted differently and failing the conditional [`if [[ $TAG == node-v${PACKAGE_JSON_VERSION} ]];`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/node/scripts/after_script.sh#L19) or is a build with a matching `BITRISE_GIT_TAG` simply [not being triggered](https://github.com/mapbox/mapbox-gl-native/issues/1349#issuecomment-207183454)?

/cc @1ec5

**Comment by 1ec5** [comment]
[The documentation](http://devcenter.bitrise.io/docs/available-environment-variables) offers no clues. Perhaps it only gets filled in if you manually trigger a build, setting the Git tag in the Advanced tab of the “Build configuration” dialog? To test the first theory, you can create a throwaway workflow in Bitrise that prints out the variables you’re interested in, then push a tagged commit to see what happens. To test the second theory, add a trigger for that tag name in the Triggers tab of the [workflow editor](https://www.bitrise.io/app/55e3a9bf71202106/workflow/editor). You might also be able to use the [Bitrise CLI tool](https://www.bitrise.io/cli) for both tests instead of messing with workflows on the actual project.
