### ISSUE TITLE
Include support for accessibility in the Android SDK

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#4857]
This is the Android counterpart of https://github.com/mapbox/mapbox-gl-native/pull/1496.

/cc: @bleege @tobrun @1ec5 @friedbunny

**Comment by tobrun** [comment]
This will boil down to implementing contentDescription for each View on the screen. 
Not sure if we can improve this by adding support for GL based content?

**Comment by 1ec5** [comment]
For #1496, I synthesized a virtual “accessibility element” for each GL annotation. There’s no performance hit because it’s only done on demand for VoiceOver users. Hopefully a similar approach is possible on Android. If not, at least it’ll be possible for the native markers in #3276 to have `contentDescription`s, right?

**Comment by tobrun** [comment]
>  at least it’ll be possible for the native markers in #3276 to have contentDescriptions, right?

💯  but having some markers with this versus other not is not very convenient for a blind person.

**Comment by adavis** [comment]
This feature will be very useful for implementing testing with Espresso or UiAutomator. Is there another way to click on the map markers currently in an automated test? Also, please let me know if this belongs in a new issue. Thanks!

**Comment by tobrun** [comment]
@adavis this depends on which kind of Markers you are using, if you are adding markers with `MapboxMap#addMarker(Marker marker)` you are adding an opengl drawn marker. Since both Espresso and UiAutomator work on the ViewHierarchy, it's not possible to rely on the concepts that those testing frameworks are exposing. 

If you are adding markers with `MapboxMap#addMarker(MarkerView marker)`, you are adding a View object on top of the map that is synchronised when the map transfroms. You are able to assign any  content description to leverage the features from Espresso/UiAutomator.

Side note: is that we use Espresso to do testing internally but this is more a hack than default behaviour. We use a custom idling resource that waits until the MapboxMap object is created and call methods on that object directly (eg.`MapboxMap#selectMarker(Marker marker)` instead of using `onView(withId(R.id.awesome_view.perform(click());`). Verifying the end results can be done through validating the object itself or use some kind of screenshot based utility to validate what is rendered.

**Comment by adavis** [comment]
@tobrun thanks for the explanation. Since I'm already using a custom idling resource, I can just use your "hack" and rely on the `MapboxMap` methods as well. Thanks again!

**Comment by 1ec5** [comment]
Fixed in #8230.
