### ISSUE TITLE
Allow setting user location directly

### ISSUE THREAD

**Issue by mkv123** [mapbox/mapbox-gl-native#4908]
Currently there is no way to set location of the user's position directly without GPS. This is useful for cases where there is an alternative location provider or finer grained control over updates are wanted (#3515, #3629). For most developers this would also make getting nice screenshots from interesting locations easier.

May be related to #4700

**Comment by LesSvant** [comment]
I have the same request for iOS, see #4185 (and Android later if that project switches over to Mapbox as well)

**Comment by tobrun** [comment]
Something we have been talking about is allowing developers to provide their own Location provider. We currently use [Mapzen LOST](https://github.com/mapzen/LOST) in the background but developers should be able to provide their own implementation. 

This feature is related to #4331 since that will result in exposing a `mapboxMap.setLocationSource(LocationSource source)` API. This should provide you with the flexibilty required for your use-case.

> For most developers this would also make getting nice screenshots from interesting locations easier.

A workaround for now is to use a location mocking app. We use this internally to simulate driving.

**Comment by mkv123** [comment]
#4331 would be great. I'm fine with closing this one in favor of that approach. It would make the decoupling of the location provider from the map view nice and clean.

**Comment by tobrun** [comment]
@mkv123 I'm going to take up your suggestion of closing this in favor of #4331. Thanks again for reaching out!
