### ISSUE TITLE
Android 4.4.x (KitKat) Hardware Acceleration Thread Bug

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#4911]
I ran some automated device tests using AWS Device Farm on `master` last week to verify that the OpenGL improvements that were recently added (#1662 and #4716) were working as expected.  The results showed that they were working as needed **except for many devices in the Android 4.4.x (KitKat) pool**.  These devices were from many different OEM (hardware) vendors indicating that it's an issue with the way that the code interacts with Android 4.4.x API.

The test that failed (`com.mapbox.mapboxsdk.testapp.espresso.ScreenshotActivityTest`) threw the following error:

```java
java.lang.IllegalStateException: Hardware acceleration can only be used with a single UI thread.
```

I discussed this with @tobrun and he said that this was a workaround test and he'll add it to the codebase now so that we can further investigate.

![screen shot 2016-04-28 at 2 32 08 pm](https://cloud.githubusercontent.com/assets/989928/14898745/0fa7ba46-0d4e-11e6-88ba-8296bdfecdb2.png)
_Android 4.4.x Failures_

/cc @tmpsantos @jfirebaugh @kkaefer @tobrun @zugaldia @twbell

**Comment by bleege** [comment]
@zugaldia suggested that this may be related to #4706 as it involves the RunLoop.

**Comment by tmpsantos** [comment]
@tobrun you have a fix for this, right?

**Comment by tobrun** [comment]
@tmpsantos the black screen bug you are referring to in https://github.com/mapbox/mapbox-gl-native/pull/4892 seems to be different from this one since this has a concrete java exception message while the black screen returned an `invalid gl context`-log message. There is a slight chance that related but at this time I'm guessing they are separate.

**Comment by tobrun** [comment]
With the help of @tmpsantos we were able to get a full stacktrace and were able pinpoint this to taking screenshots in this branch: https://github.com/mapbox/mapbox-gl-native/tree/tobrun-screenshotutil-broken/platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/espresso. 

That branch was introduced to workaround the issue in #4847 but it seems it doesn't work for pre `5.0` Android versions. Since this was a workaround and the actual bug is tracked in #4847. Going to close.
