### ISSUE TITLE
Tweak these projects to work with MapBox SDK?

### ISSUE THREAD

**Issue by sirvon** [mapbox/mapbox-gl-native#4933]
Hey you guys...i'm feeling mapbox better than anyone map sdk out there.

Anyway you can help us get these projects working with mapbox sdk?

[realm-mapview](https://github.com/thorbenprimke/realm-mapview)
[ABFRealmMapView](https://github.com/bigfish24/ABFRealmMapView)

or any tips/tidbits to look out for....

Bet alot of ppl would be happy and smiling from ear to ear.

Thanks!

**Comment by 1ec5** [comment]
While it’s possible to build a ABFRealmMapView that subclasses MGLMapView instead of MKMapView, I’m guessing the pain point would be that the Mapbox iOS SDK currently only supports rendering point annotations as static images rather than UIViews. We’re working on that for the upcoming release: #4801. Everything else should be straightforward. For example, `ABFZoomLevel` maps cleanly to the `zoomLevel` property on MGLMapView, obviating [`ABFZoomLevelForVisibleMapRect()`](https://github.com/bigfish24/ABFRealmMapView/blob/c5d84569986ea2f7f6b9d902f37d580d930963a5/ABFRealmMapView/ABFLocationFetchedResultsController.m#L262-L275).

ABFRealmMapView would also be greatly simplified once the Mapbox mobile SDKs support marker clustering out of the box: #320.

**Comment by sirvon** [comment]
can you comment on the realm-mapview source?

**Comment by 1ec5** [comment]
I'm afraid I'm not familiar enough with Android to say much about that, but @tobrun might be able to comment.

**Comment by tobrun** [comment]
@sirvon It's definitely feasible to port such this to Mapbox since we have a high API compatibility with Google Maps. That said I feel this kind of layer on top of the Android Mapbox SDK is not something we as a company are going to provide in the near future. Feel free to run with this and start the development on it. Would love to 👀  it in my spare time!

**Comment by sirvon** [comment]
thank you for the feedback!
