### ISSUE TITLE
Integrate node bindings + tests into OS X workspace

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#4978]
We should integrate the node bindings, and render/query tests into the main OS X workspace to avoid having to have two separate spaces. Since the node bindings depend on the actual node version installed, we should auto-detect the node version from the command line and write the correct settings file.

**Comment by 1ec5** [comment]
Would node be required for developing (say) the OS X SDK?

> we should auto-detect the node version from the command line and write the correct settings file.

Note that the workspace file itself is checked in; it isn't generated. So this would be limited to build settings but couldn't affect the project structure.

**Comment by 1ec5** [comment]
For what it's worth, I would also find it more convenient to combine the iOS and OS X workspaces too, since those SDKs share most of their code, but I'm hesitant to bloat the workspace further.

**Comment by mikemorris** [comment]
> We should integrate the node bindings, and render/query tests into the main OS X workspace to avoid having to have two separate spaces.

This would just be to make `make xnode` cleaner, right? `npm install --build-from-source` and `make node` would still work as they currently do?

**Comment by 1ec5** [comment]
Come to think of it, I think what you’re really asking for is for `make xnode` to create a node.xcworkspace that has everything, rather than expanding the scope of osx.xcworkspace. Is that correct? These workspaces themselves have next to zero maintenance overhead, thankfully. It’s the Xcode projects that we’d be maintaining, but it sounds like you’d have GYP continue to manage the projects for you, right?

**Comment by kkaefer** [comment]
Yeah, sounds like that's what I want.

**Comment by jfirebaugh** [comment]
This was done with the switch to cmake, right?

**Comment by 1ec5** [comment]
Yes. Fixed in #5359.
