### ISSUE TITLE
Drop cxx03abi support

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#5005]
We should drop support for cxx03abi, a.k.a. libstdc++ < 5.1, and compile everything with `_GLIBCXX_USE_CXX11_ABI=1`, even on Ubuntu Precise 12.04.

This will allow us to simplify our support matrix in upstream mason packaged libraries (https://github.com/mapbox/mason/issues/157).

cc @tmpsantos @brunoabinader @mourner

**Comment by tmpsantos** [comment]
If we do that we would need to install a new `libstdc++` on the bots prior to compile and run the tests, right?

**Comment by springmeyer** [comment]
> If we do that we would need to install a new libstdc++ on the bots prior to compile and run the tests, right?

If I'm understanding your question right, then we already do that to support C++11/14 features in general. So no change needed there as far as I can tell. We will just keep using `ubuntu-toolchain-r-test` as a ppa source and installing `libstdc++6` (which will be upgraded from that source). This is [explicit in this travis matrix](https://github.com/mapbox/mapbox-gl-native/blob/8ee222c45e31413b03d1c83006cf4eadc0e6d3a7/.travis.yml#L8-L10) but it is happening consistently in all the other travis jobs too because of the `g++` install.

**Comment by tmpsantos** [comment]
Being discussed here -> https://github.com/mapbox/mason/issues/319#issuecomment-272695354

**Comment by brunoabinader** [comment]
Some third party platforms still require CXX03ABI, reason why I've added an option in our build to manually select it via WITH_CXX11ABI (default is 1) - see https://github.com/mapbox/mapbox-gl-native/pull/8835/commits/ae3cf2e774ef33080778a73ff8d813d48ccb0d48.
