### ISSUE TITLE
Disabled gestures preempt gesture recognizers in superview

### ISSUE THREAD

**Issue by DemianSteelstone** [mapbox/mapbox-gl-native#5020]
**Platform:** IOS
**Mapbox SDK version:** 3.2.2

Hi, I have a trouble with your SDK.

I have MGLMapView as subview in MyMapViewController. 
Then place it to pageViewController as one of the pages.
Now when I'm pan to MyMapViewController can't get back to previous controller.
If use GoogleMaps there is no such problem.

```
self.osmMapView = [[MGLMapView alloc] initWithFrame:self.view.bounds styleURL:[MGLStyle streetsStyleURLWithVersion:9]];
self.osmMapView.zoomEnabled = NO;
self.osmMapView.scrollEnabled = NO;
self.osmMapView.rotateEnabled = NO;
self.osmMapView.pitchEnabled = NO;
```

Can I do something with it?

**Comment by 1ec5** [comment]
We should make these properties activate and deactivate the gesture recognizers instead of bailing at the beginning of their actions.

@DemianSteelstone, since it looks like you don’t want the map view to recognize any gestures, you can set the `userInteractionEnabled` property to `NO` instead of these four properties.

**Comment by DemianSteelstone** [comment]
Thanks for fast reply.

But I can't do so. I need selectAnnotation gesture.

**Comment by boundsj** [comment]
> We should make these properties activate and deactivate the gesture recognizers instead of bailing at the beginning of their actions

This was done in https://github.com/mapbox/mapbox-gl-native/pull/8304 that is now available to test in https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.6.0-alpha.1
