### ISSUE TITLE
collision debug doesn't work reliably

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#5055]
Turning on collision debug option results in some tiles showing it and other tiles not showing it. As you pan and zoom, it turns on and off on a tile-by-tile basis unpredictably.

**Comment by brunoabinader** [comment]
I've noticed that debug collisions are rendered as expected when using a style with raster layer only:
![screen shot 2016-10-07 at 6 21 37 pm](https://cloud.githubusercontent.com/assets/76133/19195606/fce3daa6-8cba-11e6-922f-95db535dd5ae.png)

However, debug collisions are only rendered on the tiles appearing on the bottom right corner for the examples below:
![screen shot 2016-10-07 at 6 21 31 pm](https://cloud.githubusercontent.com/assets/76133/19195733/6c97333e-8cbb-11e6-9c43-3f1bf45c0e47.png)
![screen shot 2016-10-07 at 6 21 45 pm](https://cloud.githubusercontent.com/assets/76133/19195707/56ebc19e-8cbb-11e6-9701-83e535d9f1ab.png)

**Comment by brunoabinader** [comment]
Given the examples above, my suspicion is that somehow the tile size affects the way how the collision debug is rendered.

**Comment by brunoabinader** [comment]
> Given the examples above, my suspicion is that somehow the tile size affects the way how the collision debug is rendered.

Even though [we don't always enable stencil test when rendering symbols](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/renderer/painter_symbol.cpp#L128-L139), we do [render collision using the same stencil function](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/renderer/painter_symbol.cpp#L254-L256). This gets updated on each render call, but only [if the bucket needs clipping](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/renderer/painter.cpp#L309-L311).

In the cases above, the render result was unpredictable because it used the last stencil function set by the previous bucket that needed clipping.

**Comment by jfirebaugh** [comment]
Thanks for investigating!

> In the cases above, the render result was unpredictable because it used the last stencil function set by the previous bucket that needed clipping.

This means it's a good example of a bug that will be fixed by #6468.
