### ISSUE TITLE
Offline manager access token

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#5058]
`MapboxAccountManager` has been added in `4.1.0` but we still ask for access token when setting up the `OfflineManager` object. We should look into using account manager to handle this in the background so users don't need to call `setAccessToken` still and write something like this:

```java
offlineManager.setAccessToken(MapboxAccountManager.getInstance().getAccessToken());
```

**Comment by tobrun** [comment]
Adding this to `4.1.0` since it's related to the deprecation of access tokens setters/getters.

**Comment by bleege** [comment]
Yep this is related to the original build out of `MapboxAccountManager` in #5004.  I'll dive into this to make sure that it aligns with the same deprecation strategy that other disparate access token getters and setters were using.

**Comment by bleege** [comment]
I ran into #5108 when testing this issue out.  I'm going to try an earlier version of `master` to see if that resolves the runtime issue and if so then test 54050eb3afbce7a4e019dd5b9981235e657bbd85 on it in the interim.

**Comment by bleege** [comment]
We ended up solving the issue in #5108 by reverting the NDK upgrade commit.  I'm going to rebase off of `master` now and test out the fixes from yesterday.

**Comment by bleege** [comment]
Just rebased and successfully tested!  Should be ready to merge now!

**Comment by bleege** [comment]
The `getAccessToken()` and `setAccessToken()` methods in OfflineManager have now been deprecated, while also refactoring it's constructor to check for the existence of `MapboxAccountManager` and use it if it's set.  The TestApp's `OfflineActivity` has been refactored to remove the explicitly set access token so that it relies on the `MapboxAccountManager` to set it automatically (which is the new recommended way).
