### ISSUE TITLE
Point annotations disappear at low zoomlevels

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#5109]
When you zoom out, point annotations disappears. Zooming back in restores them.

![ezgif com-video-to-gif 20](https://cloud.githubusercontent.com/assets/2151639/15486044/20a53c98-2143-11e6-843a-39568a6440ed.gif)

This was noticed on Android and was validated for iOS by @1ec5 with 3.3.0-alpha.3

**Comment by 1ec5** [comment]
These are GL point annotations, by the way.

**Comment by bleege** [comment]
Discussed internally with @tobrun @cammace today and this issue is a blocker for Android 4.1.0 FINAL release.

/cc @mapbox/mobile @jfirebaugh @kkaefer @tmpsantos @brunoabinader

**Comment by tmpsantos** [comment]
On it.

**Comment by tmpsantos** [comment]
Found the commit that caused the regression: 4c62a5508cfa96755b37850051871320d79748fb

This is not only affecting annotations but also label density on low zoom levels:
![screenshot from 2016-05-27 17-27-45](https://cloud.githubusercontent.com/assets/996307/15610918/7e63f24e-2430-11e6-9cda-6012d3e56c7f.png)
![screenshot from 2016-05-27 17-28-45](https://cloud.githubusercontent.com/assets/996307/15610919/7e656be2-2430-11e6-8cc3-e0feb58f79ad.png)

/cc @ansis

**Comment by bleege** [comment]
Awesome.  Thanks @tmpsantos @ansis!

**Comment by jfirebaugh** [comment]
@tmpsantos Any idea what about 4c62a5508cfa96755b37850051871320d79748fb is causing the issue? (Let's assume that @ansis is focused on schoolwork.)

**Comment by tmpsantos** [comment]
@jfirebaugh I'm investigating but seems to me some integer overflow or float to integer conversion making setting full transparency.

I was initially comparing to the code on JS trying to find anything wrong with the ported code but it seems fine.

**Comment by bleege** [comment]
@tmpsantos I just tested your fix in #5175 and can confirm that it solves this issue.  Both markers (C and A) were visible at all zoom levels as well as when cycled on / off using the FAB (see screenshots below).  I'm going to merge #5175 into `master` and then cherry pick the commit over to the `release-android-v4.1.0` branch so that this fix gets into the nightly SNAPSHOTS as well as the final release.  Thank you for fixing this!

![device-2016-05-27-160756](https://cloud.githubusercontent.com/assets/989928/15621335/d6116a40-2425-11e6-9c7d-7f590be0bc3d.png)

![device-2016-05-27-160811](https://cloud.githubusercontent.com/assets/989928/15621338/dafedf42-2425-11e6-91da-60985c100d88.png)

**Comment by bleege** [comment]
Cherry picked into Android's `release-android-v4.1.0` branch.

![screen shot 2016-05-27 at 4 21 41 pm](https://cloud.githubusercontent.com/assets/989928/15621523/280856d2-2427-11e6-9d3d-8224c797899c.png)

**Comment by mpuchala** [comment]
@bleege @tobrun 
When can we expect new snapshot or beta-2 release with this fix?

**Comment by tobrun** [comment]
@mpuchala, thank you for reaching out. In normal circumstances you should be able to use the SNAPSHOT containing this fix. I just double checked the nightly builds and there seems to be a problem with building. I'm fixing this in https://github.com/mapbox/mapbox-gl-native/issues/5187.
