### ISSUE TITLE
MGLOfflineStorage iCloud Backup

### ISSUE THREAD

**Issue by suvov** [mapbox/mapbox-gl-native#5112]
We're using MGLOfflineStorage to download offline maps as shown in your example code. And it seems that downloaded data gets backed up to iCloud. Which is against Apple guidelines. Actually we found it out after being rejected. 

Steps to reproduce:

・Check iCloud backup size for an app in settings before downloading offline region.
・Check iCloud backup size after

**Comment by friedbunny** [comment]
Thanks for the report.

We already try to exclude offline downloads and ambient cache from backups — that happened in https://github.com/mapbox/mapbox-gl-native/pull/4493 and v3.2.0, the first release that offline was available.

This appears to be insufficient for some applications — an enterprise app did not backup offline data to iCloud, but an App Store app did.

**Comment by 1ec5** [comment]
#4493 excluded the cache from backups [using `NSURLIsExcludedFromBackupKey`](https://github.com/mapbox/mapbox-gl-native/blob/9c9ff2d2d4aeac9f605a6ca23447e54adea9f6bd/platform/darwin/src/MGLOfflineStorage.mm#L71), as recommended in [this Technical Q&A](https://developer.apple.com/library/ios/qa/qa1719/_index.html). However, [the documentation for that option](https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSURL_Class/index.html#//apple_ref/c/data/NSURLIsExcludedFromBackupKey) also says:

> You can use this property to exclude cache and other app support files which are not needed in a backup. Some operations commonly made to user documents cause this property to be reset to `false`; consequently, do not use this property on user documents.

We used to store the cache in Caches, which does not get backed up, but as explained in #4371, we moved it to Application Support so that offline downloads wouldn’t get purged by the system.

@suvov, did you upgrade your application from iOS SDK v3.1.x? Looking through the code, I wonder if what happened is that we set that flag on a nonexistent cache, _then_ moved the legacy cache from Caches to the new location in Application Support. We should reverse the order so that the flag is set on the cache no matter where it came from. Hopefully that’s the only case in which the cache could be backed up.

/cc @jfirebaugh

**Comment by friedbunny** [comment]
@1ec5 I just retested the App Store app (that had been updated from some earlier version to v3.2.0) and a fresh install still uploaded the cache to iCloud.

Another option may be to create our own subdirectory and set `NSURLIsExcludedFromBackupKey` on a that (rather than individual files).

**Comment by 1ec5** [comment]
I’m not sure how that’s any different from setting it on the one file we create, but it’s worth a try. The migration code is going to get a bit messier, though.

**Comment by 1ec5** [comment]
Actually, that makes sense: in a fresh installation, the cache doesn’t exist until after the `mbgl::DefaultFileSource` is initialized. So let’s set `NSURLIsExcludedFromBackupKey` after initializing `mbgl::DefaultFileSource`.

**Comment by friedbunny** [comment]
It’s cumbersome to test, but I believe this could be limited to the first launch of an app. `NSURLIsExcludedFromBackupKey` is definitely not set the first time the database is initialized and, following these steps, I was able to backup to iCloud without including the database:

1. Delete app.
1. Turn off iCloud backup for app.
1. Manually trigger iCloud backup.
1. Download app.
2. Launch, kill, and then relaunch the app.
3. Download offline region.
4. Re-enable iCloud backup for app.
5. Trigger iCloud backup.

😬

**Comment by friedbunny** [comment]
@suvov Thanks again for reporting this issue. When we put out another pre-release build later this week, it would be great if you could attempt to verify that our patch actually fixes the problem (because it’s not such an easy thing to verify!).

**Comment by suvov** [comment]
@friedbunny Sure, will try it. Thank you for offline support in first place.

**Comment by 1ec5** [comment]
[v3.3.0-rc.1](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.3.0-rc.1) is out.
