### ISSUE TITLE
SpriteImageException when using a vector with non-whole number width/height

### ISSUE THREAD

**Issue by puttputt** [mapbox/mapbox-gl-native#5149]
Hi not sure if this is the right project, but.

ios SDK 3.0.1

I'm getting this error: 
mbgl::util::SpriteImageException: Sprite image pixel count mismatch

With this code:
```
func mapView(mapView: MGLMapView, imageForAnnotation annotation: MGLAnnotation) -> MGLAnnotationImage? {

        return MGLAnnotationImage(image: UIImage(named: "marker")!, reuseIdentifier: "note")
    }
```

I've discovered that it was because the pdf image I am using had a height of 35.36 pixels. Rounding this down to 35 pixels resolved the issue.

**Comment by 1ec5** [comment]
This issue was previously reported in #2198 and fixed in #3561, which made it into Mapbox iOS SDK v3.1.0 and above. Please upgrade to the [latest version of the SDK](https://github.com/mapbox/mapbox-gl-native/releases/) (currently 3.2.2; 3.3.0 alphas are also available) and let us know if the problem persists. Thanks!
