### ISSUE TITLE
MGLAnnotationView not update location immediately on setCoordinate:

### ISSUE THREAD

**Issue by Gerz-inc** [mapbox/mapbox-gl-native#5230]
**Platform:** iOS
**Mapbox SDK version:** 3.3 alpha-3

### Steps to trigger behavior

 1. [annotation setCoordinate:CLLocationCoordinate2DMake(...,...)];

### Expected behavior
Updating position of MGLAnnotationView on map view

### Actual behavior
Position changing only if map region changed, other annotations added or other manipulations with map

**Comment by 1ec5** [comment]
At one point, I think [this code](https://github.com/mapbox/mapbox-gl-native/blob/e47fe86d5d7b0dd104c39be4b9e110363bd75248/platform/ios/src/MGLMapView.mm#L1781) was getting lucky and causing all annotations to be redrawn, including view-backed annotations. But we should add something explicit here to update the annotation views.

/cc @boundsj

**Comment by 1ec5** [comment]
Actually, I’m seeing a somewhat different bug. The iosapp demo application is configured so that tapping on an annotation’s callout view changes the annotation’s coordinates to the screen center. But when tapping a view-backed annotation’s callout, an annotation image (with the default red pin image) also appears at the screen center in addition to the annotation view:

![centered](https://cloud.githubusercontent.com/assets/1231218/15803896/9d017ada-2aa9-11e6-959c-ae80cbd45ba1.png)

**Comment by 1ec5** [comment]
#5245 would fix this issue for sure by introducing an explicit update of the annotation view in response to the KVO change notification.

**Comment by 1ec5** [comment]
Fixed in #5550, which will be in v3.3.0-beta.3 shortly.

**Comment by Gerz-inc** [comment]
I tested on version 3.3.3, no change. The marker position are updated immediately only if to move the map, or after few seconds

**Comment by 1ec5** [comment]
That sounds similar to the issue described in https://github.com/mapbox/mapbox-gl-native/issues/5755#issuecomment-235818879.

**Comment by prgorasiya** [comment]
@Gerz-inc Could you provide the sample code for the animated car movement animation as I am unable to achieve the same results for my project?
Thanks
