### ISSUE TITLE
Elongated, black triangles on random streets

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#5234]
As of 7a43f8bd1eb0df0d519d48d81996e02691a02817 on master, I’m seeing some occasional artifacting in the form of elongated, black triangles at either endpoint of a street. For example, here’s a screenshot of the 12/1171/1566 tile in Mapbox Streets v9 on iOS 9.3 on an iPhone 6 after choosing Add 100 Point Annotations from the menu:

![12/1171/1566](https://cloud.githubusercontent.com/assets/1231218/15789125/7f68a74e-297f-11e6-9803-6c47b239b58a.PNG)

Here are some more examples in the 11/585/783 tile:

![12/1171/1566](https://cloud.githubusercontent.com/assets/1231218/15789206/ddb1a7f6-297f-11e6-8b57-59122882122b.PNG)

/cc @jfirebaugh @kkaefer

**Comment by jfirebaugh** [comment]
Can you bisect this?

**Comment by 1ec5** [comment]
A bisect implicates a43940afb2208c61b487bfd8729bbde1bd674794, part of #4839. 27baa34d44f0006c05ba7c417bf11e184b0bd22b is unaffected by this bug.

**Comment by 1ec5** [comment]
Also worth noting that this issue affects iPhone 6 but not any iOS simulator and not the OS X SDK.

**Comment by jfirebaugh** [comment]
Thanks, the bisect helped hugely. I was able to reproduce the issue, and found that reverting [the default for `line-round-limit`](https://github.com/mapbox/mapbox-gl-native/blob/a43940afb2208c61b487bfd8729bbde1bd674794/src/mbgl/layer/line_layer_properties.hpp#L22-L22) to 1 resolved the issue.

a43940afb2208c61b487bfd8729bbde1bd674794 changed the default to `1.05` because `1.05` is the correct value [according to the style-spec](https://github.com/mapbox/mapbox-gl-style-spec/blob/f1ffdd57d8c4d17c6e597374cc01bf163ddc8080/reference/v8.json#L400). Apparently that value triggers latent bugs in gl-native however.

**Comment by jfirebaugh** [comment]
Followups to #5258.
