### ISSUE TITLE
Add pause/resume API to DefaultFileSource

### ISSUE THREAD

**Issue by boundsj** [mapbox/mapbox-gl-native#5236]
Currently, instances of DefaultFileSource allow revalidation requests regardless of if the host process is running in the background and the map that would benefit from the requests is visible. Mobile applications that are extremely concerned about limiting network requests that is not strictly necessary   may see battery performance gains if the revalidation requests were not made in the background. 

In general, this behavior probably makes sense as the default on both iOS and Android. In addition, as usage of the SDK grows, the backend will benefit from not having to respond to as many requests as it does today.

We should consider adding and exposing an API to DefaultFileSource (or similar approach) so that each platform can inform it if it makes sense to carryout network requests based on background state (or other factors).

cc @jfirebaugh @1ec5 @mick

**Comment by 1ec5** [comment]
In the iOS SDK, we have a natural mechanism to make use of a request-pausing API, in `-[MGLMapView sleepGL:]` (which happens when the application recedes to the background or enters background mode) or a similar method that would be added to MGLOfflineStorage.

We could also more aggressively pause at the point where we stop a map view's CADisplayLink (which would also happen when the map view is removed from the view hierarchy or hidden). However, the catch is that the application could have multiple views, so we'd need to refcount somehow to avoid interfering with still-visible views.

**Comment by tmpsantos** [comment]
This could maybe implemented more generically at our class abstraction like `util::Thread::pause()`.

**Comment by boundsj** [comment]
This was fixed by https://github.com/mapbox/mapbox-gl-native/pull/8125 and https://github.com/mapbox/mapbox-gl-native/pull/8194
