### ISSUE TITLE
Delete selected offline packs, Swift

### ISSUE THREAD

**Issue by taktikal17** [mapbox/mapbox-gl-native#5243]
**Platform: Mapbox-iOS-SDK**
**Mapbox SDK version: 3.2.2**

### Steps to trigger behavior

I followed the Mapbox Offline tutorial for Swift.  I would like to :

 1.  See all the offline packs downloaded ( I found nothing on this topic )

 2.  Remove the offline packs useless. I think i should used this method : removePack(pack: MGLOfflinePack, withCompletionHandler completion: MGLOfflinePackRemovalCompletionHandler?), How to manage the completion handler?

Thank you!!

**Comment by 1ec5** [comment]
> See all the offline packs downloaded ( I found nothing on this topic )

Use the [`MGLOfflineStorage.packs`](https://www.mapbox.com/ios-sdk/api/3.2.2/Classes/MGLOfflineStorage.html#/c:objc(cs)MGLOfflineStorage(py)packs) to get a list of the downloaded offline packs.

> Remove the offline packs useless. I think i should used this method : removePack(pack: MGLOfflinePack, withCompletionHandler completion: MGLOfflinePackRemovalCompletionHandler?), How to manage the completion handler?

That’s the correct method for deleting an offline pack. Typically, the only thing you would ever put inside the completion handler would be error-handling code. Otherwise, you should perform any other tasks, such as removing the offline pack’s row from a table view, before calling `removePack(_:withCompletionHandler:)`.
