### ISSUE TITLE
[ios] Strange warning when distribute to appstore

### ISSUE THREAD

**Issue by rsimenok** [mapbox/mapbox-gl-native#5280]
Here is warning i got while uploading archive to app store, i don't know good it or bad, just let you know :)

WARNING ITMS-90080: "The executable 'Payload/BermudaYP.app/Frameworks/Mapbox.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information refer to Technical Q&A QA1788 - Building a Position Independent Executable in the iOS Developer Library."

**Comment by 1ec5** [comment]
Which version of the Mapbox iOS SDK did you build your application with?

**Comment by 1ec5** [comment]
Apparently this is a bug in iTunes Connect: https://github.com/CocoaPods/CocoaPods/issues/5453#issuecomment-223631754.

**Comment by rsimenok** [comment]
@1ec5 i'm using latest stable version from CocoaPods ios-v3.2.2, thank you for reply.

**Comment by Beno7** [comment]
Hi, has this issue been solved? We've just transisted our app from Apple Mapkit to Mapbox since first week of august, 2017. Everything went fine til' we've tried archiving the app to app store. We've experienced this warning as well, and something similar to these:

https://stackoverflow.com/questions/40093600/xcode-8-0-building-for-store-submission-errors

https://stackoverflow.com/questions/30547283/submit-to-app-store-issues-unsupported-architecture-x86

as a result, we've failed to build the app. We've included the framework manually, following this link: 
https://www.mapbox.com/help/first-steps-ios-sdk/#stay-up-to-date

We've used the latest version of the mapbox framework available during the first week of august. My question in particular then, is (1) has this issue been solved? (2) Is this normal? Have people been experiencing this as well? And (3) Are the solutions provided in the stackoverflow links provided above are a viable solution for the current problem we've been experiencing?

**Comment by captainbarbosa** [comment]
@Beno7 In your case, it sounds like the run script isn't being added before submission. To fix this, add the following run script phase in the "Build Phases" tab of the project editor:

```
bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Mapbox.framework/strip-frameworks.sh"
```

Hope this helps!
