### ISSUE TITLE
[docs] Improve core architecture documentation 

### ISSUE THREAD

**Issue by tmpsantos** [mapbox/mapbox-gl-native#5425]
We must improve the high level documentation about Mapbox GL Core to make the life of new contributors easier. The bad side about static documentation is they get outdated quickly. Suggestions are welcome on how to solve that and how the documentation should look like.

/cc @tobrun @ivovandongen @zugaldia

**Comment by jfirebaugh** [comment]
I started https://github.com/mapbox/mapbox-gl-native/blob/master/ARCHITECTURE.md -- additions welcome.

**Comment by bleege** [comment]
I ❤️ this effort.  Thanks @tmpsantos @jfirebaugh!

/cc @yhahn

**Comment by julianrex** [comment]
This is still valid.

**Comment by durgeshtrivedi** [comment]
@julianrex , @jfirebaugh @tmpsantos 

I am not sure if this is the right place to ask the question about this because it is related with the documentation so I am putting it here. 

I am trying to implement  [WebGl-Wind](https://github.com/mapbox/webgl-wind) for iOS and Android. We are using [MapBox-React-native ](https://github.com/react-native-mapbox-gl/maps) SDK
When I started exploring the SDK I realise the core part is missing in [MapBox-native](https://github.com/mapbox/mapbox-gl-native) sdk its self. The complete list of files(I said them Layers to understand it easily)  C++, Objective-C/C++ and last JS side for MapBox-React-native. So things need to implement on native side first to bring them on React-Native. So I started exploring the native code and [ARCHITECTURE.md](https://github.com/mapbox/mapbox-gl-native/blob/master/ARCHITECTURE.md) helps me a lot to understand the code flow and different implementation because I didn't know MapBox SDK and where to start. 
I reach to point where I understand Shaders need to be used which is common for [MapBox-Gl-JS](https://github.com/mapbox/mapbox-gl-js) and [MapBox-native](https://github.com/mapbox/mapbox-gl-native). While exploring the native code I understood  lot of files are generated using some script. Specially the CPP file which is generated from [Shaders](https://github.com/mapbox/mapbox-gl-js/tree/master/src/shaders) and some other supporting file here which are part of ARCHITECTURE. 
For every layer there are some set of file which are generated I refer the [HeatLayer](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/style/layers/heatmap_layer.cpp). 
I think I can use [WebGl-Wind](https://github.com/mapbox/webgl-wind) [Shaders](https://github.com/mapbox/webgl-wind/tree/master/src/shaders) from here but how to generate the files from here I didn't get the document. How to verify those generated file are correct. While building all the layers from here up and testing them while build in small module, is there a document for that because there should be away to build this in small modules and test them, if things are working correct before moving up the layer means(C++ to Objective C/C++) and even in C++ things are working correct or not. If some one can point me in right direction will be very helpful. 
If I understood the things in wrong way please correct me also. 
Pleases point me also if there is some existing implementation and I can move forward from there.

**Comment by tmpsantos** [comment]
The way how you can implement something like WebGL-Wind on top of a GL Native map would be using custom layers: https://docs.mapbox.com/android/api/map-sdk/8.1.0/com/mapbox/mapboxsdk/style/layers/CustomLayer.html

It is an experimental and unsupported feature. Basically we delegate to the API client to do a rendering pass based on the current camera configuration.

We can follow-up on our official support channel https://support.mapbox.com/hc/en-us
