### ISSUE TITLE
Marker Deselect not working!

### ISSUE THREAD

**Issue by Buminta** [mapbox/mapbox-gl-native#5434]
**Android:**
**Mapbox SDK version: 4.1.0-beta3**

Hi Mapbox Team. I had a problem when i'm ```setOnMarkerClickListener```.
Then I call ```MapboxMap.deselectMarker``` for that marker. (I want when i retry click to that marker, MapboxMap will dispatch event onClickMarker again for me)

But, It's working!

Thanks for supports!.

**Comment by tobrun** [comment]
@Buminta 

I think I'm not completely understanding the problem here, I tried reproducing the issue with the `DynamicMarkerChangeActivity` and altered the code to:

```java
  mMapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(@NonNull MapboxMap mapboxMap) {
                mMapboxMap = mapboxMap;

                mapboxMap.setOnMarkerClickListener(new MapboxMap.OnMarkerClickListener() {
                    @Override
                    public boolean onMarkerClick(@NonNull Marker marker) {
                        Toast.makeText(DynamicMarkerChangeActivity.this, "Hello from marker",Toast.LENGTH_SHORT).show();
                        return false;
                    }
                });

                mapboxMap.moveCamera(CameraUpdateFactory.newLatLngZoom(new LatLng(51.506675, -0.128699), 10));

                // Create marker
                MarkerOptions markerOptions = new MarkerOptions()
                        .position(LAT_LNG_CHELSEA)
                        .icon(mIconFactory.fromResource(R.drawable.ic_chelsea))
                        .title(getString(R.string.dynamic_marker_chelsea_title))
                        .snippet(getString(R.string.dynamic_marker_chelsea_snippet));
                mMarker = mapboxMap.addMarker(markerOptions);
            }
        });

        FloatingActionButton fab = (FloatingActionButton) findViewById(R.id.fab);
        fab.setColorFilter(ContextCompat.getColor(this, R.color.primary));
        fab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mMapboxMap.deselectMarker(mMarker);
            }
        });
    }
```

This results in following UX:

We receive a callback in OnMarkerClick when we click the Marker, we don't receive a callback when we execute `mMapboxMap.deselectMarker()`.

![ezgif com-video-to-gif 38](https://cloud.githubusercontent.com/assets/2151639/16295337/8b77ebce-3926-11e6-8fcb-000d8269b66f.gif)

Feel free to add any information to this ticket to help me understand what is going wrong for you, for now I'm closing this as a works as designed.

**Comment by Developer101253** [comment]
I also had the same problem, Then I realized that I am using `mapboxMap.clear();` before deselecting the marker. `mapboxMap.deselectMarkers();`

The proper way to use the function is.
` mapboxMap.deselectMarkers();
  mapboxMap.clear();`
