### ISSUE TITLE
Animating marker into view wont show up until map is moved

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#5444]
When animating a view annotation into the users view, the marker wont show up until they perform a gesture. 

![ezgif com-video-to-gif 4](https://cloud.githubusercontent.com/assets/5652865/16280406/4dfabe32-388d-11e6-907a-580c61b993b8.gif)

cc: @tobrun

**Comment by tobrun** [comment]
@cammace can you push the related code so I can test with it?

**Comment by cammace** [comment]
Found in this demo app PR: https://github.com/mapbox/mapbox-android-demo/pull/95

**Comment by tobrun** [comment]
This is the same issue as shown in https://github.com/mapbox/mapbox-gl-native/issues/5242#issuecomment-226470829. For this example I added a:

```java
 map.getMarkerViewManager().scheduleViewMarkerInvalidation();
```

Before executing a new animation. That results in follow UX:

![ezgif com-video-to-gif 35](https://cloud.githubusercontent.com/assets/2151639/16293908/a008bcde-391d-11e6-86e3-293c90b7da19.gif)

I'm committing this change to be part of the PR in https://github.com/mapbox/mapbox-android-demo/pull/95.
While this is not resolving the issue, it's a valid workaround for now since we are not exposing an actual API for doing this animation as documented in https://github.com/mapbox/mapbox-gl-native/issues/5422.
