### ISSUE TITLE
How to bring selected annotationt to front?

### ISSUE THREAD

**Issue by wanggang316** [mapbox/mapbox-gl-native#5458]
**Platform:iOS
**Mapbox SDK version:3.2.3

**Comment by boundsj** [comment]
Hi @wanggang316. This was fixed in https://github.com/mapbox/mapbox-gl-native/pull/5264 and is currently in the [v3.3.0 release branch](https://github.com/mapbox/mapbox-gl-native/tree/release-ios-v3.3.0). It'll be included in our next beta release (beta 2). 

In general, since annotation views are UIViews, you can use standard UIKit APIs to manipulate them (i.e. `[annotationView.superview bringSubviewToFront:annotationView]`) as demonstrated in https://github.com/mapbox/mapbox-gl-native/pull/5264.
