### ISSUE TITLE
Add instruction to building mapbox-gl-native under CentOS 6.

### ISSUE THREAD

**Issue by lygstate** [mapbox/mapbox-gl-native#5499]
The CentOS have GCC 5.2.1 by using devtoolset-4
But I can not build mapbox-gl-native on it.
How to deal with this situation.

**Comment by 1ec5** [comment]
What error messages are you seeing when building?

**Comment by lygstate** [comment]
```
* Using Python 2.6.6
* Already installed at /opt/src/mapbox-gl-native/mason_packages/headers/unique_resource/dev
* Already installed at /opt/src/mapbox-gl-native/mason_packages/headers/protozero/1.3.0
* Already installed at /opt/src/mapbox-gl-native/mason_packages/headers/boost/1.60.0
* Already installed at /opt/src/mapbox-gl-native/mason_packages/linux-x86_64/boost_libprogram_options/1.60.0
* Not using openssl
make: *** [build/linux-x86_64/config.gypi] 错误 1

```

The file build/linux-x86_64/config.gypi doesn't exist at all.

**Comment by tmpsantos** [comment]
I'll close this ticket because Ubuntu is the only Linux distribution we officially support, mostly because is the one running on the build bots and we can make sure it works for every new release.

That said, the same build instructions for Ubuntu should work on most of the Linux distros, if you install the corresponding dependencies. I've seem reports of developers building on Fedora and Arch.

Bad news is I gave CentOS a try on a LXC container and found out that CentOS uses a very old GCC (and clang too) that won't build Mapbox GL Native if you are targeting Linux (GCC you need at least 5.0). You might get better luck with Android because it would use our own toolchain to build.
