### ISSUE TITLE
Request feature: missing setTag(Object object) on Marker

### ISSUE THREAD

**Issue by fritzfs** [mapbox/mapbox-gl-native#5558]
**Platform:** Android
**Mapbox SDK version:** 4.1.0.

I believe people really need this feature. Can you implement it ASAP? We need it for handling onMarkerClick event and going further on object ...

**Comment by tobrun** [comment]
@fritzfs 

We actually support inheritance for this:

 - GL based example:  [CityStateMarker](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/model/annotations/CityStateMarker.java) and [CityStateMarkerOptions](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/model/annotations/CityStateMarkerOptions.java).

- View based example: [CountryMarkerView](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/model/annotations/CountryMarkerView.java) and [CountryMarkerViewOptions](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/model/annotations/CountryMarkerViewOptions.java)

Another approach would be to use an SparseArray with `key = id` marker and `value = your tag object`. It's for us not possible to support `setTag(Object o)` since Object doesn't implement parceable by default. Reach out if you have any other questions.
