### ISSUE TITLE
Build Dependency 

### ISSUE THREAD

**Issue by bessermt** [mapbox/mapbox-gl-native#5563]
**OS: Android Built On Linux Mint 17.2**
**Mapbox SDK version: mapbox-gl-native**

find: `../../node_modules/mapbox-gl-shaders': No such file or directory
gyp: Call to 'find -H ../../node_modules/mapbox-gl-shaders -name "*.glsl"' returned exit status 1 while in platform/android/platform.gyp.
make: *** [build/android-arm-v5/Makefile] Error 1

### Steps to trigger behavior

https://github.com/mapbox/mapbox-gl-native/blob/master/INSTALL.md

I suspect https://github.com/mapbox/mapbox-gl-shaders should be installed, but I don't see this listed in the dependency list.

**Comment by friedbunny** [comment]
`mapbox-gl-shaders` should be installed automatically by whichever `make foo` command you’re running, which is why we currently require Node.js and npm. [Our Android on Linux instructions](https://github.com/mapbox/mapbox-gl-native/blob/8947b0af27c7bc7397c9dc12e5e24bf6c2f4defb/platform/android/CONTRIBUTING_LINUX.md) don’t mention node or npm as dependencies, but that’s probably an oversight.

FYI: This project only supports Ubuntu (16.04, specifically), though Mint is similar enough that I’d guess it could also work.

/cc @jfirebaugh @tmpsantos

**Comment by jfirebaugh** [comment]
The Node dependency is [documented here](https://github.com/mapbox/mapbox-gl-native/blob/master/INSTALL.md#2-installing-dependencies). Discussion about using some other dependency mechanism for shaders is [here](https://github.com/mapbox/mapbox-gl-native/issues/5249).

Let us know if you still have issues after installing node.
