### ISSUE TITLE
OfflineRegion setObserver in Android

### ISSUE THREAD

**Issue by tcolligan-ap** [mapbox/mapbox-gl-native#5579]
**Platform: Android**
**Mapbox SDK version: 4.1**

Currently the `OfflineRegion` class has a `setObserver` method that allows devs to determine the status of an offline region, primarily for while it is being downloaded.

However there is no way to remove the observer from the `OfflineRegion` object instance. Passing in `null` looks like it will cause a crash based on the source. A way to remove the observer would be nice.

**Comment by zugaldia** [comment]
@tcolligan-ap Agreed, this is an API that would be good to add.  Passing a `null` value would be the intended way to remove the observer but right now the method signature for `public void setObserver(@NonNull final OfflineRegionObserver observer)` won't let you.

Probably we could just add a new `removeObserver()` method that simply does a `private native void setOfflineRegionObserver(null)` call.

**Comment by Guardiola31337** [comment]
> make observer param nulllable, resetting observer is valid (eg. when download finished downloading)

Landed in #8919 and it's available in version 5.1.0. 
There is an example in [`OfflineActivity.java`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/offline/OfflineActivity.java#L269).

Closing here because it's already solved.

Thanks @tcolligan-ap for your report. Feel free to open new tickets if you find any other issues 😉 

cc/ @zugaldia
