### ISSUE TITLE
circle-radius/antimeridian test is failing

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#5600]
Revealed during the upgrade to pixelmatch4. It was passing before because the old pixelmatch had a bug where black vs. white differences weren't detected.

![image](https://cloud.githubusercontent.com/assets/98601/16638219/6b97b9c8-439a-11e6-8b2a-777c8a2fdc1a.png)

**Comment by brunoabinader** [comment]
This looks similar to the symbol clip issue in https://github.com/mapbox/mapbox-gl-native/issues/5419.

**Comment by mourner** [comment]
The real reason is that circles are explicitly not clipped to tile boundary in GL JS https://github.com/mapbox/mapbox-gl-js/blob/7ec9bbba94f60f188c98b0032aca57371be285fa/js/render/draw_circle.js#L15-L17, unlike the GL Native behavior. 

Should we disable clipping in GL Native too, or the other way around? I'm not sure the "leaking" off the tile is the correct behavior here. cc @tmcw

**Comment by mourner** [comment]
OK, it looks like the real reason is not what I initially thought — stencil test is disabled for circles on native as well; however, for the 512x512 zoom 0 render test which is supposed to load z0 tile, GL JS render suite also loads adjacent "wrapped" tiles `-1,0,0` and `1,0,0`, and GL Native does not.

**Comment by mourner** [comment]
Heh, I found out that the real reason is most likely the fact we're using `MapMode::Still` for render tests, which disables leaking for circles and symbols. https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/renderer/painter_circle.cpp#L22
