### ISSUE TITLE
Highway shield text is tilted

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#5683]
When the map is tilted, Interstate and state route shields remain upright, as expected, but the text inside them tilts with the map:

![gl-native](https://cloud.githubusercontent.com/assets/1231218/16829798/a497b150-494f-11e6-9b2c-180d237c8b17.png)

Reproduces in Streets, Outdoors, and Satellite Streets styles in 5fb0e878b4eb1b2d9555860e86d720e4904de07e on iOS and macOS. Does not reproduce in mapbox/mapbox-gl-js@742b46d7bc46c9489a4bb081036b2a6add7beb40:

![gl-js](https://cloud.githubusercontent.com/assets/1231218/16829793/9df0bfcc-494f-11e6-95ad-497e8ff117fa.png)

Exit shields are unaffected. The difference is likely that highway shields have line placement, whereas exit shields have point placement.

**Comment by 1ec5** [comment]
Bisect implicates ecd4aa14397ed081a521d8412557724e52f277f3 (#5288).

/cc @yhahn

**Comment by yhahn** [comment]
@1ec5 sorry for the delay -- I started digging into this yesterday and need to vet what I think is a subtle difference in behavior between the way an undefined pitch alignment value is handled in the style:

- Native https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/style/layers/symbol_layer_impl.cpp#L39-L47
- JS https://github.com/mapbox/mapbox-gl-js/blob/master/js/style/style_layer/symbol_style_layer.js#L25-L38

Will keep trying to get to the bottom of this today.

**Comment by 1ec5** [comment]
Just a hunch, but in gl-native, if `symbolPlacement` is `line`, it doesn’t look like it’s possible for either `iconRotationAlignment` or `textRotationAlignment` to be `viewport` for the purpose of a `textPitchAlignment` fallback, even if the stylesheet sets it explicitly. The corresponding code in GL JS only defaults `text-rotation-alignment` to `map` if it isn’t specified in the stylesheet; likewise for `icon-rotation-alignment`.

**Comment by 1ec5** [comment]
Indeed, falling back to a temporarily stored value of `text-rotation-alignment` does fix the issue. Here’s what [1ec5-shields-upright-5683](https://github.com/mapbox/mapbox-gl-native/tree/1ec5-shields-upright-5683) looks like:

![upright](https://cloud.githubusercontent.com/assets/1231218/18112317/6f2ae620-6edb-11e6-9a18-2cba4556dd8f.png)

Effectively, this means that `text-pitch-alignment` falls back to the literal value of `text-rotation-alignment` but not the computed value. Is this what the style specification normally means by “matching” a property?

**Comment by boundsj** [comment]
I think the following summarizes what is required to land the set of PRs that fix this issue:

- [x] Add `auto` to the style spec https://github.com/mapbox/mapbox-gl-style-spec/pull/493
- [ ] #6253 @ivovandongen or @zugaldia review Android commit https://github.com/mapbox/mapbox-gl-native/pull/6253/commits/d26c5cecdf2fcef3521692f118de7a8ec5a84edb
- [ ] #6253 @jfirebaugh final overall review (merging is currently blocked because no reviews)
- [ ] Land #6253
- [ ] Land https://github.com/mapbox/mapbox-gl-js/pull/3203 @jfirebaugh 
- [ ] Land https://github.com/mapbox/mapbox-gl-test-suite/pull/144 @jfirebaugh 

In the future, the style spec should be updated to reflect the released versions that support `auto` where applicable.
