### ISSUE TITLE
Map Orientation in mapbox 

### ISSUE THREAD

**Issue by HoussemHfaidh** [mapbox/mapbox-gl-native#5714]
I can  not use the method setMapOrientation in the MapView .
you can help me please?

**Comment by tobrun** [comment]
@HoussemHfaidh thank you for reaching out. Could you add for which platform you are developing? I searched through this repo and couldn't find any reference to a method called `setMapOrientation`.

**Comment by tobrun** [comment]
@HoussemHfaidh 
Could you explain what you are trying to achieve? It's currently not clear with the explanation you are giving. Adding screenshots would make it easier to understand.

**Comment by tobrun** [comment]
@HoussemHfaidh 
I just found the `setMapOrientation` in our [old SDK](https://github.com/mapbox/mapbox-gl-native/issues/5201#issuecomment-222858385). This repo is dedicated to a newer version of that library but using GL instead of raster SDK. Both the tech as API has been recreated from scratch. I would advice you to look at the documentations and examples [here](https://www.mapbox.com/android-sdk/). Reach out if you have any other questions! Closing for now.
