### ISSUE TITLE
Location Picker Native Marker No Longer Shows

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#5717]
While testing Android Telemetry GZIP #5536 this morning I discovered that the Location Picker is no longer functioning as expected.  Specifically when the "Select Location" button is tapped a new native marker isn't being added to the map where the location pin previous was.  This marker is used to indicate the selected location and display an info window with the geocoded address results.

Related Ticket: #5282 

![2016-07-18 11_23_51](https://cloud.githubusercontent.com/assets/989928/16922180/2af7081c-4cda-11e6-8633-9243b293a83c.gif)
_Native Marker Now Missing_

/cc @tobrun @ivovandongen @zugaldia @cammace

**Comment by tobrun** [comment]
This will probably be related to adding SurfaceView in #5000. Will pick this up.

**Comment by tobrun** [comment]
I have been looking into this and it seems that ViewMarkers are only update on mapchange events, this is a slightly different approach as with TextureView. Looking into a efficient way of invalidating the MarkerViewManager after one is added.

**Comment by tobrun** [comment]
Here you can see the issue fixed:

![ezgif com-video-to-gif 50](https://cloud.githubusercontent.com/assets/2151639/17063399/5d9e1eb2-5037-11e6-94a7-661d0655ab18.gif)

*Note*: it still suffers from https://github.com/mapbox/mapbox-gl-native/issues/5762 which is a gl marker issue that also impacts MarkerViews. This issue is only impacts MarkerViews.
