### ISSUE TITLE
Memory issue on init

### ISSUE THREAD

**Issue by type-it** [mapbox/mapbox-gl-native#5722]
Hi,
I have installed MapBox via Fabric.
When i go an trigger the init method like this

- (void)mapBox:(UIView*)mapView
{
    self.map = [MGLMapView new];
    [self.map setFrame:mapView.bounds];
    [self.map setCenterCoordinate:CLLocationCoordinate2DMake(40.712791, -73.997848)
                        zoomLevel:12
                         animated:NO];
    [mapView addSubview:self.map];
}

it doesn't load and I get a crash like this
![zrzut ekranu 2016-07-19 o 09 58 56](https://cloud.githubusercontent.com/assets/20536013/16946970/9893e5fc-4dac-11e6-8790-da3b7894e79f.png)
![zrzut ekranu 2016-07-19 o 10 00 56](https://cloud.githubusercontent.com/assets/20536013/16946971/9895019e-4dac-11e6-9ba7-9f4bf1b7aefb.png)
![zrzut ekranu 2016-07-19 o 09 59 17](https://cloud.githubusercontent.com/assets/20536013/16946973/9895a266-4dac-11e6-9278-26fa230cfcd3.png)
![zrzut ekranu 2016-07-19 o 09 59 31](https://cloud.githubusercontent.com/assets/20536013/16946972/989536d2-4dac-11e6-9dbd-b6ae7f1c17a9.png)

AppName(3849,0x16e087000) malloc: *** mach_vm_map(size=805306368) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
(lldb) 

PLEASE HELP

**Comment by wanggang316** [comment]
me to

**Comment by Paladinfeng** [comment]
it affected me too. the memmory increase to hundreds of MB. the thread would be killed

**Comment by type-it** [comment]
I Found that using
 pod "Mapbox-iOS-SDK", "~> 3.2.0"

Works correctly ;-)

**Comment by Paladinfeng** [comment]
the service was resumed at 7:00pm (time zone: Beijing)

**Comment by friedbunny** [comment]
We’re investigating, thanks for your patience.

**Comment by 1ec5** [comment]
We’re tracking the fix in #5723 and will release the fix today in v3.3.1.

**Comment by HappyDr0id** [comment]
We have the same issue on our Android app since 10am (French time), do you plan to add a fix in the Android SDK too ? Is there any solution without having to update the app with a new MapBox SDK version ?

**Comment by zugaldia** [comment]
@HappyDr0id sorry to hear you're affected by this, we're working on a fix to address this problem as soon as possible. In the meanwhile, there're a couple of things you could do to mitigate this issue:

* You could recommend your users to clear their app cache.
* You could change the style in the app to a new style. This will invalidate the cache and load a fresh style from the server (this requires an app store submission).

**Comment by HappyDr0id** [comment]
@zugaldia Okay, thanks a lot for your answer, I will push an update on the PlayStore with a new map style. I hope that it will fix the issue. Keep up the good work !

**Comment by bsudekum** [comment]
To add a little more clarity on who would be affected by this bug:

* Any version of both the Mapbox iOS and Android SDKs
* Any user who made a request for a Mapbox style between ~12:00am GMT and ~6:00am GMT today
 * Because mapbox-gl-native caches styles once fetched from the server, **this most likely only affected new users fetching a style for the first time**
* The above bullet is also why the bug occurred; a bad style was fetched from the server and cached on the users device. The map would then try to render the bad style and the app would fail.

Like @zugaldia pointed out in https://github.com/mapbox/mapbox-gl-native/issues/5722#issuecomment-233676894, the best path forward is:

* You could recommend your users to clear their app cache (not possible on iOS)
* You could change the style in the app to a new style. This will invalidate the cache and load a fresh style from the server (this requires an app store submission).
* This PR will be rolled into a release today that will fix the issue.

**Comment by bleege** [comment]
We're releasing the PR on Android as `4.1.1` today.  The release can be tracked here: #5725

**Comment by bleege** [comment]
Android 4.1.1 is now released and publicly available on Maven Central.  https://github.com/mapbox/mapbox-gl-native/issues/5725#issuecomment-233766128

**Comment by 1ec5** [comment]
The fix is now in [iOS SDK v3.3.1](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.3.1) and [macOS SDK v0.2.1](https://github.com/mapbox/mapbox-gl-native/releases/tag/macos-v0.2.1) as well.
