### ISSUE TITLE
Style loading from attributes

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#5756]
When you open the AnimaterMarkerActivity you can see a black map with animating cars on it. 

We load the style through xml there:

```xml
<com.mapbox.mapboxsdk.maps.MapView
        android:id="@+id/mapView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/toolbar"
        app:center_latitude="51.502615"
        app:center_longitude="4.972326"
        app:style_url="@string/style_light"
        app:zoom="15" />
```

I guess the issue comes form loading the style url in xml attributes and is a regression from #5566.

**Comment by tobrun** [comment]
The strange thing about this issue is that I'm once able to load the related style, I can always show it. When I remove the app and reinstall it I always start with a black screen. At this point it could also be related to the caching issues we had recently.

**Comment by bleege** [comment]
@tobrun I'm seeing that 494e6849c2a9a0b1191fe95e3252c5418c73509d is now merged in `master`, does that mean we can close this issue or is this still more work to be done?  My assumption is that since it's been merged into `master` that this issue is done but I wanted to confirm first before simply closing.
