### ISSUE TITLE
reduce flyTo time for large distances

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#5794]
Compare starting the map in someplace far away, then locating the user, in both this toolkit and in MapKit (stuttering issues aside, which are due to simulator on desktop): 

![anigif-1469494534](https://cloud.githubusercontent.com/assets/17722/17122526/060c752a-5291-11e6-8454-10d03084f54b.gif)

![anigif-1469494519](https://cloud.githubusercontent.com/assets/17722/17122528/0ab765b2-5291-11e6-95ce-11e9b6c9adb0.gif)

Ayup. 

We should figure out a certain threshold and just snap to the location if greater than it. 

/cc @1ec5

**Comment by 1ec5** [comment]
This was by design in #3589. Snapping to the new location optimizes for informing the user of their current location sooner but at the cost of giving the user less context across long distances. We made the same tradeoff in deciding to animate the user dot in the first place: the dot always lags your actual location by up to a second, but that's preferable to jumping around.

Also note that MapKit is far from consistent: if you launch a MapKit-powered application on a device, turn on user location tracking, wait until MKMapView zooms into your real location, and simulate a very different location via Xcode, MapKit eases the entire distance without varying the zoom level. The result is what seems like an interminable animation (over a minute to travel from Cupertino to Cincinnati).

**Comment by 1ec5** [comment]
All that said, we can cap the flight duration or increase the maximum air velocity. There's plenty of room to experiment with different thresholds.

**Comment by incanus** [comment]
> Also note that MapKit is far from consistent: if you launch a MapKit-powered application on a device, turn on user location tracking, wait until MKMapView zooms into your real location, and simulate a very different location via Xcode, MapKit eases the entire distance without varying the zoom level. The result is what seems like an interminable animation (over a minute to travel from Cupertino to Cincinnati).


Yeah, but you are _simulating_ there, so it's operating under the assumption that the user really did move that distance and uses its built-in smoothly-animating viewport change.

**Comment by 1ec5** [comment]
That's the more realistic scenario, right? I wouldn't really be inclined to optimize for the iOS simulator if it differs from the device.

**Comment by incanus** [comment]
I don't think that it does differ—I see this frequently on device as well. Here's an example (admittedly on iOS 10 beta though): 

![anigif-1469662205](https://cloud.githubusercontent.com/assets/17722/17196178/789b6614-5417-11e6-99d9-082bf50cebbd.gif)

**Comment by incanus** [comment]
And then our library: 

![anigif-1469662585](https://cloud.githubusercontent.com/assets/17722/17196273/486506e8-5418-11e6-9b4c-c1947b672c76.gif)
