### ISSUE TITLE
When Resuming Offline Downloads, Progress Starts Again at 0%

### ISSUE THREAD

**Issue by frowing** [mapbox/mapbox-gl-native#5808]
As stated in the comments above the `resume` method:

```
When a pack resumes after being suspended, it may begin by iterating over the
 already downloaded resources. As a result, the `progress` structure’s
 `countOfResourcesCompleted` field may revert to 0 before rapidly returning to
 the level of progress at the time the pack was suspended.
```

This is really confusing as people using the app might think that the download has started again when it's not the case.

It'd be really nice if it's starting reporting progress from where it left off when it was paused.

**Comment by 1ec5** [comment]
This is unfortunately a consequence of the design in core. @jfirebaugh, are there any cosmetic fixes we can apply that would delay progress updates until the pack "catches up" and begins downloading new resources?

**Comment by jfirebaugh** [comment]
Note that "catching up" is the common case, but downloading of an offline pack can progress irregularly for other reasons. Consider the case where you create a pack that overlaps 50% with an existing pack. Would you expect the progress of the new pack to start from 0% (current behavior) or 50% (behavior with the change proposed here)?

Potential implementation changes that would allow us to adjust this behavior are:

* Doing a manual, in memory join between the computed resource cover of the pack and the set of completed resources existing in the database. (This can't currently be implemented as a database join because the current schema does not have a way to represent a necessary, but incomplete resources.) My hunch is this would be complex code and prohibitively expensive in memory and compute resources.
* Change the database schema such that necessary, but incomplete resources can be represented with "placeholder" rows. Prior to making network requests for incomplete resources or sending progress notifications, populate the database with a full set of placeholders, then check for existing resources (using an efficient database join), then begin the download proper. This strikes me as the correct change, but is far from being "cosmetic".

**Comment by jfirebaugh** [comment]
Closing; I don't think we're likely to change the implementation here.
