### ISSUE TITLE
MGLAnnotationView scalesWithViewDistance should take centerOffset into account

### ISSUE THREAD

**Issue by ttoni** [mapbox/mapbox-gl-native#5825]
Annotation view scales with the center as anchor point. It should scale with the centerOffset as anchor point.

**Platform: iOS**
**Mapbox SDK version: 3.3.2**

### Steps to trigger behavior

 1. Create MGLAnnotationView
 2. Set scalesWithViewingDistance to true
 3. Tilt and rotate map

### Expected behavior
Annotation should stay centered on a point

### Actual behavior
Annotation moves away from point when rotating and moving a tilted map and the annotation scales.

**Comment by boundsj** [comment]
Thanks for the report @ttoni. 

The effect you are seeing happens with or without `scalesWithViewingDistance` applied. Just like with MapKit's `centerOffset` property, the offset represents a distance from a CGPoint, in terms of points, and not a geographic coordinate on the map. This causes, for example, an annotation view with an offset on the y axis to appear to drift as you zoom in and out (while keeping the map center point constant) compared to another annotation with the same geographic coordinate but no offset. This is because the view correctly maintains its offset (in the context of a CGPoint/Vector) from the geographic position of the annotation it represents and, at each different zoom level, the scale of the map changes. 

So, in this example, if the annotations represent a point in San Francisco, the annotation view with the offset will appear to drift in to Oregon and eventually the Arctic if you zoom out far enough. The behavior you describe is the same optical effect but for tilting and rotating the map. If you try the same thing with MapKit you will see the exact same effect.

I'm going to close this issue since I'm not aware of anything we can do to change this behavior. One workaround you may consider is using a UIImage to represent your annotations and then aligning the image inside a larger UIView to get the offset effect you are looking for. That way, your containing view could still be the at the same geo position (with no offset) and would not be subjected to the visual issue described above as the map scale changes due to rotation, panning, and zoom.
