### ISSUE TITLE
Update CompassListener logic in MyLocationView

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#5861]
Our current compass integration inside of MyLocationView is not really great. It was based on a older Google example found [here](https://android.googlesource.com/platform/development/+/master/samples/Compass/src/com/example/android/compass/CompassActivity.java). In meantime @cammace and I found a more recent  example used for Google glass [here](https://github.com/googleglass/gdk-compass-sample/blob/master/app/src/main/java/com/google/android/glass/sample/compass/OrientationManager.java). We should look into porting this to `MyLocationView`.

**Comment by cammace** [comment]
To speak a little more on this issue, Android offers the following sensors to collect orientation information:

| Sensor API Name | Sensor Type |
| --- | --- |
| ~~TYPE_ORIENTATION~~ | ~~Sensor Fusion – Deprecated~~ |
| TYPE_ACCELEROMETER | Hardware |
| TYPE_MAGNETIC_FIELD | Hardware |
| TYPE_GYROSCOPE | Hardware |
| TYPE_GRAVITY | Sensor Fusion / Hardware |
| TYPE_ROTATION_VECTOR | Sensor Fusion / Hardware |

We are currently using either the accelerometer or the magnetic field (magnetometer) depending on what event type occurred. Because these measured values are directly from source they include some heavy measuring inaccuracies an an abundance of electric noise. They are also more susceptible to magnetic fields. A solution to this is to use a low-pass filter to remove some of the noise the sensor collects. In addition using the sensors in combination together will give far better accuracy.

This would result in an unnecessary amount of coding though since using the rotation vector API does exactly this along with a few other awesome features. It has great response time and uses a combination of the accelerometer, gyroscope and magnetometer if they are available. You can read [more about this here](http://developer.android.com/guide/topics/sensors/sensors_motion.html#sensors-motion-rotate).

Along with changing which orientation sensor we are using, we currently aren't accounting for the device orientation. So when the user switches from portrait to landscape, the user location will rotation 90 degrees to point in the same direction. The solution to this is to check device orientation and if they are in landscape, remap the coordinate system using:

```java
SensorManager.remapCoordinateSystem();
```

**Comment by bleege** [comment]
@cammace I love to the [detail and context that you provided for this topic](https://github.com/mapbox/mapbox-gl-native/issues/5861#issuecomment-237603191), not to mention making it happen!  Great job!
