### ISSUE TITLE
Map view does not call -viewForAnnotation when the user selects an annotation

### ISSUE THREAD

**Issue by MaxKramer** [mapbox/mapbox-gl-native#5925]
### Actual behavior

Hi Mapbox,

- The Map does not trigger an update to the appearance of the annotation view/image when it changes state from selected to deselected and vice-versa. This means that it's not possible to have a different image depending on whether the annotation was selected or not.

Our current implementation removes the annotation from the map and re-adds it, which is causing other issues as well as other delegate methods to be called.

**Platform:** iOS
**Mapbox SDK version:** 3.3.4

### Steps to trigger behavior

 1. Select an annotation on the map

### Code Snippet

```
 func mapView(mapView: MGLMapView, imageForAnnotation annotation: MGLAnnotation) -> MGLAnnotationImage? {        
        guard let annotation = annotation as? ScooterAnnotation else {
            return nil
        }
        
        var annotationView: MGLAnnotationImage!
        
        if annotation.selected == true {
            annotationView = mapView.dequeueReusableAnnotationImageWithIdentifier("SelectedPin")
            
            if annotationView == nil {
                annotationView = MGLAnnotationImage(image: UIImage(named: "map_scooter_selected")!, reuseIdentifier: "SelectedPin")
            }
        } else {
            annotationView = mapView.dequeueReusableAnnotationImageWithIdentifier("DefaultPin")
            
            if annotationView == nil {
                annotationView = MGLAnnotationImage(image: UIImage(named: "map_scooter_unselected")!, reuseIdentifier: "DefaultPin")
            }
        }
        
        return annotationView
    }
```

**Comment by friedbunny** [comment]
[This example](https://www.mapbox.com/ios-sdk/examples/annotation-views/) shows how to change an annotation view’s appearance based on selection state: override `setSelected:animated:` in your subclass.

MGLAnnotationImage lacks a `selected` property — perhaps we should add one, @boundsj?

**Comment by boundsj** [comment]
Since we already have a [selected](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/src/MGLAnnotationView.h#L163) property on `MGLAnnotationView` and the strategy of subclassing `MGLAnnotationView`'s `setSelected:animated:` method (as noted in the example from @friedbunny and as you would with MapKit) would be a good choice to achieve the desired behavior here, I think we should stay focused on the `MGLAnnotationView` based API.

@MaxKramer I'm going to close this for now but please reopen if you find that there is something blocking you from using the approach illustrated in the example.

**Comment by MaxKramer** [comment]
@boundsj I gave that a go once I'd had a read through the docs, but although it's somewhat of an edge-case, our selected and unselected images are of different sizes, and therefore the frame of the annotation view must be updated upon selection - hence the reason why I decided to use two different annotation view reuse-identifiers, such that a new frame doesn't need to be calculated when the selected state changes.

**Comment by boundsj** [comment]
Thanks @MaxKramer. I'm hesitant to add logic to call `viewForAnnotation:` for each selection. I think that, for a large majority of use cases, that would be surprising behavior. Also, I double checked and we are currently aligned with how MapKit works in this case. 

I think your feature would be best implemented by overriding `MGLAnnotationView`'s (**not** MGLAnnotationImage) `setSelected:animated:` method as noted above in [the example](https://www.mapbox.com/ios-sdk/examples/annotation-views/). Of course, you would want to do something like change the `CGAffineTransformScale` of the view instead of animating the border like in the example. The advantage with that approach is that you could animate the transform however you like instead of having a sudden view change (like what would happen in the theoretical case of doing this with `viewForAnnotation:`). I'm not sure why you would like to avoid updating/animating the frame of the `MGLAnnotationView` subclass but I would not be particularly worried about that. Especially given the UX advantages of being able to add in a little animation.
