### ISSUE TITLE
NoSuchSourceException missing

### ISSUE THREAD

**Issue by ivovandongen** [mapbox/mapbox-gl-native#6034]
The class is missing, but referenced from JNI. Also, this would make `removeSource` better aligned with `removeLayer`.

**Comment by ivovandongen** [comment]
Merged

**Comment by mattijsf** [comment]
I think you added NoSuchSourceException in the wrong package. JNI references the NoSuchSourceException from the `layers` package instead of the `sources` package resulting in a

> Didn't find class "com.mapbox.mapboxsdk.style.layers.NoSuchSourceException" on path: DexPathList

Quick workaround is to catch a generic `Exception` instead of the specific NoSuchSourceException.

See:
https://github.com/mapbox/mapbox-gl-native/blob/2a5bf311ac0b79103fc7c9ec28a5493570e5c052/platform/android/src/jni.cpp#L1214-L1218
