### ISSUE TITLE
Android: MapViews in a RecyclerView/List

### ISSUE THREAD

**Issue by vanshg** [mapbox/mapbox-gl-native#6041]
I want to use the MapView in a RecyclerView (where each list item has it's own MapView as the "image"). Is there someway to get a small section of the Map as an image (for efficiency purposes)? If not, is it possible to somehow efficiently have multiple MapViews in a list like that?

**Comment by vanshg** [comment]
If something like the image conversion doesn't exist, it'd be nice if it was added sometime in the future

**Comment by tobrun** [comment]
There are 2 ways to handle this use-case both involve using an image instead of an actual mapview. Since an actual mapview will never perform well in such a usecase. The first is using the `snapshot` API found in `MapboxMap#snapshot`. This allows to take a bitmap from the currently shown map. This approach requires you to already to have a map shown an isn't usable for all use-cases.

Another approach is using the static API webpoint. With this you can render the maps on a server and let them return a Bitmap. More information about this https://www.mapbox.com/api-documentation/#static.

Thank you for reaching out! Closing as question has been answered.

**Comment by donkii** [comment]
I have the same issue as @PieterVenter77 only when scrolling the map out and in again. My only solution is using TextureView instead of SurfaceView, but it consumes more performance.

**Comment by tobrun** [comment]
TextureView is a requirement for scrolling surfaces, GLSurfaceView is not optimized to handle this.

**Comment by donkii** [comment]
@tobrun It worked fine till I upgraded from version 5 to 7.1.2.
