### ISSUE TITLE
Render to a single context in HeadlessView

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mapbox-gl-native#6212]
The current `HeadlessView` rendering architecture was designed when each `mbgl::Map` rendered on its own thread, which necessitated the use of a unique GL context per map, as contexts are bound to a single thread. https://www.opengl.org/wiki/Memory_Model#Multiple_threads_and_contexts describes this in more detail.

Since https://github.com/mapbox/mapbox-gl-native/pull/2909 moved all rendering onto the main thread, these per-map contexts should no longer be necessary. Because calls to [`glXMakeContextCurrent`](https://www.opengl.org/sdk/docs/man2/xhtml/glXMakeContextCurrent.xml) trigger an implicit `glFlush`, swapping these contexts could be causing unnecessary synchronization and possibly [GL pipeline stalls](https://github.com/mapbox/mapbox-gl-native/issues/477#issuecomment-243474634).

I think that this change in combination with https://github.com/mapbox/mapbox-gl-native/issues/477 could possibly remove all implicit flushes from the Node.js render pipeline.

I'm hoping to avoid revisiting old nightmares in https://github.com/cutting-room-floor/node-mapbox-gl-native/issues/5 and https://github.com/cutting-room-floor/node-mapbox-gl-native/issues/64 while implementing this. 😄 

/cc @kkaefer @tmpsantos @tiagovignatti @miccolis

**Comment by jfirebaugh** [comment]
This is going to require some careful review and perhaps modifications to the internals of `Map`, which currently makes optimizations based on the assumption that the `View` provides each `Map` with a unique context.

I'm thinking mainly of [`gl::Config`](https://github.com/mapbox/mapbox-gl-native/blob/8edf9959460f9f7e80b200f0a124b1a839cfd4c8/src/mbgl/gl/gl_config.hpp). If it's _only_ used when actually painting (and not, say, opportunistically binding / uploading buffers as data comes in), and headless rendering only ever paints once per map, then this is probably safe. Otherwise, we need to ensure that `setDirty()` gets called whenever it's possible that the shared context was modified by another `Map` object.

**Comment by jfirebaugh** [comment]
Or better yet, have the view provide the `gl::Config`, and share it between `Map`s that are sharing a context.

**Comment by mikemorris** [comment]
Making a note to track https://github.com/mapbox/mapbox-gl-native/pull/5938 and https://github.com/mapbox/mapbox-gl-native/pull/5620, which fix a few bits of GL context state not yet tracked by `gl::Config`.

**Comment by tmpsantos** [comment]
> This is going to require some careful review and perhaps modifications to the internals of Map, which currently makes optimizations based on the assumption that the View provides each Map with a unique context.

We already have the `GLContextMode::Shared` mode for that no?

**Comment by jfirebaugh** [comment]
`GLContextMode::Shared` indicates we're sharing the context with code we don't have control over, so must treat the `gl::Config` as dirty after every frame. But we can do better in this case.
