### ISSUE TITLE
MapView with SlideMenu issue

### ISSUE THREAD

**Issue by amugox** [mapbox/mapbox-gl-native#6247]
![screenshot_2016-09-04-09-25-48](https://cloud.githubusercontent.com/assets/15261216/18229420/c42dfae6-7281-11e6-8b26-fe5f706a36dd.png)

**Platform:**
**Mapbox SDK version:**
### Steps to trigger behavior
1. Have an activity that has a MapView and a SlidingMenu
### Expected behavior

When SlideMenu moves the Map should not be invisible thus overlapping the menu bar
### Actual behavior

When the SlideMenu moves the Map is invisible making the background menu visible

**Comment by tobrun** [comment]
@amugox could you add some more information to the ticket as:
 - mapbox sdk version?
 - link to the SlidingMenu dependency you are using?

We had similar issues with the official NavigationDrawer from Google but were able to workaround that issue by adding a transparent overlay on top of our MapView.

**Comment by cammace** [comment]
We added a [navigation drawer activity](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/NavigationDrawerActivity.java) to the testapp awhile back which shows the nav drawer working properly. Closing due to lack of information.
