### ISSUE TITLE
Map not centered over bottom-aligned user puck

### ISSUE THREAD

**Issue by miccolis** [mapbox/mapbox-gl-native#6257]
**Platform:** iOS
**Mapbox SDK version:** 3.4.0-alpha.4 (51b2033)

It's looking like we're not putting the user puck on the actual location of the user. For example:

![2016-09-06 11 53 33](https://cloud.githubusercontent.com/assets/77205/18281195/f31ae90a-7429-11e6-9ef5-a49ad8d5a503.png)

Has me down an alley off 15th street, but actually I'm standing right at the corner of 14th and S.

It's very easy to generate this behavior in a test app, so I'm happy to provide more screenshots.

As you move around and the POV changes the puck swings around and has a very disorienting behavior.

**Comment by boundsj** [comment]
This was caused by https://github.com/mapbox/mapbox-gl-native/pull/6216

**Comment by 1ec5** [comment]
(For those following along at home, this is an internal testbed application we use to exercise the SDK more thoroughly than iosapp does.)

The issue is that the user puck is anchored correctly towards the bottom of the map view, but the map isn’t taking that vertical alignment into consideration when centering the map on a particular coordinate. This regression was almost certainly introduced by #4067. https://github.com/mapbox/mapbox-gl-native/pull/4067#issuecomment-187941664 might be relevant to a fix.

**Comment by 1ec5** [comment]
The issue can also be seen in https://github.com/mapbox/mapbox-gl-native/pull/4067#issuecomment-243612467: the user dot appears to shift between the Mapbox SF office and a location several blocks to the south just by changing the vertical alignment to `MGLAnnotationVerticalAlignmentBottom`.
