### ISSUE TITLE
Course tracking mode animates at 30fps

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-native#6258]
**Platform: iOS 10**
**Mapbox SDK version: ios-v3.4.0-alpha.4**
### Steps to trigger behavior
1. Set `userTrackingMode` to `followWithCourse`
2. Move user location
### Expected behavior

Smooth user location animation updates
### Actual behavior

Jagged movement between location updates

![4](https://cloud.githubusercontent.com/assets/1058624/18281385/8b3d240a-7411-11e6-992f-681fd51fb238.gif)
# 

*Only tested in the simulator. Unsure if this happens on device

/cc @1ec5 @friedbunny

**Comment by friedbunny** [comment]
I don’t see this while using a simulated trace on my iPhone 5, iOS 10b8. (Admittedly, course does not work with GPX traces.)

**Comment by 1ec5** [comment]
I’m currently unable to reproduce this issue in v3.4.0-alpha.4 on an iPhone 6 running iOS 9. In the iPhone 6s / iOS 10 simulator, there can be quite a bit of stuttering even in user location tracking mode. However, it appears to affect the Core Animation–driven user dot animations as well, suggesting a general simulator performance issue rather than an issue in the SDK.

**Comment by friedbunny** [comment]
Not reproducible.
