### ISSUE TITLE
enhancement - Heatmap overlays

### ISSUE THREAD

**Issue by johndpope** [mapbox/mapbox-gl-native#6304]
Are there any plans to extend gl-native to support heatmap overlays?

https://github.com/mapbox/mapbox-gl-native/issues/2167
https://github.com/mapbox/mapbox-gl-native/issues/3420

There are different sdks to support mapkit / google maps - but it doesn't look like the native mapbox sdk can currently support this. 
https://github.com/ryanolsonk/HeatMapDemo

**Comment by 1ec5** [comment]
Yes, Android SDK 4.2.0 (in beta) and iOS SDK 3.4.0 (in alpha) do support faux heatmaps using circles, but using a clustered GeoJSON source and circle layers rather than the MGLCircle class proposed in #2167.

The Android demo application has a [a heatmap activity](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/CreateHeatmapPointsActivity.java) that demonstrates how to do this. We don’t have an example ready for iOS yet, but the relevant classes are [MGLGeoJSONSource](https://www.mapbox.com/ios-sdk/api/3.4.0-alpha.4/Classes/MGLGeoJSONSource.html) and MGLCircleStyleLayer, and you may be able to follow the Android and [GL JS](https://www.mapbox.com/mapbox-gl-js/example/heatmap/) examples to some extent.

**Comment by 1ec5** [comment]
In case the faux heat map solution I mentioned above (which I’ve since learned is called a “hot spot map”) doesn’t meet your needs, I’ve filed mapbox/mapbox-gl#27 for adding support for real heat maps.

**Comment by johndpope** [comment]
Thanks
