### ISSUE TITLE
Cannot load offline map on iOS device

### ISSUE THREAD

**Issue by alpadedhia** [mapbox/mapbox-gl-native#6344]
Hello, 

I download offline map in view controller A. The map is downloaded. But I cannot load the offline map on device in view controller B. This works on simulator. I am using iPhone 6, iOS 9.3.5.

Do we need to configure anything in mapbox token ? Anything else that we may be missing?
Platform: ios
Mapbox SDK version: 3.3.3

Appreciate your help on this. 
Thanks

**Comment by friedbunny** [comment]
Thanks for using our iOS SDK. Per [our contribution guidelines](https://github.com/mapbox/mapbox-gl-native/blob/master/CONTRIBUTING.md), this repository is intended for development and bug reports. For support, please see our [help docs](https://www.mapbox.com/help/#build-a-mobile-app) and [iOS SDK](https://www.mapbox.com/ios-sdk/) pages.

In order to diagnose this issue, please provide a project that reproduces the problem you’re seeing.

**Comment by friedbunny** [comment]
Thanks for the invitation to your app’s repo, but please provide a _minimal_, clean project that reproduces your issue. This will help isolate the issue and allow you to write instructions for how to reliably reproduce it.
