### ISSUE TITLE
Mapbox-iOS-SDK 1.6

### ISSUE THREAD

**Issue by iDevelopper** [mapbox/mapbox-gl-native#6369]
Hello,

You know that many developers are working with the older version of the SDK. However, this version was removed from cocoa and github repo.

Would it be possible to make it available again?

Thanks.

**Comment by friedbunny** [comment]
We can make it more readily available to those who are already using it: [here’s a link to 1.6.1](https://s3.amazonaws.com/mapbox/mapbox-gl-native/ios/builds/mapbox-ios-sdk-1.6.1.zip).

Fixing the CocoaPods issue will mean pushing a new version (`1.6.1-cocoapods-made-us-do-this`, perhaps) because updating podspecs is not allowed.

_Please be aware that the legacy SDK has been deprecated for some time now and we cannot guarantee future compatibility._

**Comment by jfirebaugh** [comment]
Sorry @iDevelopper, this SDK is deprecated; our resources need to remain focused on the modern version.

**Comment by iDevelopper** [comment]
@friedbunny , thanks for quick answer and as you said, for future compatibility I need to have the sources too (.m). Cocoapods is not necessarily required. I would like to integrate in my app the last version of the older api with sources. Or if you know a way to skip the repo update when run pod install.

@jfirebaugh , yes but my application use old offline mbtiles spec.

Thanks a lot. Regards.
