### ISSUE TITLE
Get rid of dependent texture reads

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#64]
Our line pattern shader performs dependent texture reads. The word "dependent" is slightly misleading, as it typically refers to using the result of one texture read as input to another texture read. However, in our case it refers to us performing lots of calculations before we use it as an input parameter to the texture read.

**Comment by ansis** [comment]
Three shaders have these kind of dependent texture reads: pattern, linepattern, linesdf. All three of these perform a modulus in order to wrap the patterns.

I can think of two ways to remove the dependent reads:
- use individual textures for each pattern and use the built in texture wrapping. This would break future data-driven styling which will need to use atlases.
- split up geometries so that coordinates never need to be wrapped. This seems really, really complicated.

I'm not seeing us implementing either approach. The complexity and downsides seem bigger than the benefits.
