### ISSUE TITLE
Unable to use LOST API in conjunction with Mapbox Android SDK

### ISSUE THREAD

**Issue by dmeignan** [mapbox/mapbox-gl-native#6462]
**Platform:** Android
**Mapbox SDK version:** 4.1.1

The Android Mapbox SDK use the [LOST API](https://github.com/mapzen/lost) version 1.1.0 (see `compile 'com.mapzen.android:lost:1.1.0'` in [Gradle dependencies of MapboxGLAndroidSDK](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/build.gradle)). I also use in my app the LOST API. However, the [version 1.1.0 of the LOST API does not manage correctly multiple location listeners](https://github.com/mapzen/lost/issues/62). In particular, when the `LocationServices` of Mapbox requests the `locationClient` to disconnect (in [LocationServices.java](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationServices.java)), then it shuts down the LOST location engine for all location listeners. This problem has been [solved in version 1.1.1 of the LOST API](https://github.com/mapzen/lost/releases/tag/lost-parent-1.1.1).

The Mapbox Android SDK should use the version 2.0.0 or at least 1.1.1 of the LOST API for a better integration in apps that also use LOST API.

**Comment by tobrun** [comment]
I did a gradle sync to see how big the semver change of 2.0.0 is:
![screen shot 2016-09-27 at 13 30 23](https://cloud.githubusercontent.com/assets/2151639/18871649/a5e580ee-84b6-11e6-9de9-b409a5a35afd.png)

Since we are close to release I'm going to assign it to `android-future`. We are currently thinking of rewriting the way we are handling these location udpdates. For now I'm going to update the dependency to `1.1.1` as requested. This should introduce any changes in code. Thank you for reaching out!

**Comment by tobrun** [comment]
Update to 1.1.1 got merged in #6476. We will upgrade other dependencies with next release cycle.

**Comment by clydebarrow** [comment]
See PR #6548

**Comment by tobrun** [comment]
closing this in favor of #6537
