### ISSUE TITLE
Custom annotation looses their origin position after changing its size

### ISSUE THREAD

**Issue by aksonov** [mapbox/mapbox-gl-native#6474]
**Platform:** iOS
**Mapbox SDK version:** latest

### Steps to trigger behavior

 1. Use custom annotation example and add button inside custom annotation view.
 2. Change its frame when button is tapped

### Expected behaviour
Size of annotation is changed, position on map is the same

### Actual behaviour
Size of annotation is changed, position is in left upper corner. After scrolling map, annotation position became correct.

Before touch:

![simulator screen shot 27 sep 2016 12 34 40](https://cloud.githubusercontent.com/assets/1321329/18869892/a88a6a42-84ae-11e6-9d76-bcaf22bf7f26.png)

After touch:
![simulator screen shot 27 sep 2016 12 34 42](https://cloud.githubusercontent.com/assets/1321329/18869894/aa498eb2-84ae-11e6-820e-5d1400e19d22.png)

**Comment by boundsj** [comment]
Hi @aksonov. It sounds like you may want to use a scale transform instead of adjusting the frame.

Keep in mind that adjustments that the application developer makes to the view that represents the annotation are not controlled by the SDK. In other words, you must re-center the view as desired if you are changing its width and height. In your case, it appears that you are increasing the width and height and using {0,0} as the origin point.

Relatedly, the SDK does update the position of the view when the map is scrolled (as you've noticed) and it does so by updating the view's center.

**Comment by aksonov** [comment]
But how to find out original annotation position at the map? I believe SDK should know it, right?

Pavel.

**Comment by aksonov** [comment]
In other words, how to restore annotation position?

Pavel.

**Comment by boundsj** [comment]
>  how to find out original annotation position

You could send [-[MGLMapView convertCoordinate:toPointToView:]](https://www.mapbox.com/ios-sdk/api/3.3.4/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(im)convertCoordinate:toPointToView:) and pass the coordinate of the annotation of the view you want to manipulate. In general, you should first look to reference [the API documentation](https://www.mapbox.com/ios-sdk/api/3.3.4/index.html) for questions like these.
