### ISSUE TITLE
Interacting with annotation points in style layer

### ISSUE THREAD

**Issue by rmnblm** [mapbox/mapbox-gl-native#6505]
**Platform:** iOS 10, Swift 3
**Mapbox SDK version:** 3.4.0-alpha.4

First: Let me thank the Mapbox community. I'm using Mapbox since more than a week and may have seen just the tip of the iceberg, still learning a lot of things everyday, and I'm really impressed about the fast responsiveness of this community.

While I'm currently building an app for a client using the Mapbox iOS SDK, knowing that there a lot of features to come in the future (especially runtime styling), I often miss a few things that'd be great for future releases (and that's why I'm always writing down my thoughts and ideas which can help improve Mapbox for iOS. Because of the lack of documentation for the newest version of Mapbox iOS SDK, I first check in code, if there is a possible solution to my problem, if not, I check if there's a planned feature/issue written down in the repo, if not, I'm going to write an issue).

Now to my question: Is there a way to interact with annotation points in a style layer coming from a style URL? Because `public func mapView(_ mapView: MGLMapView, didSelect annotation: MGLAnnotation)` isn't called when I touch a point in a style layer.

**Comment by 1ec5** [comment]
Unlike annotations, style layers don’t come with interactivity and callout views out of the box. Instead, you have to build it yourself: install your own tap gesture recognizer, call `MGLMapView.visibleFeatures(at:styleLayerIdentifiers:)`, and position your own custom callout view over the feature’s coordinate (using `convert(_:toPointTo:)`. Hide the callout view in `mapView(_:regionWillChange:)`, or update its location continuously in `mapView(_:regionIsChanging:)` and `mapView(_:regionDidChange:)`.

I know this sounds like a lot of work. #6181 would make annotations more like style layers, in the process adding a lot of annotation-like functionality to style layers in general. That’s quite a ways off, however. Under the hood, annotations are already implemented using style layers to some extent; once #6097 lands, you’ll be able to use an annotation but otherwise treat it like part of a style layer, more or less.

**Comment by rmnblm** [comment]
Works perfectly, thanks for your help @1ec5. Here's how I did it:

```
override func viewDidLoad() {
    let tapGestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(handleTap))
    mapView.addGestureRecognizer(tapGestureRecognizer)
    
    mapView.styleURL = URL(string: "YOUR_STYLE_URL")
    let center = CLLocationCoordinate2D(latitude: 37.383925, longitude: -122.07135)
    mapView.setCenter(center, zoomLevel: 11.0, animated: false)
}

func handleTap(recognizer: UITapGestureRecognizer) {
    let location = recognizer.location(in: mapView)
    let touchableSquare = squareFrom(location: location)
    for feature in mapView.visibleFeatures(in: touchableSquare) {
        print(feature.attributes)
    }
}

private func squareFrom(location: CGPoint) -> CGRect {
    let length = 50.0
    return CGRect(x: Double(location.x - CGFloat(length / 2)), y: Double(location.y - CGFloat(length / 2)), width: length, height: length)
}
```

**Comment by rmnblm** [comment]
I'm currently facing a problem with above solution: The function `mapView.visibleFeatures(in:)` correctly returns all features inside my touchable square. The problem is: there are some coordinates missing in the `MGLPolylineFeature` depending on the zoom level I'm currently at. See examples below:

**ZoomLevel between 12-13**

![line1](https://cloud.githubusercontent.com/assets/5942764/19006212/abd0ba14-875e-11e6-8d7c-f0a4b980bc21.gif)

```
<MGLPolylineFeature: 0x1740be1e0; count = 81; bounds = { sw = {47.1, 8.6}, ne = {47.1, 8.6}}>
```

**ZoomLevel between 13-14**

![line2](https://cloud.githubusercontent.com/assets/5942764/19006205/a7514418-875e-11e6-9139-f2ed211e628b.gif)

```
<MGLPolylineFeature: 0x1742b5480; count = 66; bounds = { sw = {47.1, 8.6}, ne = {47.1, 8.6}}>
```

Is this a bug or am I doing something wrong? 🙈
