### ISSUE TITLE
MapboxAccountManager refactor

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#6534]
We are looking into changing the way MapboxMapManager works. Recently this object was only responsible for managing accesstokens but recently it became responsible for managing connection changes as well. With an upcoming release I suggest is completely rework currently exposed API. I would suggest updating the name to something else eg. `Mapbox`.

cc @mapbox/android

**Comment by zugaldia** [comment]
I would like to move this object to `mapbox-java` so that it can easily handle tokens for API requests too. The challenge is that as you note `MapboxAccountManager`:

> recently it became responsible for managing connection changes as well.

I'm thinking of having a generic `NetworkInfo` interface without any Android deps, with the SDK providing a default implementation using Android's.

I like `Mapbox` instead of `MapboxAccountManager` too.

**Comment by ivovandongen** [comment]
> I'm thinking of having a generic NetworkInfo interface without any Android deps, with the SDK providing a default implementation using Android's.

👍 This would indeed give some more flexibility here
