### ISSUE TITLE
Custom Projection

### ISSUE THREAD

**Issue by bessermt** [mapbox/mapbox-gl-native#6554]
I would like to write my own custom projection code to replace the Mercator projection. I can't see how this can be done with the current code. Is this possible? If not, how can this feature be added?

**Comment by ryanbaumann** [comment]
Hi @bessermt, can you project your source data before adding it as a source to Mapbox GL JS? Mapbox GL JS maps use the Web Mercator coordinate system `EPSG:3857`.

PROJ4 is a popular library for coordinate transformations. it has [JS bindings](https://github.com/proj4js/proj4js), as well as bindings for other languages.

**Comment by tmcw** [comment]
Going to guess that this is about display projections, not projections in data. Mapbox GL Native supports the Mercator projection only. There's a [PR](https://github.com/mapbox/mapbox-gl-js/pull/1466) (closed for inactivity) and an [issue](https://github.com/mapbox/mapbox-gl-js/issues/3184) in GL JS for this feature, and the maintainer opinion is that we'd accept a PR.

**Comment by mitch-besser** [comment]
I can't use JS, AFAIK. My app will have no Internet connection and I assume the JS requires that. ??? The point is to not project the data, but to use a different map projection. The tiles are not in Mercator intentionally and changing them is not allowed. There are many uses for custom map projections, not the least of which is games. From what I can see, exposing the projection would be super easy to code, only requiring 2 functions to use a callbacks instead of direct calls. Current users would see no changes to existing code. Unbelievably simple, extremely useful, but not done. Seems very strange that custom projections are not supported. Google supports them, but only in their JS version. This would allow a jump ahead of Google if that matters.

**Comment by tmcw** [comment]
> Unbelievably simple, extremely useful, but not done. 

Please refrain from evaluating the technical difficulty of this work, especially in a larger system. There are very valid reasons why projections are not supported more broadly, on a product (you can't mix projections), standards (no standard scale sets) and performance (on-the-fly reprojection) dimensions. Or, if you're confident that it is a two-line fix, then we're happy to accept a pull request.

**Comment by mitch-besser** [comment]
I never claimed it was a 2 line fix. I did say it was a 2 function fix. Yes, simple. Is this not the place to make change requests?

**Comment by tmcw** [comment]
Yep, this is the place you can submit a pull request, through the normal GitHub flow, and see the [contributing documentation](https://github.com/mapbox/mapbox-gl-native/blob/master/CONTRIBUTING.md) to get started.

**Comment by mitch-besser** [comment]
Not a pull request, a change request.

**Comment by myarjunar** [comment]
```
PROJ4 is a popular library for coordinate transformations. it has JS bindings, as well as bindings for other languages. The client or the server could perform the projection from the source coordinate system to EPSG:3857.
```

Could this be the way to enable custom projection in mapbox-gl-native? By using PROJ4? If so, I would like to contribute to add this feature utilizing PROJ4 lib.
