### ISSUE TITLE
allow mutation of MGLPolygon interior polygons/holes

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#6576]
Tail work from https://github.com/mapbox/mapbox-gl-native/pull/6565. If we allow this, we can use the same facility as there to update the annotation on the fly visually.

**Comment by 1ec5** [comment]
At first blush, it’d be trivial to also observe changes to the `interiorPolygons` key path of any polygon we add to the map. However, note that, since #6565 makes _any_ polygon a shape-shifting polygon, we actually (also?) need to observe the `interiorPolygons.coordinates` key path. (We don’t have to recurse any further than that: unlike MapKit’s MKPolygon, MGLPolygons can’t contain islands.)

**Comment by 1ec5** [comment]
Pulling into the v3.4.0 milestone. I think it would be highly desirable to ship this issue and #6583 in the same release as #6565 to simplify expectations about what we support.
