### ISSUE TITLE
Map remains greyed out when displayed in a DialogFragment

### ISSUE THREAD

**Issue by mattryavec** [mapbox/mapbox-gl-native#6634]
**Platform: Android**
**Mapbox SDK version: 4.2.0-beta3**

This is a regression from 4.1.1. I've attached a small sample Android Studio app, [MapboxBug.zip](https://github.com/mapbox/mapbox-gl-native/files/516635/MapboxBug.zip), that reproduces the issue.
### Steps to trigger behavior
1. Set up a DialogFragment to display a MapView
2. Trigger a display of the DialogFragment
### Expected behavior

Map displays normally (see "Screenshot_4_1_1")
![screenshot_4_1_1](https://cloud.githubusercontent.com/assets/330353/19197873/2e943374-8c8a-11e6-826b-fefe338239dc.png)
### Actual behavior

Map displays and appears to be functional, but still has a grey disabled-looking overlay
![screenshot_4_2_0](https://cloud.githubusercontent.com/assets/330353/19197890/4b1113a0-8c8a-11e6-9ab6-73a04c71c089.png)

**Comment by tobrun** [comment]
This is probably related to the introduction of SurfaceView in #5000. We are going to switch from TextureView to SurfaceView in the `4.2.0` release for performance reasons. I will look into the issue more thoroughly but for now you can use the `textureMode(true)` option MapboxMapOptions or use `textureMode=true` in xml to use TextureView instead of SurfaceView.

cc @mapbox/android

**Comment by cammace** [comment]
Like @tobrun mentioned, this has to do with the upgrade we made to using SurfaceView. For now, enabling `texureMode` results in the map looking correct:

<img src="https://cloud.githubusercontent.com/assets/5652865/19520730/307f8734-95df-11e6-863f-79326d72242f.png" width=360/>

**Comment by tobrun** [comment]
Using TextureView is a valid workaround. Closing.
