### ISSUE TITLE
Annotation symbols are overdrawn if located on tile edges

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#6670]
Spin-off from the discussions around stencil clip usage from #3563.

Fixing the position of repeated features near tile edges caused a new issue to rise: opaque symbols are now overdrawn:
<img width="1136" alt="screen shot 2016-10-09 at 9 20 47 pm" src="https://cloud.githubusercontent.com/assets/76133/19222648/720a04e8-8e66-11e6-9f15-7df9440775cc.png">

**Comment by brunoabinader** [comment]
As [previously mentioned in #3563](https://github.com/mapbox/mapbox-gl-native/pull/3563#issuecomment-252650498), fixing this issue requires either removing stencil clip usage for symbols (option 1), or enforcing stencil clip for all symbol buckets (option 2).

__Option 1__ is tricky because it contains some corner cases in which I have no proper fix in mind:
- Style property [symbol-avoid-edges](https://www.mapbox.com/mapbox-gl-style-spec/#layout-symbol-symbol-avoid-edges) depends on stencil clip functionality
- Requires enforcing non-duplicated entries when _updating tile layers_, _layout_ and _querying_ features:
 - 1.1) When updating annotation tile layers, we check if each [symbol intersects with them](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/annotation/annotation_manager.cpp#L164-L167). We can enforce them to be unique by e.g. letting only the left-topmost tile to get the feature. That's not something trivally possible with regular symbol layers because we already [receive them duplicated from the server](https://github.com/mapbox/vector-tile-spec/tree/master/2.1):
> For example, if a tile has an extent of 4096, coordinate units within the tile refer to 1/4096th of its square dimensions. A coordinate of 0 is on the top or left edge of the tile, and a coordinate of 4096 is on the bottom or right edge. Coordinates from 1 through 4095 inclusive are fully within the extent of the tile,

 - 1.2) When inserting symbol geometries in layout step, we could [filter symbol instances based on their ID](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/layout/symbol_layout.cpp#L496). That involves [forwarding the feature ID](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/layout/symbol_layout.cpp#L229) when populating the symbol instances container.
- 1.3) When querying, we can easily filter out duplicated features based on their ID.

__Option 2__ involves enforcing stencil clip for all symbol buckets. I've already tried this and it produces erroneous rendering results such as the ones seen below (clipped symbols close to tile edges):
<img width="1136" alt="screen shot 2016-10-10 at 10 48 56 am" src="https://cloud.githubusercontent.com/assets/76133/19229594/5a23d6d0-8ed7-11e6-9935-4dca67fe07cc.png">

**Comment by ansis** [comment]
> As previously mentioned in #3563, fixing this issue requires either removing stencil clip usage for symbols (option 1), or enforcing stencil clip for all symbol buckets (option 2).

Why is this the case? I read through #3563 and I still don't understand why only these options exist

**Comment by brunoabinader** [comment]
>Why is this the case? I read through #3563 and I still don't understand why only these options exist

@ansis though not specific to annotation symbols, this issue happens when both assertions below are true for symbol layers:

1. Stencil clip is __disabled__ (_draw across tile edges_); and
2. Symbol feature is located on tile edge i.e.:
  - `anchorPoint.x == 0 || anchorPoint.x == util::EXTENT` or
  - `anchorPoint.y == 0 || anchorPoint.y == util::EXTENT`

My understanding is that the overdraw happens because we [consider a feature to be __inside__](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/layout/symbol_layout.cpp#L287) when its anchor point is located within the `0...extent` __inclusive__ range when populating _symbol instances_ - used for calculating collision and generating _symbol buckets_ in `SymbolLayout::place`. 
__Because features are repeated among neighbor tiles when they are located on tile edges__, this makes each symbol bucket render its own repeated version of the same feature, and because we are not clipping, overdraw happens.

I've added a render test example here: [symbol-opacity-edge/default](https://github.com/mapbox/mapbox-gl-test-suite/blob/symbol-opacity-on-tile-edge/render-tests/symbol-opacity-edge/default/style.json?short_path=b329890)

In the render test above, I've added a source containing two GeoJSON points: one at `[ 0, 0 ]` and the other at `[ 1.1, 0.1 ]`. That source is used on a symbol layer in which stencil clip is _disabled_ (we don't set any of the layout properties that enables stencil clip for symbols). In this layer, `icon-opacity` is set to `0.25`.

| Expected  | Actual |
|:-:|:-:|
| ![expected](https://cloud.githubusercontent.com/assets/76133/19412457/52740b48-931f-11e6-8dde-ea98931c8ba3.png) | ![actual](https://cloud.githubusercontent.com/assets/76133/19412458/578c0842-931f-11e6-9e8f-66f4416afcf2.png) |

The actual result above are from GL JS. In GL native, we obtain the same results when we fix/remove the hacks that disables symbol stencil clip [here](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/renderer/symbol_bucket.cpp#L65-L67), [here](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/renderer/painter_symbol.cpp#L124-L126) and [here](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/layout/symbol_layout.cpp#L301-L302). I have a proof-of-concept patch for GL native: https://github.com/mapbox/mapbox-gl-native/commit/782a4776b5762cf091073eadb4171b555af25353.

**Comment by jfirebaugh** [comment]
Here's my understanding of the situation, and points where I have gaps in my understanding.

* Currently, in `Continuous` mode, we endeavor to draw symbol layers with the stencil test _disabled_, i.e. the symbol bucket is _not clipped_ to its tile.
* It has been asserted that [this is a necessary measure](https://github.com/mapbox/mapbox-gl-native/pull/2829#issuecomment-154128371) for layout and rendering performance. However, I don't believe it's something we've formally benchmarked.
* We're inconsistent about how we refer to this mode. Sometimes it's referred to as "clipping" and sometimes in the inverted sense as "drawAcrossEdges". To avoid confusion and ambiguity, let's settle on "clipped" vs "unclipped". This is preferable to "drawAcrossEdges" because even clipped drawing can "draw across" a tile edge -- it just requires both tiles to cooperate in the drawing to do so.
* In order to obtain the correct result for unclipped drawing, we require that the text and/or icon for a given feature be drawn by _exactly one_ tile, even when that text and/or icon crosses a tile boundary.
* For `Continuous` mode, we attempt to satisfy this constraint by throwing out features that lie within the buffer area of a tile. However, our implementation fails to consider that features can lie _exactly on_ the line delineating "tile proper" and "tile buffer". That's this issue.
  * A quick fix -- call it "Option 3" -- for this issue would seem to be to keep features that with `x` or `y` coordinate equal to 0, but throw out features with `x` or `y` coordinate equal to `EXTENT`.
* The "throw out features in the tile buffer area" approach does not work for `Still` mode, because a critical use case for `Still` mode is to render a single tile without requiring data for any adjacent tiles. I.e. each tile must be responsible for drawing the portion of any text and/or icons that lie within that tile.
* Therefore we must have different code paths for both layout and drawing in `Still` versus `Continuous` mode. [In the past I have argued](https://github.com/mapbox/mapbox-gl-native/pull/2829#issuecomment-154212183) that this is dangerous, not only because of the additional code complexity, but also because it can lead to situations where someone designs a style with large fonts or generous text spacing that looks fine in `Continuous` mode but then gets clipped in `Still` mode.
* This strategy produces edge-case misrenderings even in `Continuous` mode: when the edge of the map coincides with the edge of a tile, text and icons that cross that edge can "pop" in and out depending on whether the adjacent tile is just off screen and not rendered, or just on screen and rendered.
* Certain other symbol layout properties also require modifications to the above approach. In particular `symbol-avoid-edges`.

Gaps in my understanding:

* Why does `symbol-avoid-edges` require clipping? What does it actually do?
* What does [this comment](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/renderer/painter_symbol.cpp#L124) mean? It implies that `{text,icon}-allow-overlap` and `{text,icon}-ignore-placement` are relevant to whether we want clipping or not. Why?
* #1673: why would we care whether the point annotation layer has a buffer, if we're going to throw out features within the buffer anyway? Note that, other than for rendering tests, we don't require annotations to support `Still` mode -- we're going to use GeoJSON layers for static overlays, which are already buffered.

**Comment by mikemorris** [comment]
@jfirebaugh `symbol-avoid-edges` was discussed in https://github.com/mapbox/mapbox-gl-native/issues/3582 and implemented in https://github.com/mapbox/mapbox-gl-native/pull/3623. We've considered removing it in https://github.com/mapbox/mapbox-gl-style-spec/issues/287 and hard-coding smarter decisions around clipping.

**Comment by jfirebaugh** [comment]
I'm not sure I really understand those issues. #3582 seems to indicate that the purpose of `symbol-avoid-edges` is to avoid icons placed on lines from being clipped at tile edges in `Still` rendering mode. That's not at all what [the documentation](https://www.mapbox.com/mapbox-gl-style-spec/#layout-symbol-symbol-avoid-edges) suggests. And the default value for `symbol-avoid-edges` is false, which would seem to indicate that the rendering shown in #3582 is still the norm for `Still` mode.

**Comment by mikemorris** [comment]
The purpose of `symbol-avoid-edges` is to prevent placing features near edges at all, which is nearly always the right decision for icons on lines because of

> The point positions for line labels are calculated by finding the points every __px along the line. Since the same line could be clipped differently in both tiles, it is pretty likely that these calculated points won't be the same in both tiles.
https://github.com/mapbox/mapbox-gl-native/issues/3582#issuecomment-172084414

`symbol-avoid-edges` defaults to `false` because when applied to features that render fine across tiles, like roads, [it make them disappear](https://github.com/klokantech/tileserver-gl/issues/35#issuecomment-244694571). I believe we always set this to `true` for line labels in `mapbox` styles though.

**Comment by brunoabinader** [comment]
> It has been asserted that this is a necessary measure for layout and rendering performance. 

Ansis comments about the extra quads are right. On #6832, I add a virtual padding that accounts for 1/8 of the tile size, for each direction. This can result in a performance impact during placement for a big amount of features (~100k). However, I don't see a large number of features like this to be the common use case.

> In order to obtain the correct result for unclipped drawing, we require that the text and/or icon for a given feature be drawn by exactly one tile, even when that text and/or icon crosses a tile boundary.

Yes - e.g. issue #6670 is about the rendering artifact caused by unclipped features being overdrawn on tile edges.

> A quick fix -- call it "Option 3" -- for this issue would seem to be to keep features that with x or y coordinate equal to 0, but throw out features with x or y coordinate equal to EXTENT.

Yes - IIRC [this was my first proposed solution for #3563](https://github.com/mapbox/mapbox-gl-native/pull/3563#issuecomment-252284116). However, that implies in features on tile edges in which tile is rightmost or bottommost being skipped, plus other issues mentioned below.

> Therefore we must have different code paths for both layout and drawing in Still versus Continuous mode. In the past I have argued that this is dangerous, not only because of the additional code complexity, but also because it can lead to situations where someone designs a style with large fonts or generous text spacing that looks fine in Continuous mode but then gets clipped in Still mode.

I believe both code paths _and_ behavior should be the same for both modes - this is what I propose in #6832.

> Why does symbol-avoid-edges require clipping? What does it actually do?

Besides the comments from @mikemorris - I believe we enable clipping there because we don't want symbols from other tiles _polluting_ the requested tile in still mode.

> What does this comment mean? It implies that {text,icon}-allow-overlap and {text,icon}-ignore-placement are relevant to whether we want clipping or not. Why?

Yes - rationale is that collision detection algorithm runs on a per-tile basis, relying on additional padding added to each tile for detecting collision with features on neighbor tiles. This gives us some guarantees that a _colliding_ feature near one tile edge won't collide with another from a neighbor tile - thus no need for clipping.

In theory, this is not an issue for non-colliding features (we disable collision when enabling one of the style properties mentioned above) - because we shouldn't need to worry about overdraw. __However__:
- _because we duplicate features on tile edges_; and
- [_because we want non-colliding features to be sorted by their y position, even on tile edges_](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/layout/symbol_layout.cpp#L343-L358);

We then add buffers around each tile and then enable clipping to avoid overdraws.

> #1673: why would we care whether the point annotation layer has a buffer, if we're going to throw out features within the buffer anyway? Note that, other than for rendering tests, we don't require annotations to support Still mode -- we're going to use GeoJSON layers for static overlays, which are already buffered.

We use the buffer for rendering the "other side" of the clipped feature - and we [only throw out features outside of the tile boundaries if `symbol-avoid-edges` is true](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/layout/symbol_layout.cpp#L289).

--

OK, this is a lengthy reply so here's a summary of my thoughts on this:
- We __always__ need buffers around each tile:
 - Colliding symbols uses them to calculate collision with near symbols from neighbor tiles.
   - We don't need to enable clipping here because we have guarantees that the feature won't collide with others.
 - Non-colliding symbols uses them to properly sort features by their y position near tile edges - which is why IMO option 3 won't work as expected.
   - We need to enable clipping to avoid overdraws.
- When we enable each one of the `{text,icon}-allow-overlap` and `{text,icon}-ignore-placement`, we disable collision, thus requiring clipping.
- Annotation symbols are non-colliding, thus requires clipping and extra buffers - this is what I propose in #6832.

**Comment by ansis** [comment]
### Fixing the original duplicate feature problem.

> A quick fix -- call it "Option 3" -- for this issue would seem to be to keep features that with x or y coordinate equal to 0, but throw out features with x or y coordinate equal to EXTENT.

Sounds right to me. A point should only exist inside one tile.

> However, that implies in features on tile edges in which tile is rightmost or bottommost being skipped

I think this is the correct behavior. The rightmost edge of the world is the same space as the leftmost. The bottommost edge is a trickier question, but depending on the interpretation of the tile space and projection this edge maybe shouldn't exist. In practice I think excluding it won't cause any problems.

### Answers / comments about clipping

The first part would fix the original issue so this question is completely separate from that.

> It has been asserted that this is a necessary measure for layout and rendering performance. However, I don't believe it's something we've formally benchmarked.

It would be good to benchmark. I think the 50% - 66% number came from counting the number of skipped labels but it would be good to get a difference a tile's total buffer size and processing time.

A 1/8 buffer for annotations sounds good. We need a much bigger buffer for text labels though depending on their size and max width. Some of the text layers in the vector tiles have pretty large buffers.

> Why does symbol-avoid-edges require clipping? What does it actually do?

I can't think of why this needs clipping. If it does, it's buggy.

> What does this comment mean? It implies that {text,icon}-allow-overlap and {text,icon}-ignore-placement are relevant to whether we want clipping or not. Why?

In order to get y sorting to work correctly at tile boundaries we need to have the features in both tiles and then clip them when rendering. This is what -js does. We can't do this in -native yet because the annotation tiles only contain features strictly within them.

> #1673: why would we care whether the point annotation layer has a buffer, if we're going to throw out features within the buffer anyway? Note that, other than for rendering tests, we don't require annotations to support Still mode -- we're going to use GeoJSON layers for static overlays, which are already buffered.

We're not going to throw them away. Annotations in continuous mode need to be clipped to tile boundaries to get y sorting to be correct. The annotations along borders need to be in both tiles.

### What I think about clipping

I don't like the two paths. If we can get rid of the non-clipped one and the cost in size/time is reasonable I think this would be a worthwhile tradeoff. It might result in some visible clipping when rapidly zooming out but it would fix popping when panning.

**But** I'm not sure how clipping everywhere would play with 3D. Labels in 3D will extend too far beyond tile edges for the clipping approach to work. I'm not sure if we can make the current tiled collision algorithm work in 3D. Collision detection in 3D will need some global knowledge. I haven't thought much about what this would look like but I think we might need two separate paths here.

**Comment by jfirebaugh** [comment]
> I don't like the two paths. If we can get rid of the non-clipped one and the cost in size/time is reasonable I think this would be a worthwhile tradeoff.

The only way I could see getting rid of the unclipped mode is if we distinguished between two still rendering modes:

* Still rendering of a single tile. In this mode, we can never throw away features within the tile buffer. However, since we're only rendering a single tile, it doesn't matter whether we clip or not.
* Still rendering of an arbitrary bounding box. We could change this mode to load extra tiles around the border of the bounding box, and then follow the pathway for the `Continuous` rendering mode, with buffered feature discarding and clipping.

I gotta admit, even with all the above discussion, I'm not clear on the role of `symbol-avoid-edges` and `{text,icon}-allow-overlap` and `{text,icon}-ignore-placement`. Does anyone feel they understand these properties at a deep level?

**Comment by ansis** [comment]
> Still rendering of a single tile. In this mode, we can never throw away features within the tile buffer. However, since we're only rendering a single tile, it doesn't matter whether we clip or not.

If we get rid of unclipped mode we will never want to throw away features, so we wouldn't need to distinguish here.

> Still rendering of an arbitrary bounding box. We could change this mode to load extra tiles around the border of the bounding box, and then follow the pathway for the Continuous rendering mode, with buffered feature discarding and clipping.

We discard buffered features in **un**clipped mode. We can't discard them in clipped mode.

> I gotta admit, even with all the above discussion, I'm not clear on the role of symbol-avoid-edges and {text,icon}-allow-overlap and {text,icon}-ignore-placement. Does anyone feel they understand these properties at a deep level?

- -allow-overlap determines if previous symbols affect the placement of the current symbol
- -ignore-placement determines if the current symbol will affect the placement of layer symbols

In most cases you want both to have the same value. I can't think of an example you would want them to be different. I think we should merge them into one property.

There is an open spec issue about this: https://github.com/mapbox/mapbox-gl-style-spec/issues/429

### symbol-avoid-edges
`symbol-avoid-edges` prevents the symbols from crossing any tile boundary. The reasons behind it are complicated. It exists because of some limitations of our tiled collision detection.

These same limitations existed in Mapnik before it. CartoCSS had `-avoid-edges` properties which worked the same way. We calculate placement separately for each tile. In order to support cross-tile labels we need both tiles to be able to make the same choice without any communication between them. A tile needs to know where the neighbouring tile would place labels close to the tile edge. We include features in a tile that are outside it's strict boundaries so that it can make a good guess what it's neighbours are doing. There are some cases where these guesses aren't good enough.

We can't predict line labels because they could be anywhere along the line. Any point labels placed after line labels are contaminated by the chaos in the line labels so we can't predict their position either. `symbol-avoid-edges` should be used to prevent these point labels from crossing tile edges.

OK, why don't we just automatically set this for any point labels below a line label layer? My understanding (I might be wrong) is that there are cases where we want to risk the chaos in exchange for having cross-tile point labels that are placed after line labels. We might have a rare line label layer somewhere early on and we don't want that to affect all subsequent point layers.

I don't like this but my understanding is that this is a necessary part of mapnik-style tiled label placement. I've wondered if we could figure out a way to eliminate the chaos caused by lines.

**Comment by brunoabinader** [comment]
In practice, on -native `symbol-avoid-edges` is used only [to check whether a feature outside of the tile border should be accounted as a symbol instance](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/layout/symbol_layout.cpp#L289) (symbol instances are used for y-sorting, placement and to draw collision debug rects).

>> Why does symbol-avoid-edges require clipping? What does it actually do?

> I can't think of why this needs clipping. If it does, it's buggy.

Check out https://github.com/mapbox/mapbox-gl-test-suite/blob/master/render-tests/symbol-avoid-edges/rotated-false/expected.png:
![expected](https://cloud.githubusercontent.com/assets/76133/19810928/fd3afe52-9d37-11e6-9fc7-d4603d7c6e8c.png)

I remember this specific render test being _failing_ on my initial tests with clipping disabled (option 1). I also agree this clipping behavior looks _wrong_.

__If__ option 1 is still viable as long as we also add padding to annotation tiles to account for y-sorting, then a side effect is that the sorting is right up to the padding we add e.g. 1/8:
![screen shot 2016-10-28 at 6 09 59 pm](https://cloud.githubusercontent.com/assets/76133/19811449/1b39582a-9d3a-11e6-8475-59650efcb077.png)
IMO this is the only side-effect for choosing option 1. if you're curious, the screenshot above was taken using a [modified patch](https://gist.github.com/brunoabinader/c744ea0bd39395dbdcc404a730b042f4) on top of [`fix-symbol-clipping`](https://github.com/mapbox/mapbox-gl-native/tree/fix-symbol-clipping) branch.

**Comment by brunoabinader** [comment]
Heads up I found a way of rendering _sorted_, _non-colliding_ symbol annotations across tiles - we just need to order symbol render tiles in opposite Y order prior to rendering. Since this was the only reason for adding padding to symbol annotation tiles (#1673) - it seems we no longer need it. Sorting symbol render tiles is a cheap operation (certainly much cheaper than add padding to every render tiles) and also portable into -js code.

IMO this makes getting rid of symbol clipping __a valid option again__. I'm going to update #6832 to reflect these findings. We still clip when in Still mode, __but just because we need to update our render test results__ e.g. some render tests results have (expected!) clipped symbols that don't need to be.

**Comment by ansis** [comment]
> Heads up I found a way of rendering sorted, non-colliding symbol annotations across tiles - we just need to order symbol render tiles in opposite Y order prior to rendering. 

I don't think this works in all cases. Take a look at the image in the original issue (https://github.com/mapbox/mapbox-gl-native/issues/1673). Some icons from the left tile need to be rendered on top of some icons from the right tile and some icons from the right tile need to be rendered on top of icons from the left tile.

**Comment by brunoabinader** [comment]
> I don't think this works in all cases.

Yes - it does not cover all cases, but the exceptions are almost imperceptible:

![degree-0](https://cloud.githubusercontent.com/assets/76133/19849271/e1706480-9f5a-11e6-963b-9a95bb6281d2.png)
![degree-1](https://cloud.githubusercontent.com/assets/76133/19849272/e4d272d0-9f5a-11e6-8515-9e28a16c51b0.png)

IMO that sounds good enough as an argument against over-populating the symbol instances for each symbol annotation tile. What do you think?

**Comment by ansis** [comment]
If we are fine with closer-to-the-top annotations sometimes being drawn over closer-to-the-bottom annotations then this is ok. I think the mobile team could better answer whether this is acceptable

Also, I'm not sure if the closely packed grids are the worst case. I think the incorrect overlap could be more visible with just two annotations

**Comment by brunoabinader** [comment]
Fair enough @ansis :bowing_man:

Just worth noticing I'm not against adding padding - that is the best solution render-wise. I'm just curious whether we could use a faster (needs benchmark?) implementation that doesn't use padding and produces _almost_ the same results.

> I think the incorrect overlap could be more visible with just two annotations

Not sure if I follow, but the results I obtained with just two annotations looks OK with the sorted render tile approach:
![output](https://cloud.githubusercontent.com/assets/76133/19874703/e0822e8a-9fcf-11e6-80a2-6087d1625060.gif)

**Comment by brunoabinader** [comment]
Can we settle a decision? I'm afraid #6832 is going to get bit-rotten soon.

I'm a supporter for avoiding the extra padding given the results above, plus the fact we can avoid using clipping for symbols. If we proceed with this implementation decision, we'd need to backport these changes into GL JS before [removing clip for Still mode](https://github.com/mapbox/mapbox-gl-native/pull/6832/commits/c9c6382c81349d94f9ffea7a2145c8f82a40b42d#diff-fba50460e0e94de5553f1eb1126816a1R39), so we can update render test expectations that currently expects clipped symbols (which looks _wrong_ IMO).

ITOH, I won't argue if we decide to keep with the extra padding in favor of rendering results and parity with GL JS implementation.

**Comment by jfirebaugh** [comment]
Once again: we will likely _never_ be able to remove clipping in Still mode. We have to be able to render a *single tile* without loading the 8 surrounding tiles. That requires rendering all features within the tile buffers, but clipping the rendering.

I don't see a way around this that won't kill our COGS for static tile rendering. @brunoabinader you seem very very keen on removing clipping in Still mode. How do you propose to get around this?

**Comment by jfirebaugh** [comment]
> Check out https://github.com/mapbox/mapbox-gl-test-suite/blob/master/render-tests/symbol-avoid-edges/rotated-false/expected.png:
> ![expected](https://cloud.githubusercontent.com/assets/76133/19810928/fd3afe52-9d37-11e6-9fc7-d4603d7c6e8c.png)
> I remember this specific render test being _failing_ on my initial tests with clipping disabled (option 1). I also agree this clipping behavior looks _wrong_.

The clipping in this test-case is a side effect of:

* Needing to use clipping for Still mode
* Using line placement for icons but not `symbol-avoid-edges` (https://github.com/mapbox/mapbox-gl-native/issues/6670#issuecomment-256816692)

I don't think we can avoid it. In the real world, you'd be using `symbol-avoid-edges: true` if you wanted line-placed symbols.

**Comment by brunoabinader** [comment]
> We have to be able to render a single tile without loading the 8 surrounding tiles. That requires rendering all features within the tile buffers, but clipping the rendering.

Thank you @jfirebaugh - this helped me understand/record why we need to clip symbols in still mode. I'll update the comments in #6832 accordingly.

Please reconsider what I've said [here](https://github.com/mapbox/mapbox-gl-native/issues/6670#issuecomment-259245955) except removing symbol clipping in Still mode. FWIW this is exactly what is proposed in #6832 atm.

**Comment by zugaldia** [comment]
Capturing chat with @brunoabinader + some Android folks, the solution proposed in https://github.com/mapbox/mapbox-gl-native/issues/6670#issuecomment-257245885 (option 1 preserving current behavior for still mode), while not perfect, is an improvement over the current state of things and seems unlikely that we'll see it in real world situations. On the other hand, the alternative solution (option 2) is more expensive and will bring a performance hit.

From a practical point of view, if I were to choose between a performance hit, or a better performing solution with rendering errors in unlikely scenarios, I'd say we go with the more performant approach (option 1).

**Comment by brunoabinader** [comment]
Fixed in #6832.
