### ISSUE TITLE
add 'starter-tasks' label to issues 

### ISSUE THREAD

**Issue by mollymerp** [mapbox/mapbox-gl-native#6720]
mapbox-gl-js has a [`starter-task`](https://github.com/mapbox/mapbox-gl-js/issues?q=is%3Aopen+is%3Aissue+label%3A%22starter+task%22) label for tickets that don't require a deep knowledge of the codebase for new contributors interested in getting involved with the project. Could we implement something similar here? It would require those who _do_ have a deep knowledge of the codebase to add the label to issues they deem appropriate. 

cc @mapbox/gl

**Comment by 1ec5** [comment]
We tagged starter tags in this repository until fairly recently. The tag was deleted at some point, but maybe there’s a way to search for issues that used to be tagged with it.

**Comment by mollymerp** [comment]
Hmm is there a reason it was deleted @1ec5? 

@jfirebaugh maybe we could make an announcement in the gl meeting on Wednesday to request that folks add the label to applicable issues when they see them?

**Comment by 1ec5** [comment]
It was underused, so it get culled in a routine label cleanup.

I had a go at populating the new [<kbd>starter-task</kbd>](https://github.com/mapbox/mapbox-gl-native/labels/starter-task) label with a variety of issues from the iOS and macOS SDKs, mostly things to fix in the demo apps or SDK tasks that don't involve MGLMapView. However, I'm almost certainly biased, since I'm not exactly unfamiliar with these SDKs. :wink:

**Comment by tobrun** [comment]
I added some starter tasks on the [Android](https://github.com/mapbox/mapbox-gl-native/issues?q=is%3Aopen+is%3Aissue+label%3AAndroid+label%3Astarter-task) label while doing some issue cleanup.

**Comment by jfirebaugh** [comment]
In use!
