### ISSUE TITLE
Document that case and diacritic folding is unsupported in predicates

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#6781]
Diacritics (`é` `ç` `ü` etc.) aren't folded (compared against `e` `c` `u`) when evaluating filters/predicates for runtime styling. 

This can particularly bite you when you round-trip feature querying, pulling up a feature with attribute `name = Québec` but then try to style a layer qualifying to that render feature, yet only `Quebec` exists there. 

This needs to happen in core first. 

Meanwhile the docs need updated e.g. [here](https://www.mapbox.com/ios-sdk/api/3.4.0-beta.1/Classes/MGLVectorStyleLayer.html#/c:objc%28cs%29MGLVectorStyleLayer%28py%29predicate) to indicate this behavior. 

/cc @1ec5

**Comment by 1ec5** [comment]
Case and diacritic folding should only ever be opt-in, not opt-out, so the current behavior is correct inasmuch as no diacritic option has been specified.

In order to support case and diacritic folding, the style specification needs to be extended to support additional options on filter operators: mapbox/mapbox-gl-style-spec#548.

> Meanwhile the docs need updated

We can state that the operator modifiers `c`, `d`, and `cd` are unsupported for comparison and aggregate operators.

**Comment by 1ec5** [comment]
> This can particularly bite you when you round-trip feature querying, pulling up a feature with attribute `name = Québec` but then try to style a layer qualifying to that render feature, yet only `Quebec` exists there. 

I assume this happened because you filtered on `name_en` in the predicate. If you had filtered on `name` instead, any feature with its `name` attribute set to `Québec` would’ve been included in the layer.

**Comment by boundsj** [comment]
Fixed by https://github.com/mapbox/mapbox-gl-native/pull/7232
