### ISSUE TITLE
Runtime changes to text-field are not immediate

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#6820]
On the current iOS release branch (dbfa8dcc89ff55fa1f8366433d24b1a270e53a02), changing the value of `MGLStyleValue.textField` (in this case, the language labels via #6819) is not reflected immediately on the map.

Instead, the labels go blank.
- Zooming several levels (and triggering a [re]load?), then zooming back to the original zoom level will cause the labels to appear correctly at the original zoom level.
- Panning outside of the viewport at the original zoom level (to an area that was not shown) _will_ show the labels in those new areas.

![asdf](https://cloud.githubusercontent.com/assets/1198851/19711119/43012c2e-9ae8-11e6-9c5d-a6c167930591.gif)

/cc @boundsj @1ec5 @ivovandongen

**Comment by 1ec5** [comment]
This might affect all layout properties, not just `text-field`.

/cc @bsudekum @jfirebaugh

**Comment by 1ec5** [comment]
Given #6903, this is definitely affecting all layout properties on both iOS and Android.

**Comment by jfirebaugh** [comment]
The bug in this case is specific to `text-field`, not all properties.

`GeometryTileWorker` expects to be notified when the main thread has loaded additional glyphs which may be needed in order to proceed with symbol layout. However the notification mechanism, `GeometryTileWorker::setPlacementConfig`, is overloaded. Its primary purpose is to notify `GeometryTileWorker` when the camera changes in a way that affects label placement, such as rotating. In order to avoid needless updates for camera changes that _don't_ affect placement, the provided value for `PlacementConfig` is compared against the last used value, and short circuited if unchanged. This short circuiting conflicts with the use of `GeometryTileWorker::setPlacementConfig` as a notification that new glyphs have been loaded. That needs to be a separate notification pathway.

**Comment by jfirebaugh** [comment]
Related issues: #2851, #2511. This has perpetually been a problematic area of the code.
