### ISSUE TITLE
Investigate pixelated symbols in labels

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mapbox-gl-native#6863]
**Platform:** Ubuntu 16.04 with NVIDIA closed-source GPU driver version 367.27
**Mapbox SDK version:** master

### Steps to trigger behavior

When rendering tiles from `mapbox/streets-v8` in `MapMode::Still`, some label icons appear pixelated.

- London `mapbox/streets-v8/tiles/17/65502/43585@2x`
  - `center: [ -0.092010498046875, 51.50617819737356 ]`
- New York City `mapbox/streets-v8/tiles/17/38592/49273@2x`
  - `center: [ -74.00253295898438, 40.72748642299778 ]`
- Changing the decimal precision of the lat/lng centerpoint can affect the artifacts, sometimes fixing them if precision is trimmed enough. However, trimming centerpoint precision does not fix all instances of this artifact, and in some cases makes it worse. **Is there a potential float precision issue here and if so how should it be handled?**

**master**

![43585 2x 3](https://cloud.githubusercontent.com/assets/1149913/19866793/dd73f082-9f77-11e6-9371-1fca3bf04ebb.png)

**trimmed to 8 decimal places**

![43585 2x 2](https://cloud.githubusercontent.com/assets/1149913/19866763/c4091460-9f77-11e6-88ba-0a5650ab79c1.png)

- [Removing `GL_LINEAR` mode rendering](https://github.com/mapbox/mapbox-gl-native/pull/6790) changes the style of artifact, fixing some but introduces others (fuzziness visible in `RBBTS` icon).

![1f7d29b4-9f71-11e6-8fd7-717bf4c70bec](https://cloud.githubusercontent.com/assets/1149913/19866541/e33fea44-9f76-11e6-92b9-fd96d3c94c39.png)

### Expected behavior

Label icons are rendered without pixelation or fuzziness artifacts.

![bec71b9c-9f71-11e6-868b-69ffb17f86e5](https://cloud.githubusercontent.com/assets/1149913/19866517/d0e460fa-9f76-11e6-8707-8b592080c767.png)

### Actual behavior

Label icons are pixelated (`Villa Mosconi`, `Emmet's`, `The Dutch`).

![49273 2x](https://cloud.githubusercontent.com/assets/1149913/19866612/32fd3942-9f77-11e6-94fe-5ab759d82938.png)

/cc @jfirebaugh @brunoabinader @kkaefer @samanpwbb

**Comment by jfirebaugh** [comment]
My hunch is that the artifact happens when this OpenGL implementation is asked to sample a texture with `GL_NEAREST` interpolation and texture coordinates that are exactly on a half-texel boundary. I believe that in that case, this implementation sometimes rounds the texture coordinates up and sometimes rounds down.

In particular, I've seen it in the Annotation unit tests when I had an annotation placed at null island using an image with an odd width. In that case, there was a vertical line artifact looking very similar to the ones above. Once I switched to an even width image, the problem went away.

To test this theory, I think we could try modifying the `symbol_icon` shader to round `v_tex` coordinates in a consistent way [here](https://github.com/mapbox/mapbox-gl-shaders/blob/44b65f8090a74cbb0319664d010b8d8a8a1512b0/src/symbol_icon.fragment.glsl#L18). If this works, then a complete fix would involve providing a way for the shader to know if `GL_NEAREST` or `GL_LINEAR` interpolation was being used, and do the rounding only in the `GL_NEAREST` case. Does this sound viable @ansis / @kkaefer?

**Comment by ansis** [comment]
>  Does this sound viable @ansis / @kkaefer?

If it works it is viable!

> In particular, I've seen it in the Annotation unit tests when I had an annotation placed at null island using an image with an odd width. In that case, there was a vertical line artifact looking very similar to the ones above. Once I switched to an even width image, the problem went away.

Internally all images are padded so that their dimensions are multiples of 4 pixels. Unless this is broken, I'd guess the even vs odd didn't matter as much as it being a different width.

> My hunch is that the artifact happens when this OpenGL implementation is asked to sample a texture with GL_NEAREST interpolation and texture coordinates that are exactly on a half-texel boundary. I believe that in that case, this implementation sometimes rounds the texture coordinates up and sometimes rounds down.

It could also be that the the varying interpolation produces a `v_tex` that is sometimes slightly on one half and sometimes slightly on the other half. The texture interpolation itself would consistently pick a side, it would just get slightly off values as input. If this is the case, I think we might need to do the rounding in the vertex shader.

**Comment by brunoabinader** [comment]
> complete fix would involve providing a way for the shader to know if GL_NEAREST or GL_LINEAR interpolation was being used, and do the rounding only in the GL_NEAREST case.

This heuristic sounds promising - though we'd need to pass an extra bool in shader code?

**Comment by mikemorris** [comment]
For reference, after the partial `GL_LINEAR` revert in https://github.com/mapbox/mapbox-gl-native/pull/6866, label icons appear to be rendered with `GL_NEAREST` in `MapMode::Still`, yielding the following renders:

**17/65502/43585@2x**

![43585 2x](https://cloud.githubusercontent.com/assets/1149913/19903246/62838d74-a044-11e6-9717-62501d990390.png)

**17/38592/49273@2x**

![49273 2x](https://cloud.githubusercontent.com/assets/1149913/19903245/6281fa0e-a044-11e6-945d-cf5f158303e0.png)

**Comment by mikemorris** [comment]
`git bisect` landed on https://github.com/mapbox/mapbox-gl-native/commit/f03afdee218680d95eb5b9b0ab04083bc7cea512 (`overscaledZ`) as responsible for the differing pixelation visible in the images above.

**Comment by jfirebaugh** [comment]
That means there's an uncontrolled variable in your `bisect` test. f03afdee218680d95eb5b9b0ab04083bc7cea512 will only affect collision tile debug box rendering. It has no effect on icon rendering.

**Comment by jfirebaugh** [comment]
I'm seeing this now even on retina iOS:

![image](https://cloud.githubusercontent.com/assets/98601/21663042/79d688e8-d292-11e6-9ede-4e794a866750.png)
