### ISSUE TITLE
Removed markers show up when rotate screen

### ISSUE THREAD

**Issue by iBinh** [mapbox/mapbox-gl-native#6952]
**Platform:** iOS
**Mapbox SDK version:** 3.4.0 beta 1

### Steps to trigger behavior

 1. Add annotationView to mapView
 2. Rotate screen from portrait to Landscape

### Actual behavior
All removed markers occur in the right side of the screen. It seems that them attach to screen not to the map (that means when I move the map, the markers still stay)

![img_0976](https://cloud.githubusercontent.com/assets/13776018/20086377/5144b340-a5a2-11e6-9ff2-f5761ff3b53b.PNG)

/cc @1ec5

**Comment by boundsj** [comment]
Thanks for the report @iBinh. Can you please test with https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.4.0-beta.2 and see if you notice the same issue? Relatedly, beta.2 introduces a new issue that is fixed in https://github.com/mapbox/mapbox-gl-native/pull/6924 and that will be in beta.3 later this week or early next.

**Comment by iBinh** [comment]
I just updated to 3.4.0 beta2, when I move or zoom mapView after a while, my app crashes
<img width="1411" alt="screen shot 2016-11-08 at 12 07 57 pm" src="https://cloud.githubusercontent.com/assets/13776018/20087559/2643a480-a5ac-11e6-9be8-7a609d25b8c3.png">

**Comment by 1ec5** [comment]
> when I move or zoom mapView after a while, my app crashes

Let’s track the `std::out_of_range` exception separately in #6953.

**Comment by 1ec5** [comment]
Fixed in #6924 and #7626, which are both in v3.4.0-beta.7.
