### ISSUE TITLE
Assertion failure in collision_tile.cpp

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#6988]
Assertion failed: (box.x1 <= box.x2 && box.y1 <= box.y2), function getTreeBox, file /Users/john/Development/mapbox-gl-native/src/mbgl/text/collision_tile.cpp, line 158.

```
box	const mbgl::CollisionBox &	0x000060800022a860
anchor	mbgl::Point<float>	
x1	float	5.11907196
y1	float	5.11907196
x2	float	-5.11907196
y2	float	-5.11907196
maxScale	float	+Inf
placementScale	float	0
```

This happened after adding a single symbol icon to the map with a GeoJSON source, and panning the map.

**Comment by ragaisis** [comment]
Any progress? Cause I'm having this crash too

**Comment by ChrisLoer** [comment]
#10103 will change this code dramatically, and may incidentally resolve whatever the underlying issue is.

**Comment by ChrisLoer** [comment]
After PR #10436, this code no longer exists. Since this issue seems to indicate one of our assumptions is wrong, that same assumption (whatever it was) could still be problematic, but if so it will manifest differently.

If `getShaping` ever returns a "left" position to the right of the "right" position, we'd see something similar to this, but I just audited the code and I don't see a way for that to happen. Previously, the left vs right assumption would also have to hold for all the boxes generated for line labels, but that's no longer the case because we use circles (represented as a center point plus a radius) for line labels.
