### ISSUE TITLE
Marker.showInfoWindow is not available

### ISSUE THREAD

**Issue by somehibs** [mapbox/mapbox-gl-native#6994]
**Platform: Android**
**Mapbox SDK version: 4.1.0-beta.1**

### Steps to trigger behaviour

 1. Attempt to show a Marker's InfoWindow.

### Expected behaviour

A function called showInfoWindow() to be public and accessible in the Marker class.

### Actual behaviour

A function called showInfoWindow(MapboxMap, MapView) is public but is commented as 'do not use this method'.

PS: This issue template has behaviour misspelt.

**Comment by tobrun** [comment]
showInfoWindow is only used for internal management. The public API for showing an InfoWindow  is `MapboxMap.selectMarker(Marker marker);`. We can't make the one on InfoWindow itself available right now since we have some addtional logic to maintain in selectMarker. Note that a lot of this will change with some refactors we have planned. Feel free to comment on the InfoWindow refactor #6535. Closing as non-actionable for now, linked refactor ticket for visibility.
