### ISSUE TITLE
better way of setting access token for android

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#713]
The README on recommends setting the access token by editing a string in MapFragment.java. This means there's a modified file that you have to remember not to check in. Instead, setting the access token should be done via some mechanism that's not under source control.

**Comment by ljbade** [comment]
I did a bit of experimenting with gradle and have tried using a .properties file that is generated by gradle from an environment variable.

I am still not happy with it.

I think filtering the AndroidManifest.xml file is the way to go

**Comment by ljbade** [comment]
Gradle seems more complicated than it needs to be for some stuff.

Can't get gradle to do what I want.

Will see what I get from StackOverflow: http://stackoverflow.com/questions/27749789/how-to-run-task-before-checkdebugbuild-android-gradle-task

**Comment by ljbade** [comment]
Still haven't got a response on stackoverflow, and @bleege didn't have much knowldege in this area either.

The official gradle forums don't seem very useful either.

**Comment by ljbade** [comment]
OK I went back to having gradle generate the `token.txt` file from the value of the `MAPBOX_ACCESS_TOKEN` variable at build time.

I think this is the best we can do at the moment.

**Comment by mikemorris** [comment]
If `token.txt` gets gitignored this feels like a fine solution :+1:

**Comment by ljbade** [comment]
@mikemorris it is

**Comment by tobrun** [comment]
@ljbade @bleege 

I want to pick up this discussion again.

In my opinion, when we ship we should support one of the following mechanisms:
 - token in res/config.xml with a non-translatable String resource
 - token in AndroidManifest with a meta-data tag 

Motivation behind this is that Android developers expect this kind of configuration. 
Using a txt file is bit unconventional. 

Taking in account that we want a gitignored config. I'm suggesting supporting both current implementation and one mentioned above by implementing this at SDK level. The former will only be used by us during development. The latter will only be used by end developers.

**Comment by ljbade** [comment]
@tobrun currently we support setting it via constructor and layout XML.

I looked at AndroidManifest - since that is what Google Maps uses, but I recall there was an issue with that, or maybe it was something else.

If you get the Manifest working then we can switch Sirius over to test that method. TestApp will remain using the text file.

@incanus Will we eventually need something like the MGLAccountManager for Android?

**Comment by incanus** [comment]
I don’t know enough about the workflow for Android to answer that. The reason we have it for iOS is because we need to set a token for both programmatic map view uses as well as Interface Builder, which features an alternative code path for instantiation — these XML-based interface files don’t work like layouts & manifests do on Android.

**Comment by bleege** [comment]
We have two issues here that need to be solved:

1. Ease development by having a locally persistent Access Token that is NOT checked into VCS (Git).
1. How developers will set their app's Access Token.

For 1. the `toxen.txt` is used as it's a non regular Android file and is NOT checked into Git.  I would be happy to get away from this as it is a bit non standard and rely on a file in `res`.  However, I think this file in `res` should be Mapbox specific so that it is easy to isolate / keep out of Git via `.gitignore`  This concern goes away if we decide to make a Mapbox development Access Token public (aka store it in Git plaintext) and then we can store it in `res/strings.xml` like most developers will likely do for their own apps.

For 2. SDK implementing developers can store their Access Tokens where ever they want to currently (in code, strings.xml, etc) and then use that String to pass to the MapView either via XML or via `MapView.setAccessToken()`.  There's nothing more that needs to be done to meet this need.

**Comment by ljbade** [comment]
@bleege Is it possible to store strings in more than one resource file? Ideally a `res/strings-private.xml` could work.

Also there is now a `MapView` constructor that takes an access token.

**Comment by ljbade** [comment]
Key thing is that the token is set before `onCreate` where we will throw an exception if it is not set. I documented this behaviour clearly in JavaDoc.

**Comment by tobrun** [comment]
My main target here is to make as easy as possible for end developers to integrate while also taking into account how it normally works with other libraries. I'm also obeying the requirement of having a gitignored setup for us while developing.

The main gist behind my proposition:
>Why are we asking the end developer to execute a certain method at a certain time while we can easily do the heavy lifting for them? 

How I would implement this:
 - move MapFragment to SDK module
 - add empty token in sdk/raw/token.txt
 - add empty token in sdk/res/config.xml (expose this as a public resource) or manifest
 - while creating the Map in MapFragment 
  - try to set token from resources
    - if ok set token (for end developers)
    - if not try to read out token.txt
       - if ok set token (for us)
       - else throw exception indicating that end developers need to override the resource

This will remove one method call in their extended MapFragment, why I'm dead serious about this:
 > It is all about first impressions.. This occurs when the end developer is trying to get the Map to show the first time. The requirement of him to add methods that need to execute at a certain time is error-prone and this could result in a bad first impression if he needs to build/run multiple times.

**Comment by tobrun** [comment]
@ljbade 
we must set it ourselves if we want a blackboxed implementation of MapFragment..

> Key thing is that the token is set before onCreate where we will throw an exception if it is not set. I documented this behaviour clearly in JavaDoc.

How are we going to that if MapFragment is currently doing this?
```java
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        super.onCreateView(inflater, container, savedInstanceState);
        Log.v(TAG, "onCreateView");

        // Create the map
        mMap = (MapView) inflater.inflate(R.layout.fragment_main, container, true);

        // Need to pass on any saved state to the map
        mMap.onCreate(savedInstanceState);

        // Return the map as the root view
        return mMap;
    }
```

cc @bleege

**Comment by ljbade** [comment]
@tobrun `MapFragment` is rather stale bit of code, needs updating. Also it is possible to stick the access token in the layout XML which is then loaded via `infalter.inflate`.

**Comment by ljbade** [comment]
@tobrun I believe there might be a new lifecycle method for low memory you need to implement, I think that might have been added after we stopped using MapFragment.

**Comment by tobrun** [comment]
@ljbade 
[onLowMemory](https://github.com/mapbox/mapbox-gl-native/blob/master/android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/MapFragment.java#L114) is in place on master. 
Token setup is in same PR #2561. 
Feel free to validate, reopen this if you want to discuss this further.
