### ISSUE TITLE
don't work properly when the current time is set to past time during execution

### ISSUE THREAD

**Issue by ntomizawa** [mapbox/mapbox-gl-native#7200]
Our QA member found somewhat tricky bug which occur when the current time is set to past time during Mapbox running.

**Platform:**　Nexus 5 (Android 4.4.4)
**Mapbox SDK version:** 4.0.1 (but be able to reproduce on recent "Mapbox Dev Preview app" ( https://play.google.com/store/apps/details?id=com.mapbox.mapboxandroiddemo ). 

### Steps to trigger behavior
 1. Launch  "Mapbox Dev Preview app" ( https://play.google.com/store/apps/details?id=com.mapbox.mapboxandroiddemo ).
 2. Tap "A simple map view"
 3. Pinch, scroll, etc. works fine (OK)
 4. Set system current time to past time
    4.1 Select "Date & time" from "Settings"
    4.2 Uncheck "Automatic date & time"
    4.3 Set the current time to past time, for example 1 day ago.
    4.4 Back to "A simple map view app"
### Expected behavior
 5. Pinch, scroll, etc. works fine (OK)
### Actual behavior
 5. Pinch, scroll, etc. not work (NG). "Map box Dev Preview app" seems to freeze. In our application, pin ch & scroll works, but map is not updated properly (some gray area remains).

**Comment by tobrun** [comment]
Thank you for reaching out, I'm pretty sure that this is because of SSL handshaking not working anymore because your device isn't configured correctly. SSL takes in account time when validating messages. I don't consider this a bug, feel free to add more information if that isn't the case (you can debug calls in HttpRequest.class and look for any exception there). Closing for now.
