### ISSUE TITLE
Android AnimatedMarkerActivity bugs in test app

### ISSUE THREAD

**Issue by klblk** [mapbox/mapbox-gl-native#7380]
**Platform:** Android
**Mapbox SDK version:** 4.2.0-beta5

### Steps to trigger behavior

 1. https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/AnimatedMarkerActivity.java
 2. 
a) getLatLngInBounds() returns an incorrect result. Problem in mapboxMap.getProjection().getVisibleRegion().latLngBounds value: 
```
bounds N:85.02070418030257; E:134.99996915347242; S:-85.02070418030256; W:-134.99996915347265
```
b) Animated markers blinking if the camera shift (sorry, I'm bad gif-maker): 
![myimage](https://cloud.githubusercontent.com/assets/6357562/21090992/e9fdbf58-c075-11e6-857a-64e972044bcc.gif)

c) #6422 actual (if change MarkerViewOptions to MarkerOptions passengerMarker)

**Comment by tobrun** [comment]
@klblk could you try testing with the latest SNAPSHOT? We made some changes since the last beta, I'm trying to pinpoint if the root cause will be different from https://github.com/mapbox/mapbox-gl-native/issues/6762.

```gradle
dependencies {
    compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:4.2.0-SNAPSHOT@aar') {
        transitive=true
    }
}
```

To reach the dependency you need to add following repository to the root directory gradle file:

```gradle
    maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }
```

**Comment by klblk** [comment]
Yes, all reproduce with latest SNAPSHOT. 
"a", "b" problems not reproduce with beta-4.
Android 5.1 (Nexus 4)

**Comment by tobrun** [comment]
a) The issue that LatLngBounds returns a wrong bounding box is noted in #6769, this is because we changed the way the OnMapReadyCallback is invoked and at that time the View isn't measured yet. To workaround this I would advice you to wrap it in a runnable or use `addOnGlobalLayoutListener`. We are working on including this as a requirement to invoke the OnMapReady but this will only land as part of the 5.0.0 release since it requires some internal refactoring.

b) The issue in https://github.com/mapbox/mapbox-gl-native/issues/6762 will be the same as shown here. Going to use that issue to investigate.

Since both issues are tracked elsewhere, going to close as duplicate.

Thanks again for reaching out and reporting your issue!
