### ISSUE TITLE
android gcc version

### ISSUE THREAD

**Issue by AndersBillLinden** [mapbox/mapbox-gl-native#7434]
To build mapbox-gl-native, it seems like no older compiler than g++ 5 can be used, but android NDK only has g++ 4.9.

Is there anyone that can confirm said information?

**Comment by jfirebaugh** [comment]
We recommend end users of the Mapbox Android SDK use our [prebuilt SDKs](https://www.mapbox.com/android-sdk/) rather than building it themselves.

If you do want to build it yourself, our build toolchain and build scripts use clang, which is also provided by the Android NDK. We don't test or support building the Android SDK using GCC (any version).

**Comment by AndersBillLinden** [comment]
is the prebuilt SDK link correct? Also, are we talking about a lib that is possible to use in a qt project?

**Comment by tmpsantos** [comment]
@AndersBillLinden you might want to give my unsupported branch a try:
https://github.com/mapbox/mapbox-gl-native/tree/tmpsantos-qt_vendor_gcc4.9

It also features a QMake build file inside `platform/qt`.

So you can build with `qmake plaform/qt && make`

**Comment by AndersBillLinden** [comment]
My colleague sais that branch is broken. Is it?
