### ISSUE TITLE
Feature request: analog to Google Maps TileProvider

### ISSUE THREAD

**Issue by kjkrum** [mapbox/mapbox-gl-native#7477]
I've recently been learning about MapBox after having used the Google Maps SDK for several Android projects.  I've noticed that there seems to be no analog to the Google Maps [`TileProvider`](https://developers.google.com/android/reference/com/google/android/gms/maps/model/TileProvider) interface, which allows overlays to be rendered in Java code.  I believe this is a consequence of the fact that Mapbox rendering is done in native code that is common to the Android and iOS SDKs.  [This SO Q&A](http://stackoverflow.com/questions/39563829/custom-drawing-on-mapbox-map-canvas) shows how an Android app can draw over the Mapbox map, but that solution draws over labels and markers.

Would it be practical to allow the Android and iOS SDKs to register a native callback that allows Java or (I assume) ObjectiveC code to draw on the base map before labels and markers are rendered?

**Comment by tobrun** [comment]
@kjkrum we aim to match our API with the one that google exposes (at least on Android) but the TileProvider part is something where we differentiate. Instead of allowing users to render something with a TileOverlay, we give you full access to all the layers and sources of the map. This should allow you to draw something between the base map and the markers/labels above. You only need a source and hook into `MapboxMap#addLayer(Layer layer, String beforeLayerId)` where beforeLayerId is the id of the labels (you can look up the id with Mapbox studio).

More information on RuntimeStyling can be found in [this](https://www.mapbox.com/blog/runtime-styling-release/) blog post. 
More information on the classes etc [here](https://github.com/mapbox/mapbox-gl-native/tree/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style).

**Comment by kjkrum** [comment]
From the API docs for `Layer`, `Style`, etc., it appears that map tiles and data can only come from recognized URLs.  There's no way to generate tiles dynamically on the mobile device, except perhaps by exposing them to the Mapbox API via a URL.  Is that correct?

**Comment by incanus** [comment]
👉 https://github.com/mapbox/mapbox-gl-native/issues/7471

**Comment by kjkrum** [comment]
This is still preventing me from ditching Google Maps.  I found a similar request in #4210.  One of the links there might have been useful, but it's 404 now: [custom raster style example](https://www.mapbox.com/android-sdk/custom-raster-style/).

Everything about the Mapbox API seems to be designed around the assumption that a map will display layers hosted by Mapbox Studio and other online sources.  That does not fit my use case.  I want users to be able to add layers from files that they provide on their own devices.  I can do this in Google Maps with `TileProvider`, but I can't figure out how to do it in Mapbox.

Would  `RasterSource(String id, String url)` recognize a custom URI scheme exposed by a `ContentProvider`?
