### ISSUE TITLE
MGLRasterStyleLayer not fully implemented

### ISSUE THREAD

**Issue by vivienlegrand** [mapbox/mapbox-gl-native#7490]
**Platform:** iOS
**Mapbox SDK version:** 3.4.0 Beta 5

I don't know how to display raster sources on top of a Mapbox map in the actual Beta. The documentation cover only the MGLRasterSource, and not MGLRasterStyleLayer. And other layers didn't seem to suite.

### Behavior

 1. Missing method sourceLayerIdentifier in MGLRasterStyleLayer
 2. Missing documentation about MGLRasterStyleLayer in #7337

### Sample
```swift
let tileUrl: [String] = ["http://exemple.com/raster/{z}/{x}/{y}.png"]
var options = [MGLTileSourceOption: Any?]()
// [...] Other options
options[MGLTileSourceOption.tileSize] = 256

let rasterSource = MGLRasterSource(identifier: "raster-source", tileURLTemplates: tileUrl, options: options)
mapView.style.addSource(rasterSource)
        
let rasterLayer = MGLRasterStyleLayer(identifier: "raster-layer", source: rasterSource)
// Missing method in the SDK ?
//rasterLayer.sourceLayerIdentifier = "raster-source"
mapView.style.addLayer(rasterLayer)
```

**Comment by 1ec5** [comment]
> Missing method sourceLayerIdentifier in MGLRasterStyleLayer

[`sourceLayerIdentifier`](https://www.mapbox.com/ios-sdk/api/3.4.0-beta.5/Classes/MGLVectorStyleLayer.html#/c:objc%28cs%29MGLVectorStyleLayer%28py%29sourceLayerIdentifier) is a property on MGLVectorStyleLayer that allows you to specify which _source layers_ within a vector source the _style layer_ should draw. This property is intentionally omitted from MGLRasterStyleLayer because a raster source isn’t divided into source layers the way vector sources are.

Does the code above work for you? What are you seeing instead of the raster tiles?

> Missing documentation about MGLRasterStyleLayer in #7337

#7337 does in fact add an example for using MGLRasterStyleLayer. I hope the prose documentation added in #7475 will also help to clear up the distinctions between the various sources and style layers. These improvements will be in the upcoming beta or release candidate of the SDK.

**Comment by vivienlegrand** [comment]
Actually, with the exemple above, no raster tiles appear. I just see the Mapbox map setup by the 'Style URL' of the MapView in the Interface Builder.

**Comment by 1ec5** [comment]
When does this code run? Because the style loads asynchronously, any code that modifies the style should run inside `MGLMapViewDelegate.mapView(_:didFinishLoadingStyle:)` or in response to user input. The next prerelease will clarify this point in documentation.

**Comment by vivienlegrand** [comment]
Oh yeah, that's the problem. I came from Android and I forget that I need to execute this in a specific place. Tks for the help.

**Comment by 1ec5** [comment]
I think this will be a common pitfall for developers, so #7512 would warn when you say `mapView.style` too soon.
