### ISSUE TITLE
Offlined region is not completely removed from the database

### ISSUE THREAD

**Issue by andrewstay** [mapbox/mapbox-gl-native#7521]
**Platform:** iOS
**Mapbox SDK version:** ios-v3.4.0-beta.5

### Steps to trigger behavior

 1. Offline any region using API from MGLOfflineStorage
 2. Delete the offlined region using
```-[MGLOfflineStorage removePack:withCompletionHandler:]```
 3. Observer the offlined database size

### Expected behavior
Tiles associated with the region should be deleted

### Actual behavior
It is only the region metadata gets removed from the database

**Comment by friedbunny** [comment]
From https://www.mapbox.com/help/mobile-offline/:

> When you remove an offline region, any resources that are required by that region, but not other regions, become eligible for removal from the offline database. Because the offline database is also used as a general purpose cache for map resources, such resources may not be immediately removed if the implementation determines that they remain useful for general performance of the map.

There is currently no way to force cached resources to be removed, though we have plans to implement a method that will clear the ambient cache — see https://github.com/mapbox/mapbox-gl-native/issues/4376.

**Comment by 1ec5** [comment]
#3437 tracks adding an API to limit the cache size, which is currently unbounded (except for tile download limits enforced by MGLOfflineStorage).

**Comment by jfirebaugh** [comment]
> the cache size, which is currently unbounded

This isn't entirely accurate. The space consumed by offline regions is unbounded. However, the implementation endeavors to restrict the space consumed by ambient caching to 50 MB. This includes resources that were originally added to the database as part of an offline region, but where that offline region has subsequently been deleted. In that case, the implementation will attempt to shrink the database down to the remaining 50 MB of most recently used resources, but this depends on SQLite being able to effectively recapture free space within the database. It's possible that SQLite is not always able to do so due to database fragmentation.
