### ISSUE TITLE
When pinch zooming quickly, map scrolls also

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#7666]
In the GIF below, you will notice when pinch zooming in or out quickly, the map will scroll in various directions. This appears to be a regression from either https://github.com/mapbox/mapbox-gl-native/pull/7383 or https://github.com/mapbox/mapbox-gl-native/pull/7299. This is reproducible on both 4.2.1 and master branch.

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/5652865/21827525/081a69c8-d75a-11e6-881c-01e271b8a41c.gif)

cc: @mapbox/android

**Comment by tobrun** [comment]
Why do you think this is a regression? 
I'm able to reproduce this with both of those commits reverted:

![ezgif com-video-to-gif 6](https://cloud.githubusercontent.com/assets/2151639/21840956/7ac49760-d7e0-11e6-99c0-2ee646cb56a9.gif)


I think the underlying issue is that a fling gesture is triggered as result of a finishing pinch gesture. This looks very similar to what I noticed with the pan gesture in https://github.com/mapbox/mapbox-gl-native/issues/7536#issuecomment-270366538. I think ignoring fling gestures with a lower velocity will solve this.

**Comment by tobrun** [comment]
#7675 solves the issue that you can trigger an OnFling gesture after a pinch zoom gesture
