### ISSUE TITLE
Add Marker.setRotation(bearing) method for Android Marker

### ISSUE THREAD

**Issue by deinlandel** [mapbox/mapbox-gl-native#7696]
**Platform:** Android
**Mapbox SDK version:** 4.2.1

It's impossible to rotate already created marker. This is very inconvenient for "tracking" application when marker represents moving asset. The only way  is to recreate marker with new rotation, but it's very inefficient in terms on performance.

The solution is to add the method: Marker.setRotation(bearing) (similar to Google Maps API).

**Comment by Guardiola31337** [comment]
Hey 👋 @deinlandel 
First of all, thanks a lot for reaching out and report your problem.

[`MarkerView#setRotation()`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerView.java#L257-L274) landed first in #5082 and since then numerous improvements have been made. There are a couple of examples in the test app that you can check too ([`AnimatedMarkerActivity.java`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/AnimatedMarkerActivity.java#L175), [`MarkerViewActivity.java`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java#L255)).

Are we good to close here?

**Comment by tobrun** [comment]
We have runtime styling and rotation of symbols is supported.

**Comment by LEINNNNNN** [comment]
.setRotation  does not exist in my Android,  what need  i compile?

**Comment by tobrun** [comment]
`SymbolLayer` has a property `icon-rotate` which allows to rotate symbols

**Comment by Deaniesaur** [comment]
@tobrun do you have some example of the Symbollayer with icon-rotate? I would like to know how to implement them. Thank you

**Comment by farfromrefug** [comment]
@tobrun wouldn't that be a good idea to add all properties from ```SymbolLayer``` to Markers?
As Markers are actually drown inside a ```SymbolLayer``` that would be fairly easy.
I think we would just need to add something like "featureProperties" to [SymbolAnnotation](https://github.com/mapbox/mapbox-gl-native/blob/e99e1678488246bf850864fdaba1fc1de2fe4480/include/mbgl/annotation/annotation.hpp) which could be a map of properties.
Then those properties would simply be passed to the [Feature](https://github.com/mapbox/mapbox-gl-native/blob/122db775818a305cbae797875cc5aae48b6dfe19/src/mbgl/annotation/symbol_annotation_impl.cpp#L21)

I think i am going to test it. And make a PR if this is of interest for you
