### ISSUE TITLE
Are the API's in Android changing in 5.0?

### ISSUE THREAD

**Issue by Emeritus-DarranKelinske** [mapbox/mapbox-gl-native#7699]
I tried to use the latest version and some of the current api appears to not exist in 5.0.x.

**Comment by tobrun** [comment]
@Emeritus-DarranKelinske thank you for trying out the SNAPSHOT. On the Android SDK we try to follow [semantic versioning](http://semver.org/). This means that upgrading from 4.x to 5.0 is allowing us to change the public facing API. Often these changes are refactors that we have been willing to do for some time but couldn't due to restrictions of semantic versioning from the 4.0 release. Closing this as non-actionable, feel free to reach of if you have any questions.
