### ISSUE TITLE
Manipulate camera pitch without leaving .followWithCourse

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-native#7789]
**Platform: iOS**
**Mapbox SDK version: 3.4.0-rc.1**

### Steps to trigger behavior

 1. Enter tracking mode `.followWithCouse`
 2. Change camera pitch 

### Expected behavior

Tracking mode remains in `.followWithCourse`

### Actual behavior

Tracking mode enters `.none`

--------------
I'm open to extending this beyond manipulating `pitch`. I can think of use cases for `heading` as well.

/cc @frederoni @boundsj @1ec5 @pveugen

**Comment by 1ec5** [comment]
In other words, we should avoid kicking the user out of user tracking mode due to a programmatic camera change, but still kick the user out of user tracking mode in response to a user gesture. This would fix #1490 as well.

Unfortunately, without concurrent animations (#3625), animated pitch changes would still cause an undesirable stuttering effect in user tracking mode: the usual animation due to user location updates would pause while the pitch animates, similar to the effect seen in heading tracking mode: https://github.com/mapbox/mapbox-gl-native/issues/3625#issuecomment-173128298. I would consider #3625 to be a blocker for this feature, because you’d never want to animate the pitch in user tracking mode due to this issue.

**Comment by 1ec5** [comment]
Fixed in #7856 on the release-ios-v3.4.0 branch.

**Comment by ReSpawN** [comment]
@1ec5 Can you share a Swift 4 implementation on how to achieve this? Manipulating the camera with a button has zero effect for me.
