### ISSUE TITLE
Resuming partial offline packs fail to report progress

### ISSUE THREAD

**Issue by hhartz** [mapbox/mapbox-gl-native#7810]
Platform: iOS
Mapbox SDK version: 3.3.7

 1. Create a new single view application project and replace the ViewController.swift with https://gist.github.com/hhartz/e05fb938ab8a64ad56714eb0628a1885
 2. Run the app
 3. Invoke shake gesture (ctrl-cmd-Z), and kill the app after download has progressed a little bit
 4. restart start the app again

### Expected behavior
The offline storage singleton should report progress, like it does when downloading a fresh pack

### Actual behavior
The offline storage singleton does not report progress via NotificationCenter, while the debug navigator (and network tools like Charles proxy) will show disk and network activity.

**Comment by hhartz** [comment]
the same issue is present in 3.4.0 by the way which I just upgraded to :)

**Comment by jfirebaugh** [comment]
This is the expected behavior; offline downloads do not automatically resume when an application is relaunched. Among other things, this gives application developers the control to resume only when a wifi connection is available, for instance.

**Comment by hhartz** [comment]
@jfirebaugh but shouldn't the API report progress when you actually _resume_ a pack? If you had tried the example you would have seen that it calls `resume()` on the `MGLOfflinePack`, the download is actually started but no progress is reported.

**Comment by jfirebaugh** [comment]
Sorry, I missed that. @friedbunny @jmkiley, can you take a look?

**Comment by hhartz** [comment]
@jfirebaugh any news on when you'll be able to investigate this? it's basically breaking offline download when resuming partial downloads, since you will never know when packs' state change or finish

**Comment by boundsj** [comment]
Hi @hhartz. Thanks for the report and for posting your repro case. Your repro looks almost identical to our [offline pack example](https://www.mapbox.com/ios-sdk/examples/offline-pack). In your repro and in the example, there is no code path that calls `resume` on a previously initiated pack. 

In your repro, the pack creation and the call to resume is done in `startOfflinePackDownload()` and that is a side effect of shaking the device. There is nothing that looks for a previously initiated pack with the intention of resuming it.

There is an [example of calling resume on a previously initiated pack](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/app/MBXOfflinePacksTableViewController.m#L214) in the iosapp demo in this repo. As you can see there, the stored pack is retrieved from `MGLOfflineStorage`'s `packs` property and then it is resumed if the state is `MGLOfflinePackStateInactive`.

As was mentioned before in this issue, it looks like you will need to add additional logic to your application to find and resume packs that were started in a previous application session.

**Comment by hhartz** [comment]
Hi @boundsj.

Thanks for following up. The reason why it's almost identical to the offline pack example is because the code is adapted from it ;) My example clearly calls `resume` on a previously started offline pack in line [62](https://gist.github.com/hhartz/e05fb938ab8a64ad56714eb0628a1885#file-viewcontroller-swift-L62), which happens after requesting progress on existing packs in the shared offline storage. After this call, `offlinePackProgressDidChange` is not reported as you would expect.

To help you visualise the problem more accurately I have recorded [a screen-grab of the situation](https://youtu.be/HIwn4dQXTck), where you clearly see that mapbox is indeed downloading, but no download progress is being reported either visually or via the console.

**Comment by boundsj** [comment]
Hi @hhartz. Please see this [fork of your gist](https://gist.github.com/boundsj/679d3c332e2a9c0a5df738e95f31ace9/revisions). I modified your example to only observe `MGLOfflineStorage` packs instead of redundantly setting up per pack observers inside `ViewController.observeValue(forKeyPath:of:change:context:)`. 

With these updates, the download progress resumes as expected when the application restarts. It relies on the fact that `MGLOfflinePack` reports progress back via `ViewController.offlinePackProgressDidChange(notification:)` after the state changes from `.unknown` to `.inactive`. So, it is possible to resume each pack that is inactive in `offlinePackProgressDidChange()` without having to set up a per pack observer system.

I think the resume functionality itself in `MGLOfflineStorage` or `MGLOfflinePack` does work. However, we may be able to add additional examples and documentation to guide developers away from the troubles you encountered. It may also be the case that we need to file new bug reports about issues (usability or otherwise) that arise from setting up per pack observers. I'm going to close this issue but please feel free to reopen if the changes I suggested don't work for you.

Thanks for the report!

cc @jmkiley @friedbunny @1ec5

**Comment by hhartz** [comment]
I finally got back to this after having to work on other issues, and got it working now! Thank you for the helpful feedback! I worked on moving the download functionality to a separate class, is this interesting for you as an example?

**Comment by boundsj** [comment]
Thanks for the follow up @hhartz and for sharing your work in the example repo!
