### ISSUE TITLE
mapView:regionDidChangeAnimated() parameter is wrong

### ISSUE THREAD

**Issue by Laeyoung** [mapbox/mapbox-gl-native#7824]
iOS
3.3.7 (Swift)

### Steps to trigger behavior

 1. Implement [`mapView:regionDidChangeAnimated()`](https://www.mapbox.com/ios-sdk/api/3.3.7/Protocols/MGLMapViewDelegate.html#/c:objc(pl)MGLMapViewDelegate(im)mapView:regionDidChangeAnimated:) as document
 2. `func mapView(_ mapView: Any!, regionDidChangeAnimated animated: Any!)`
 3. Crash! when moving MapView

### Expected behavior
Worked well

### Actual behavior
Crash...

_regionDidChangeAnimated animated: Any!_ should be changed to _regionDidChangeAnimated animated:_ **Bool**

**Comment by friedbunny** [comment]
Apologies, I think you may be confused by a limitation of our documentation generator (https://github.com/realm/jazzy/issues/609), wherein parameter types aren’t correctly extracted for Swift. Rest assured, [this delegate method is defined correctly](https://github.com/mapbox/mapbox-gl-native/blob/b35ca2099aef5f5a49b104ee57aecc566feb99a1/platform/ios/src/MGLMapViewDelegate.h#L60).

Rather than copy+paste from the documentation, you might allow Xcode to complete these method names for you — it’s rather convenient and less prone to errors. For instance:

```swift
func mapView(_ mapView: MGLMapView, regionDidChangeAnimated animated: Bool) {
     print(mapView.centerCoordinate.latitude, mapView.centerCoordinate.longitude)
}
```

If you’re just starting out with our SDK, I suggest you have a look at our [examples](https://www.mapbox.com/ios-sdk/examples/) and the [First Steps guide](https://www.mapbox.com/help/first-steps-ios-sdk/).
