### ISSUE TITLE
Selecting an existing AnnotationView is noticeably slow

### ISSUE THREAD

**Issue by piohhmy** [mapbox/mapbox-gl-native#7842]
**Platform:** iOS
**Mapbox SDK version:** Tested on 3.3.7 and 3.4

### Steps to trigger behavior

 1. Add an annotation to map with a subclass of MGLAnnotationView
 1. Implement `gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldReceive touch: UITouch) -> Bool` in the ViewController with the MGLMapView to log when the annotation was tapped.  (E.g. `if let view = touch.view as? MyCustomAnnotationView { NSLog("annotation tapped") }`
 1. Override the function `setSelected(_ selected: Bool, animated: Bool)` in the MyCustomAnnotationView subclass to log when the annotation was selected 

### Expected behavior
Should see the log messages in 2) and 3) with near the same timestamp when user taps an existing annotation. 

### Actual behavior
~500ms delay between step 2) & 3).  This is an issue as when the user taps an existing annotation I trigger an animation in step 3) and it is noticeably sluggish with the delay.  In 3.3.7 I was able to hack around this issue by manually triggering mapView.selectAnnotation in the gestureRecognizer function in step 2) (this step is triggered immediately after touching an annotation), but this doesn't work in 3.4.0 (the mapView seems to get confused and call setSelected with false on the AnnotationView after the ~500ms).  Ideally, the hack in calling setSelected manually isn't necessary and the AnnotationView can receive the setSelected call from the mapView immediately when the user selects an existing annotation.

**Comment by chc24** [comment]
Hello. This is also happening in development on v3.4 for me. @piohhmy Have you managed to hack around this issue in a sustainable way? Really looking for some movement on this issue because as it is now, the user experience is very lacking.

**Comment by boundsj** [comment]
I think this may be happening because the annotation view selection is done by the map view and the map view figures out what annotation should be selected for a tap as a result of `[MGLMapView gestureRecognizerShouldBegin:]` being called by UIKit. That call does seem to take up to a half a second longer than the initial call to `-[MGLMapView gestureRecognizer:shouldReceiveTouch:]` (if that existed). 

The value of the map view figuring out which annotation view is selected is that the map has logic to cycle through annotations that are near each other so all annotation views have a chance of being selected if there are repeated taps in the same area.

At the moment, I'm not exactly sure what a refactor to speed this up would look like. Could we consider having annotation views notify the map directly when they are touched to avoid the delay that the `UITapGestureRecognizer` seems to impose?

As for a work around, I suppose you could trigger the annotation view animation with something like an override of `touchesBegan(_ touches: Set<UITouch>, with event: UIEvent)`. But, I think that would suffer from the same possible bug as the workaround noted in https://github.com/mapbox/mapbox-gl-native/issues/7842#issue-202991869 -- since the map view may not always select the same view that was touched (when annotations are grouped closely together), the animation may be applied to the wrong annotation view.

cc @1ec5 @incanus

**Comment by 1ec5** [comment]
Also worth checking out what effect #7246 has on the response time.

**Comment by chc24** [comment]
Through some method swizzling, I've been able to determine that the delay happens because a single tap waits for a potential 2nd tap due to the relationship between the single tap GR and the double tap GR within MGLMapView. My workaround involves removing the double tap GR from mapview and consequentially not having the double tap zoom. This way, I can animate my annotation views immediately (v3.4.0)

**Comment by 1ec5** [comment]
Thanks @chc24. #7246 and some other gesture changes went into v3.5.0, which was just released, so I’m curious whether there’s any effect there.

**Comment by piohhmy** [comment]
Ok, after playing more around with this I think it can be closed as not a bug.  As @chc24 mentions, the delay is for the gesture recognizer to detect a double tap for a zoom.  By removing the zoomable property from the map it can be seen that the detection happens immediately.  

Also note, Apple Maps behaves the same way in that tapping on an annotation there will be a short delay before it's selected as it waits for the double tap GR to fail.
