### ISSUE TITLE
IPv6 Compatibility Request: Offline Maps Rejection

### ISSUE THREAD

**Issue by szaszpeter** [mapbox/mapbox-gl-native#7928]
Hi **all**,

Our team recently introduced ***Mapbox Offline maps*** in our app. However Apple rejected our app with the following statement: "The map download crashes the app when testing through IPv6 protocol".

We are trying to reproduce the issue on our environment as well. As soon as we have explicit crashlogs we will post them here.

Until then we ask you kindly, to help us find out the solution for this problem.

**Comment by jfirebaugh** [comment]
We don't know of any issues specific to IPv6. If you can reproduce a crash and provide crash logs, that would be appreciated.

**Comment by mb12** [comment]
@jfirebaugh I ran into a similar issue recently. I've included below details on when issues can arise on a pure IPV6 network for sample mapbox application. 

This can happen with Mapbox (on iOS 8.3) if tile.json uses IP literals in tile urls (e.g. http://xx.yy.zz.ww./...) . On iOS 8.x, NSURLsession/CFNetwork does not do IPV6 <--> IPV4 translation automatically. (On a pure IPV6 network, this can also happen on other platforms). (If you are using iOS 9 or OS X 10.11 , this will not reproduce because on these OSes, the translation is handled even for IP literals).

In the past, mapbox used hostnames in tile urls. So this should not be an issue for Mapbox sources. But this might have changed recently. It would be good to add warning in mbgl-core when tile URLS or styles containing IP literals are encountered.

The following should reproduce the issue consistently.

1. Use a style that references tiles with IP literals.
2. Set up network sharing on your Mac with NAT64.

https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html

3. Connect your iOS device to the network set in step #2
