### ISSUE TITLE
test Android platforms

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#793]
Per @ljbade, need to test: 

 * [ ] running `arm64` build on Nexus 9 (`MASON_ANDROID_ABI=arm-v8 make android`)
 * [ ] running `x86` emu (`MASON_ANDROID_ABI=x86 make android`)

**Comment by incanus** [comment]
@ljbade `arm64` builds fine but fails to run on device: https://gist.github.com/incanus/ea4bded813a4e592a65f

**Comment by incanus** [comment]
Built but failed on `x86` `4.4.4` as well: https://gist.github.com/incanus/dbee996f937f91d45c92

**Comment by ljbade** [comment]
Hmm arm64 was a missing symbol:
```
dlopen failed: cannot locate symbol "pthread_cond_timedwait_monotonic_np" referenced by "/data/app/com.mapbox.mapboxgl.app-1/lib/arm64/libmapbox-gl.so"...
```

Possibly no pthread was linked in.

**Comment by ljbade** [comment]
@incanus for the x86 crash can you disable the log cat filter and post the native stack trace, should be a bunch of hex numbers.

**Comment by ljbade** [comment]
Looks like the pthread thing is due to it being removed in newer NDK platforms:
https://code.google.com/p/chromium/issues/detail?id=349865

**Comment by ljbade** [comment]
@incanus It turns out to be a bug in libuv not supporting latest Android NDK platforms - https://github.com/libuv/libuv/issues/172

I am working on a fix in https://github.com/ljbade/libuv-1/tree/fix-android-clock

I created https://github.com/mapbox/mapbox-gl-native/tree/android-libuv-fix with the libuv fix. So @incanus can you test if this works on the Nexus 9 when building in arm64 mode?

If that fixes it I will create the libuv PR and update mapbox-gl with the new release that fixes it.
