### ISSUE TITLE
Offline downloads lots of resources even for a small map

### ISSUE THREAD

**Issue by chiuki** [mapbox/mapbox-gl-native#7932]
**Platform: Android**
**Mapbox SDK version: 4.2.0**

### Steps to trigger behavior

Download an offline region with the following parameters:

|param|value|
|-------|-----|
|styleURL|mapbox://styles/mapbox/outdoors-v9|
|bounds|N:40.017636702500596; E:-105.28388673830995; S:40.016397140468; W:-105.28499028602425|
|minZoom|18.0|
|maxZoom|21.0|
|pixelRatio|2.625|

See code at https://github.com/AndroidAtelier/OfflineTrails/ at commit `7c5a50d` (change `mapbox:zoom` to `18` in `activity_main.xml`, click on the download icon in action bar)

### Expected behavior

Download to finish quickly.

### Actual behavior

Download takes about a minute on wifi, with 1284 resources totaling 73304900 bytes.

Why does it download 73 MB for such a small area?

**Comment by jfirebaugh** [comment]
See #4069.

**Comment by zugaldia** [comment]
@chiuki Thanks for the feedback. This larger download that you're observing happens once, for the first map that you download, subsequent region downloads are smaller. This happens because the first time an offline region is created for a particular style, we download all glyph ranges for all font stacks in that style (a glyph is the visual representation of a single character, this can be a letter, number, punctuation mark, or even a ligature, basically, any unicode character).

This is a known issue and we're tracking future improvements on https://github.com/mapbox/mapbox-gl-native/issues/4069.

In case it helps, we also have more information on network data and disk space for offline maps in our [help guide](https://www.mapbox.com/help/mobile-offline/#network-data-and-disk-space). I hope this helps, let me know if you have any questions.

**Comment by chiuki** [comment]
Fancy seeing you here, @zugaldia!

I read the [guide](https://www.mapbox.com/help/mobile-offline/#network-data-and-disk-space) before filing this issue but it didn't mention the initial glyph download. Would be good to add.

I tried downloading the exact same region for a second time, and it still reports the same number of resources and bytes. Also still takes a long time. How do I make sure that subsequent downloads are faster?

**Comment by friedbunny** [comment]
Subsequent regions that use the same resources may appear to re-download, but it should just be verifying their existence. This verification can also take some time, depending on the hardware, but should take less time than the initial download.

If you find that resources are being re-downloaded, that’ll be a bug we’d want to look in to.

**Comment by altafrm3d** [comment]
While downloading the same region for the second time, i observed that http requests are still being made and network usage is still active, ideally if a tile is either found in the cache or in any of the previous downloads then server shouldn't even be asked for it. That made me came to the conclusion that probably you're re-downloading the tiles of that region.

Could you please confirm it? thanks.

**Comment by zugaldia** [comment]
@altafrm3d How much time passed between region downloads? It's possible the tiles had expired and we were just downloading updated ones.

**Comment by altafrm3d** [comment]
@zugaldia thanks for your reply. Since i am running tests so i am doing them one after another, i am sure the tiles haven't expired, the mapbox version that i am running tests on is release-android-v4.2.2

**Comment by zugaldia** [comment]
@altafrm3d downloads are asynchronous, are the tests certain that the previous download has completed before attempting another same region download?

**Comment by altafrm3d** [comment]
@zugaldia Yes, i downloaded a region for a test, waited for it to complete, then decreased the region bounds a little bit (all the tiles for this new region should already be downloaded at this point), and started a download on it.

**Comment by Guardiola31337** [comment]
@altafrm3d How do you know it's starting a new download? If it's because you're seeing log messages like `202/5122 resources; 13476596 bytes downloaded.`, in reality, the manager is "downloading" the resources from the cache. Definitely, we should have a better message for that. Please, try subsequent times in airplane mode and check actual http requests (there shouldn't be any and should continue to work) and let us know.
