### ISSUE TITLE
[Android] Rotate marker not working

### ISSUE THREAD

**Issue by nijs9** [mapbox/mapbox-gl-native#7936]
I'm trying to rotate a marker in the Android Mapbox SDK in this way:

`ValueAnimator markerAnimator = ObjectAnimator.ofObject(marker, "rotation", new FloatEvaluator(), -90, 90);
   markerAnimator.setDuration(5000);
   markerAnimator.start();`

But marker is not rotating. Is this even possible?

**Comment by tobrun** [comment]
This is currently not support, this has been fixed with https://github.com/mapbox/mapbox-gl-native/pull/7907 and will ship with the next Android SDK. At the moment calling setRotation will rotate the marker with an animation so no need to use an animator yourself. Side note is that you can always get the actual view representing the MarkerView with `MarkerViewManager#getView(MarkerView marker)` and use a ViewAnimator on it.
