### ISSUE TITLE
Subclassing a Feature not working as expected

### ISSUE THREAD

**Issue by rmnblm** [mapbox/mapbox-gl-native#7949]
**Platform:** iOS 10.2
**Mapbox SDK version:** 3.4.1

### Steps to trigger behavior

 1. Subclass for example `MGLPointFeature`, let's call it `CustomPointFeature`
 2. Add an array `[CustomPointFeature]` to `MGLMapView` by creating a `MGLShapeSource` and pass it as features parameter `identifier:features:options:`.
 3. Calling `visibleFeatures(in:)` to get all features in a specified location

### Expected behavior

The return type of `visibleFeatures(in:)` is `[MGLFeature]` and I should be able to cast the array to `[CustomPointFeature]`

### Actual behavior

Casting doesn't work.

### Notes

Is this a behaviour by design or am I missing something here? Is it somehow possible to get the original `CustomPointFeature`s?

**Comment by boundsj** [comment]
Noting a somewhat related `MGLShape` / `MGLFeature` issue: https://github.com/mapbox/mapbox-gl-native/issues/7913

**Comment by boundsj** [comment]
@rmnblm when you say "Casting doesn't work.", what exact error are you seeing when you try to cast?

**Comment by rmnblm** [comment]
@boundsj 
If I print out the result of `visibleFeatures(in:)` to the console, it prints out all of type `MGLFeature`.
If I cast the property `MGLShapeSource.shape` to an `MGLShapeCollectionFeature` to the console, it prints out all of the expected type `CustomPointFeature`. 

And of course if I try to cast them with `as!`, my app crashes.

**Comment by boundsj** [comment]
An instance of a feature that is created for the purpose of being added to the map via `MGLShapeSource` cannot currently be thought of as anything other than a data transfer object. The reason is that the Swift/Objective-C object is transformed into a C++ object as it is transferred to the core of the SDK and the a reference to the Objective-C instance is not maintained (by the SDK). 

Later, if the map is queried via `visibleFeatures()` , the C++ core returns objects that are then [turned into new object instances](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/darwin/src/MGLFeature.mm#L223-L227) that have no way of knowing about instances of any subclass that may have been used to add a feature to the map originally. 

The SDK does not maintain a lookup table of added feature instances. However, as a workaround, your application could keep such a table and match up returned `MGLPointFeature`s with your subclass instances via the `identifier` attribute or some some key/value pair in the feature `attributes` dictionary that is suitable for identification.

Closing because we don't currently have plans to support this sort of lookup and original instance restoration functionality in the SDK itself.
