### ISSUE TITLE
Please allow us to change the position of the Mapbox logo

### ISSUE THREAD

**Issue by millenbop** [mapbox/mapbox-gl-native#8003]
It is already possible to hide it. But we would like a way to change the position of the logo instead. In this case we would want to move it to the bottom right to be able to put the view finder closer to the bottom.

![screen shot 2017-02-09 at 11 31 26](https://cloud.githubusercontent.com/assets/12835674/22779519/66f701ae-eebb-11e6-9504-37e00d196c28.png)

**Comment by frederoni** [comment]
You can change the `contentInsets` to adjust the logo, attribution and compass margins but it's not ideal in this situation because it will affect the focal point.

Here are a couple of options:
- Hide the logo and add it manually on top the of map view. Make sure you use the same image from the framework's bundle.
- Subclass `MGLMapView`, override `-[MGLMapView updateConstraints]` in your subclass. Call `[super updateConstraints]` first, then find the logo's leading constraint and replace it with a trailing constraint.

**Comment by millenbop** [comment]
Ok, I went with

```
UIImageView* logo = [[UIImageView alloc] initWithImage:[UIImage imageNamed:@"mapbox.png"]];
logo.center = CGPointMake(self.mapView.frame.size.width - 70, self.mapView.frame.size.height - 20);
[self.mapView addSubview:logo];
```

Thanks!

**Comment by afomich** [comment]
Ok, I try to do second trick with compass view.
I override updateConstraints in my map view class as shown below: 
- (void)updateConstraints
{
    [super updateConstraints];
    // compass
    //
    [self removeConstraints:self.compassView.constraints];
    [self.compassViewConstraints removeAllObjects];
    
    [self.compassViewConstraints addObject:
     [NSLayoutConstraint constraintWithItem:[super compassView]
                                  attribute:NSLayoutAttributeTop
                                  relatedBy:NSLayoutRelationEqual
                                     toItem:[super compassView]
                                  attribute:NSLayoutAttributeTop
                                 multiplier:1
                                   constant:5 + 50]];
    
    [self.compassViewConstraints addObject:
     [NSLayoutConstraint constraintWithItem:self
                                  attribute:NSLayoutAttributeTrailing
                                  relatedBy:NSLayoutRelationEqual
                                     toItem:[super compassView]
                                  attribute:NSLayoutAttributeTrailing
                                 multiplier:1
                                   constant:5 + 50]];
    
    [self addConstraints:self.compassViewConstraints];
}

but I got exception 
 *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: [constraints isKindOfClass:[NSArray class]]'


on line  [super updateConstraints];

**Comment by volodymyrslipak** [comment]
where to get that mapbox.png file???
