### ISSUE TITLE
OpenGL is being invoked in inefficient way

### ISSUE THREAD

**Issue by oguzyildiz1991** [mapbox/mapbox-gl-native#8023]
**Platform:iOS and Android**
**Mapbox SDK version: Latest**

In context.cpp, glTexImage2D is being called when the texture is being updated. But it should only be called when creating it. For uploading to the existing texture, glTexSubImage2D should be called. This will dramatically improve the rendering performance.

For more info: http://stackoverflow.com/questions/12922846/uploading-texture-very-slow-in-opengl (See Nicol Bolas's answer).

### Steps to trigger behavior
 1. Render anything

### Expected behavior
Should call glTexImage2D once per texture, then should keep calling glTexSubImage2D

### Actual behavior
Uses glTexImage2D to upload to the existing texture

**Comment by eimantas** [comment]
Given it's quite smooth on iOS, I'd really love to see this fixed as this may considerably reduce the energy impact used for drawing the maps.

**Comment by ragaisis** [comment]
What is more, I'm trying to use markers with dynamic icons. Every icon has different rules, so I'm drawing it on canvas and converting to bitmap to set it as an marker icon. After using mapbox map for a while they just disappear, because of out of memory from the mapbox core. Hopefully this will fix the problem.

**Comment by kkaefer** [comment]
We've removed our use of `glTexSubImage2D` in https://github.com/mapbox/mapbox-gl-native/pull/6836, which fixed https://github.com/mapbox/mapbox-gl-native/issues/1526 for us (of course, it could also have been some other bug).

Using `glTexSubImage2D` might sound like a good idea, and it may show improved performance on some GPUs, but in particular on mobile GPUs like the PowerVR-derived chips Apple uses, it doesn't have any effect. These chips are typically using deferred rendering, which means that they just queue up the commands and send it to the GPU without waiting for completion. When updating a texture, the driver first has to create a copy of the existing texture, before it can patch it with `glTexSubImage2D`, since the original texture might still be in use. This means that an update call first needs to copy, then overwrite everything.

Another option might be to instead maintain a list of all of the changed parts of the texture, and only upload these with many small calls. This could be beneficial if we find that transfer bandwidth is a performance bottleneck, but we don't have an indication that this is the case.

**Comment by oguzyildiz1991** [comment]
@kkaefer Could that be glTexImage2D wasn't called at the right time before glTexSubImage2D? I mean I'm only guessing here. In Android, in some cases glTexImage2D takes 70ms where glTexSubImage2D takes 4 ms, so there may be a big perf loss in there.

**Comment by kkaefer** [comment]
Added an implementation of this in https://github.com/mapbox/mapbox-gl-native/tree/opengl-glTexSubImage2D, but given that we don't have a good way of verifying performance, I'm hesitant to merge it.

**Comment by oguzyildiz1991** [comment]
I'm gonna try that branch, thanks a lot :)
