### ISSUE TITLE
MapboxGL becomes unresponsive on OnePlus 2 and Location move but MapView is frozen

### ISSUE THREAD

**Issue by puzanov** [mapbox/mapbox-gl-native#8030]
**Platform:Android**
**Processor: ARMv8-A**
**Architecture: Kryo**
**Mapbox SDK version:4.2.2**

We have this two issues #6138 and #6342 on OnePlus2. Please help! 

### Steps to trigger behavior

 1. Open the map
 2. Start to scroll
 3. Map is freezed!

**Comment by puzanov** [comment]
any updates?

**Comment by tobrun** [comment]
@puzanov sadly we don't have a OnePlus2 for testing. Would you be able to try something out? 

Do you still see the issue when you do:

```java
mapView.findViewById(R.id.markerViewContainer).setVisibility(View.Gone)
```

Can you try disabling touch interaction on that viewgroup?

```java
mapView.findViewById(R.id.markerViewContainer).setClickable(false)
mapView.findViewById(R.id.markerViewContainer).setFocusable(false)
```

**Comment by MrDazt** [comment]
With 5th version the same story

**Comment by puzanov** [comment]
@tobrun please help! we are suffering

**Comment by puzanov** [comment]
@tobrun any updates?

**Comment by jfirebaugh** [comment]
@puzanov We don't have access to this device, and it's unlikely we're going to be able to determine the cause with so little information. You're going to have to dig into this a bit more yourself. Here are some suggestions:

* Try other devices or configurations for comparison
* Add logging to the code to determine where it starts failing
* Attach a debugger after the freeze occurs and obtain a stack trace

**Comment by mb12** [comment]
@puzanov  You can try the following:

1.)  A low effort test would be to run the random tests on Amazon device farm.  It should  be able to reproduce basic issues caused by scrolling/pressing random keys.

https://aws.amazon.com/device-farm/device-list/

2.) I can confirm that in the past I've tested the  sample app on One Plus One (AWS) and One Plus Two(Real device) and I did not run into any issue.
I did this test at a time when mapbox used to publish 32 bit ARM binaries for ARM V8 as well. You can try removing the armv8 folder from the release. This will force the system to pick up the 32 bit version when running the application.

**Comment by MrDazt** [comment]
@mb12 we tried to force use 32 bit, with no results

I do not know how it's working on your phone, in mine it works few sec and after map just stops updating. Could you try to open simple map and zoom until city shows up?
And I also opened fragment and activity, the same story, but in dialog fragment it works very clever.

@jfirebaugh I launched on other phones and there app works fine.
Add logging to the code to determine where it starts failing // where should I insert Logging ?

**Comment by tobrun** [comment]
> Add logging to the code to determine where it starts failing // where should I insert Logging ?

Feel free to capture the logcat from a session and dump it into a [gist](https://gist.github.com/).

**Comment by MrDazt** [comment]
@tobrun @jfirebaugh  Test App Debug Mode screen , sdk 5.0.0-beta1 (for older logs the same)
https://gist.github.com/MrDazt/628be50c5c7817a92fa0ec84c3031d2c

**Comment by puzanov** [comment]
@tobrun @jfirebaugh guys, any updates on this issue? Our users are crying :(

**Comment by puzanov** [comment]
guys?

**Comment by puzanov** [comment]
hey

**Comment by tobrun** [comment]
@puzanov would you be able to do some debugging from your end as we don't have access to a OnePlus2? Could you add some breakpoints to `MapView#onDraw(Canvas)` and see if the flags checked there are still valid. Is `MapView#OnTouchEvent(MotionEvent)` still being called when the map "freezes"? Are you seeing the same result when switching to TextureView (you can enable this option through xml attrs or MapboxMapOptions).

**Comment by GianhTran** [comment]
@tobrun hi, I have same issue and I try your way, the result is: `MapView#onDraw(Canvas)` and `MapView#OnTouchEvent(MotionEvent)` still being called every when the map being "freezes". 
I enable TextureMode and OMG, Its work !, map no longer "freezes". But I think this not a best solution, right? I don't known what happen in another device which can't work with TextureView and of course, about the performance , Hope you fix it in next release, anw, thank you so much for your support (bow)

**Comment by GianhTran** [comment]
one more thing, what do you think about change from SurfaceView to TextureView, I meant should I sacrifice performance, for fix bug of a little bit of users ? and how I know about performance difference between two way, exactly ? Please give a suggestion, thank you so much, again (bow)

**Comment by tobrun** [comment]
One possible source of this bug is using an inner fragment in another fragment and using the Activity FragmentManager instead of the ChildFragmentManager of the fragment. See https://github.com/mapbox/mapbox-gl-native/issues/9661. 

@GianhTran the difference between SurfaceView and TextureView is that a TextureView will use a Texture to display the rendered content. While surfaceView allows to direclty render on the surface. Benefit of this is that SurfaceView will be more performant. Benefit of using TextureView is that it supports animation and has better synchronsitation for overlain view elements.

**Comment by GianhTran** [comment]
@tobrun thank you so much for your support, but in my case, I using mapView in activity so your solution not work for me.

**Comment by NancyAndroid** [comment]
Same issue is with me using latest sdk v5.1.3 I am using in activity So any update
Here is my log:

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.NativeMapView.createSurface(android.view.Surface)' on a null object reference  at com.mapbox.mapboxsdk.maps.MapView$SurfaceCallback.surfaceCreated(MapView.java:426)

**Comment by NancyAndroid** [comment]
@GianhTran any update how you resolve this issue.

**Comment by gang018** [comment]
@NancyAndroid did you got a solution?

**Comment by tobrun** [comment]
Capturing from related issues that using TextureView can be a workaround for this.

**Comment by HappyDr0id** [comment]
I got exactly the same issue : I have a map in a bottomsheet, which is in textureMode because of visual glitches when I drag the bottomsheet, and if I collapse the bottomsheet and expand it back, the map is totally frozen, not responding to user interaction, but MarkersViews are moving okay.
Finally the map is only working correctly on the first display.

I retrieved these logs when it happens :
```
01-18 14:49:19.297 15642-17390/fr.xpdigit.apptourism E/BufferQueueProducer: [SurfaceTexture-0-15642-2] dequeueBuffer: BufferQueue has no connected producer
                                                                            
                                                                            [ 01-18 14:49:19.297 15642:17390 D/         ]
                                                                            NULL == surf->write_back_color_buffer
01-18 14:49:19.300 15642-17390/fr.xpdigit.apptourism E/BufferQueueProducer: [SurfaceTexture-0-15642-2] dequeueBuffer: BufferQueue has no connected producer
                                                                            
                                                                            [ 01-18 14:49:19.301 15642:17390 D/         ]
```

I am using the last MapBox Android SDK Version (5.3.1) and I reproduced the issue on multiple devices : Samsung A3 (2016) SM-1310F on Android 7.0, Samsung S7 on Android 7.0, Moto E on Android 4.4.4, Nexus 5 on Android 6.0.1. But the issue is not reproduced on the Nexus 5X on Android 8.0.

I hope that it will help you to resolve this issue guys.
