### ISSUE TITLE
[iOS] re-adding all of the annotations when adding a single annotation

### ISSUE THREAD

**Issue by eimantas** [mapbox/mapbox-gl-native#8036]
**Platform:** iOS
**Mapbox SDK version:** probably v3.4.0

### Steps to trigger behavior

 1. Implement `didMoveToSuperview` method in a subclass of `MGLAnnotationView`
 2. Add as many annotations to the map as needed

### Expected behavior

`didMoveToSuperview` is called only for the newly added annotation

### Actual behavior

`didMoveToSuperview` is called for all annotations when new annotation is added.

It seems that the cause is recreation of `MGLAnnotationContainerView` that is removed from superview and re-added to the same view after every call to `addAnnotations:`. Is there any specific reason for this behavior? And if so, I'd like to know if there is an easy way to add an animation when the  annotation is being added to the map.

**Comment by fabian-guerra** [comment]
Hi @eimantas,

`MGLAnnotationContainerView` is removed and re-added due to performance issues adding subviews to a view that is already in the hierarchy.

Regarding 

> And if so, I'd like to know if there is an easy way to add an animation when the annotation is being added to the map.

Check these links:
[Delegate that gets called when one or more annotation views have been added and positioned on the map](https://www.mapbox.com/ios-sdk/api/3.4.1/Protocols/MGLMapViewDelegate.html#/c:objc(pl)MGLMapViewDelegate(im)mapView:didAddAnnotationViews:)
[How to make a custom annotation animation](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/app/MBXAnnotationView.m#L52-L63)

**Comment by fabian-guerra** [comment]
Hi @eimantas, this is expected behavior, we don't plan on changing at the moment.
Hope links above were useful.

**Comment by eimantas** [comment]
Thanks @fabian-guerra.

Are there any benchmarks to run to view if the issue is still present regarding adding one vs readding all?

And thanks for the link regarding the annimation!
