### ISSUE TITLE
Map change errors/failures should be specified and passed through to platform SDKs

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-gl-native#8086]
Currently [map.cpp](https://github.com/mapbox/mapbox-gl-native/blob/d4c569a0187d98bca6b71671fa5daf6ee09747da/src/mbgl/map/map.cpp#L1100) only returns single `mbgl::MapChangeDidFailLoadingMap` event for any and all map failures, making it impossible for a developer to distinguish between map failures. 

For example, on iOS the same error is returned whether a map load failed due to a bad access token, a bad style, or a bad network connection. 

/cc @1ec5

**Comment by 1ec5** [comment]
The error was implemented in #3063 to use a generic code and `nil` message because of this issue. As such, it’s debatable whether we’ve actually fixed #2762, and certainly this blocks #2775. mbgl notifications could be structs with richer information, but at that point we might as well start throwing real C++ exceptions and catching them at the SDK level, along the lines of #3063.

**Comment by 1ec5** [comment]
This is happening in #8418.

**Comment by boundsj** [comment]
#8418 landed in the master branch.
