### ISSUE TITLE
MapBox - MapBoxAccountManager, Unresolved Symbol

### ISSUE THREAD

**Issue by genaray** [mapbox/mapbox-gl-native#8165]
**Android:**
**5.0.0,4.2.2:**

### Steps to trigger behavior

 1. Create new project in Android Studio
 2. Add gradle Dependencies
 3. Notice that it seems like MapBoxAccountManager isnt valid.

### MapBoxAccountManager isnt valid for some reason, theres even no import option for it!

![desktop](https://cloud.githubusercontent.com/assets/20269164/23219672/056af7dc-f920-11e6-9afe-53cb7cdf9a55.PNG)

**Comment by tobrun** [comment]
With the 5.0.0 release we are moving towards using `Mapbox.java` instead of `MapboxAccountManager.java`. More information on this in our [migration guide](https://github.com/mapbox/mapbox-gl-native/wiki/Android-4.x-to-5.0-update). If you are still unable to hook into MapboxMap maybe try removing your local gradle cache with [this](http://stackoverflow.com/a/30450020/1281750) . Let us know if you have additional questions, closing this issue as answered.
