### ISSUE TITLE
macOS CI builds mbgl-core twice

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#8173]
The macOS build is taking longer than necessary because it builds mbgl-core twice (`BUILDTYPE=Debug` in both cases).

Excerpts from the [build log](https://www.bitrise.io/build/956de00e4e82903c):

```
+------------------------------------------------------------------------------+
| (3) Run Core and SDK Unit Tests                                              |
+------------------------------------------------------------------------------+
...
set -o pipefail && xcodebuild -derivedDataPath build/macos -configuration Debug -workspace platform/macos/macos.xcworkspace -scheme 'mbgl-test' build | tee /Users/vagrant/deploy/raw-xcodebuild-output.txt | xcpretty --color --report html --output /Users/vagrant/deploy/xcode-test-results.html
...
▸ Building mbgl/mbgl-core [Debug]
▸ Check Dependencies
▸ Compiling reachability.m
▸ Compiling headless_backend_cgl.cpp
▸ Compiling headless_display_cgl.cpp
...
[  PASSED  ] 463 tests.

  YOU HAVE 7 DISABLED TESTS

set -o pipefail && xcodebuild -derivedDataPath build/macos -configuration Debug -workspace platform/macos/macos.xcworkspace -scheme 'CI' test | tee /Users/vagrant/deploy/raw-xcodebuild-output.txt | xcpretty --color --report html --output /Users/vagrant/deploy/xcode-test-results.html
2017-02-22 10:20:14.895 xcodebuild[2578:13254] [MT] IDETestOperationsObserverDebug: (C06994F8-FB2D-48C8-9C76-E746D14D8639) Beginning test session test-C06994F8-FB2D-48C8-9C76-E746D14D8639 at 2017-02-22 10:20:14.894 with Xcode 8C1002 on target <DVTLocalComputer: 0x7ff7fdc81bd0 (My Mac | x86_64)> (10.12.2 (16C67))
2017-02-22 10:20:14.896 xcodebuild[2578:13267]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/vagrant/git/build/macos/Logs/Test/B7791001-868C-423B-B3E1-E1D35B73FE34/Session-test-2017-02-22_102014-xd542v.log
...
▸ Building mbgl/mbgl-core [Debug]
▸ Check Dependencies
▸ Compiling reachability.m
▸ Compiling headless_backend_cgl.cpp
▸ Compiling headless_display_cgl.cpp
...
```

**Comment by kkaefer** [comment]
Here are my observations:

- This error only occurs with `xcodebuild`, not with the Xcode GUI.
- When building the project in the Xcode GUI first, then running `xcodebuild`, nothing gets rebuilt, and the build succeed immediately.

To resolve this error, I tried:

- Not setting the derived data path on the command line and the `WorkspaceSettings.xcsettings` file. This makes Xcode/`xcodebuild` default to the `~/Library/Developer/Xcode/DerivedData/` directory.
- Setting `HEADERMAP_USES_VFS` to `YES` as recommended in https://forums.developer.apple.com/thread/62737?tstart=0

I ran  `defaults write com.apple.dt.Xcode ExplainWhyBuildCommandsAreRun -bool true`, which makes `xcodebuild` show information like this:

```
CompileC build/macos/mbgl.build/Debug/mbgl-core.build/Objects-normal/x86_64/headless_display_cgl.o platform/darwin/src/headless_display_cgl.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
    (running because there is no record of having run this command since the last clean)
```

I ran the build again with this on [Bitrise](https://www.bitrise.io/build/79daef4e218863bb), but to no avail; it reports the same message for both builds.

I think I'm attributing this to an Xcode bug. Let's see if it's fixed in 8.3. If not, we could start using [xcbuild](https://github.com/facebook/xcbuild)
