### ISSUE TITLE
MGLInterpolationMode docs should clarify relative differences

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#8192]
v3.5.0 deprecates [`+[MGLStyleValue valueWithStops:]`](https://www.mapbox.com/ios-sdk/api/3.5.0-beta.1/Classes/MGLStyleValue.html#/c:objc(cs)MGLStyleValue(cm)valueWithStops:), replacing it with [`+[MGLStyleValue valueWithInterpolationMode:cameraStops:options:]`](https://www.mapbox.com/ios-sdk/api/3.5.0-beta.1/Classes/MGLStyleValue.html#/c:objc(cs)MGLStyleValue(cm)valueWithInterpolationMode:cameraStops:options:).

Besides being a much more verbose initializer, this change adds ambiguity: what [`MGLInterpolationMode`](https://www.mapbox.com/ios-sdk/api/3.5.0-beta.1/Enums/MGLInterpolationMode.html) was being used in v3.4 and which of the four options should I use now?

We should clarify:

- What the default interpolation mode is, if any can be said to be the default.
- The relative advantages of each interpolation mode for typical use cases.

/cc @boundsj

**Comment by boundsj** [comment]
The iOS `MGLInterpolationMode` corresponds to the GL-JS notion of [function type](https://www.mapbox.com/mapbox-gl-js/style-spec/#function-type).

The iOS SDK 3.4.x versions offer a single function type (`MGLStyleFunction` now known in the 3.5.0 beta 1 as `MGLCameraStyleFunction`) that uses exponential or interval interpolation depending on the property data type. Although we've talked about exponential (linear) interpolation in the 3.4.x API docs, I don't think we documented clearly that `MGLStyleFunction`'s exponential stops would be treated as interval stops if the data type of the property it was applied to could not be interpolated (i.e. color vs an enumeration or boolean).

The Mapbox iOS 3.5.0 beta 1 release introduces `source` and `composite` functions along with porting the legacy function to `camera` function. Not all interpolation modes apply to all function types (i.e. only exponential and interval make sense for camera) and interpolation modes can mean different things depending on the function type (i.e. source vs. composite functions). 

It would be great to add more information to the [MGLInterpolationMode](https://www.mapbox.com/ios-sdk/api/3.5.0-beta.1/Enums/MGLInterpolationMode.html) docs. Also, the API documentation for [MGLSourceStyleFunction](https://www.mapbox.com/ios-sdk/api/3.5.0-beta.1/Classes/MGLSourceStyleFunction.html), [MGLCameraStyleFunction](https://www.mapbox.com/ios-sdk/api/3.5.0-beta.1/Classes/MGLCameraStyleFunction.html), and [MGLCompositeStyleFunction](https://www.mapbox.com/ios-sdk/api/3.5.0-beta.1/Classes/MGLCompositeStyleFunction.html) already hints at why you may want to use one function over the other and may be a good place to add more information. However, because these concepts may be hard to explain fully in any one part of the API documentation, I think a DDS specific guide may be really useful (ref https://github.com/mapbox/mapbox-gl-native/issues/7924).

cc @friedbunny @jmkiley @incanus

**Comment by friedbunny** [comment]
Fixed by #8425.
