### ISSUE TITLE
Add linker script for android to limit exported symbols

### ISSUE THREAD

**Issue by ukreator** [mapbox/mapbox-gl-native#8360]
**Platform:** Android
**Mapbox SDK version:** 5.0 beta

### Steps to trigger behavior

Run ```$NDK_ROOT/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-nm libmapbox-gl.so```

### Expected behavior

Something similar to
```
0001c6d0 T JNI_OnLoad
002c200c A __bss_start
002c200c A _edata
002c59e1 A _end
```

### Actual behavior

Outputs thousands of lines of re-exported functions from zlib, pnglib, std c++ lib, sqlite, etc.
This not only increases the binary size and loading time, but also can cause problems to other native libraries in the same Android app which can by accident dynamically link to symbols in libmapbox instead of the proper libzlib.so, libpgn.so, etc.

How to fix: use linker script (linker flag -Wl,--version-script) with the file like this:

```
{
  global: JNI_*;
  local: *;
};
```

**Comment by jfirebaugh** [comment]
This implies our [use of `-fvisibility=hidden`](https://github.com/mapbox/mapbox-gl-native/blob/3afae825c7b2f95e58cbcb85c59857f2253c945e/platform/android/config.cmake#L243-L243) isn't working.

**Comment by kkaefer** [comment]
Looking at https://mapbox.github.io/mapbox-gl-native/metrics/binary-size/, the change to Android system NDK happened in the Feb 22 build. `arm-v7`, and `arm-v5` are way down, while all other Android architectures are up. This may be related?

**Comment by jfirebaugh** [comment]
Looks like `-fvisibility=hidden` is working where we use it; there are no `mbgl` symbols exported. The symbols listed by `nm -D` are:

* libc++ symbols, mostly weak, which wind up visible [due to libc++ policy](http://libcxx.llvm.org/docs/DesignDocs/VisibilityMacros.html)
* sqlite, icu, zip symbols, because Mason doesn't build these libraries with `-fvisibility=hidden`

**Comment by zugaldia** [comment]
> sqlite, icu, zip symbols, because Mason doesn't build these libraries with -fvisibility=hidden

@jfirebaugh Would it make sense to use `-fvisibility=hidden` with these dependencies too? Could that bring any reduced-size benefits?

**Comment by ukreator** [comment]
The easiest way is to use a linker script. For example, see similar problems in Chromium:
https://bugs.chromium.org/p/chromium/issues/detail?id=448386
https://bugs.chromium.org/p/chromium/issues/detail?id=681557
https://bugs.chromium.org/p/chromium/issues/detail?id=588815

**Comment by jfirebaugh** [comment]
Yeah, I'm leaning toward that too, since it would also hide the libc++ symbols. Those symbols are visible by default so that exceptions, `dynamic_cast`, and static member data are safe to use across shared library boundaries, but AFAIK we don't need any of that because libmapbox-gl.so is totally self-contained.

I'm testing it out now.

**Comment by jfirebaugh** [comment]
Before: 6186072
After: 5739608
7% reduction
