### ISSUE TITLE
fill-outline-color displayed correctly

### ISSUE THREAD

**Issue by yangzhedeID** [mapbox/mapbox-gl-native#8411]
**Platform:Android**
**Mapbox SDK version:5.0.0-betal.3**

### Steps to trigger behavior

 1.Android load style `mapbox://styles/freewu/ciysaeyq0000d2suds159ade3`
 2. use chrome to load https://api.mapbox.com/styles/v1/freewu/ciysaeyq0000d2suds159ade3.html?title=true&access_token=pk.eyJ1IjoiZnJlZXd1IiwiYSI6ImNpdTR0cndlNDAwMWYyenM0emNlY2wzdXIifQ.b6ES6ewS-L7PXgrX4HoWUA#20.2/33.006518/113.999219/0
 3.fill-outline-color displayed correctly

### Actual behavior
![chrome](https://cloud.githubusercontent.com/assets/6702107/23943486/a0035196-09aa-11e7-89fe-194e4d5dcc20.png)
![phone](https://cloud.githubusercontent.com/assets/6702107/23943507/a8413eae-09aa-11e7-8468-1354663eaa60.png)

**Comment by jfirebaugh** [comment]
`fill-outline-color` is a property that we can't guarantee exact rendering from device to device due to how it's implemented with OpenGL. If you need exact rendering of fill outlines, I suggest creating a separate `line` layer that uses the same geometry. That also gives you control over the line width.
