### ISSUE TITLE
Windows/ANGLE Implementation

### ISSUE THREAD

**Issue by adamhewitt627** [mapbox/mapbox-gl-native#8429]
I'm researching for an upcoming project leveraging the native SDKs, and am simply missing out on Windows support. I'm not sure if using [ANGLE](https://github.com/Microsoft/angle) or OpenGL directly is better, but either would be better than nothing. (My end need is WPF, so ANGLE would certainly be preferable and likely better for other consumers too)

I might be able to do the implementation and PR when it comes time for needing it, but it would be great if someone else wanted to take a crack at it in the meantime.

**Comment by tmpsantos** [comment]
@adamhewitt627 I had success in the past building Mapbox GL Native on Windows using our Qt SDK:
https://doc-snapshots.qt.io/qt5-5.9/location-plugin-mapboxgl.html

It was done using ANGLE through Qt. The major problem we have today is that on Windows is the compiler. MSVC (and I tried all of them, including 2017 with `/permissive-`) doesn't understand the same C++ as Clang and GCC, specially because we use C++11/14.

The only way I managed was using the Clang/C2 frontend for MSVC (https://blogs.msdn.microsoft.com/vcblog/tag/clang/).

I'm in talks with the MS compiler team to see if they can make MSVC 2017 compile Mapbox GL. Meanwhile, Windows is not supported.

**Comment by tmpsantos** [comment]
One last thing, building Qt 5.9 with Mapbox GL on Windows probably works with MinGW (https://wiki.qt.io/MinGW).

**Comment by adamhewitt627** [comment]
I'm not really a C++ guy, so I'm not speaking to my strengths, but I'd prefer to skip a dependency on Qt if at all possible, if only to eliminate layers and build dependencies. I'd have no problem with the build requiring the Clang/C2 frontend, and even needing the Linux subsystem in Win10 depending on the tools.

Is this something that has any interest if I were to do the work?

**Comment by tmpsantos** [comment]
> Is this something that has any interest if I were to do the work?

We have no plans to officially support Windows. I only did it on Qt because I was testing how robust our Qt release was and we pretty much got it for free there.

**Comment by adamhewitt627** [comment]
Thanks, I guess I'll just consider my options when it comes time to implement the Windows control. More direct Windows integration would be ideal, even if it's not-entirely-supported just like the macOS one.

**Comment by tmpsantos** [comment]
@adamhewitt627 Mapbox Qt now has a MSVC Win64 build https://ci.appveyor.com/project/Mapbox/mapbox-gl-native/build/54/artifacts
