### ISSUE TITLE
VectorSource url not getting data

### ISSUE THREAD

**Issue by ssheetz** [mapbox/mapbox-gl-native#8498]
**Platform: Android**
**Mapbox SDK version:4.2.2**

### Steps to trigger behavior
Create a VectorSource object with id and template url, add to map.
Create a LineLayer with basic styles and add to map.

### Expected behavior
Mapbox downloads mvt data as needed and displays it in the LineLayer. 

### Actual behavior
When using our traffic flow template url, mapbox is not substituting the {x}, {y}, {z} parameters, so nothing is downloaded and no lines are drawn.  This url and data do work in the javascript version. When using the terrain contours data ("mapbox://mapbox.mapbox-terrain-v2") the contours appear fine.

**Comment by ssheetz** [comment]
Update:
The solution is to first create a TileSet object with an id and template url, and then pass that to the new VectorSource in the correct constructor.  Then the parameter substitution happens and the lines are drawn as expected.

**Comment by jfirebaugh** [comment]
> The solution is to first create a TileSet object with an id and template url, and then pass that to the new VectorSource in the correct constructor.

Yes, this is the correct solution. For the `VectorSource` constructors that take `String id` and `String/URL url`, the second argument is a URL to a [TileJSON](https://github.com/mapbox/tilejson-spec) resource, rather than a tile template URL. @mapbox/android -- this should be clarified in the JavaDocs.
