### ISSUE TITLE
Differences between MarkerViewOptions and MarkerOptions

### ISSUE THREAD

**Issue by ouska** [mapbox/mapbox-gl-native#8591]
Hello,
I found a weird behavior when working with MarkerViewOptions. There is more issues:

1) when I add only MarkerViewOptions the info window is opened and immediately closed when I tap on the marker. When I also add MarkerOptions, info window keeps opened when taping both Markers.

@Override
public void onMapReady(MapboxMap map) {
    IconFactory iconFactory = IconFactory.getInstance(ExampleActivity.this);
    Icon icon = iconFactory.fromResource(R.drawable.marker_pointer_test);
    // When adding only this, info window cannot be opened - it keeps closing
    map.addMarker(new MarkerViewOptions()
        .position(new LatLng(48.13863, 30.57603))
        .icon(icon)
        .anchor(0.5f, 0.5f)
        .title("Hisense Arena")
        .snippet("Olympic Blvd, Melbourne VIC 3001, Australia")
        .infoWindowAnchor(0.5f, 0.5f)
        .flat(true));

    //When adding this, info windows can be opened
    /*
    map.addMarker(new MarkerOptions()
          .position(new LatLng(48.13863, 11.57603))
          .title("Obyc marker!")
          .snippet("Obyc market snippet"));
    */      
}

When adding this line
mapboxMap.getUiSettings().setDeselectMarkersOnTap(false);
it works properly.

2) When I add MarkerOptions with custom icon similar to the default one (with arrow at the bottom), the arrow does not point to the location - location is rather situated at the center of the marker

3) When I use MarkerViewOptions and scroll the map, the markers does not move smoothly with the map. Instead, they jump as "they would be trying to catch the map". When I use MarkerOptions, the markers stick with map and move smoothly when I scroll the map.

4) When I use MarkerViewOptions and scroll the map so the marker is nearly out of the screen, it disappears while the center of the marker is out of the screen. It also works vice versa. When the location is out of the screen and I move the map toward the location, the marker does not appear until marker's center is on the screen. When I use MarkerOptions, the marker icons appear even when the marker center is out of the screen (near to the visible rectangle)

Platform: Android 6.0.1
Mapbox SDK version: 5.0.0 and 5.0.1

**Comment by tobrun** [comment]
@ouska 

Thank you for reaching out and reporting your issue!

1. This was an issue with the 5.x releases, this will be fixed with the upcoming 5.0.2 bug fix release. Revert of the related commits in https://github.com/mapbox/mapbox-gl-native/pull/8585.

2. You can use `anchor` to change the anchor point.

3. this is because Markers are GL drawn components and are drawn when the map is drawn. MarkerView however are Android SDK Views and we try to synchronise them on top of the map.

4. MarkerViewOptions uses a similar system as ViewRecycling as with ListView to limit the amount of views shown at once on the screen. The current invalidation region is currently the same as the screen. In #5440 there is a feature request to allow defining padding on this region.

Information in this ticket is known/ticketed out in others. 
Closing but definitely let us know if you have any other questions!

**Comment by ouska** [comment]
@tobrun 
Thank you for your answers. It is great to hear that some of these issues have been already fixed. 
Generally I found using Markers (MarkerOptions) suiting me more than MarkerView (MarkerViewOptions). The only trouble I have is related to 2). As Far as I get it, anchor can be used only with MarkerViewOptions, not MarkerOptions. Am I right? That's why the default icon is half-transparent (the bottom part), right? That was the reason I was forced to use MarkerViewOptions instead of MarkerView .

I might go this direction and enlarge my icons the same way as well. But then also the invisible part of the marker can be tapped. That makes it a little bit fuzzy when there is a cluster of markers - tapping one particular marker sometimes opens an InfoWindow belonging to a marker above (northern location)

Would't be possible to introduce anchor also for MarkerOptions?

Thanks.
V.
