### ISSUE TITLE
mapView.fly(to: camera) produces no action when the camera's center is the same as the current center

### ISSUE THREAD

**Issue by chc24** [mapbox/mapbox-gl-native#8610]
**Platform:**
iOS
**Mapbox SDK version:**
3.4.0

### Steps to trigger behavior

 1. Set the center to your location
 2. attempt to fly to your location with a higher altitude or lower altitude

### Expected behavior
Some sort of flying should happen, especially if there is a new altitude specified in the MGLCamera

### Actual behavior
The camera does not move / no flying happens.

**Comment by 1ec5** [comment]
Thinking out loud: the intended behavior is that the map would [ease](https://github.com/mapbox/mapbox-gl-native/blob/939864cb901fa35c41e7a04e93988cf746e921a6/src/mbgl/map/transform.cpp#L244) to the new altitude, since the parabolic flight motion makes less sense when either endpoint is directly atop the other. If nothing happens, that suggests either the zoom level is being capped somehow or the center coordinate [isn’t making it through](https://github.com/mapbox/mapbox-gl-native/blob/939864cb901fa35c41e7a04e93988cf746e921a6/src/mbgl/map/transform.cpp#L172) to the flight code.
