### ISSUE TITLE
factor out tile extent as constant

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#862]
![screen shot 2015-02-11 at 5 07 45 pm](https://cloud.githubusercontent.com/assets/17722/6159875/b9258a3e-b210-11e4-8f57-f9d3c7ba02ff.png)

**Comment by mb12** [comment]
In addition to this, the factor 8.0 needs to be factored out to layer_extent/tileSize.

Once that is done, then  performance on retina displays can be improved by 4x by setting tileSize for iPad Air/retina devices to a higher value. Currently for the same zoom level, it loads 4x the number of tiles compared to non-retina devices. 
Since a tile represents a fixed physical region on earth, for Vector sources tileSize should be a function of device physical size not pixel density.

**Comment by incanus** [comment]
Dupe of https://github.com/mapbox/mapbox-gl-native/issues/250, really.
