### ISSUE TITLE
Use case for analog to TileProvider

### ISSUE THREAD

**Issue by kjkrum** [mapbox/mapbox-gl-native#8687]
I opened a feature request for this previously (#7477) and it was closed with a suggestion that does not address the need.  I don't think I adequately explained why this feature is so badly needed.  This alone is preventing me from dropping Google Maps in favor of Mapbox.

The entire Mapbox API seems to be designed around the assumption that maps will be sourced from URLs.  This does not fit my use case.  I want to allow users to open various map files (.shp, .mbtiles, possibly custom formats) located on their own device.  For vector formats, I would load the geometry into a spatial index and generate each tile at the moment it is requested.  As far as I can tell, this is currently impossible in Mapbox unless I create a `Source` with a HTTP URL that points to a server running inside my app.

I see that there has been some work on adding support for `file:///` URLs.  This also does not address the need.  I would have to generate the entire tileset and dump it in the app's temp directory each time the user opens a file.

**Comment by jfirebaugh** [comment]
Hi @kjkrum, thanks for sharing your use case. Rest assured we recognize these the use cases for local tiles and non-URL based tile loading and have plans for adding features to support them. Here are some of the issues tracking these features and work on them:

* [Programmatically generated raster sources](https://github.com/mapbox/mapbox-gl-native/issues/7471)
* [Adding a new MGLSource subclass that implements datasource pattern for fetching tiles](https://github.com/mapbox/mapbox-gl-native/issues/6861)
* [Custom vector source](https://github.com/mapbox/mapbox-gl-native/pull/8473)

Some of these tickets are phrased in platform-specific terms, but we intend to add equivalent features to both iOS and Android SDKs.

Closing here since we have existing issues that track this work.

**Comment by kjkrum** [comment]
Thanks.  I was under the impression that this was deliberately unsupported, perhaps for non-technical reasons.
