### ISSUE TITLE
support anisotropic filtering on raster tiles

### ISSUE THREAD

**Issue by mollymerp** [mapbox/mapbox-gl-native#8688]
relevant PR: https://github.com/mapbox/mapbox-gl-js/pull/4443
ref issue: https://github.com/mapbox/mapbox-gl-js/issues/1064

https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_texture_filter_anisotropic.txt 
not 100% sure this is supported on all our platforms so will have to do some digging

**Comment by kkaefer** [comment]
I've implemented this in [8688-anisotropic-filtering](https://github.com/mapbox/mapbox-gl-native/compare/8688-anisotropic-filtering), but couldn't measure a difference in image quality.

In JS, we added a call to `generateMipMap` [on a hunch](https://github.com/mapbox/mapbox-gl-js/commit/1bb0d6960ed7ca88e1911fc3250adbad9df04c7a) a few years ago, and it has remained in the raster drawing code ever since. Mipmaps only make sense when the texture is scaled down significantly (way below 50% of its original size), as a mean to improve the quality of the texels used to calculate the fragment color.

We never added mipmapping for raster tiles in Native, and I don't think we need to, given that we almost always draw the textures in a size that isn't smaller than half the original dimensions. Since we don't mipmap raster tiles, we also don't need anisotropic filtering.

We should consider removing mipmapping (and anisotropic filtering) from JS as well for parity.
