### ISSUE TITLE
Open GL Layer renders above opaque fill layer regardless of layer order

### ISSUE THREAD

**Issue by jmkiley** [mapbox/mapbox-gl-native#8700]
**Platform:** Core
**Mapbox SDK version:** v3.5.2

### Steps to trigger behavior

 1. Create a custom Open GL layer and add it to the map view. (I used the[ LimeGreenStyleLayer](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/macos/app/LimeGreenStyleLayer.m) from the macOS app)
 2. Create a fill layer and add it above the custom layer.

```
    LimeGreenStyleLayer *layer = [[LimeGreenStyleLayer alloc] initWithIdentifier:@"mbx-custom"];
    MGLSymbolStyleLayer *symbolLayer = [style layerWithIdentifier:@"admin-3-4-boundaries"];
    [style insertLayer:layer belowLayer:symbolLayer];
    
    NSURL *url = [NSURL URLWithString:@"mapbox://examples.69ytlgls"];
    
    MGLVectorSource *source = [[MGLVectorSource alloc] initWithIdentifier:@"state-source" configurationURL:url];
    [style addSource:source];
    
    MGLFillStyleLayer *fillLayer = [[MGLFillStyleLayer alloc] initWithIdentifier:@"states" source:source];
    fillLayer.sourceLayerIdentifier = @"stateData_2-dx853g";
    fillLayer.fillColor = [MGLStyleValue valueWithRawValue:[UIColor redColor]];
    MGLSymbolStyleLayer *symbolLayer2 = [style layerWithIdentifier:@"country-label-lg"];
    fillLayer.fillOpacity = [MGLStyleValue valueWithRawValue:@1];
    [style insertLayer:fillLayer aboveLayer:symbolLayer2];
```
### Expected behavior

The fill layer should appear above the custom layer.

### Actual behavior

The custom layer appears above the fill layer, but below the label layer (see #8699 for issue related to opaque fill layers rendering below symbol layers).

Current workaround is to set the `fillOpacity` to `0.99`.

Currently working with @lbud to investigate underlying cause.

**Comment by jfirebaugh** [comment]
In order for a custom layer to draw correctly underneath an opaque fill, it needs to:

* Respect the depth buffer settings that have been set by mgbl
* Give the fragments it shades an appropriate depth value

--- | Custom layer disables depth test | Custom layer does not change depth test
--- | --- | ---
Fill opacity = 1 | ![image](https://cloud.githubusercontent.com/assets/98601/25026638/29c33fdc-205c-11e7-82a7-b297a734d9f8.png) | ![image](https://cloud.githubusercontent.com/assets/98601/25026638/29c33fdc-205c-11e7-82a7-b297a734d9f8.png)
Fill opacity < 1 |  ![image](https://cloud.githubusercontent.com/assets/98601/25026702/a6ecb4de-205c-11e7-9244-d5c41fc98818.png) | ![image](https://cloud.githubusercontent.com/assets/98601/25026702/a6ecb4de-205c-11e7-9244-d5c41fc98818.png)

The unexpected result here is the top right corner. I believe this is happening because the position for custom style layer vertices is `vec4(a_pos, 0, 1)`, i.e. the z-index is not affected by a view matrix and so fragments are always failing the depth test.
