### ISSUE TITLE
[android] Fix developer config creation task

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-gl-native#8783]
Current [task](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/gradle-config.gradle) is not working when you don't have `MAPBOX_ACCESS_TOKEN` environment variable set. Actually, it always creates a file in which `mapbox_access_token` is `null` which throws a `MapboxConfigurationException` crashing the app.

It's fixed in [`mapbox-navigation-android`](https://github.com/mapbox/mapbox-navigation-android/blob/master/navigation/app/developer-config.gradle) so porting those changes would fix the issue.

**Comment by tobrun** [comment]
The initial approach was to not require developers to have the access token set as an environment variable. When they haven't set the variable, the file is generated with a null value so they can manually insert the value themselves after running into the runtime exception. I'm not opposed to requiring this as a requirement though, just adding this as background information.

**Comment by zugaldia** [comment]
I suggest the following changes:

- If the `MAPBOX_ACCESS_TOKEN` environment variable is set, we use it to populate the `developer-config.xml` file.
- If it isn't set, we print a warning but we do not break the build.
- Either way, the `developer-config.xml` file is generated.
- Instead of defaulting to a `null` value when it isn't set, we put something like `YOUR_MAPBOX_ACCESS_TOKEN_GOES_HERE` which explains better what needs to be done.
- When we do token validation in the SDK, if we detect that the token value is `YOUR_MAPBOX_ACCESS_TOKEN_GOES_HERE` we know exactly what happened and we can provide additional logging/error messages.

How does that sound?
