### ISSUE TITLE
[iOS] User annotation lag with iOS 10.3

### ISSUE THREAD

**Issue by RomainQuidet** [mapbox/mapbox-gl-native#8874]
**Platform: iOS 10.3**
**Mapbox SDK version: 3.5.2**

### Steps to trigger behavior

 1. Launch the demo app in Release mode
 2. Center map on user location
 3. Pan the map around

### Expected behavior
Map and user annotation should stay synchronized

### Actual behavior
We experience some "jumps", showing lags. After some Instruments sessions, I don't see anything wrong here. We run the exact same app on the same device with iOS 10.2, there is absolutely no lag.
This behavior is not visible with annotation views, but with their callout views (small desynchro and jumps).

I don't know why iOS 10.3 introduced a latency here.

**Comment by jmkiley** [comment]
Noting that this seems to effect both default and custom user location annotations.

![userlocationannotation](https://cloud.githubusercontent.com/assets/12474734/25919705/56f7c5a8-3584-11e7-97fb-a1cb9a4e263b.gif)

**Comment by 1ec5** [comment]
> Noting that this seems to effect both default and custom user location annotations.

The screen recording above is #5489.

> This behavior is not visible with annotation views, but with their callout views (small desynchro and jumps).

This ticket, meanwhile, is specifically about callout views, not annotation views. I think it’s related to #5489 in the sense that callout views are also synchronized with the map in the same way as annotation views. It’s likely the same root cause, but our options for fixes or workarounds would differ because callout views can contain much more complex content than a typical annotation view.
