### ISSUE TITLE
Troubles with Routes on Cycling profile

### ISSUE THREAD

**Issue by Floreturns** [mapbox/mapbox-gl-native#8946]
Hello MapBox !

**Platform: Android**
**Mapbox SDK version: 4.2.2**

I need to find a route for cycling users so my app is on Cycling profile, but this profile allow parking and private roads.

For now I use Driving profile to avoid these problems, but one way roads and cycling ways are not allowed in this mode.

Do someone have to solve this problem or someones know how to deal with it ?

![image](https://cloud.githubusercontent.com/assets/10733262/25904521/c7f6e05c-359f-11e7-884e-a5b54879b518.png)

Arrival Point before parking's exit :

![image](https://cloud.githubusercontent.com/assets/10733262/25904648/1f5b2c2c-35a0-11e7-9272-34fe332b9ddb.png)

Arrival Point after parking's exit :
![image](https://cloud.githubusercontent.com/assets/10733262/25904670/2fd94912-35a0-11e7-988f-88f63f8e819c.png)

**Comment by cammace** [comment]
Support for other direction profiles such as cycling is currently in the process of being implemented (see https://github.com/mapbox/mapbox-navigation-android/issues/24). Besides you using the cycling profile, I don't see any resolution to this issue. Closing since this topic doesn't belong in this repo but rather the [Android Navigation repo](https://github.com/mapbox/mapbox-navigation-android/)
