### ISSUE TITLE
Cannot move MGLCircleStyleLayer with draggable MGLAnnotationView

### ISSUE THREAD

**Issue by evgzor** [mapbox/mapbox-gl-native#8964]
**iOS**
**3.5.4:**

### Steps to trigger behavior

 1. Create MGLAnnotation with MGLCircleStyleLayer
 2. Make MGLAnnotation draggable
 3. Move annotation by dragging

### Expected behavior
MGLCircleStyleLayer can move with MGLCircleStyleLayer
### Actual behavior
MGLCircleStyleLayer is static and no API referenced to it. Only reloadStyle: reload all styles - and flash the screen
![screenshot_ios_2 14 0 7 1](https://cloud.githubusercontent.com/assets/5227456/25960936/2f601e8e-3681-11e7-958b-52e27e63e9b4.png)
code: 

```swift
func mapView(_ mapView: MGLMapView, didFinishLoading style: MGLStyle) {
        guard let annotations = mapView.annotations else {
            return
        }
        if !annotations.isEmpty {
            let point = MGLPointAnnotation()
            guard let coordinate = mapView.annotations?.first?.coordinate else {
                return
            }
            point.coordinate = coordinate
            let source = MGLShapeSource(identifier: "circle", shape: point, options: nil)
            style.addSource(source)

            let layer = MGLCircleStyleLayer(identifier: "circle", source: source)
            let radiusPoints = 80.0
            layer.circleRadius = MGLStyleValue(rawValue: NSNumber(value: radiusPoints))
            layer.circleColor = MGLStyleValue(rawValue: UIColor.gray)
            layer.circleOpacity = MGLStyleValue(rawValue: 0.5)
            style.addLayer(layer)
        }
    }
```

**Comment by boundsj** [comment]
Hi @evgzor. It sounds like you would like the changes that a draggable `MGLAnnotationView` makes to the `coordinate` in the `MGLPointAnnotation` it represents to automatically cause the `shape` in the source to be updated to reflect the latest value of the annotation's `coordinate`. 

The code you provided suggests how one might think this ought to work. Since the `MGLPointAnnotation` is passed directly to the `MGLShapeSource`, the source seems like it could keep a reference to and monitor the annotation (shape) and make the internal calls to the gl system that would actually update the shape on the map automatically. 

https://github.com/mapbox/mapbox-gl-native/issues/7458 tracks making the shape property of a source mutable. I don't think we were already discussing the feature you've described but I think we should keep this ticket open as a feature request. This does seem like it might be convenient for single points and maybe also other kinds of more complex shapes.

In the meantime, you should already be able to do what you are asking for here by observing the `coordinate` of the annotation that the `MGLAnnotationView` represents and mutating the shape property of the `MGLShapeSource` when the coordinate changes. You will need to set the source's shape property to a new `MGLPointAnnotation` each time the annotation coordinate is updated. Also, since it appears you are using annotation views (`MGLAnnotationView` is the only class that has a `draggable` API) you might consider using a more complex MGLAnnotationView to get the effect you are looking for if doing the extra work to connect the native view and the style layer seems like too much.

**Comment by staticdreams** [comment]
@boundsj , I'm trying to implement what you're suggesting by observing ``MGLPointAnnotation`` coordinate changes and setting the ``MGLShapeSource`` shape coordinate to a new coordinate, but it seem to be read-only. Any suggestions?

<img width="861" alt="screen shot 2017-07-16 at 08 44 17" src="https://user-images.githubusercontent.com/988705/28245281-74c4840a-6a03-11e7-9b0f-9b185eafe560.png">

**Comment by boundsj** [comment]
Hi @staticdreams, I think I suggested setting the `shape` property itself. Have you tried that?

**Comment by staticdreams** [comment]
@boundsj Thank you Jesse, it seem to work :)
