### ISSUE TITLE
Inconsistent coordinate at different zoom level for the same feature

### ISSUE THREAD

**Issue by always-beta** [mapbox/mapbox-gl-native#8992]
**Platform:** iOS
**Mapbox SDK version:** 3.5.4

### Steps to trigger behavior

 1. Set to a smaller zoom 10, use visibleFeaturesInRect to extract a certain MGLFeature, check the coordinate.
 2. Set to a bigger zoom 20, use visibleFeaturesInRect to extract the same MGLFeature with step 1, check the coordinate.
 3. Compare the coordinate

### Expected behavior
Coordinates should be the same

### Actual behavior
Coordinates are slightly different

The problem I have is that when the user clicks a feature at small zoom, I add an annotation view which exactly matches the feature's view, and zoom in to 20, the annotation view now has a slight offset from the feature itself.

Coordinate at zoom 13:

<img width="384" alt="zoom 13" src="https://cloud.githubusercontent.com/assets/1987864/26031721/253a9b2e-38b0-11e7-82f1-09e6d17d5e4d.png">

Coordinate at zoom 20:
<img width="378" alt="zoom 20" src="https://cloud.githubusercontent.com/assets/1987864/26031724/401ac0ae-38b0-11e7-85a1-020e2239659a.png">

The offset caused:

<img width="160" alt="screen shot 2017-05-14 at 2 08 26 pm" src="https://cloud.githubusercontent.com/assets/1987864/26031726/486352e4-38b0-11e7-83f4-e7906205aa6e.png">

**Comment by fabian-guerra** [comment]
I'm working on a new implementation for the `coordinate` property. Need to test if this is fixed as a result of https://github.com/mapbox/mapbox-gl-native/pull/8713

**Comment by jfirebaugh** [comment]
This is expected behavior. To minimize their size, vector tiles use a quantized coordinate system that's precise enough for rendering a tile at the zoom level it's intended for, but not necessarily precise enough for higher zooms.

To place the MGLFeature precisely at all zoom levels, you should call visibleFeaturesInRect in response to zoom changes, and update the coordinate to match the response.
