### ISSUE TITLE
String localization does not work when using the static framework

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#9072]
Our replacement [`NSLocalizedString` methods](https://github.com/mapbox/mapbox-gl-native/blob/a19fd817300abf00b81cba5765fda62c48057efa/platform/darwin/src/NSBundle%2BMGLAdditions.h#L20) rely on [`+[NSBundle mgl_frameworkBundle]`](https://github.com/mapbox/mapbox-gl-native/blob/a19fd817300abf00b81cba5765fda62c48057efa/platform/darwin/src/NSBundle%2BMGLAdditions.m#L7) to provide the Mapbox bundle that contains the localizations.

When using the static Mapbox.framework:
1. Localizations live in a separate Mapbox.bundle.
2. `+[NSBundle mgl_frameworkBundle]` returns the app bundle (not Mapbox.framework or Mapbox.bundle).

This means that localizations never load because we’re looking for them in the base app bundle, not Mapbox.bundle.

(Mapbox.bundle has existed for static builds since https://github.com/mapbox/mapbox-gl-native/pull/4455.)

## Why do images and such work?
For other resources that we load from the bundle, like [images](https://github.com/mapbox/mapbox-gl-native/blob/a19fd817300abf00b81cba5765fda62c48057efa/platform/ios/src/MGLMapView.mm#L5294-L5297) or [SSL certificates](https://github.com/mapbox/mapbox-gl-native/blob/a19fd817300abf00b81cba5765fda62c48057efa/platform/ios/src/MGLAPIClient.m#L120), we manually append `Mapbox.bundle` to the path using [`-[NSBundle mgl_resourcesDirectory]`](https://github.com/mapbox/mapbox-gl-native/blob/a19fd817300abf00b81cba5765fda62c48057efa/platform/darwin/src/NSBundle%2BMGLAdditions.m#L35):

```objc
NSBundle *frameworkBundle = [NSBundle mgl_frameworkBundle];
NSString *resource = [frameworkBundle pathForResource:@"somefile"
                                               ofType:@"extension"
                                          inDirectory:frameworkBundle.mgl_resourcesDirectory];
[NSData dataWithContentsOfFile:resource];
```

This works, but seems like incorrect behavior: shouldn’t we be treating Mapbox.bundle as _the_ bundle and not just a directory?

/cc @boundsj @1ec5

**Comment by friedbunny** [comment]
Fixed by #9074, will be in v3.6.0-beta.1.

**Comment by dunqi** [comment]
So does localization no work with MapboxStatic?

**Comment by 1ec5** [comment]
@dunqi, this issue was tracking a bug affecting the localization of UI strings within the iOS map SDK, not map labels.

MapboxStatic.swift doesn’t have a `localizesLabels` option as the iOS map SDK does, but it does allow you to specify a custom style URL. In [Mapbox Studio](https://www.mapbox.com/studio/), create a new style based on one of the templates, then [change the language of each layer containing labels](https://www.mapbox.com/help/change-language/#change-label-language-in-mapbox-studio). Finally, click the “Share, develop & use” button to get the style URL that you can [set on SnapshotOptions](https://github.com/mapbox/MapboxStatic.swift/blob/a1474a2122c495c2a620e7e89869cdf00e2d0594/MapboxStatic/SnapshotOptions.swift#L267-L291).
