### ISSUE TITLE
Change FPS for iphone

### ISSUE THREAD

**Issue by krupin-maxim** [mapbox/mapbox-gl-native#9097]
Hello. Is it possibly to change FPS of mapbox on iphone? We need it in our project, because iphone 4s works with many lags. In particular, taps on mapbox have lags.

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. I assume by "change" you mean "limit to a maximum FPS". The iOS SDK does not expose a way to limit the maximum frame rate. It's unlikely that doing so would improve tap performance specifically, since frames are only rendered as needed. If you have specific performance concerns with tap operations, please open a performance-focused ticket, including profiling results from Instruments so we can make sure we're looking at the same data. Thanks!

**Comment by krupin-maxim** [comment]
Thank you for answer. But there is const that affect on FPS https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/src/MGLMapView.mm#L110 
Is it legally to make it as var and change it externally?

**Comment by mb12** [comment]
@krupin-maxim the reason you are perceiving lag on tap detection is because single tap detection needs to wait for double tap to fail before single tap event is emitted. Try disabling double tap gesture recognizer to see if it improves perceived single tap lag for you.
