### ISSUE TITLE
Attempt to always load fresh traffic tiles

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-native#9103]
**Platform: iOS (although applicable to all)**
**Mapbox SDK version: v3.5.4**

### Steps to trigger behavior

 1. Add a style (traffic-day-v2)
 2. Move map around, cache tiles
 3. Close app for a little
 4. Open app
 5. Zoom around

### Expected behavior

Traffic map data between zoom levels is smooth and constant.

### Actual behavior

Traffic map data between zoom level is inconsonant. One zoom level could be green, while the next adjacent zoom level is red.

### Proposal

If the user has a healthy network, we attempt to load traffic tiles over the network versus by reaching into the tile cache.

![untitled](https://cloud.githubusercontent.com/assets/1058624/26418890/be5b7caa-4072-11e7-8f36-33ce6265614c.gif)

/cc @1ec5 @tcql @nickidlugash

**Comment by jfirebaugh** [comment]
Tiles are refreshed according to the caching headers in the response. Are you sure it's not loading new tiles? How long is "for a little"? What's the max-age of the traffic tiles?

**Comment by bsudekum** [comment]
> Are you sure it's not loading new tiles?

Unsure, hard knowing by just looking at the app/gif above. I'm just trying to prevent a different congestion level loaded for the same road in between zoom levels. 

> How long is "for a little"? 

I think the gif above is about 10m of inactivity.

> What's the max-age of the traffic tiles?

`Cache-Control:max-age=60,s-maxage=0`

**Comment by bsudekum** [comment]
![](https://user-images.githubusercontent.com/1058624/27880043-75821846-6178-11e7-9246-f3e233b63482.gif)

Note, these tiles were requested ~2 days ago. I'm doing this in airplane mode to show the error happening but perhaps there is logic in place that pulls tiles from the cache not matter the max-age if there is no connection?

**Comment by willwhite** [comment]
> > What's the max-age of the traffic tiles?

> `Cache-Control:max-age=60,s-maxage=0`

Traffic tiles don't have `Cache-Control` header. @bsudekum where were you seeing this set? Traffic tiles use an `Expires` header.

```
curl -I "https://api.mapbox.com/v4/mapbox.mapbox-traffic-v1/9/81/198.vector.pbf?access_token=pk.eyJ1Ijoid2lsbHdoaXRlIiwiYSI6ImNpamV3dTdhbTAwMTB0Zm01MGY1OGRtaDIifQ.NkgyaKN3zpCZ8jRZ0Zjfjg"
HTTP/1.1 200 OK
Content-Type: application/x-protobuf
Content-Length: 6584
Connection: keep-alive
Date: Fri, 21 Jul 2017 02:09:46 GMT
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET
Timing-Allow-Origin: *
X-Rate-Limit-Limit: 100000
X-Rate-Limit-Interval: 60
X-Rate-Limit-Reset: 1500603046
Content-Encoding: gzip
Last-Modified: Fri, 21 Jul 2017 02:08:16 GMT
ETag: "3f5d37bb22f843507e5ce01b3e366be9"
Expires: Fri, 21 Jul 2017 02:15:09 GMT
X-Cache: Miss from cloudfront
Via: 1.1 33b747b33fddb3c7992b56d0e5e55d38.cloudfront.net (CloudFront)
X-Amz-Cf-Id: eNqV5V6iUnHTIpIxKcqcSNcEU9vV4AhRuoopC64hgKa45wwIV-fDfQ==
```

The headers related to cached are `Expires`, `Last-Modified`, and `ETag`. I believe mapbox-gl-native respects `Expires` - I'm not sure if it does conditional GETs using `Last-Modified` or `If-None-Match`.

Ideally, mapbox-gl-native wouldn't display expired content at all - even if the connection is unstable.

**Comment by tcql** [comment]
> where were you seeing this set?

it's what was [set in the tilejson](https://github.com/mapbox/mapbox-machine-maps/blob/5309cf595b6bf56187c8eb1874d9b68dc599118d/lib/mapbox.mapbox-traffic-v1.json#L13) and what `@mapbox get-map-cacheControl mapbox.mapbox-traffic-v1` reports

**Comment by willwhite** [comment]
At the map server level, we ignore tilejson and get-map-cacheControl settings and don't set `Cache-Control` headers when the individual tiles have Expires headers (which are set by our traffic map rendering pipeline). That's how we end up with headers that look like the above.

@jfirebaugh @kkaefer are you seeing anything about how mapbox-gl-native handles the `Expires` header that could cause this? I know we did a lot of work around respecting this header (including refreshing content when expiration is hit even if the map is just sitting open).

**Comment by kkaefer** [comment]
Mapbox GL handles both, `ETag`, and `Expires` headers. However, [we always prefer `ETag` when it is available](https://github.com/mapbox/mapbox-gl-native/blob/b83d79708185f0d8def1d3638fcc702305cd3fab/platform/darwin/src/http_file_source.mm#L213-L219), and only use `If-Modified-Since` when there is no `ETag`.

When parsing response headers, we prefer an explicit `Expires` header over the `Cache-Control` header, and we always parse the `ETag` when available.

The default caching behavior is to return expired tiles if we can find them in the cache. If we load an expired tile, we also create a conditional HTTP request to the server to get fresh data. However, we *also* start parsing the expired tile. This explains why we're seeing stale data; it's being displayed as a last resort until the new data has been loaded. We're doing this so that Mapbox GL can operate in offline mode when we can't connect to the server to ask for fresh data.

It seems like we need an alternate way of handling time-sensitive data: For that kind of data, we would never return expired data, and only use fresh data. I think there are two ways to implement this:

* We could come up with a certain combination of HTTP response headers, e.g. no `ETag`, absolute expiry time via `Expires` and `Cache-Control: must-revalidate` to prevent use of stale resources (looks like this is even HTTP standards compliant)
* A setting in our source/TileJSON that indicates that this source shouldn't use stale data from the cache.

**Comment by willwhite** [comment]
> We could come up with a certain combination of HTTP response headers, e.g. no ETag, absolute expiry time via Expires and Cache-Control: must-revalidate to prevent use of stale resources (looks like this is even HTTP standards compliant)

We could try setting `Cache-Control: must-revalidate` pretty easily. _Not_ setting an ETag is a little more difficult. Would that be a requirement?

Just to capture some demos of the behavior:

As you zoom around the map there is a delay where old data (potentially very old) is displayed for anywhere between a few moments to many seconds - I counted up to 30 seconds on a weak 4G connection.

![lag2](https://user-images.githubusercontent.com/93564/28502827-18252fd0-6fc9-11e7-97a7-cacea52d3127.gif)

![lag3](https://user-images.githubusercontent.com/93564/28502863-8d2e1968-6fc9-11e7-99ec-e4e1ff013b5d.gif)

![lag4](https://user-images.githubusercontent.com/93564/28502873-a4f4db04-6fc9-11e7-9481-e27a56aeee90.gif)

![lag5](https://user-images.githubusercontent.com/93564/28502892-e5e97778-6fc9-11e7-8908-41aecfbfb10c.gif)

**Comment by willwhite** [comment]
Also want to note that rapidly zooming in an out (e.g. the kind of thing you do when you try to replicate this kind of issue) appears to make it worse (perhaps because it's rapidly queuing up / canceling tile requests?) and there have been a few times where I've managed to get my map stuck in an inconsistent state for an extended period of time (minutes).

**Comment by kkaefer** [comment]
> We could try setting `Cache-Control: must-revalidate` pretty easily. Not setting an `ETag` is a little more difficult. Would that be a requirement?

Ah, I think `ETag` doesn't matter, since that only controls freshness matching rather than expiration date. Note that support for `Cache-Control: must-revalidate` isn't implemented yet.
