### ISSUE TITLE
Provide fallback to rotation vector sensor missing

### ISSUE THREAD

**Issue by mpetroff** [mapbox/mapbox-gl-native#9149]
**Platform:** Android
**Mapbox SDK version:** 5cf0fc0f8bb3f66fd7844cae73efca1a4c2d94f5

### Steps to trigger behavior

 1. Open user tracking mode example in SDK test app
 2. Set bearing mode to either GPS bearing or compass bearing

### Expected behavior

View tracks bearing, and arrow appears above user location marker as in the screenshots in https://github.com/mapbox/mapbox-gl-native/issues/8238#issuecomment-283681408.

### Actual behavior

The bearing mode settings doesn't appear to do anything.

![device-2017-05-30-190421](https://cloud.githubusercontent.com/assets/1450212/26608955/5a18421a-456c-11e7-8d7d-79857ab6e80b.png)

I've tested it in an Android 7.1 emulator and on a Moto G running Android 5.1. I know it worked in version 4.0 of the SDK.

**Comment by tobrun** [comment]
@mpetroff thank you for reaching out, we changed the way the compass sensor works in https://github.com/mapbox/mapbox-gl-native/pull/5877. Instead of using the low level sensors, we are using [TYPE_ROTATION_VECTOR](https://developer.android.com/reference/android/hardware/Sensor.html#TYPE_ROTATION_VECTOR). This uses sensor fusion to provide better results. 

I debugged this on a Samsung J3 and was seeing that the sensor is null and not available and thus can't show the bearing (note that Google Maps isn't showing the bearing either for this device). I've ran this on a LG-v500 and I'm seeing the bearing correctly.

**Comment by mpetroff** [comment]
The Moto G in question doesn't have a gyroscope, which appears to be required for Android's rotation vector sensor, so this explains why it no longer works; I had looked through the release notes and didn't find anything, so thanks for pointing out the change. Google Maps shows the bearing just fine, since the phone does have a magnetometer; the Samsung J3 you mention doesn't have a magnetometer, so there's no way for it to measure the bearing.

For phones that support it, using the rotation vector sensor is a definite improvement, since sensor fusion with the gyroscope stabilizes the bearing measurement. However, many low-end Android phones don't have gyroscopes, so I consider this change to be a regression. Would it be possible to fall-back to the old behavior, which only uses the accelerometer and magnetometer, when the rotation vector sensor isn't available but a magnetometer is?

**Comment by tobrun** [comment]
Continuing this work in https://github.com/mapbox/mapbox-plugins-android/issues/82, MyLocationView is going to be replaced with the LocationLayer plugin.
