### ISSUE TITLE
Apply text-keep-upright after text-offset

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-native#9180]
**Platform:** Mapbox Raster Tiles API?
**Mapbox SDK version:**

equivalent of https://github.com/mapbox/mapbox-gl-js/issues/2350

**Comment by jfirebaugh** [comment]
@ansis @ChrisLoer Was this included in recent text rendering PRs?

**Comment by ChrisLoer** [comment]
@jfirebaugh Yeah, it should be handled here:

https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/layout/symbol_projection.cpp#L200

I tested the JS version with @andrewharvey 's jsbin: http://jsbin.com/danexuj/1/edit?html,output. The actual `text-offset` now works "as expected" (i.e. applied relative to line, not based on text direction). But the original example was actually using `text-anchor: bottom` instead of `text-offset`, which still behaves the same as before. Should it? It seems to me that it makes more sense for `text-anchor` to be based off of text direction.

**Comment by ChrisLoer** [comment]
PR to enable the test on native: https://github.com/mapbox/mapbox-gl-native/pull/9580
