### ISSUE TITLE
MGLMapView does not make efficient use of memory

### ISSUE THREAD

**Issue by ianthetechie** [mapbox/mapbox-gl-native#9203]
**Platform:** iOS
**Mapbox SDK version:** 3.5.4

### Steps to trigger behavior

 1. Create a view controller with an `MGLMapView`
 2. Create another view controller that also contains an` MGLMapView` and push it onto the navigation stack (or whatever your favorite method is of adding views; the main point being that you now have 2 `MGLMapView`s in memory)

### Expected behavior

The memory impact of adding a new `MGLMapView` should be minimal, as it is with Apple's `MKMapView`. While this may be tricky to handle automatically at first, a relatively neutral memory footprint should at least be attainable by some action less drastic than destroying the map view. For example, by exposing some methods that let you clean up memory used by the map view manually in a view controller segue method.

### Actual behavior

Memory usage increases significantly for each instantiated `MGLMapView`. On a device with less RAM, this frequently causes out of memory terminations once the app has 2 or 3 map views in memory.

### Remedies attempted

I have attempted to remove all sources and layers (I only had some simple pins and 1 layer of boundary overlays in this example) from the map style when the view disappears, but this only puts a small dent in memory usage. Other attempts included calling the deprecated `emptyMemoryCache` function, removing the map view from it's superview, and switching to a "simpler" style.

The only way to keep memory usage in check when pushing a new view controller is to completely destroy the map view from the previous view. This was not necessary with MapKit, and is not a sustainable development pattern.

### Additional commentary

In informal testing, it seems as if data is not being shared across map views. If it is, then it is not readily apparent. Using a shared cache or something across instances seems like an elegant way to solve this issue, but I understand that may be rather complex. This could potentially solve both the issue at hand and improve performance.

**Comment by ianthetechie** [comment]
Please let me know if there's any specific information you need from me.

**Comment by ianthetechie** [comment]
Our present hack, which seems to work reasonably well, is to stash the `superview`, `delegate`, `styleURL`, `annotations`, and `camera` properties when the containing view controller disappears (in `viewDidDisappear(_:)`. Then we remove the map view from it's superview and any other references so it is deallocated.

As this occurs across a number of views in our app, we've bundled most of this logic into a class, created a new base class for most of our view controllers, etc. I realize that a fix may be a while in coming, but if anyone knows of any other properties that contain relevant map view state, I'd love to hear them. These are the ones that we found through trial and error worked reasonably well for our app.

One thing to note about this approach is that reloading is not instant. There is a flicker while the style and any tiles are reloaded. It doesn't appear that there is any way to persist and then restore a style, complete with layers, sources, etc. I understand this is a reasonably complex thing to do, but for anyone reading this, make sure you do as much of your configuration as possible in `mapView(_:, didFinishLoading:)`, and things should come back as you left them.

**Comment by dr-falsch** [comment]
Hello ianthetechie,

do you have a working code example for your work-a-round?

Because I tried the following (worked with Google Maps), but it has no effect:

```
override func viewDidDisappear( _ animated: Bool ) {
  mapView.removeAnnotations( annotations )
  mapView.showsUserLocation = false
  mapView.delegate = nil
  mapView.removeFromSuperview()
}
```

Thank you very much!

**Comment by dr-falsch** [comment]
The only thing that helps a little bit is removing old ViewControllers using Mapbox, like this:

```
override func viewDidLoad() {
  super.viewDidLoad()
  
  // delete old MapsVC from navigation stack
  if let nav = self.navigationController {
    var stack = nav.viewControllers
    
    var indexToDelete : Int?
    for i in 0..<stack.count - 1 {
      if let actVC = stack[i] as? MapsTabBarController {
        if actVC.selectedViewController is MapsVC {
          indexToDelete = i
        }
      }
    }
    if let i = indexToDelete {
      stack.remove( at: i )
    }
    nav.setViewControllers( stack, animated: false )
  }
}
```

Strangely it doesn't free as much RAM as going back via the navigation controller.

**Comment by CodeKunal** [comment]
`override func viewDidDisappear( _ animated: Bool ) {
    mapView = nil
}`

Just making mapView nil seems to improve performance.

**Comment by ChrisLoer** [comment]
PR #11197 makes some improvements that are related to this issue, in that it will significantly reduce how much memory an app with multiple map views will use when it goes into the background. However, it doesn't do anything to make multiple map views actually share memory, as suggested here.

The straightforward implementation of memory sharing between map views would depend on both maps using exactly the same style -- and I _think_ that assumption would be too frequently violated to make the feature worthwhile. I think to do a good job of this, we'd need to change our in-memory caching architecture from being tile-based to being bucket-based (a "bucket" is basically one layer/one tile). In that case, maps with slightly different styles but showing the same tiles could share the bulk of their memory.

If the maps are showing different tiles, there's not going to be a lot that's useful to share between them. I don't know how `MKMapView` behaves in that case. We want to keep at least the currently rendering tiles for each map in memory so that we can render immediately if the map is displayed. Otherwise you get that little bit of flicker you mention in https://github.com/mapbox/mapbox-gl-native/issues/9203#issuecomment-307607167. There might be something else we could do to store ready-to-render buckets on disk instead of in-memory but that'd be a whole different feature.

**Comment by ChrisLoer** [comment]
> Am I correct in thinking the changes in PR #11197 purge unused tiles down to a reasonable level in the event of a low memory notification? The "out of viewport" tiles in each map view, for example?

Close -- we actually purge "out of viewport" tiles as soon as we go into the background, instead of waiting for a "low memory" notification before releasing them. The reason we do it _before_ getting a low memory event is that on iOS we can't actually release GPU memory while we're in the background.
