### ISSUE TITLE
LatLngBounds Camera Update not working when Padding is set to MapView

### ISSUE THREAD

**Issue by neo17** [mapbox/mapbox-gl-native#9217]
### Steps to trigger behavior
The bug is similar to the #5034
 1. Set Padding to Map
 2. Draw polyline in the map
 3. Use polyilne list of coordinates for calculating CameraUpdate with new LatLngBounds. 

### Expected behavior
Camera update would center the polyline bounds to the area specified by the padding. 

### Actual behavior
Camera update does not respect the padding set in the MapView and zooms to the bounds as if the paddings are not set. You can see the [video here](https://youtu.be/YO6NU2afNsc) and also check out a sample project that reproduces the bug [here.](https://drive.google.com/open?id=0B79Z0XQ1O6BdbXpGaXNFUWt4blU)

**Comment by tobrun** [comment]
With the upcoming 5.1.0 release we have changed the way we handle LatLngBounds in https://github.com/mapbox/mapbox-gl-native/pull/8765. Feel free to test out the SNAPSHOT or any of the beta releases. More information on those [here](https://www.mapbox.com/android-sdk/). 

For reference: no map or latlngbounds padding:
![0padding](https://user-images.githubusercontent.com/2151639/26923453-6ce7c4c4-4c42-11e7-98cc-bb7195eb1864.png)

Map padding, no latlngbounds padding:
![device-2017-06-08-120240](https://user-images.githubusercontent.com/2151639/26923456-7044fbc8-4c42-11e7-910a-41402c4c0583.png)

Map and latlngbounds padding:
![device-2017-06-08-120342](https://user-images.githubusercontent.com/2151639/26923493-893c03c4-4c42-11e7-8b07-90ce3bd120a1.png)

Thank you for reaching out but closing this as resolved.

**Comment by neo17** [comment]
The bug is still present even at 5.1.0-beta.3 release. You can simply use the same sample project and update to 5.1.0-beta.3 and you will notice that the `CameraUpdateFactory.newLatLngBounds` will not animate to the center of the MapView by respecting specified padding, but instead is pushed upwards. @tobrun 
![zoomtobound](https://user-images.githubusercontent.com/5824180/26932150-f1b2c3dc-4c62-11e7-8c6e-3bbf7492bde2.png)

**Comment by tobrun** [comment]
I think we should add some additions to the javadoc as there is some misunderstanding about the padding parameter. Instead of general padding this is the minimum additional space around the bounds. The padding is only getting applied if the given bounds doesn't already have a larger bounds. Take for example Iceland with no padding:
<img width="291" alt="screen shot 2017-06-20 at 16 38 07" src="https://user-images.githubusercontent.com/2151639/27339267-9e4d70c4-55d7-11e7-9540-0457f9541519.png">

Take again Iceland but this time with padding:
<img width="369" alt="screen shot 2017-06-20 at 16 10 44" src="https://user-images.githubusercontent.com/2151639/27339272-a17abf90-55d7-11e7-9310-dfe8df62ea2a.png">

This is identical as before but if you rotate the device you can see the padding working:
<img width="482" alt="screen shot 2017-06-20 at 16 38 48" src="https://user-images.githubusercontent.com/2151639/27339281-a939b9c0-55d7-11e7-96dd-85043b22993a.png">

This is how this is currently implemented in the public API. You should be able to your expected use-case working by calculating the LatLng object yourself through Projection.java. Calling this a work as designed. closing.

**Comment by mdakram** [comment]
One very weird issue i found with CameraUpdate with new LatLngBounds it shifts your mapbox logo which it should not.
