### ISSUE TITLE
Callout View Jumping When Panning/Zooming

### ISSUE THREAD

**Issue by Kayeee** [mapbox/mapbox-gl-native#9228]
**Platform: iOS**
**Mapbox SDK version: 3.5**

### Steps to trigger behavior

 1. Make a custom Callout View using MGLCalloutView
 2. set dismissesAutomatically: Bool = false
 3. set isAnchoredToAnnotation: Bool = true

### Expected behavior
Callout will stay above annotation and follow it while panning.

![screen shot 2017-06-05 at 5 40 44 pm](https://user-images.githubusercontent.com/11282972/26958783-659631d0-4c81-11e7-8d54-cb14c7e89f5f.png)

### Actual behavior
Callout drops down about 20 pixels and covers annotation when panning begins.

![screen shot 2017-06-05 at 5 40 51 pm](https://user-images.githubusercontent.com/11282972/26958785-6790991c-4c81-11e7-9fe6-fc769d537f20.png)

I followed the tutorial [here:](https://www.mapbox.com/ios-sdk/examples/custom-callout/
 ) and only added the dismissesAutomatically and isAnchoredToAnnotation variables. I tried setting the center of the callout view, but that didn't seem to do anything either. I also asked [SO](https://stackoverflow.com/questions/44379788/mapbox-callout-moving-on-pan-zoom), but still no luck.

**Comment by friedbunny** [comment]
Per the docs for `-[MGLCalloutView.anchoredToAnnotation]`:

> You can adjust the callout view’s precise location by overriding `-[UIView setCenter:]`.

Overriding `setCenter:` in your custom callout view appears to be necessary, otherwise the callout changes position. [You can see an example implementation here.](https://github.com/mapbox/mapbox-gl-native/blob/ios-v3.6.1/platform/ios/app/MBXCustomCalloutView.m#L71-L74)

This seems like something we should try handle automatically in most cases, I don’t know why it was implemented this way.

/cc @frederoni

**Comment by frederoni** [comment]
My hunch is that the bottom arrow is out of bounds.

Overriding `setCenter:` for custom callout views should work as intended but bottom center should work by default as long as the frame corresponds to the actual bounds.

**Comment by friedbunny** [comment]
> My hunch is that the bottom arrow is out of bounds.

In the callout view example that this issue is based on, the bounds and frame are the same size and the arrow is within them.

Here are the changes to that example that needed to be made to support “sticky” callouts: https://github.com/mapbox/ios-sdk-examples/pull/108/commits/405b4914a23684b4b3fdeb5667180335bc8a514b

**Comment by Kayeee** [comment]
Just noticed this was still open. [Merge #108](https://github.com/mapbox/ios-sdk-examples/pull/108) fixed it. Thanks!
