### ISSUE TITLE
Overlapping Fragments each containing MapViews 

### ISSUE THREAD

**Issue by premisedata-coverage** [mapbox/mapbox-gl-native#9358]
In my android app, I have a mapView in a fragment and if an informational drawer is pulled over the fragment containing a second mapView the first mapView tiles show instead of the mapView in the drawer. It looks like this is caused from the use of SurfaceView with out z-index being set.

![screen shot 2017-06-23 at 1 55 22 pm](https://user-images.githubusercontent.com/23178765/27500215-54bcf776-581c-11e7-865d-2103895c46b2.png)

Note the tiles that are rendered above the ToolBar are correct. Just those above the other MapView are incorrect.

**Platform:** android
**Mapbox SDK version:** 5.0.2

### Steps to trigger behavior

 1. Place a fragment that contains a fullscreen mapView in it.
 2. Open a drawer or DialogFragment containing a second MapView
 3. Ensure the second MapView is placed on top of the first MapView

### Expected behavior
The second MapView shows the correct tiles

### Actual behavior
The second MapView shows the tiles from the underlying first MapView

**Comment by tobrun** [comment]
@premisedata-coverage the issue here is that the overlapping SurfaceViews are fighting for the z order and the underlying surfaceview wins. There are two workarounds:
 - Make the navigation drawer use a texture view (this can be enabled through xml or MapboxMapOptions)
 - Zet Z order on top for the surfaceview in the navigation drawer by `(SurfaceView) mapview.findViewById(R.id.surfaceView)).setZorderOnTop(true)`

For the use-case shown above, I would advice you to show a bitmap of Map instead. This will result in best performance and afaik you don't need an interactive map in that location. You can get bitmap from our static API services.

**Comment by hp-harsh** [comment]
@tobrun
I am facing the same issue while adding a Fragment. To cope up with my functionality I must have to add Fragment instead of replacing one. Do you any hack or idea to deal with this issue?

I have tried both solutions.

Thanks.
