### ISSUE TITLE
Padding can only be set once

### ISSUE THREAD

**Issue by johanneslaubermoovel** [mapbox/mapbox-gl-native#9379]
**Platform:** Android
**Mapbox SDK version:** 5.1.0-beta.3

### Steps to trigger behavior
 map.setPadding(0, 0, 0, 200)
 map.setPadding(0, 0, 0, 200)

### Expected behavior
calling setPadding twice should still have 200px padding on the bottom

### Actual behavior
bottom padding is 400px in the ui although call map.getPadding is returning 200px bottom padding

Once padding is set, it can't be removed from the map anymore. In my case I have a bottom sheet, if I expand or collapse it I have to change the bottom padding.

**Comment by tobrun** [comment]
Validated that this is reproducible and identified that this issue is related to UiSettings.java where we're adding/removing padding based on previous value. Instead of the previous value we should keep reference to the initial value and apply padding on that instead. 

As workaround for now you can do the following:

```java
map.setPadding(0, 0, 0, 200)
map.setPadding(0, 0, 0, -200)
map.setPadding(0, 0, 0, 200)
```
to get the same padding as you had initially.
