### ISSUE TITLE
[Android] Unusable map on Genymotion.

### ISSUE THREAD

**Issue by mayardb** [mapbox/mapbox-gl-native#9506]
**Platform:** Genymotion emulator (Google Nexus 6 - API 23)
**Mapbox SDK version:** 5.1.0

### Steps to trigger behavior
 1. starts the Simple Map Sample
 2. Try to move or zoom.

### Expected behavior
No freeze, no lag.

### Actual behavior
Map is not usable.

I think it mays be link to the processor architecture (x86-64).

**Comment by tobrun** [comment]
@mayardb thank you for the report. I believe it's not related to the ABI itself but more related to virtualisation of genymotion and how it hooks into the host GPU. Since the latest years the performance of genymotion has started to degrade and with the rise of performant official Android SDK emulators, I don't feel support for Genymotion is high a priority for us right now. Closing, will reopen if this changes.

**Comment by TranThuong** [comment]
Hello
Our project can't update to the MapBox V5.1 or higher because the performance on the Genymotion emulator. 

In fact if we compile the `mapbox-gl-native` from github and launch the `MapboxGLAndroidSDKTestApp` from Android Studio, we have the performance problem on the Genymotion emulator. 

However if we use your compiled version as below, we can launch the application from android studio on the Genymotion Emulator, there isn't any performance issue.

compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.2@aar') {
        transitive=true
 }

We compile the `mapbox-gl-native` from github on iMac. 
Could you please let me know there was any configuration special if we compile the `mapbox-gl-native` from iMac. Noted that we didn't have this performance problem on Genymotion until the version 5.1
