### ISSUE TITLE
queryRenderedFeatures returns wrong feature ID

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#9523]
When querying rendered features and then calling `feature.getId()` the number returned should match up with the OSM ID for that specific OSM geometry (`node`, `way`, or `relation`) but the ID seems to always add one digit to the end of the ID which makes it invalid. For example, clicking a specific point returns the id `670863441` which [doesn't have a match on OSM](http://www.openstreetmap.org/way/670863441) but [`67086344`](http://www.openstreetmap.org/way/67086344) does. 

cc: @ivovandongen @tobrun @zugaldia

**Comment by tobrun** [comment]
Don't think this is a bug. I remember @1ec5 talking about needing to do a conversion to get the correct id. Can you speak more to this @1ec5?

**Comment by 1ec5** [comment]
This is by design: see the [Mapbox Streets source documentation](https://www.mapbox.com/vector-tiles/mapbox-streets-v7/#overview), specifically the section on “OSM IDs”. Note in particular that certain features like buildings and divided highways may be unioned together into multipolygons and multilinestrings, respectively.

**Comment by cammace** [comment]
Today I learned we have documentation about our map sources... Thanks.
