### ISSUE TITLE
GlyphAtlas needs a better way to keep track of tiles

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#957]
The GlyphAtlas currently tracks glyphs by tile ID and removes the glyph if no tile exists that uses the glyph anymore. However, there can be multiple tiles with the same ID, but from different sources. Instead of tracking per ID, we should e.g. use the TileData pointer as a key.

**Comment by ansis** [comment]
A part of the problem in #832 might be that the glyph atlas isn't properly cleaned up when sources are destroyed. In -js, GlyphAtlas is now part of the Style object, so whenever the style changes the atlas is blown away and we start from scratch.

**Comment by incanus** [comment]
If I'm understanding correctly from https://github.com/mapbox/mapbox-gl-native/issues/832#issuecomment-77624088, the GlyphAtlas could be garbling text because of this. This seems to be in effect anytime there is more than one vector source, which is impacting https://github.com/mapbox/mapbox-gl-native/issues/893 annotations as well. 

Adding to iOS beta milestone.

**Comment by incanus** [comment]
Keeping this on beta 1 milestone. @jfirebaugh I know you're gonna take a look — this is top of my list for blocking annotations right now.

**Comment by jfirebaugh** [comment]
⇢ #995
