### ISSUE TITLE
Transifex missing translations, replace curvy quotes

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#9629]
Lint  complains about:

![image](https://user-images.githubusercontent.com/2151639/28664512-08b5f61a-72c1-11e7-9572-c776c7a5641c.png)

This should be fixed upstream in the [Transifex project](https://www.transifex.com/mapbox/mapbox-gl-native). For now we will be ignoring these warnings.

**Comment by 1ec5** [comment]
@tobrun, feel free to curl the Catalan quotes directly in Transifex. I’ve done that for several localizations myself.

The warnings about incomplete translations are because Transifex has an old copy of strings.xml. In https://github.com/mapbox/mapbox-gl-native/issues/8641#issuecomment-291861454, you disabled Transifex’s auto-updating feature, so we need to manually upload strings.xml to Transifex any time a string is added or modified in master.

**Comment by 1ec5** [comment]
#9945 will probably add more warnings to the mix until we set up autoupdating.

**Comment by langsmith** [comment]
Just ran `make android-lint-sdk` . 

The curvy quote complaint doesn't seem to exist anymore.

<img width="982" alt="Screen Shot 2019-03-12 at 3 47 33 PM" src="https://user-images.githubusercontent.com/4394910/54241466-41454d00-44de-11e9-9897-951c594543d3.png">


I went into Transifex and that particular translation _does_ seem to be using a curly quote now .

<img width="1278" alt="Screen Shot 2019-03-12 at 3 46 35 PM" src="https://user-images.githubusercontent.com/4394910/54241499-5de18500-44de-11e9-9f84-014b8fdada21.png">

**Comment by langsmith** [comment]
Incomplete translation doesn't seem to be an issue anymore either. Or am I looking in the wrong place? Ticket can be closed?

**Comment by langsmith** [comment]
Screenshot above was the lint check report for the Maps SDK . Below is for the Maps SDK Android test app


<img width="767" alt="Screen Shot 2019-03-12 at 3 55 04 PM" src="https://user-images.githubusercontent.com/4394910/54241760-4bb41680-44df-11e9-966b-314d1e2e2c43.png">

<img width="643" alt="Screen Shot 2019-03-12 at 3 55 08 PM" src="https://user-images.githubusercontent.com/4394910/54241766-5078ca80-44df-11e9-83de-599f5d1b0c46.png">
