### ISSUE TITLE
Incorrect zoom level after entering course tracking on viewDidLoad without animation

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-native#9637]
**Platform: iOS**
**Mapbox SDK version: iOS SDK >= v3.5**

### Steps to trigger behavior

 1. In `viewDidLoad` set `mapView.setUserTrackingMode(.followWithCourse, animated: false)`
 2. Run app

### Expected behavior

Map opens at users location

### Actual behavior

Map stutters at zoom 0

![untitled](https://user-images.githubusercontent.com/1058624/28693577-3326e544-72da-11e7-902b-70dfcc0695f4.gif)

/cc @1ec5

**Comment by 1ec5** [comment]
The screen recording above shows what happens if the map view starts at the default position (Null Island) and zoom level (z0). At z0, changes to the camera’s center latitude have no effect because the latitude is constrained. Therefore, the user puck floats in an incorrect location, as originally reported in #4781. Disabling animation when entering course tracking (or user tracking in general?) skips the initial flight animation that would increase the zoom level to z14, at which point the latitude constraints would have no effect on the camera.

We could reapply a sensible zoom level on each location update to fix the most egregious symptom of this issue. However, that would cause a flight animation on the first location update – the very animation that setting `animation` to `false` is supposed to skip. So if the initial animation is disabled, we should call `-setCamera:…` with the same camera that we pass into `-flyToCamera:…`.
