### ISSUE TITLE
terrain style

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#964]
Let's track progress on vector-only terrain style here. 

Carrying over @jfirebaugh's last comment in #935: 

> The rendering errors (black labels, missing contours) are reproducible on any platform.
> 
> 9897ae7 fixes contour rendering. fddd27f fixes label rendering but I'm not sure if it's correct. @kkaefer?

**Comment by peterqliu** [comment]
First pass: hill shadows have an unintended hairline stroke on iOS

GL on desktop:

![screen shot 2015-03-12 at 1 40 22 pm](https://cloud.githubusercontent.com/assets/4551508/6627806/145c671a-c8be-11e4-8abc-ef1a1f67e9ea.png)

iOS:

![screen shot 2015-03-12 at 1 42 28 pm](https://cloud.githubusercontent.com/assets/4551508/6627815/1ca1c28a-c8be-11e4-87f2-21d30c095569.png)

Terrain also looks blockier overall, but that might be because of the stroke's emphasis

**Comment by peterqliu** [comment]
@incanus wanna dig in on ^ ? it is the only bug I've found in iOS so far

**Comment by incanus** [comment]
Ah, sorry, didn't realize this was a renderer bug and not a design issue in progress. I can try to take a look but deep in some other areas, so we'll get it on the table at tomorrow's scrum.

**Comment by jfirebaugh** [comment]
I can look at this today.

**Comment by incanus** [comment]
Something to think about here is what marker we ship by default to work with this map style. For example, in our iOS SDK, if no options are specified, we use a blank, medium Maki marker tinted to the current view's `tintColor` (Apple's default view tint color is blue `#00faff`), looking like this: 

![](http://api.tiles.mapbox.com/v4/marker/pin-m+007aff.png?access_token=pk.eyJ1IjoianVzdGluIiwiYSI6Ijh1RmhSN2cifQ.-R7zSJ3glf2uXy5XzMWYnA)

The user can pass any size, Maki icon, and/color, but the point is annotations get a look by default. Should we just stick with this on top of Emerald?

**Comment by peterqliu** [comment]
@incanus let's use a dot by default:

<img src='https://api.tiles.mapbox.com/v4/marker/pin-l-circle+104e81@2x.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6IlhHVkZmaW8ifQ.hAMX5hSW-QnTeRCMAy9A8Q'>

**Comment by incanus** [comment]
Cool, @peterqliu can you throw a 1x and 2x of that into the style's sprite sheet? This will be how we need to distribute marker images for b1. Also we will need the originals, because if someone wants to create their own style or add any custom marker imagery of their own to this style, they will need to do it in the sprite sheet.

**Comment by jfirebaugh** [comment]
Hillshade seams:

![image](https://cloud.githubusercontent.com/assets/98601/6696098/d6ccdfb2-cca3-11e4-9c91-f0f3c3c8e249.png)

**Comment by ljbade** [comment]
@jfirebaugh also see https://github.com/mapbox/mapbox-gl-native/issues/889

**Comment by peterqliu** [comment]
iPhone 5 screenshot:

![img_1068](https://cloud.githubusercontent.com/assets/4551508/6760731/d8249a32-cf08-11e4-8d12-1ecab97db657.png)

**Comment by 1ec5** [comment]
@peterqliu I take it you have Emerald loading by default on your local checkout of this project, right? Once mapbox/mapbox-gl-styles#42 goes in, can you file a PR for that change?

**Comment by peterqliu** [comment]
@1ec5 https://github.com/mapbox/mapbox-gl-native/commit/a1a7ab62e176afb354109ba23360c668f84771e8

**Comment by 1ec5** [comment]
Thanks @peterqliu. I forgot to mention that mapbox/mapbox-gl-native is pegged to a specific commit in mapbox/mapbox-gl-styles, so we have to update that submodule each time you revise Emerald. I did that this time in 9ee8bac1fe420076772918a25ca24504fef798ff, but here’s how to do it in the future:

```bash
# in /path/to/my/checkouts/mapbox-gl-native/
cd styles/
git checkout mb-pages
git pull
cd -
git commit -am 'Updated to latest Emerald style'
git push
```

#1043 makes Emerald the default style. (Turns out a1a7ab62e176afb354109ba23360c668f84771e8 only made the test app say “Emerald” at launch but didn’t change the default. Sorry about that.)

**Comment by peterqliu** [comment]
thanks @1ec5 -- i see that commit changed the long string after `submodule commit`, but where did you get the string from?

**Comment by friedbunny** [comment]
Git sees that the submodule commit changed and automatically pushes that to the host repo, which I think is pretty clever. @1ec5 shortened it to `git commit -a`, but you could also do `git add styles` and then `git commit`.

**Comment by jfirebaugh** [comment]
Closing here, time to break out rendering issues in separate tickets.

#381 and #889 track the outline/seams issue.
