### ISSUE TITLE
sqliteVersionCheck breaks apps

### ISSUE THREAD

**Issue by donpark** [mapbox/mapbox-gl-native#968]
I had an app in Testflight that ran just fine on iOS 8.1 but crashes consistantly on launch after updating the phone (iPhone 6) to iOS 8.2 (released today). Rebuild the app (using XCode 6.2) fixed the crash but didn't offer any insight into why the app crashed (nothing in the logs). When I debugged the app in iOS 8.1 Simulator, I ran into `sqliteVersionCheck` exception. After commenting out the version check, app ran just fine.

This shouldn't happen if my app was using the custom built SQLite library so I think what happened was that the app ended up using system provided version somehow (still trying to figure it out) and iOS 8.2 has a different version of SQLite so this version check failed under two situations:

1. app built with iOS 8.1 SDK running on iOS 8.2 device/simulator.
2. app built with iOS 8.2 SDK running on iOS 8.1 device/simulator.

I don't know what the right thing to do is but it would help non-critical version checks resulted in mere warnings instead of exceptions.

**Comment by kkaefer** [comment]
What's happening is that iOS 8.2 updates the included SQLite version to 3.8.4 So far, iOS 7.0 up to iOS 8.1 consistently have used version 3.7.13. When compiling with the 8.2 SDK and running on 8.1 or below, this will result in the version check failing, the same thing will happen the other way around (running a pre SDK 8.2 build on a 8.2 device).

Unfortunately, SQLite doesn't seem to have an ABI compatibility guarantee. While it *seems* that no existing ABI changed, a few new ones have been added.

There are two ways out of this:

* We could ship with a **custom SQLite** build and link it into the library. However, we'd likely get symbol conflicts if consumers of this library link against the system sqlite, since we'll have the symbols statically linked into this library *and* dynamically loaded from the system library, which might produce other weird effects.
* Remove the version check and manually ensure that we're not using any interfaces that were introduced after 3.7.13. Not sure if there's an automated way of checking this. It looks like Apple's SQLite headers don't contain any ABI information/pragmas for this.

/cc @springmeyer

**Comment by mb12** [comment]
Can we just delete cache.db and recreate it if there is a version check mismatch?

**Comment by kkaefer** [comment]
This won't solve the problem because it's a problem of the library, not the database file

**Comment by donpark** [comment]
Whatever the right solution is, I have two observations to make:

1. Problems this version check address are **potential** problems.
2. Crashes this version check causes are **real** and happening **now** to all apps embedding mapbox-gl-native with the code.

**Comment by robipresotto** [comment]
Just set the library target for iOS8.2 and build it! 
Works like a charm!

**Comment by donpark** [comment]
@robipresotto you can either try running that same app on older iOS devices or, faster, read the description of this issue I wrote.

**Comment by dpletter** [comment]
We removed the version check in platform/default/sqlite3.cpp and tested our app in ios 8.2 and 8.1, and it works in both now.
