### ISSUE TITLE
mapView.viewFor annotation: MGLAnnotation) -> MGLAnnotationView? not called all the time

### ISSUE THREAD

**Issue by chc24** [mapbox/mapbox-gl-native#9703]
**Platform:** iOS 10.2.1
**Mapbox SDK version:** 3.5.4

### Steps to trigger behavior

 1. Add a small cluster of annotation's anywhere on the map, I started at zoom level 11. 
 2. Return a custom MGLAnnotationView with anything inside (a pin, or image of your choice)
 2. Set the center of the map to the cluster of the annotations
 3. Scroll the map off most of the pins, breakpoint on mapView.viewFor and notice that the delegate method is not triggered 100% of the time. 

### Expected behavior
mapView.viewFor always fires
### Actual behavior
mapView.viewFor only fires sometimes. I have a total of about ~100 pins for my situation and after the first time I add annotations (and those annotations get a view callback), I don't get a viewFor trigger when I scroll an annotation back onto the map.

**Comment by chc24** [comment]
I also noticed calling mapView.fly(to camera) causes viewFor to start being called every time again.

**Comment by boundsj** [comment]
It is expected that MGLMapViewDelegate's [-mapView:viewForAnnotation:](https://www.mapbox.com/ios-sdk/api/3.6.1/Protocols/MGLMapViewDelegate.html#/c:objc(pl)MGLMapViewDelegate(im)mapView:viewForAnnotation:) would not always be called if view reuse is used. It is only called when using view backed annotation and an annotation currently does not have a view (i.e. when an annotation is first added or when an annotation's view was reused for another annotation). You could consider using `MGLMapView.viewForAnnotation()` to obtain references to and update views for arbitrary annotations after they have been added to the map.

**Comment by boundsj** [comment]
Going to close this as expected behavior. Please feel free to reopen with more details about what you are trying to accomplish and if one of the other APIs that should return annotation views is not working correctly.

**Comment by chc24** [comment]
Thanks for the response @boundsj  - I understand that viewForAnnotation will be called when we're using view backed annotations (which I am), and the annotation currently doesn't have a view (first time load of views for new annotations). My question is that when one of these views is scrolled off the screen, and then back on, wouldn't viewForAnnotation trigger? My own expected behavior (always triggering) DOES happen **after** I use mapView.fly(to: MGLCamera), and does not trigger otherwise until the fly method happens. Just as a UITableViewCell will call cellForRow, I was expecting the view to be dequeue'd when the annotation should be visible again.

**Comment by boundsj** [comment]
> when one of these views is scrolled off the screen, and then back on, wouldn't viewForAnnotation trigger

Once annotations are added, `viewForAnnotation` is only called if an annotation that is in the viewport rect does not have a view associated with it. Annotations can lose their views when they are scrolled offscreen so that those views can be reused. However, when that happens is a function of how large the annotation view is, how far the view is scrolled offscreen, and if the view is in the process of animating or not. So, simply scrolling annotation views off and on screen again will not necessarily trigger `viewForAnnotation` if the scroll action does not go far enough to trigger the reuse queue for the view.

If `viewForAnnotation` is not called for an annotation that is in the viewport and has no view associated with it, that'd be a bug.
