### ISSUE TITLE
Selecting an off-screen annotation doesn't work

### ISSUE THREAD

**Issue by ivanmkc** [mapbox/mapbox-gl-native#9790]
**Platform:**
iOS 9
**Mapbox SDK version:**
3.6.1
### Steps to trigger behavior

 1. Plot a bunch of annotations
 2. Programmatically select an annotation that is far offscreen (if it's close and offscreen, selection seems to work)
3. Programatically call setCenter to pan the map to the annotation

### Expected behavior
1. The annotation selected should appear selected 
2. The mapView(_ mapView: MGLMapView, didSelect annotation: MGLAnnotation) delegate function of MGLMapViewDelegate should fire.

### Actual behavior
1 and 2 do not happen. Only when the annotation is very close by (even offscreen works sometimes)

**Comment by settl** [comment]
+1, I'm having the same issue. Do you have any plans to work on this?

**Comment by friedbunny** [comment]
Though I don’t recall the reasons (@boundjs and @1ec5 would know), not selecting off-screen annotations is [intentional](https://github.com/mapbox/mapbox-gl-native/blob/87348234d16915176fab313f0d3f2dae246216d9/platform/ios/src/MGLMapView.mm#L3848-L3853) and [documented](https://www.mapbox.com/ios-sdk/api/3.6.2/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(im)selectAnnotation:animated:):

> If the given annotation is not visible within the current viewport, this method has no effect.

**Comment by 1ec5** [comment]
It might make sense to change the behavior so that selecting an off-screen annotation moves the annotation into view, similar to calling `-[MGLMapView showAnnotation:]`. That is, the camera changes so that the annotation becomes visible at the same time it is selected. This wasn’t possible before #6676, because the annotation would immediately get deselected as soon as the camera moved. But now that we have the ability to keep the callout open, we could have off-screen selection work and solve #3249 at the same time.

**Comment by julianrex** [comment]
It only seems to be the `selectedAnnotations` property that checks for offscreen, `-selectAnnotation:animated:` does not. @1ec5 What was the reason for checking offscreen?

**Comment by 1ec5** [comment]
Not sure. It could be a remnant of a limitation that has since been fixed. I think we should try to match MapKit’s behavior in this regard if possible.
