### ISSUE TITLE
Native iOS API equivalent of addClass();

### ISSUE THREAD

**Issue by kristfal** [mapbox/mapbox-gl-native#983]
Hello,

first of all, this client has us really excited for the future of mobile maps, really looking forward to the beta release. 

A quick question:

We've been working with the javascript client so far (it is pretty awesome), and we're using different style classes, swapping between them on the fly with addClass(). Is the iOS native equivalent API call implemented, if so are they listed anywhere?

**Comment by friedbunny** [comment]
[This is what it looks like just now](https://github.com/mapbox/mapbox-gl-native/blob/2b6afe6a549284a862d0231653d2183d57a5b496/platform/ios/MGLMapView.mm#L1032-L1048), but I wouldn't expect that to necessarily stay as-is.

**Comment by incanus** [comment]
That model should stay relatively stable as our styles spec is built around the idea of classes for changes.

**Comment by jfirebaugh** [comment]
@incanus Is there a reason to use different method names than the native base library (`setAppliedStyleClasses` versus just `setClasses`)?

**Comment by incanus** [comment]
Originally something like `setClasses` on a map object felt weird, because of classes in the OOP sense. Getting `style` in there at least seemed wise since we were introducing new ideas of how a map could be affected.

**Comment by ljbade** [comment]
Hmm I am using the same method name on Android too.

`setClasses` does seem more concise and faster to type though. I can't see why people would mix up OOP classes and style classes because the concepts are so different

@bleege do you have an opinion?

**Comment by incanus** [comment]
I am seeing something in the middle more like `setStyleClasses`.

**Comment by 1ec5** [comment]
In Objective-C and Swift, `setClasses` looks like a setter for a `classes` property, which means `map.classes` and `map.class` return very different things. That’s confusing from a code reviewer standpoint.

**Comment by bleege** [comment]
> @bleege do you have an opinion?

I ALWAYS have opinions!  :-)

But seriously, I think @incanus and @1ec5  are right here.  `setClasses` on it's own seems to me like something that is related to OS level objects like on `NSObject` or `java.lang.Object` rather than something one would expect to see and use in a Map SDK.  I'd be happy with `setStyleClasses` or something like `setMapStyleClasses` just to drive the point home.

> `setClasses` does seem more concise and faster to type though

I wouldn't worry too much about length of method names.  iOS and Android devs all rely on autocomplete for their day to day work already.  Name length is probably more an issue for JS developers who tend to code more artisanally using just text editors.

**Comment by incanus** [comment]
Yeah, the fact that Objective-C refers to classes frequently at runtime due to its dynamic nature argues against shortening too much. Let's go with `setStyleClasses`; using `setMapStyleClasses` is redundant when it's performed on a map object. 

→ https://github.com/mapbox/mapbox-gl-native/pull/1000

**Comment by bleege** [comment]
:+1:
