### ISSUE TITLE
Custom vector tile layers disappear when zooming in (too much)

### ISSUE THREAD

**Issue by millenbop** [mapbox/mapbox-gl-native#9863]
**Platform: iOS & Android**
**Mapbox SDK version:**

We have a custom vector tile layer which displays where people have been mapping with Mapillary. We supply layers for zoom level 16, but when zooming in more, the vector tiles disappear. Please see attached video.

### Steps to trigger behavior

 1. Add a custom vector source and a layer
 2. Zoom in beyond the zoom level that the source delivers vector tiles for

### Expected behavior

Vector tiles are visible and are interpolated.

### Actual behavior

Vector tiles disappear.

### More information

Our layers:

```
"sources": {
        "composite": {
            "url": "mapbox://mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v7",
            "type": "vector"
        },
        "mapillary": {
            "tiles": [
                      "https://d25uarhxywzl1j.cloudfront.net/v0.1/{z}/{x}/{y}.mvt"
                      ],
            "type": "vector"
        }
    },
...
 "layers": [
{
            "id": "mapillary-sequence-overview",
            "type": "circle",
            "source": "mapillary",
            "source-layer": "mapillary-sequence-overview",
            "paint": {
               "circle-opacity": 0.6,
               "circle-color": "#39AF64",
               "circle-radius": 4
            }
        },               
        {
            "id": "mapillary-sequences",
            "type": "line",
            "source": "mapillary",
            "source-layer": "mapillary-sequences",
            "interactive": true,
            "layout": {
               "line-join": "round",
               "line-cap": "round"
            },
            "paint": {
               "line-color": "#39AF64",
               "line-width": 2
            }
        },
...
```

Video: https://www.youtube.com/watch?v=lRFhJ_AwzKw

**Comment by tobrun** [comment]
Thank you for the report @millenbop! I noticed the same thing myself in https://github.com/mapbox/mapbox-gl-native/issues/9860. Closing as a duplicate.

**Comment by millenbop** [comment]
Ooops my bad! I searched yesterday but not today :) Sorry for the duplicate.

**Comment by tobrun** [comment]
np, thank you for taking the time to write this up!

**Comment by millenbop** [comment]
Can we please reopen this one since the other one (https://github.com/mapbox/mapbox-gl-native/issues/9860) was closed and isn't the same as this one.

**Comment by tobrun** [comment]
cc @asheemmamoowala

**Comment by asheemmamoowala** [comment]
@millenbop  - you vector tile source at `https://d25uarhxywzl1j.cloudfront.net/v0.1/{z}/{x}/{y}.mvt` is not returning any data in tiles at z15 and z16.

**Comment by millenbop** [comment]
Aren't they supposed to be interpolated, like in mapbox-js? Am I misunderstanding https://github.com/mapbox/vector-tiles/issues/21?

We use the same source on www.mapillary.com/app/ and there it works as expected.

**Comment by tobrun** [comment]
@millenbop as noted by @asheemmamoowala we are now trying to load data in z15 and z16 since the default maxZoom is set to 16. could you try adding a maxZoom to your source in that style definition? On gl-native we are possibly treating the 404 responses as valid tiles with no content and possibly there is a discrepancy in how 404 tiles are treated between gl-js and gl-native. 

Additionally related to #9860, we are missing the android api of `Source#setMaxZoom` and `Source#setMinZoom`. Hooking into the layer equivalent methods was not correct.

**Comment by kkaefer** [comment]
Overall, there's a difference between setting the maxZoom for a `source`, and setting the `maxZoom` for a layer:

* Source `maxZoom` controls from which zoom levels tiles are loaded. If your custom tile source only has tiles up to z14, please set `maxZoom: 14` so that Mapbox GL doesn't attempt to load z15/z16/... tiles. As per the [style specification](https://www.mapbox.com/mapbox-gl-js/style-spec/#sources-vector-maxzoom), the default value of `maxZoom` is 22.
* Layer `maxZoom` controls when the layer is displayed depending on the zoom. This is independent of the source zoom level, e.g. we can show z14 tiles when zoomed to 16. If you specify a `maxZoom` of 14, the layer won't be shown at all when the zoom level is >= 14, even if there are still tiles available.

As @tobrun noted, it looks like Android is missing the API for setting these values on sources. iOS, however, supports this by [setting `maximumZoomLevel` on the `MGLVectorSource` object](https://www.mapbox.com/ios-sdk/api/3.6.2/Classes/MGLVectorSource.html).

**Comment by millenbop** [comment]
OH! Right! My bad. I didn't know there was a "maxzoom" for sources!! Before in the SDK, and currently in the JS lib, it interpolated tiles at missing zoom levels. Works now! Thanks.

**Comment by kkaefer** [comment]
The SDK will still interpolate/overzoom lower zoom level tiles, but specifying a maxzoom for your *source* is important, e.g. when you start out your map at z16. In this case, Mapbox GL will attempt to load z16 tiles (which will fail). When setting a maxzoom of 14, it will load z14 tiles and display them at z16 size and all is good.
