### ISSUE TITLE
Android: Offline maps not available in different activities

### ISSUE THREAD

**Issue by nijs9** [mapbox/mapbox-gl-native#9927]
In a certain activity, I download an offline region, which works fine. I have another activity with mapboxmap (same style url as the activity where I did dodwnload offline region), but in this activity, the previous downloaded offline region is not available. Is this normal behaviour? Is it not possible to use the same offline regions in different activities?

**Comment by Guardiola31337** [comment]
Hey @nijs9 👋 
Thanks for reaching out and report your problem.

> the previous downloaded offline region is not available. Is this normal behaviour? Is it not possible to use the same offline regions in different activities?

This is totally possible.
I made a quick test and it's working as expected 👀

![offline](https://user-images.githubusercontent.com/1668582/30210007-dc96e2dc-949a-11e7-9d45-e78dfc5ef750.gif)

Could you add some more information for reproducing the issue or any other specifics around your test setup? If there is any sample or pseudo code you can provide, that would be really helpful because without having additional information, I'm unable to reproduce.
