### ISSUE TITLE
[qt] QML 5.6 support

### ISSUE THREAD

**Issue by rinigus** [mapbox/mapbox-gl-native#9934]
Hi,

after a merge with Qt 5.9, it looks like the Qt platform development is mainly focused on that Qt version (which is understandable). However, there are systems where Qt 5.9 is not available yet and I would be interested in QML Qt 5.6 backport. Or any other alternative that would allow to use QMapBoxGL together with QML. 

There used to be a QML application and QQuickMapboxGL for these case, but it got removed after the merge with Qt. I will tried to restore this code and had to change a bit for making it compile against current QMapBoxGL. As a result, I can get some map displayed, with issues: location names displayed in flipped chars (in contrast to street names that are shown as they should).

**Comment by rinigus** [comment]
The flipped chars can be cured in 5.6 by using vertical mirroring options in QML and allowing QMapBoxGL to draw in default mode.

I would leave this issue open for know to hear what are the plans regarding QML/Qt 5.6 support. In particular, whether there are plans to add Mapbox GL as a qlocation plugin? Some other specific issues I would prefer to file separately as I work on getting QMapBoxGL under QML.

**Comment by tmpsantos** [comment]
Somehow I missed this, sorry about that.

We removed `QQuickMapboxGL` because the work we were doing here was being duplicated on the QtLocation repository and we just didn't have the bandwidth to maintain both versions, so it made sense for us to support only the Qt 5.9+ plugin because that is more accessible to a broader audience and better integrated with Qt (i.e. using Qt data types at the Qt namespace).

We do understand people sometimes have concerns about licensing of newer versions of Qt or don't want to upgrade stable software to a newer Qt. With that in mind, the "low level API" which is the foundation for the QtLocation plugin is quite stable, documented with qdoc and tested with Qt4+ (yes, 4 :smile:) on our bots (https://github.com/mapbox/mapbox-gl-native/blob/master/circle.yml#L535). We are also making sure it builds with GCC 4.9+ in our CI.

/cc @brunoabinader

**Comment by rinigus** [comment]
No problem, thank you for your reply. Your decision is understandable. I managed to write a small library that allows me to use QMapboxGL from QML. Its based on QtLocation 5.9 code of yours and, as a consequence, has the same license as QtLocation 5.9 (LGPL3). If anyone is interested, its available at https://github.com/rinigus/mapbox-gl-qml and I am using it to bring Mapbox GL to Sailfish OS (Qt 5.6).

**Comment by brunoabinader** [comment]
> No problem, thank you for your reply. Your decision is understandable. I managed to write a small library that allows me to use QMapboxGL from QML. Its based on QtLocation 5.9 code of yours and, as a consequence, has the same license as QtLocation 5.9 (LGPL3). If anyone is interested, its available at https://github.com/rinigus/mapbox-gl-qml and I am using it to bring Mapbox GL to Sailfish OS (Qt 5.6).

This is great stuff @rinigus - please let us know if there's anything we could help in that sense :bowing_man: Issues and PRs are more than welcome!
